### ISSUE TITLE
Add Fan Control only Without Light on it 

### ISSUE THREAD

**Issue by punj** [HomeSpan/HomeSpan#101]
Hello!
I would like to add Fan Control only without Light because my fan doesn't have light.

I tried implementing 03-CeilingFanWithLight and it is working well with Light.

Then, I tried commenting LightBulb code from the example below, but then the accessory stops responding.

```
new Service::HAPProtocolInformation();          // Create the HAP Protcol Information Service  
      new Characteristic::Version("1.1.0");           // Set the Version Characteristicto "1.1.0" as required by HAP

  //  new Service::LightBulb();                       // Create the Light Bulb Service
    //  new Characteristic::On();                       // This Service requires the "On" Characterstic to turn the light on and off

  // Now we create the a Fan Service within this same Accessory

    new Service::Fan();                             // Create the Fan Service
      new Characteristic::Active(); 
```

Is there a way to Implement only fan to control fan speeds?

Advice and ideas are highly appreciated.

TIA.

**Comment by HomeSpan** [comment]
Try unpairing and re-pairing the device.  Sometime HomeKit caches setting and won't fully recognize the change to your configuration.

**Comment by punj** [comment]
> Try unpairing and re-pairing the device. Sometime HomeKit caches setting and won't fully recognize the change to your configuration.

Thank you, mate.

Is there a way to control Air Conditioner? I checked but didn't found.

**Comment by HomeSpan** [comment]
The HeaterCooler Service would be the best to use for an Air Conditioner.   You can configure it for simple on/off or add the CoolingThresholdTemperature Characteristic for automatic operation.
