### ISSUE TITLE
WiFi Failed using setWifiCredentials("","");

### ISSUE THREAD

**Issue by punj** [HomeSpan/HomeSpan#104]
Hello!

I used the same SSID, Password to connect to WiFi using CLI ("W" command) and it is getting connected to it.

But when I used the below code to try to connect to WiFi it Failed to connect
```
void setup_HomeKit()
{

  Serial.begin(115200);
  homeSpan.begin(Category::Lighting, "SGN_LEDS");
  homeSpan.setWifiCredentials("XXXX", "XXXXX");
  homeSpan.setLogLevel(HOMESPAN_LOG_LEVEL);
}

```
Can somebody please help me to solve this?

TIA.

**Comment by punj** [comment]
> Hello!
> 
> I used the same SSID, Password to connect to WiFi using CLI ("W" command) and it is getting connected to it.
> 
> But when I used the below code to try to connect to WiFi it Failed to connect
> 
> ```
> void setup_HomeKit()
> {
> 
>   Serial.begin(115200);
>   homeSpan.begin(Category::Lighting, "SGN_LEDS");
>   homeSpan.setWifiCredentials("XXXX", "XXXXX");
>   homeSpan.setLogLevel(HOMESPAN_LOG_LEVEL);
> }
> ```
> 
> Can somebody please help me to solve this?
> 
> TIA.

I just now figured out that before calling the above code I am doing below
```
WiFi.mode(WIFI_STA);
WiFi.begin(asyncSSID, asyncPassword);
```

if this could be the reason for failing WiFi in HomeSpan?

TIA

**Comment by HomeSpan** [comment]
Yes, this could be impacting.  You will need to close the STA before continuing.

**Comment by punj** [comment]
> Yes, this could be impacting. You will need to close the STA before continuing.

But I need STA for rest things to work like, webserver. Is there a way to work both things together?

**Comment by HomeSpan** [comment]
HomeSpan already opens up a web server - it is how all communication is done with HomeKit.  You can start a second web server and build logic for access that is independent from HomeKit, but there is no need to start a separate WiFi session.  Presumably you have one WiFi network to which you want to connect .  HomeSpan will connect the "entire device" to this network at start-up when you provide its credentials.  After connecting, HomeSpan starts its own web server and other services.  You can then start a second, separate web server since the device is already connected to your network.

Some considerations:  HomeSpan starts its web server on port 80.  Your can either start a second web server on another port, or more likely you will want to also use port 80 (since it is standard for browsers) in which case you can instruct HomeSpan to use a different port with the method `setPortNum(uint16_t port)`.  Also, whatever code you use to launch and operate the second web server needs to "behave" and not do anything that interferes with HomeSpan itself.  I have never tried to operate a second web server within HomeSpan but other users have done so successfully.

Note that implementing a web server and allowing a client (your web browser) to connect consumes TCP/IP sockets.  Normally HomeSpan reserves all 8 sockets available on the ESP32 for HomeKit Controllers.  If you enable OTA, HomeSpan reserves one for the OTA server and reduces the number of allowable simultaneously-connected  HomeKit Controllers to 7.  Adding your own web server and connecting a client requires 2 sockets.  So you will need to tell HomeSpan to reserve only 6 sockets for itself, or 5 if you also use OTA, so that there 2 left for your web server.  This is done with the `setMaxConnections(uint8_t nCon)` method (see the API for details).

Finally, you will want to start your web server only AFTER HomeSpan has connected to your WiFi network.  HomeSpan includes a command to facilitate this as well - see `setWifiCallback(void (*func)())` for details.

Hope this helps.

**Comment by punj** [comment]
Hi!

Put commeted code for SITD. 


> HomeSpan already opens up a web server - it is how all communication is done with HomeKit. You can start a second web server and build logic for access that is independent from HomeKit, but there is no need to start a separate WiFi session. Presumably you have one WiFi network to which you want to connect . HomeSpan will connect the "entire device" to this network at start-up when you provide its credentials. After connecting, HomeSpan starts its own web server and other services. You can then start a second, separate web server since the device is already connected to your network.
> 
> Some considerations: HomeSpan starts its web server on port 80. Your can either start a second web server on another port, or more likely you will want to also use port 80 (since it is standard for browsers) in which case you can instruct HomeSpan to use a different port with the method `setPortNum(uint16_t port)`. Also, whatever code you use to launch and operate the second web server needs to "behave" and not do anything that interferes with HomeSpan itself. I have never tried to operate a second web server within HomeSpan but other users have done so successfully.
> 
> Note that implementing a web server and allowing a client (your web browser) to connect consumes TCP/IP sockets. Normally HomeSpan reserves all 8 sockets available on the ESP32 for HomeKit Controllers. If you enable OTA, HomeSpan reserves one for the OTA server and reduces the number of allowable simultaneously-connected HomeKit Controllers to 7. Adding your own web server and connecting a client requires 2 sockets. So you will need to tell HomeSpan to reserve only 6 sockets for itself, or 5 if you also use OTA, so that there 2 left for your web server. This is done with the `setMaxConnections(uint8_t nCon)` method (see the API for details).
> 
> Finally, you will want to start your web server only AFTER HomeSpan has connected to your WiFi network. HomeSpan includes a command to facilitate this as well - see `setWifiCallback(void (*func)())` for details.
> 
> Hope this helps.

Thank you very much for your explanation. I will check, try and update you. I really hope your help will solve the issue.

**Comment by punj** [comment]
> > HomeSpan already opens up a web server - it is how all communication is done with HomeKit. You can start a second web server and build logic for access that is independent from HomeKit, but there is no need to start a separate WiFi session. Presumably you have one WiFi network to which you want to connect . HomeSpan will connect the "entire device" to this network at start-up when you provide its credentials. After connecting, HomeSpan starts its own web server and other services. You can then start a second, separate web server since the device is already connected to your network.
> > Some considerations: HomeSpan starts its web server on port 80. Your can either start a second web server on another port, or more likely you will want to also use port 80 (since it is standard for browsers) in which case you can instruct HomeSpan to use a different port with the method `setPortNum(uint16_t port)`. Also, whatever code you use to launch and operate the second web server needs to "behave" and not do anything that interferes with HomeSpan itself. I have never tried to operate a second web server within HomeSpan but other users have done so successfully.
> > Note that implementing a web server and allowing a client (your web browser) to connect consumes TCP/IP sockets. Normally HomeSpan reserves all 8 sockets available on the ESP32 for HomeKit Controllers. If you enable OTA, HomeSpan reserves one for the OTA server and reduces the number of allowable simultaneously-connected HomeKit Controllers to 7. Adding your own web server and connecting a client requires 2 sockets. So you will need to tell HomeSpan to reserve only 6 sockets for itself, or 5 if you also use OTA, so that there 2 left for your web server. This is done with the `setMaxConnections(uint8_t nCon)` method (see the API for details).
> > Finally, you will want to start your web server only AFTER HomeSpan has connected to your WiFi network. HomeSpan includes a command to facilitate this as well - see `setWifiCallback(void (*func)())` for details.
> > Hope this helps.
> 
> Thank you very much for your explanation. I will check, try and update you. I really hope your help will solve the issue.

I tried exactly as per your explanation and also commented below lines and http server code:
```
   // WiFi.mode(WIFI_STA);
  // WiFi.begin(SSID, password);
```

added below lines
```
  homeSpan.setWifiCredentials("REPL_UP", "XXXXX");
  homeSpan.setPortNum(8088);
  homeSpan.setMaxConnections(4); 
  homeSpan.setLogLevel(HOMESPAN_LOG_LEVEL);
  homeSpan.begin(Category::Lighting, "SGN_LEDS");
```

Now its getting fail to connect to WiFi. Also tried using 'W' Command and setup using CLI, but same
```
Trying to connect to REPL_UP.  Waiting 1 second(s) for response...
Trying to connect to REPL_UP.  Waiting 2 second(s) for response...
Trying to connect to REPL_UP.  Waiting 4 second(s) for response...
Trying to connect to REPL_UP.  Waiting 8 second(s) for response...
Trying to connect to REPL_UP.  Waiting 16 second(s) for response...
```
For your reference, pls find the complete log below:


```
> Executing task in folder Firmware1: platformio device monitor <

--- Available filters and text transformations: colorize, debug, default, direct, esp32_exception_decoder, hexlify, log2file, nocontrol, printable, send_on_enter, time
--- More details at http://bit.ly/pio-monitor-filters
--- Miniterm on /dev/cu.usbserial-0001  115200,8,N,1 ---
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
�YK�j
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
[E][BluetoothA2DPSink.cpp:744] get_last_connection(): ERROR GETTING NVS BLOB
[E][BluetoothA2DPSink.cpp:747] get_last_connection(): NVS NOT FOUND
[E][esp32-hal-cpu.c:93] addApbChangeCallback(): duplicate func=40081564 arg=3FFBE834
␀
************************************************************
Welcome to HomeSpan!
Apple HomeKit for the Espressif ESP-32 WROOM and Arduino IDE
************************************************************

** Please ensure serial monitor is set to transmit <newlines>

Message Logs:     Level 2
Status LED:       Pin 13
Device Control:   Pin 21
Sketch Version:   n/a
HomeSpan Version: 1.3.0
ESP-IDF Version:  v3.3.5-1-g85c43024c
ESP32 Board:      nodemcu-32s
Sketch Compiled:  Jul  1 2021 11:55:36

Device Name:      SGN_LEDS

*** HomeSpan Info ***

➤ Accessory:  AID=1
   ➟ Service AccessoryInformation:  IID=1, UUID=0x3E
      ⇨ Characteristic Name("On/Off LED"):  IID=2, UUID=0x23
      ⇨ Characteristic Manufacturer("HomeSpan"):  IID=3, UUID=0x20
      ⇨ Characteristic SerialNumber("123-ABC"):  IID=4, UUID=0x30
      ⇨ Characteristic Model("20mA LED"):  IID=5, UUID=0x21
      ⇨ Characteristic FirmwareRevision("0.9"):  IID=6, UUID=0x52
      ⇨ Characteristic Identify(0):  IID=7, UUID=0x14
   ➟ Service HAPProtocolInformation:  IID=8, UUID=0xA2
      ⇨ Characteristic Version("1.1.0"):  IID=9, UUID=0x37
   ➟ Service LightBulb:  IID=10, UUID=0x43
      ⇨ Characteristic On(0):  IID=11, UUID=0x25
➤ Accessory:  AID=2
   ➟ Service AccessoryInformation:  IID=1, UUID=0x3E
      ⇨ Characteristic Name("Dimmable LED"):  IID=2, UUID=0x23
      ⇨ Characteristic Manufacturer("HomeSpan"):  IID=3, UUID=0x20
      ⇨ Characteristic SerialNumber("123-ABC"):  IID=4, UUID=0x30
      ⇨ Characteristic Model("20mA LED"):  IID=5, UUID=0x21
      ⇨ Characteristic FirmwareRevision("0.9"):  IID=6, UUID=0x52
      ⇨ Characteristic Identify(0):  IID=7, UUID=0x14
   ➟ Service HAPProtocolInformation:  IID=8, UUID=0xA2
      ⇨ Characteristic Version("1.1.0"):  IID=9, UUID=0x37
   ➟ Service LightBulb:  IID=10, UUID=0x43
      ⇨ Characteristic On(0):  IID=11, UUID=0x25
      ⇨ Characteristic Brightness(50):  IID=12, UUID=0x8  Range=[0,100]
         ⬌ Set Range for Brightness with IID=12: Min=5, Max=100, Step=1
➤ Accessory:  AID=3
   ➟ Service AccessoryInformation:  IID=1, UUID=0x3E
      ⇨ Characteristic Name("Fan"):  IID=2, UUID=0x23
      ⇨ Characteristic Manufacturer("HomeSpan"):  IID=3, UUID=0x20
      ⇨ Characteristic SerialNumber("123-ABC"):  IID=4, UUID=0x30
      ⇨ Characteristic Model("20mA LED"):  IID=5, UUID=0x21
      ⇨ Characteristic FirmwareRevision("0.9"):  IID=6, UUID=0x52
      ⇨ Characteristic Identify(0):  IID=7, UUID=0x14
   ➟ Service HAPProtocolInformation:  IID=8, UUID=0xA2
      ⇨ Characteristic Version("1.1.0"):  IID=9, UUID=0x37
   ➟ Service Fan:  IID=10, UUID=0xB7
      ⇨ Characteristic Active(0):  IID=11, UUID=0xB0  Range=[0,1]
      ⇨ Characteristic RotationDirection(0):  IID=12, UUID=0x28  Range=[0,1]
      ⇨ Characteristic RotationSpeed(50):  IID=13, UUID=0x29  Range=[0,100]
         ⬌ Set Range for RotationSpeed with IID=13: Min=0, Max=100, Step=25
➤ Accessory:  AID=4
   ➟ Service AccessoryInformation:  IID=1, UUID=0x3E
      ⇨ Characteristic Name("Temperature"):  IID=2, UUID=0x23
      ⇨ Characteristic Manufacturer("HomeSpan"):  IID=3, UUID=0x20
      ⇨ Characteristic SerialNumber("123-ABC"):  IID=4, UUID=0x30
      ⇨ Characteristic Model("20mA LED"):  IID=5, UUID=0x21
      ⇨ Characteristic FirmwareRevision("0.9"):  IID=6, UUID=0x52
      ⇨ Characteristic Identify(0):  IID=7, UUID=0x14
   ➟ Service HAPProtocolInformation:  IID=8, UUID=0xA2
      ⇨ Characteristic Version("1.1.0"):  IID=9, UUID=0x37
   ➟ Service TemperatureSensor:  IID=10, UUID=0x8A
      ⇨ Characteristic CurrentTemperature(22):  IID=11, UUID=0x11  Range=[0,100]
➤ Accessory:  AID=5
   ➟ Service AccessoryInformation:  IID=1, UUID=0x3E
      ⇨ Characteristic Name("Humidity"):  IID=2, UUID=0x23
      ⇨ Characteristic Manufacturer("HomeSpan"):  IID=3, UUID=0x20
      ⇨ Characteristic SerialNumber("123-ABC"):  IID=4, UUID=0x30
      ⇨ Characteristic Model("20mA LED"):  IID=5, UUID=0x21
      ⇨ Characteristic FirmwareRevision("0.9"):  IID=6, UUID=0x52
      ⇨ Characteristic Identify(0):  IID=7, UUID=0x14
   ➟ Service HAPProtocolInformation:  IID=8, UUID=0xA2
      ⇨ Characteristic Version("1.1.0"):  IID=9, UUID=0x37
   ➟ Service HumiditySensor:  IID=10, UUID=0x82
      ⇨ Characteristic CurrentRelativeHumidity(22):  IID=11, UUID=0x10  Range=[0,100]
➤ Accessory:  AID=6
   ➟ Service AccessoryInformation:  IID=1, UUID=0x3E
      ⇨ Characteristic Name("AC"):  IID=2, UUID=0x23
      ⇨ Characteristic Manufacturer("HomeSpan"):  IID=3, UUID=0x20
      ⇨ Characteristic SerialNumber("123-ABC"):  IID=4, UUID=0x30
      ⇨ Characteristic Model("20mA LED"):  IID=5, UUID=0x21
      ⇨ Characteristic FirmwareRevision("0.9"):  IID=6, UUID=0x52
      ⇨ Characteristic Identify(0):  IID=7, UUID=0x14
   ➟ Service HAPProtocolInformation:  IID=8, UUID=0xA2
      ⇨ Characteristic Version("1.1.0"):  IID=9, UUID=0x37
   ➟ Service HeaterCooler:  IID=10, UUID=0xBC
      ⇨ Characteristic Active(0):  IID=11, UUID=0xB0  Range=[0,1]
      ⇨ Characteristic CurrentTemperature(25):  IID=12, UUID=0x11  Range=[0,100]
      ⇨ Characteristic CurrentHeaterCoolerState(1):  IID=13, UUID=0xB1  Range=[0,3]
      ⇨ Characteristic TargetHeaterCoolerState(2):  IID=14, UUID=0xB2  Range=[0,2]
      ⇨ Characteristic Name("AC"):  IID=15, UUID=0x23
      ⇨ Characteristic RotationSpeed(2):  IID=16, UUID=0x29  Range=[0,100]
      ⇨ Characteristic TemperatureDisplayUnits(1):  IID=17, UUID=0x36  Range=[0,1]
      ⇨ Characteristic SwingMode(1):  IID=18, UUID=0xB6  Range=[0,1]
      ⇨ Characteristic CoolingThresholdTemperature(25):  IID=19, UUID=0xD  Range=[10,35]
         ⬌ Set Range for CoolingThresholdTemperature with IID=19: Min=18, Max=30, Step=0.5
      ⇨ Characteristic HeatingThresholdTemperature(16):  IID=20, UUID=0x12  Range=[0,25]

Configured as Bridge: NO

Service                         UUID         AID  IID  Update  Loop  Button  Linked Services
------------------------------  ----  ----------  ---  ------  ----  ------  ---------------
AccessoryInformation              3E           1    1      NO    NO      NO  -
HAPProtocolInformation            A2           1    8      NO    NO      NO  -
LightBulb                         43           1   10     YES    NO      NO  -
AccessoryInformation              3E           2    1      NO    NO      NO  -
HAPProtocolInformation            A2           2    8      NO    NO      NO  -
LightBulb                         43           2   10     YES    NO      NO  -
AccessoryInformation              3E           3    1      NO    NO      NO  -
HAPProtocolInformation            A2           3    8      NO    NO      NO  -
Fan                               B7           3   10     YES    NO      NO  -
AccessoryInformation              3E           4    1      NO    NO      NO  -
HAPProtocolInformation            A2           4    8      NO    NO      NO  -
TemperatureSensor                 8A           4   10     YES    NO      NO  -
AccessoryInformation              3E           5    1      NO    NO      NO  -
HAPProtocolInformation            A2           5    8      NO    NO      NO  -
HumiditySensor                    82           5   10     YES    NO      NO  -
AccessoryInformation              3E           6    1      NO    NO      NO  -
HAPProtocolInformation            A2           6    8      NO    NO      NO  -
HeaterCooler                      BC           6   10     YES    NO      NO  -

*** End Info ***

Accessory ID:      6A:27:D4:34:EA:60                               LTPK: 9FCB1A06B7E3B21115354B4A8B2286B21E155437CBB540464FB86F2EE6DEB513
Paired Controller: E176806B-715F-4B39-8F62-F505F4ED2C08   (admin)  LTPK: 5E5A77E91E9EAB3FC14027C4CEDFF56FEE0AC305B6B661FAB6CB7570A9DF4F46

Accessory configuration number: 11

SGN_LEDS is READY!

Trying to connect to REPL_UP.  Waiting 1 second(s) for response...
Trying to connect to REPL_UP.  Waiting 2 second(s) for response...
Trying to connect to REPL_UP.  Waiting 4 second(s) for response...
Trying to connect to REPL_UP.  Waiting 8 second(s) for response...
Trying to connect to REPL_UP.  Waiting 16 second(s) for response...

*** Can't connect to REPL_UP.  You may type 'W <return>' to re-configure WiFi, or 'X <return>' to erase WiFi credentials.  Will try connecting again in 60 seconds.
```

To trace the issue, I tried connecting to WiFi using WiFi.h library and it's getting connected to it.

I don't know why it is failing to connect to WiFi using homespan.

**Comment by punj** [comment]
Hi @HomeSpan 

I tried exactly as per your advice. Now, I am able to connect to WiFi and HomeSpan Server and its services are working well. However, there are issues with rebooting, but that's a later part.

Below code is implemented:
```
AsyncWebServer serverAsync(80);
AsyncWebSocket ws1("/ws");

void setup(){
  Serial.begin(115200);
  homeSpan.setWifiCredentials(asyncSSID1, asyncPassword1);
  homeSpan.setPortNum(8888);
  homeSpan.setMaxConnections(4);
  homeSpan.setLogLevel(HOMESPAN_LOG_LEVEL);
  homeSpan.setWifiCallback(&callBackTest);
  homeSpan.begin(Category::Lighting, "SGN_LEDS");
}

void callBackTest(){
  Serial.println("SGN :: callBackTest");
  homeSpanCallBackAsyncWeb();
}

void homeSpanCallBackAsyncWeb()
{
  serverAsync.on("/", HTTP_GET, handleRoot);
  serverAsync.onNotFound(handleNotFound);
  ws1.onEvent(onWebSocketEvent);
  serverAsync.addHandler(&ws1);
  serverAsync.begin();
}
```

However,  AsyncWebServer is not getting started without any error or exception.
If I ran the below code by commenting HomeSpan Code and calling homeSpanCallBackAsyncWeb() in setup it is getting connected to AsyncWebServer but in that case, HomeSpan will not work.

```
void createWebServer()
{
  WiFi.mode(WIFI_STA);
  WiFi.begin(asyncSSID, asyncPassword);
  serverAsync.on("/", HTTP_GET, handleRoot);
  serverAsync.onNotFound(handleNotFound);
  ws1.onEvent(onWebSocketEvent);
  serverAsync.addHandler(&ws1);
  serverAsync.begin();
}
```
I am really confused and stuck at this stage. Can you please advise if I am missing something? 

Appreciate your best advise.

Thank you

**Comment by punj** [comment]
> Hi @HomeSpan
> 
> I tried exactly as per your advice. Now, I am able to connect to WiFi and HomeSpan Server and its services are working well. However, there are issues with rebooting, but that's a later part.
> 
> Below code is implemented:
> 
> ```
> AsyncWebServer serverAsync(80);
> AsyncWebSocket ws1("/ws");
> 
> void setup(){
>   Serial.begin(115200);
>   homeSpan.setWifiCredentials(asyncSSID1, asyncPassword1);
>   homeSpan.setPortNum(8888);
>   homeSpan.setMaxConnections(4);
>   homeSpan.setLogLevel(HOMESPAN_LOG_LEVEL);
>   homeSpan.setWifiCallback(&callBackTest);
>   homeSpan.begin(Category::Lighting, "SGN_LEDS");
> }
> 
> void callBackTest(){
>   Serial.println("SGN :: callBackTest");
>   homeSpanCallBackAsyncWeb();
> }
> 
> void homeSpanCallBackAsyncWeb()
> {
>   serverAsync.on("/", HTTP_GET, handleRoot);
>   serverAsync.onNotFound(handleNotFound);
>   ws1.onEvent(onWebSocketEvent);
>   serverAsync.addHandler(&ws1);
>   serverAsync.begin();
> }
> ```
> 
> However, AsyncWebServer is not getting started without any error or exception.
> If I ran the below code by commenting HomeSpan Code and calling homeSpanCallBackAsyncWeb() in setup it is getting connected to AsyncWebServer but in that case, HomeSpan will not work.
> 
> ```
> void createWebServer()
> {
>   WiFi.mode(WIFI_STA);
>   WiFi.begin(asyncSSID, asyncPassword);
>   serverAsync.on("/", HTTP_GET, handleRoot);
>   serverAsync.onNotFound(handleNotFound);
>   ws1.onEvent(onWebSocketEvent);
>   serverAsync.addHandler(&ws1);
>   serverAsync.begin();
> }
> ```
> 
> I am really confused and stuck at this stage. Can you please advise if I am missing something?
> 
> Appreciate your best advise.
> 
> Thank you

I checked headers in the browser console is
```
Request URL: http://192.168.1.20/
Referrer Policy: strict-origin-when-cross-origin
```

**Comment by HomeSpan** [comment]
I have not used the Async server before - it unfortunately may not be compatible with the rest of the HomeSpan environment.  Can you use the standard WiFiServer() instead?

**Comment by punj** [comment]
I will try and update you soon.

**Comment by Csh5fr** [comment]
is there any solution for this problem? I have coded a large project with asyncwebserver  and will add some HomeKit functions. But is not running both together (homespun & asyncwebserver lib)  iam using the Arduino suite.
