### ISSUE TITLE
Set up network suggestions

### ISSUE THREAD

**Issue by zuozhehao** [HomeSpan/HomeSpan#106]
AP mode set WiFi and pin HTML support custom.

**Comment by HomeSpan** [comment]
Sorry, can you be more detailed. I'm not sure exactly what this suggestion means.

**Comment by zuozhehao** [comment]
> Sorry, can you be more detailed. I'm not sure exactly what this suggestion means.

Sorry, I didn't express it clearly.
https://github.com/HomeSpan/HomeSpan/blob/e0c47f6a194bb79c1d90daa8e7897d35950134f6/src/Network.cpp#L256-L369

**Comment by HomeSpan** [comment]
Thanks for clarifying the request.  No plans for now to provide library functions to customize the built in AP web pages, though it is possible to create your own AP code and have HomeSpan use it instead.
