### ISSUE TITLE
how to pair homekit with multiple mobile

### ISSUE THREAD

**Issue by mightChamp** [HomeSpan/HomeSpan#109]
I want to operate homekit from different mobiles, but When homekit is paired with one mobile, it doesn't show up on other device to be able to pair.

**Comment by HomeSpan** [comment]
HomeKit devices (including those created with HomeSpan) can only pair with one device at a time.  Once you pair a device with one phone, other phones sharing that same iCloud account should be able to access as well.  To link devices with a different iCloud account you need to "invite" that other party to access your home.

**Comment by mightChamp** [comment]
Thanks for info
