### ISSUE TITLE
how to enter Device Configuration Mode?

### ISSUE THREAD

**Issue by paultang** [HomeSpan/HomeSpan#113]
I have an espressif DEV kit V4 board. there are only EN and Reset Button.  which button you call it control button. and the LED is on always.  don't change.  
i am reading the HomeSpan User guide.  i am confused.  Pairing sometime doesn't work
Can you show it with a picture.   thanks.

**Comment by VirtualGentlemen** [comment]
You need to research which GPIO pin the buttons and led's are connected to. 
Then you can set the connection accordingly with the commands:

```
  homeSpan.setControlPin(0); // set control button
  homeSpan.setStatusPin(13); // sets LED Pin
```

Read the Documentation. You'll find everything and more there.
https://github.com/HomeSpan/HomeSpan/blob/b3237f06ed8ce38fabb384bc1190d0b67740905c/docs/Reference.md

**Comment by paultang** [comment]
I got it. Thanks.
