### ISSUE TITLE
Do you plan on implementing Doors / Locks?

### ISSUE THREAD

**Issue by philgin** [HomeSpan/HomeSpan#117]
Great project!
Do you plan on implementing Doors / Locks?

**Comment by HomeSpan** [comment]
Thanks!

HomeSpan currently supports both the HAP *Door* and HAP *Lock Mechanism* Services, so you can create a single Accessory that operates a motorized door with lock, or even just an Accessory with a single lock.  However, HomeSpan does not support the more advanced *Lock Management* Service.  This Service is designed to track who operated the lock, when it was last opened or closed, etc., but requires a special data format (TLV8) that HomeSpan does not support for Services.
