### ISSUE TITLE
Getting Uncertified Accessory message when adding device

### ISSUE THREAD

**Issue by rajtrada** [HomeSpan/HomeSpan#120]
Can we remove the "Uncertified Accessory" alert when adding a device to HomeKit?

**Comment by HomeSpan** [comment]
Unfortunately, no.  The Home App automatically shows this message whenever connecting to a non-commercial product (anything built with HAP-R2).

**Comment by rajtrada** [comment]
Is there any way by which we can create a commercial product using the HomeSpan library?

**Comment by HomeSpan** [comment]
No, the pairing API is slightly different and I believe requires some form of software-based licensing keys from Apple.

**Comment by rajtrada** [comment]
Thanks for the detailed explanation.
