### ISSUE TITLE
Characteristics updates do not allow whitespace in values

### ISSUE THREAD

**Issue by unreality** [HomeSpan/HomeSpan#123]
When receiving characteristics updates from controllers, the 'value' property could have whitespace in it, the parser currently throws an error since it incorrectly parses the JSON if a property has whitespace in it. This is fixed in #121 , but if that does not get merged in, the fix is in commit 86f99f696b43af72d444074e9b9d594b51b02eaf

**Comment by HomeSpan** [comment]
This has been addressed in release 1.4.1.
