### ISSUE TITLE
Serial preventing boot

### ISSUE THREAD

**Issue by danricho** [HomeSpan/HomeSpan#125]
Hello again!

I have small issue with a custom ESP32 board I have been using which doesn't have a built in USB to Serial bridge and instead has an FTDI port which I use to flash it and use the CLI. Only the GND, RX and TX lines are connected.

When the FTDI is connected and a serial monitor is open, the device boots and behaves as normal.

Unfortunately it stops booting when I disconnect the FTDI.

My workaround has been to program it and setup the WiFi credentials via the CLI, then re-program it with the `Serial.begin(115200);` line commented out. This allows the device to behave correctly but obviously removes the ability to use the CLI without reprogramming.

It'd be great if anyone had any ideas or steps I should take to further troubleshoot. Unfortunately when I had the PCB made I didn't add the status LED or the control button... Next version will have them!

**Comment by danricho** [comment]
I should also add that the code I'm using on this device is the tutorial "15-RealPushButtons" with minor changes.

**Comment by HomeSpan** [comment]
Hmm.  I think I understand the problem but unfortunately not sure how to fix it.  It may be possible to use the Arduino if(Serial) command to check whether the Serial port is active, but even if this works this would likely require every Serial.print() command to check as well to avoid hanging.  I don't have an FTDI so unfortunately can't test this hypothesis.

**Comment by danricho** [comment]
I had the same thought but I'm struggling to understand why it is blocking. I'm not sure how it's any different to any prebuilt board. I'll need to read more about the blocking nature of serial with FTDI.

With the Wifi bug fixed, my need to use the serial commands is lessened.

I will provide any updates if I get some.

**Comment by danricho** [comment]
I have localised the issue to within the `homespan.poll()` function where it checks for any available serial. If I comment out the if block, the module works. See below:

https://github.com/HomeSpan/HomeSpan/blob/5e8d8ed76fd9c2f34979abac876b9eb670ab3544/src/HomeSpan.cpp#L185

**Comment by danricho** [comment]
Solution for this specific case was to add a high value resister between RX and VCC to pull the floating RX line high.
See [comment in issue 131](https://github.com/HomeSpan/HomeSpan/issues/131#issuecomment-904368923) for more detail.

Closing this as it is now being tracked in #131.
