### ISSUE TITLE
Can we certify with Apple using this library and if yes what's the process of it?

### ISSUE THREAD

**Issue by mightChamp** [HomeSpan/HomeSpan#126]

**Comment by HomeSpan** [comment]
No, unfortunately the HAP-R2 spec can only be used for non-commercial purposes.  There is apparently a separate commercial spec with different pairing logic for certified devices.  I believe this requires license keys that must be obtained from Apple through their [MFi program](https://mfi.apple.com).

**Comment by mightChamp** [comment]
ok thanks
