### ISSUE TITLE
ESP32-C3 ERROR

### ISSUE THREAD

**Issue by mjkdz** [HomeSpan/HomeSpan#139]
RFControl.cpp:4:10: fatal error: soc/dport_reg.h: No such file or directory

**Comment by HomeSpan** [comment]
Sorry, HomeSpan is not presently configured for the S2 or C3 versions of the ESP32.  Once Espressif publishes their initial stable release of the [Arduino-ESP32 2.0 library](https://github.com/espressif/arduino-esp32#esp32-s2-and-esp32-c3-support) (with support for the S2 and C3 chips), HomeSpan will be updated to run on those chips (to the extent possible).

**Comment by HomeSpan** [comment]
This bug has been fixed in release 1.4.1.

**Comment by YouCanNotBeSerious** [comment]
I might have something related to this bug - specifying a pin that doesn't exist, on a -C3 causes a WDT reboot loop.  How I got to that stage was compiling the simple LED example on an ESP32-WROOM  board, then chaining to the -C3 board and recompiling but left the LED pin defined as 17. Changing the pin to something present on the C3 like 5 allows it too run fine.

But, changing it to say 99 on the -WROOM board also ran fine.

This is not necessarily a HomeSpan issue of course, but I thought you might like to know or it might reveal some other variant weirdness, or if nothing else someone googling for similar may find this :-)

**Comment by YouCanNotBeSerious** [comment]
Oh - Important note - I have only done extremely limited testing, but this WDT reset only happens with HomeSpan, not with for example the basic blink sketch - on a serial terminal with pin 99 specified in the "blink" sketch,  this gives a GPIO error every time the LED is blinked.
