### ISSUE TITLE
Door Service Documenation

### ISSUE THREAD

**Issue by helo-head** [HomeSpan/HomeSpan#149]
Just noted that the HomeSpan service documentation states that the only required door characteristic is CurrentPosition. However when you start HomeSpan up it complains saying that TargetPostion and PositionSate are required.

**Comment by HomeSpan** [comment]
In the Apple docs?  According to HAP R2, TargetPosition and PositionState are also required.

![image](https://user-images.githubusercontent.com/68477936/132611001-015a8b69-8194-4550-a6fe-789c2bcfdd0c.png)

**Comment by HomeSpan** [comment]
Ah - sorry.  You meant in my own documentation!  I will update accordingly.  Thanks for catching.

**Comment by HomeSpan** [comment]
Thanks again for catching this - the doc has been updated in the master branch.
