### ISSUE TITLE
Home app unable to connect to Homekit device until Mobile WiFi reconnect to router

### ISSUE THREAD

**Issue by mightChamp** [HomeSpan/HomeSpan#157]
Hello,

After 2-3 hours, I got error in Home App that Homebridge is not responding. I soft reboot(by command) the ESP32, but Home app can't connect to it, and shows same error of not responding then I reconnect Mobile to WiFi and issue is solved. I faced this issue frequently.

I also observed that this issue also solved when  I power off and on ESP32. 

Please help me to solve this issue.
 
Thank You

**Comment by MarvinSMX** [comment]
did you manage to fix it?

**Comment by mightChamp** [comment]
not till now

**Comment by HomeSpan** [comment]
Have you been able to resolve this issue?

**Comment by mightChamp** [comment]
No

**Comment by dlangamer** [comment]
I noticed the same problem when I switched to Mesh routers. In the past I used normal TPlink routers and never had experienced this problem! I believe it is something related to the technology of these routers or something similar

**Comment by homonto** [comment]
guys, have you found if HomeSpan has a mechanism to detect WiFi disconnect? does it do anything when detected (if it has)?

**Comment by HomeSpan** [comment]
Yes, it will automatically reconnect if disconnected.  It also reports this automatically to the weblog if used.
