### ISSUE TITLE
Button debouncing

### ISSUE THREAD

**Issue by EinRainerZufall** [HomeSpan/HomeSpan#16]
If i use buttons like in the example 16 are the buttons automatic debounced?

**Comment by HomeSpan** [comment]
Yes, buttons are automatically debounced.   The buttons in Example 16 use HomeSpan's default settings, but you can also change the debounce (short-press) timing, as well the long-press and double-press timings to customize the operations of any specific button.  Example 15 provides examples of different button configurations.  Full details of the settings can be found on the [HomeSpan API](https://github.com/HomeSpan/HomeSpan/blob/master/docs/Reference.md#spanbuttonint-pin-uint16_t-longtime-uint16_t-singletime-uint16_t-doubletime) page.

**Comment by EinRainerZufall** [comment]
Thanks for the fast answer.
