### ISSUE TITLE
Help!! controlling an accessory with two esp's 

### ISSUE THREAD

**Issue by DevSpur** [HomeSpan/HomeSpan#160]
Hi Im looking to control an accessory with another esp, so basically two separate esp's controlling one light. So these esp's will be in two separate rooms but need to control one light. does anyone know how to do this or is there an example that I can follow.
Thanks

**Comment by HomeSpan** [comment]
One way would be to use one ESP32 to control the light directly in HomeKit using HomeSpan.  The second ESP32 could be configured as  a HomeSpan [ProgrammableSwitch](https://github.com/HomeSpan/HomeSpan/blob/master/examples/16-ProgrammableSwitches) with buttons that tell your Home App to turn on/off another device, including the first ESP32 connected to the light.  This is basically how to implement 3-way light switches.

**Comment by DevSpur** [comment]
Okay, So will there be two tiles in the home app or will there only be one tile.

**Comment by HomeSpan** [comment]
I think just one tile that operates the light.  The other will show up as a control in the Home App that you use to trigger other scenes and events - it's basically a generic "button" that supports long, short, and double-presses.  The tutorial above takes you through every step.  If you already have some HomeKit devices in your home you can try out the tutorial and see how you can control those devices with a ProgrammableSwitch Accessory.

**Comment by DevSpur** [comment]
Okay, Thanks I'll have a look
