### ISSUE TITLE
Nextion display support

### ISSUE THREAD

**Issue by DevSpur** [HomeSpan/HomeSpan#161]
Hi so I have a nextion display I was wondering if anyone has used this to control devices and if so do you have any examples

**Comment by HomeSpan** [comment]
Can you be more specific with your request?  Are you currently using HomeSpan to control accessories via the Home App on your iPhone and want to add a nextion display to provide additional manual control?

**Comment by DevSpur** [comment]
> Can you be more specific with your request? Are you currently using HomeSpan to control accessories via the Home App on your iPhone and want to add a nextion display to provide additional manual control?

Hi, yes we are currently using homeSpan and using our phones, so now we would like to have nextion displays to control the lights, fans, etc locally. 
So I tried setting something up but it doesn't work the way I want it to.

So the way I have it kinda working is that the nextion display is communicating over serial and using the esp32 as a "StatelessProgrammableSwitch" detecting a long and single press to turn on and off the lights and fans. 
The only problem is now I can update the home app tile using the programmable switch but once you control it from the app, the screen "Nextion Display" does not update so its then kinda pointless.

So maybe you can add a function that you can notify the network that an accessory has been updated or changed then you can use any device to update another accessory or something like that. I haven't looked into any code as I would have to learn  how it works and I don't really have the time do that right now, but you might know how to make something work quick. 

I hope you can work on a solution as I think it would really be a cool add-on for this service.

**Comment by HomeSpan** [comment]
If the Nextion Display is attached to the same device that physically controls the lights, fan, etc., then you should be able to update is locally within the update() loop (no need to using  StatelessProgrammableSwitch).  But if the display is attached to a separate ESP32 device, then StatelessProgrammableSwitch is the best way to communicate changes to the Home App, which in turn then communicates with the ESP32 device running HomeKit to perform the action (or any HomeKit device, not just a HomeSpan ESP32).

The problem with StatelessProgrammableSwitch is that by definition it's stateless:  Communication is only one way.  To solve this one would need an "out-of-band" communication between the two ESP32 devices that operates distinct from HomeKit.  A second, though more kludgy way, would be to create a duplicate copy of the fan and light Services on the ESP32 with the Nextion Display and configure your Home App with duplicate tiles assigned to an undisplayed room that are activated when the main tile for a light/fan is activated.

**Comment by DevSpur** [comment]
So I've thought of one way of doing this is by broadcasting a message across all the esp’s using esp.now but I’m not sure if that would work, I don’t know if you have worked with esp.now, or know of any software that can broadcast over the network like mqtt as then it would make this really easy.

**Comment by HomeSpan** [comment]
Version 1.7.0 of HomeSpan (just released) now includes integrated support of ESP-NOW via a dedicated **SpanPoint** class.  See the [tutorial](NOW.md) for details.
