### ISSUE TITLE
Door sensor functionality - polling, sleep

### ISSUE THREAD

**Issue by PeteBurgess** [HomeSpan/HomeSpan#168]
Hi folks

I need to create a door sensor using a Hall effect sensor. That bit’s easy. However what I’m not clear on is state management.

I can do a digital read in a loop and report when the sensor changes from high to low. I could alternatively attach an interrupt and report on that change.

So my question is regarding polling to/from HomeKit. Does HomeKit regularly query the sensor state or is it solely the job of the sensor to report changes ? I’m assuming I at least want the sensor to report state on startup.

Also, if I attach an interrupt can I put the ESP32 in a sleep state until there’s a change or will there be to much of a delay whilst in connects to WiFi to report the change to HomeKit in a timely fashion ?

Thanks.

**Comment by HomeSpan** [comment]
No need for any of this.  Please see [Tutorial 12](https://github.com/HomeSpan/HomeSpan/blob/master/examples/12-ServiceLoops) for complete details.

**Comment by PeteBurgess** [comment]
Thanks. Surprisingly easy to implement !

I do still have a few questions, though, having done a bit of reading. My understanding is that the ESP can be put to sleep whilst leaving the WiFi enabled and GPIOs 16 and 17 powered. This is ideal for a contact sensor so my plan would be something like...

1 - Sleep
2 - Wake on interrupt from contact sensor pin
3 - Update HomeSpan

To my mind that's a lot more efficient than poll/send every X seconds and also avoids any delay in doing whatever needs to be done as a result of an automation.

Can I do this with interrupts and just call homeSpan.poll() when the interrupt hits ? The polling may be fine but it seems like me sending data to HomeKit every half a second probably isn't the greatest idea.

**Comment by HomeSpan** [comment]
You can poll continuously but only send a notification back to HomeKit if there is a change in the state of the sensor.  No need to send an update unless there is a change. 

I've not tried to use low-power sleep modes.  Note that HomeKit requires a constant connection, initiated by a client (iPhone, HomePod, etc). If the connection is lost to a client, HomeSpan cannot establish an outbound connection and must wait until a client decides to connect again.

**Comment by PeteBurgess** [comment]
Thanks. Having take a further look at the polling I realize what a ridiculously elementary question it was. Having said that anything programming is not remotely in my wheelhouse, unless you’re talking 1980’s BBC Basic or maybe a bit of Z80 if you caught me if the right day.

I’ll mess around with the sleep functions a bit. Reading further it looks like the only sleep mode usable is “modem sleep” which powers down WiFi in between beacons. The connection stays up but the WiFi is powered down unless it needs to do something or respond to a beacon.

**Comment by paulprd** [comment]
Hello, I'm trying to use the Tutorial 12 to make a door sensor but I can't do it... Could you help me to set up my door sensor please.

**Comment by HomeSpan** [comment]
I would use Tutorial 12 but replace the TemperatureSensor with a ContactSensor and use the ContactSensorState.  See the HAP-R2 docs for details on how the the Contact Sensor Service and associated Characteristics work.
