### ISSUE TITLE
Eve Temperature Humidity Sensor

### ISSUE THREAD

**Issue by valeriofantozzi** [HomeSpan/HomeSpan#169]
Is it possible to emulate a Eve temperature and humidity sensor ([like this](https://www.evehome.com/en-us/eve-weather)) with the aim of having the graphic history on the Eve application ?

**Comment by HomeSpan** [comment]
Yes, it is possible to create something like this but HomeSpan will only help with the HomeKit portion -- you'll need to develop your own code or use libraries to create a display.  Also, note that HomeKit devices generally connect via WiFi which means they typically need to be plugged in (WiFi consumes a lot of power).  Most temperature sensors use bluetooth, which requires much less energy and allows the device to be battery powered.

**Comment by ivale** [comment]
thanks for the answer :) I didn't mean the hardware sensor. 
I would like to be able to exposes a temperature and a humidity sensor with EVE history support, something like [this](https://github.com/HomeKidd/ESP8266-HomeKit-New-Eve-Weather) with your library

**Comment by ivale** [comment]
thanks for the answer :) I didn't mean the hardware part.
I would like to be able to exposes a temperature and a humidity sensor with EVE history support, something like [this](https://github.com/An00bIS47/Homekit) with your library. 
If you use a normal temperature sensor in HomeKit the Eve app recognise it but doesn't support history graphs.

**Comment by HomeSpan** [comment]
Thanks for clarifying.  The Apple HomeKit framework allows manufacturers to extend HAP by adding custom Services and Characteristics.  However, these will all be ignored by the Home App.  The EVE App picks up these extra Services and Characteristics from its own devices, and displays them accordingly.  If you are trying to display EVE-like data (graphs, etc.) on Apple's Home App, it unfortunately can't be done.

The reverse is technically possible - you could add custom Services and Characteristics to a HomeSpan device that would be ignored by the Home App, but could be read by the EVE App.   HomeSpan does not presently include methods to add custom Services and Characteristics, but this is something I can try to add in a future release.  The reason I had not added it before is that the custom codes other manufacturer's devices are typically considered proprietary and need to be reverse-engineered.  From the link you posted above, it looks like the author did identify a list of codes that could be used with EVE.

**Comment by HomeSpan** [comment]
The latest version of HomeSpan (v1.4.1) contains a new macro to create Custom Characteristics.  I have been able to add some Eve-specific Characteristics, such as Voltage, but getting Eve history to work will take some more work and possibly a new data type.

**Comment by aLAN-LDZ** [comment]
I bet, I am not able to write this code myself, but it would be a very nice and useful feature in the homespan library.

**Comment by aLAN-LDZ** [comment]
> I was just asking if there is a way for Homespan library to add custom Services and Characteristics like the ones by Eve ecosystem. From what I know the majority of Elgato sensors have been retro engineered so I was thinking of a way to expose multiple services and characteristics with custom UUID with your library. Hope in a future release 😁

If you manage to run the charts, please let me know how to do it <3

**Comment by ivale** [comment]
Just an example of the 01-SimpleLightBulb in the example library adding custom Voltage and Watt Characteristic. It does work!!


```
#include "HomeSpan.h"         // HomeSpan sketches always begin by including the HomeSpan library
#define REQUIRED VERISON(2,1,3)   // throws a compile-time error unless HomeSpan library used is version 2.1.3 or later

CUSTOM_CHAR(Voltage,  E863F10A-079E-48FF-8F27-9C2605A29F52, PR+EV, UINT16, 120, 0, 240, false);  
CUSTOM_CHAR(Watt,     E863F10D-079E-48FF-8F27-9C2605A29F52, PR+EV, FLOAT, 100, 0, 1000, false);  

void setup() {                // Your HomeSpan code should be placed within the standard Arduino setup() function
 
  Serial.begin(115200); 
  homeSpan.begin(Category::Lighting,"HomeSpan LightBulb");   // initializes a HomeSpan device named "HomeSpan Lightbulb" with Category set to Lighting

new SpanAccessory();                              // Begin by creating a new Accessory using SpanAccessory(), which takes no arguments
  
    new Service::AccessoryInformation();            // HAP requires every Accessory to implement an AccessoryInformation Service, which has 6 required Characteristics:
      new Characteristic::Name("My Table Lamp");      // Name of the Accessory, which shows up on the HomeKit "tiles", and should be unique across Accessories
      
  // The next 4 Characteristics serve no function except for being displayed in HomeKit's setting panel for each Accessory.  They are nevertheless required by HAP:
                                                      
      new Characteristic::Manufacturer("HomeSpan");   // Manufacturer of the Accessory (arbitrary text string, and can be the same for every Accessory)
      new Characteristic::SerialNumber("123-ABC");    // Serial Number of the Accessory (arbitrary text string, and can be the same for every Accessory)
      new Characteristic::Model("120-Volt Lamp");     // Model of the Accessory (arbitrary text string, and can be the same for every Accessory)
      new Characteristic::FirmwareRevision("0.9");    // Firmware of the Accessory (arbitrary text string, and can be the same for every Accessory)

  // The last required Characteristic for the Accessory Information Service is the special Identify Characteristic.  We'll learn more about this
  // Characteristic in later examples.  For now, you can just instantiate it without any arguments.
  
      new Characteristic::Identify();                 // Create the required Identify

new Service::HAPProtocolInformation();          // Create the HAP Protcol Information Service  
      new Characteristic::Version("1.1.0");           // Set the Version Characteristicto "1.1.0" as required by HAP

  // Now that the required "informational" Services have been defined, we can finally create our Light Bulb Service

    new Service::LightBulb();                       // Create the Light Bulb Service
      new Characteristic::Name("Low-Voltage Lamp");
      new Characteristic::On(0);
      new Characteristic::Brightness(50);
      new Characteristic::Voltage(12);      // adds Voltage Characteristics and sets initial value to 12 volts
      new Characteristic::Watt(500);      // adds Voltage Characteristics and sets initial value to 12 volts

} // end of setup()

void loop(){

  // The code in setup above implements the Accessory Attribute Database, but performs no operations.  HomeSpan itself must be
  // continuously polled to look for requests from Controllers, such as the Home App on your iPhone.  The poll() method below is all that
  // is needed to perform this continuously in each iteration of loop()
  
  homeSpan.poll();         // run HomeSpan!
  
} // end of loop()
```

> > I was just asking if there is a way for Homespan library to add custom Services and Characteristics like the ones by Eve ecosystem. From what I know the majority of Elgato sensors have been retro engineered so I was thinking of a way to expose multiple services and characteristics with custom UUID with your library. Hope in a future release 😁
> 
> If you manage to run the charts, please let me know how to do it <3
