### ISSUE TITLE
Ethernet support

### ISSUE THREAD

**Issue by webjocke** [HomeSpan/HomeSpan#171]
Hey,
I just read the Q&A about HomeSpan over ethernet. I know that the esphome library have support for ethernet (using the ESP32's integrated controller) and they output mdns / dns-sd.

I have been building an app that discoveres esphome devices and all of them are only Ethernet connected so it should at least be possible to get that working on HomeSpan as well if I am not mistaken.

Good day 😁

**Comment by HomeSpan** [comment]
Thanks for the info on this - I will check it out and see if I can figure out how they get it to work.
