### ISSUE TITLE
Category Television Not Supported

### ISSUE THREAD

**Issue by mLihs** [HomeSpan/HomeSpan#19]
Hi thanks for your great Library.
I was trying to transfer a project to Homespan but unfortunately the Category Television is not Supported.
Could you add this please?
homekit_accessory_category_television

**Comment by HomeSpan** [comment]
At present, HomeSpan tracks Apple's Non-Commercial HAP Release 2 specifications.  It seems that Apple has not yet included the specs for TV Services or TV Characteristics in their HAP document.  However, I can see that some of the other open-source HomeKit applications have added this functionality.  I'll see what I can find and potentially include the TV functionality in HomeSpan as well.  Please let me know if you know of a definitive source for the TV specs.  Thanks!

**Comment by mLihs** [comment]
Hi as I know there is no official source but different projects that support the Characteristics: 

e.g.
https://github.com/maximkulkin/esp-homekit
https://github.com/merdok/homebridge-webos-tv/blob/master/index.js
https://github.com/NRCHKB/node-red-contrib-homekit-bridged/wiki/Television-Service

maybe this helps.
Right know I got my ESP32 TV Controller work with the Maxim lib. There a still some questions but now I can control my Amp via rs232 :)

**Comment by HomeSpan** [comment]
Added FAQ explaining that Television Services are not currently supported since Apple has not publicly released specs.  Will add as soon as specs are available.

**Comment by Glujaz** [comment]
> Hi as I know there is no official source but different projects that support the Characteristics:
> 
> e.g. https://github.com/maximkulkin/esp-homekit https://github.com/merdok/homebridge-webos-tv/blob/master/index.js https://github.com/NRCHKB/node-red-contrib-homekit-bridged/wiki/Television-Service
> 
> maybe this helps. Right know I got my ESP32 TV Controller work with the Maxim lib. There a still some questions but now I can control my Amp via rs232 :)

Hey, I know it's not great to open issues again, but what you did is actually what I want to do as well : control a rotel amp using RS232. Any guidance on how you did ? Thanks :)

**Comment by mLihs** [comment]
I can share with you my code - I will put them on GitHub so u can use it

**Comment by Glujaz** [comment]
That would be nice ! Thank you :)

(for now, I'm actually trying to at least turn on and off the amp by seeing it as a lamp, but even there, I have issues...)
