### ISSUE TITLE
ESP32C3 (Devkit-M1) crash after triggering door sensors

### ISSUE THREAD

**Issue by FannyLoi** [HomeSpan/HomeSpan#193]
Everything is functional testing a light service.

I've tried with both the garagedooropener and door services.  4-5 seconds after pressing "open" the micro crashes with the following (please ignore the windowshade; I was testing that to see if it could be used instead for my purpose):

Build:Feb  7 2021
rst:0x3 (RTC_SW_SYS_RST),boot:0xc (SPI_FAST_FLASH_BOOT)
Saved PC:0x403d0f8a
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd6100,len:0x484
load:0x403ce000,len:0x90c
load:0x403d0000,len:0x2398
SHA-256 comparison failed:
Calculated: e0c357829f601add6a50d6ea19f89687ec5acf531610506a38b33d09b4a71c7e
Expected: 77332826ec7bc491df854452f675071e3a094e80858dd7d91dd7e27940204216
Attempting to boot anyway...
entry 0x403ce000
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x1 (POWERON),boot:0x4 (DOWNLOAD(USB/UART0/1))
waiting for download

************************************************************
Welcome to HomeSpan!
Apple HomeKit for the Espressif ESP-32 WROOM and Arduino IDE
************************************************************

** Please ensure serial monitor is set to transmit <newlines>

Message Logs:     Level 0
Status LED:       Pin -  *** WARNING: Status LED Pin is UNDEFINED
Device Control:   Pin -  *** WARNING: Device Control Pin is UNDEFINED
Sketch Version:   n/a
HomeSpan Version: 1.4.1
Arduino-ESP Ver.: 2.0.1
ESP-IDF Version:  4.4.0
ESP32 Chip:       ESP32-C3 Rev 3 single-core 4MB Flash
ESP32 Board:      esp32c3
PWM Resources:    6 channels, 4 timers, max 14-bit duty resolution
Sodium Version:   1.0.12-idf  Lib 9.4
MbedTLS Version:  mbed TLS 2.16.11
Sketch Compiled:  Nov 21 2021 17:17:06

Device Name:      HomeSpan Bridge

Configuring Garage Door Opener
Configuring Motorized Window Shade

*** HomeSpan Info ***

➤ Accessory:  AID=1
   ➟ Service AccessoryInformation:  IID=1, UUID="3E"
      ⇨ Characteristic Name("Bridge #1"):  IID=2, UUID="23"
      ⇨ Characteristic Manufacturer("HomeSpan"):  IID=3, UUID="20"
      ⇨ Characteristic SerialNumber("123-ABC"):  IID=4, UUID="30"
      ⇨ Characteristic Model("HS Bridge"):  IID=5, UUID="21"
      ⇨ Characteristic FirmwareRevision("0.9"):  IID=6, UUID="52"
      ⇨ Characteristic Identify(0):  IID=7, UUID="14"
   ➟ Service HAPProtocolInformation:  IID=8, UUID="A2"
      ⇨ Characteristic Version("1.1.0"):  IID=9, UUID="37"
➤ Accessory:  AID=2
   ➟ Service AccessoryInformation:  IID=1, UUID="3E"
      ⇨ Characteristic Name("Garage Door"):  IID=2, UUID="23"
      ⇨ Characteristic Manufacturer("HomeSpan"):  IID=3, UUID="20"
      ⇨ Characteristic SerialNumber("123-ABC"):  IID=4, UUID="30"
      ⇨ Characteristic Model("Door"):  IID=5, UUID="21"
      ⇨ Characteristic FirmwareRevision("0.9"):  IID=6, UUID="52"
      ⇨ Characteristic Identify(0):  IID=7, UUID="14"
   ➟ Service GarageDoorOpener:  IID=8, UUID="41"
      ⇨ Characteristic CurrentDoorState(1):  IID=9, UUID="E", Range=[0,4]
      ⇨ Characteristic TargetDoorState(1):  IID=10, UUID="32", Range=[0,1]
      ⇨ Characteristic ObstructionDetected(0):  IID=11, UUID="24"
➤ Accessory:  AID=3
   ➟ Service AccessoryInformation:  IID=1, UUID="3E"
      ⇨ Characteristic Name("Window Shade"):  IID=2, UUID="23"
      ⇨ Characteristic Manufacturer("HomeSpan"):  IID=3, UUID="20"
      ⇨ Characteristic SerialNumber("123-ABC"):  IID=4, UUID="30"
      ⇨ Characteristic Model("Shade"):  IID=5, UUID="21"
      ⇨ Characteristic FirmwareRevision("0.9"):  IID=6, UUID="52"
      ⇨ Characteristic Identify(0):  IID=7, UUID="14"
   ➟ Service WindowCovering:  IID=8, UUID="8C"
      ⇨ Characteristic CurrentPosition(0):  IID=9, UUID="6D", Range=[0,100]
      ⇨ Characteristic TargetPosition(0):  IID=10, UUID="7C", Range=[0,100]
         ⬌ Set Range for TargetPosition with AID=3, IID=10: Min=0, Max=100, Step=10
      ✘ Characteristic PositionState *** WARNING!  Required Characteristic for this Service not found. ***

Range Check: No Warnings

*** CAUTION: There is 1 WARNING associated with this configuration that may lead to the device becoming non-responsive, or operating in an unexpected manner. ***

Configured as Bridge: YES

Service                         UUID         AID  IID  Update  Loop  Button  Linked Services
------------------------------  ----  ----------  ---  ------  ----  ------  ---------------
AccessoryInformation              3E           1    1     YES    NO      NO  -
HAPProtocolInformation            A2           1    8      NO    NO      NO  -
AccessoryInformation              3E           2    1     YES    NO      NO  -
GarageDoorOpener                  41           2    8     YES   YES      NO  -
AccessoryInformation              3E           3    1     YES    NO      NO  -
WindowCovering                    8C           3    8     YES   YES      NO  -

*** End Info ***

Accessory ID:      DE:4D:C6:6D:9E:65                               LTPK: F2A9F1AB111BCD96F9D8718382A3A2B1C3C6FBCD5B7238E13C5C4D28E3678535
Paired Controller: C553F9AF-164F-49AC-9C39-620A5B5D5EBA   (admin)  LTPK: 88BBA7418460055EBA5E930AA20FD7A4570D68E35D48BDA613088A44D196F584

Accessory configuration has changed.  Updating configuration number to 13

HomeSpan Bridge is READY!

Successfully connected to SSID! IP Address: 192.168.68.128

Starting MDNS...

HostName:      HomeSpan-DE4DC66D9E65.local:80
Display Name:  HomeSpan Bridge
Model Name:    HomeSpan-ESP32
Setup ID:      ASDF

Starting Web (HTTP) Server supporting up to 8 simultaneous connections...

Guru Meditation Error: Core  0 panic'ed (Load access fault). Exception was unhandled.

Core  0 register dump:
MEPC    : 0x42001f96  RA      : 0x42001f6c  SP      : 0x3fc9f9c0  GP      : 0x3fc8dc00  
TP      : 0x3fc7fc78  T0      : 0x4005890e  T1      : 0x40000000  T2      : 0x012d6736  
S0/FP   : 0x3fcadbb4  S1      : 0x3fc934f8  A0      : 0x3fcaef7c  A1      : 0x3c0b1073  
A2      : 0x00000002  A3      : 0x00000000  A4      : 0x00000000  A5      : 0x3fcaef74  
A6      : 0x00000003  A7      : 0x0000000a  S2      : 0x3fc93710  S3      : 0x00010173  
S4      : 0x3c0b1000  S5      : 0x00000001  S6      : 0x3fc94000  S7      : 0x3fc99000  
S8      : 0x3c0b1000  S9      : 0x3c0b3000  S10     : 0x3c0b3000  S11     : 0x3c0b3000  
T3      : 0x00000000  T4      : 0x03a9f0bf  T5      : 0x00000000  T6      : 0xffffffff  
MSTATUS : 0x00001881  MTVEC   : 0x40380001  MCAUSE  : 0x00000005  MTVAL   : 0x00000000  
MHARTID : 0x00000000  

Stack memory:
3fc9f9c0: 0x6f6d6552 0x676e6976 0x44495020 0x3935343d 0x33343736 0x31363433 0x36323836 0x38383138
3fc9f9e0: 0x4c412020 0x3d4d5241 0x30000a30 0x42000a36 0x00000000 0x00000000 0x00000000 0x4200fb7e
3fc9fa00: 0x3fc99000 0x3fc98b40 0x0000001c 0x00000008 0x3fc934f8 0x3fc934f8 0x3fc94000 0x4200a140
3fc9fa20: 0x3fc8dfc4 0x00000001 0x00000000 0x0000003f 0x00000000 0x00000000 0x00000000 0x00000000
3fc9fa40: 0x3c0b55a0 0x00000000 0x000003e8 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fc9fa60: 0x00000000 0x00000000 0x3c0b55a0 0x00000000 0x000003e8 0x00000000 0x00000000 0x00000000
3fc9fa80: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000001 0x3fc8dfc4 0x00000000
3fc9faa0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fc9fac0: 0x00000000 0x3fc99000 0x4200fda6 0x420111c6 0x00000000 0x00000000 0x00000000 0x403896ba
3fc9fae0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5
3fc9fb00: 0x27146414 0x01010107 0x00000001 0x000000ff 0x8800759c 0x7e37e43c 0x00000000 0x7ff80000
3fc9fb20: 0x7f7fffff 0x00000000 0x00000000 0x3fe00000 0x00000000 0x40000000 0xffc00000 0x41dfffff
3fc9fb40: 0x94a03595 0x3fdfffff 0x35afe535 0x3fe00000 0x94a03595 0x3fcfffff 0xffffffff 0x7fefffff
3fc9fb60: 0x00000000 0x3fc00000 0x00000000 0x40300000 0x00000000 0x3ff80000 0x636f4361 0x3fd287a7
3fc9fb80: 0x8b60c8b3 0x3fc68a28 0x509f79fb 0x3fd34413 0x00000000 0x40240000 0x00000000 0x401c0000
3fc9fba0: 0x00000000 0x40140000 0x00000000 0x43500000 0x7fc00000 0x00000000 0x00000010 0x00000000
3fc9fbc0: 0xa5a5a5a5 0x00000154 0x3fc9f8d0 0x0000fa6c 0x3fc955ac 0x3fc955ac 0x3fc9fbc8 0x3fc955a4
3fc9fbe0: 0x00000018 0x3fca1b24 0x3fca1b24 0x3fc9fbc8 0x00000000 0x00000001 0x3fc9dbc4 0x706f6f6c
3fc9fc00: 0x6b736154 0x08139000 0x001c0058 0x00000000 0x3fc9fbc0 0x00000001 0x00000000 0x3fca6f84
3fc9fc20: 0x4201a968 0x0000000b 0x3fc99f5c 0x3fc99fc4 0x3fc9a02c 0x00000000 0x00000000 0x00000001
3fc9fc40: 0x00000000 0x00000000 0x00000000 0x42090f36 0x00000000 0x00000000 0x00000000 0x00000000
3fc9fc60: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fc9fc80: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fc9fca0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fc9fcc0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fc9fce0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fc9fd00: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000001 0x3fc90000 0x00000054
3fc9fd20: 0x00000000 0x3fc9fd20 0x00000000 0x00000000 0x00000000 0x3fc9fd38 0xffffffff 0x3fc9fd38
3fc9fd40: 0x3fc9fd38 0x00000000 0x3fc9fd4c 0xffffffff 0x3fc9fd4c 0x3fc9fd4c 0x00000001 0x00000001
3fc9fd60: 0x00000000 0x3100ffff 0x00000000 0x90a7e105 0x3fc9fd18 0x00000100 0x00000000 0x00000000
3fc9fd80: 0x3fc9a494 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fc9fda0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000

ELF file SHA256: 0000000000000000

Rebooting...

**Comment by HomeSpan** [comment]
I'm not sure I'm following from the above.  As an initial test, can you first check that an example sketch (one of the tutorials) works as expected.  If it does, then that suggests something in your specific code - please provide a link to, or copy of, the code and I can try to debug.  It also may be something related to version 2.0.1 of the board manager - I have not yet tried the latest build from Espressif.

**Comment by FannyLoi** [comment]
Apologies, this was done using and adapting a demo file.  Please see attached -- .ino renamed to .txt
[DualGarageOpener.txt](https://github.com/HomeSpan/HomeSpan/files/7598379/DualGarageOpener.txt)

**Comment by HomeSpan** [comment]
Are you running under 2.0.0 or 2.0.1?

**Comment by FannyLoi** [comment]
I'm running 2.01, but if 2.0 supports the C3 chip, I'll gladly downgrade.

**Comment by HomeSpan** [comment]
Since HS won't compile under 2.0.1 without a patch for the Blinker class, if you are running under 2.0.1 did you use your patch?  If so, that might be the problem - as noted in the separate issue you posted, I need to review the Blinker class given the changes between 2.0.0 and 2.0.1.

**Comment by HomeSpan** [comment]
Yes, please use 2.0.0 for now until I can address the 2.0.1 issue.

**Comment by FannyLoi** [comment]
Much appreciated!

**Comment by FannyLoi** [comment]
Okay, I can confirm the crash still occurs under 2.0.0 using the example file I uploaded (basically no I/O)

**Comment by HomeSpan** [comment]
I have been able to reproduce this issue.  The code works fine on an ESP32 but seems to be failing on an ESP32-C3.  Will debug.

**Comment by HomeSpan** [comment]
I have identified the problem and fixed a long-standing latent bug in how TimeWrite processes work (these are used only for certain Services related to open/closing of doors and locks).  Frankly, I'm not sure why this issue never surfaced on the ESP32 and only affects the ESP32-C3.  Must have something to with the slight variations in compiler logic.

In any case, the issue is fixed and I will release in a small patch this weekend.  In the interim, you can download the dev branch, which contains the fix (as well as a few other additions that will be part of 1.4.2).   Will also try to fix the compilation issue that arises when using Arudino-ESP32 version 2.0.1.

Thanks for catching this issue and providing the example!

**Comment by FannyLoi** [comment]
Wow, huge thanks.  I'm admittedly very rusty in programming, but where/when I can contribute, I will!  I'm so glad you built this project.
