### ISSUE TITLE
ESP32 Arduino 2.01 timer setup (Utils.cpp)

### ISSUE THREAD

**Issue by FannyLoi** [HomeSpan/HomeSpan#194]
It seems the timer setup has changed in a recent version of ESP-IDE.  Doing a little googling, I found what I believe works, but I wanted to post it here for review before committing:

#elif CONFIG_IDF_TARGET_ESP32C3        // ESP32-C3 only has one timer per timer group
  if(b->group){
    timer_group_clr_intr_status_in_isr(TIMER_GROUP_1, TIMER_0); //seems to work
    //TIMERG1.int_clr_timers.t0=1; //no longer works (existing code)
  } else {
    timer_group_clr_intr_status_in_isr(TIMER_GROUP_0, TIMER_0); //seems to work
    //TIMERG0.int_clr_timers.t0=1; //no longer works (existing code)
  }
#endif

**Comment by HomeSpan** [comment]
Thanks for raising this.  In version 2.0.0 the IDF uses different names for certain timer variables in the S2 and C3 chips compared to the original ESP32.  I corrected for this strange convention in HomeSpan v1.4.0 but now it appears they changed once again in version 2.0.1.  I'll review and add to a patch I was planning to release this weekend.

**Comment by HomeSpan** [comment]
The logic in `Blinker::isrTimer()` has been updated to reflect changes from 2.0.0 to 2.0.1 in the Arduino-ESP32 board manager that prevented compilation for ESP32-S2 and C3 chips (the original ESP32 is unaffected).  The patch is included in the dev branch and will be part of the next patch release (sometime in the next few days).  The new logic is now compatible with versions 2.0.1, 2.0.0, and original version 1.0.6 of the Arduino-ESP32 board manager.  The logic will also hopefully be more future-proof to any further IDF changes.

**Comment by HomeSpan** [comment]
This fix for this has now been released in HomeSpan version 1.4.2.

**Comment by FannyLoi** [comment]
Works great, thanks again.
