### ISSUE TITLE
Homkit automation failed

### ISSUE THREAD

**Issue by nishadpathoor** [HomeSpan/HomeSpan#199]
I'm using esp32 with homspan to connect many devices and it works great. 

When I tried with automation it was not working. 

Scenario 1: 
Personal automation to turn off fan when i snooze alarm in the morning. 
It works, because i'm taking the phone to click on snooze. 

Scenario 2:
Same automation instead of snooze i set on a specific time (or 1 hr before sunrise). Here I'm not taking my phone. The esp 32 homespan failed to do the job. 

￼

**Comment by HomeSpan** [comment]
Hmm.  I just tried this on my setup and the automation seems to work fine.  I scheduled a few lights to turn off at a fixed time and they did.  Automation is generally handled by HomeKit and the Home App, not the devices themselves.  Are you using a HomeKit Hub?

**Comment by nishadpathoor** [comment]
Thanks for your quick response. 
The issue occurs only when i kept my homekit idle for long time may be 6-7 hours and schedule something to do. 
For eg. i sleep at 10 and wake up by 5
So when I schedule anything to run at 5 it doesn't. 
From 10PM i'm not using homekit. 

I'm not using homekithub, i connect with my iphone 13. 

One quick question, can i control my device through internet if i connect through a homekit hub such as ipad or apple tv ?

**Comment by HomeSpan** [comment]
Yes, as would be the case for any commercial HomeKit device, you can control a HoneSpan device from anywhere over the internet if an iPad, AppleTV, or HomePod is used as a HomeKit Hub.

**Comment by nishadpathoor** [comment]
Not for commercial use. Do homespan have commercial version ?

**Comment by HomeSpan** [comment]
No, Apple restricts that only to commercial vendors.
