### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by kinkeichun** [HomeSpan/HomeSpan#202]
core_version.h lost the file？or my board install error

**Comment by HomeSpan** [comment]
Sounds like an error on board install.  To ensure your board is installed correctly you may want to first test and compile one of the examples that come with the Arduino-ESP32 library.  Also, don't forget to set the board in the Arduino-IDE to an ESP32 variant.

**Comment by kinkeichun** [comment]
my board install form espressif github select ESP32 Dev Module build。lost file core_version.h。the #include on setting.h

**Comment by HomeSpan** [comment]
You need to install the board with the Board Manager from the Arduino IDE.  Please follow the instructions at https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html.  Also, you should use the STABLE release link.

**Comment by kinkeichun** [comment]
failed still
/Users/kinkeichun/Documents/Arduino/libraries/HomeSpan/src/Settings.h:30:10: fatal error: core_version.h: No such file or directory
 #include <core_version.h>

**Comment by HomeSpan** [comment]
Can you compile an Arduino-ESP32 example?   One that comes with the board manager that is unrelated to HomeSpan?  For example, if you select the Adafruit ESP32 Feather as your board (you do not to have the board itself), you will see numerous examples related to this board under File->Examples in the Arduino Menu Bar.  You should be able to select  any of those examples and successfully compile them (not upload, just compile).  If you don't see this menu, or you get errors compiling, the Arduino-ESP32 board manager has not been properly installed.  May want to start with a fresh install of the Arduino IDE and Arduino-ESP32 board manager.

**Comment by kinkeichun** [comment]
yes ,i am test example EEPROM (in esp32 example open. select board "ESP32 DEV Module") can compile.but you  example still failed.are you need any other libraries to support ?

**Comment by HomeSpan** [comment]
No other libraries are needed.  Can you check that the board manager successfully installed all the files.  The root folder for all board files should be in [User]/Library/Arduino15/packages/esp32/hardware/esp32.  Within that folder there should another folder associated with the version of the Arduino-ESP32 library.  I'm using the latest version, which is 2.0.1.  The full path name for core_version.h is:

[User]/Library/Arduino15/packages/esp32/hardware/esp32/2.0.1/cores/esp32/core_version.h

What version of the Arduino IDE are you using?

**Comment by kinkeichun** [comment]
thank you .failed because board install not complete.
