### ISSUE TITLE
ESP32. HomeSpan's access point blocks main cycle.

### ISSUE THREAD

**Issue by novacom34** [HomeSpan/HomeSpan#213]
We faced with issue on ESP32 where HomeSpan's access point blocks main cycle. Our sketch simultaneously uses WiFi AP and bluetooth connection and once ESP is on AP mode bluetooth does not work. For example WiFiManager library has function 
`wifiManager.setConfigPortalBlocking(false);` which prevents this issue.
Could you please fix it?

**Comment by HomeSpan** [comment]
Can you please provide more details on what you are trying to do?  The AP in HomeSpan is an optional component and is only used to initially program the WiFi Credentials if you choose not to input them from the Command Line (via the IDE).  The entire AP code blocks the main Arduino loop - it has nothing to do with WiFi.   Also, HomeSpan does not use the WiFi Manager.

Note there is a HomeSpan function that allows you to create your own AP if needed, in which case you can program to fit your specific needs.

**Comment by novacom34** [comment]
I have a project for control LED strip using ESP32 chip. Firmware has been written on Arduino EDA. In this project I'm using 3 different ways to communicate with chip, first it's bluetooth, second wifi and third it's a simple button to switch colors. When I use only bluetooth, without wifi, I initiate Access point from HomeSpan library and in this way AP mode blocks loop() cycle and my led strip does not recognize any actions from bluetooth or from button, but actions to connect esp to network is working. Once I connect esp to wifi, all start work as expected. 
The same issue I noticed on another libraries which creates AP, for example WiFiManager, but in that case guys added wifiManager.setConfigPortalBlocking(false); to avoid blocking loop() cycle.
Could you please also inspect your code which is responsible for creating and operating AP mode and find what exactly blocks cycle.

**Comment by HomeSpan** [comment]
Sorry, I'm not understanding your use case.  The AP mode is a temporary configuration mode - its not an operational mode.  You should only enter it ONCE when you initially configure HomeSpan.   You start the AP mode, enter you WiFI credentials, then exit AP mode.  You should not need to enter AP mode again.  AP mode is also optional - you can avoid using it altogether if you configure your device from the CLI.  Note AP mode is itself fully blocks all functions, since it is a temporary configuration routine, not something run alongside of the main code.

Under normal operation HomeSpan will be in STA mode to connect to your WiFi network.  Buttons should work fine.  Is bluetooth not working under normal STA mode?

**Comment by novacom34** [comment]
Fixed on our end. Sorry for distribution.

**Comment by gpena208777** [comment]
> Sorry, I'm not understanding your use case. The AP mode is a temporary configuration mode - its not an operational mode. You should only enter it ONCE when you initially configure HomeSpan. You start the AP mode, enter you WiFI credentials, then exit AP mode. You should not need to enter AP mode again. AP mode is also optional - you can avoid using it altogether if you configure your device from the CLI. Note AP mode is itself fully blocks all functions, since it is a temporary configuration routine, not something run alongside of the main code.
> 
> Under normal operation HomeSpan will be in STA mode to connect to your WiFi network. Buttons should work fine. Is bluetooth not working under normal STA mode?

Can you set a static IP for the AP?

**Comment by HomeSpan** [comment]
No, it's currently hardcoded as 192.168.4.1.   But note that in AP mode HomeSpan is broadcasting its own WiFi network, so there is only one device on the network - there will be no conflict without anything else while you use the AP to input the WiFi Credentials for the network that HomeSpan will eventually connect to.   You can also skip the AP entirely and input your WiFi Credentials directly into the Serial Monitor or even hardcode them into the sketch (though not recommended).

**Comment by gpena208777** [comment]
Do you have any information on utilizing the server?I have a webpage using spiffs and some json urls using wifimanger but I am looking to switch to homespan. Thanks On Jan 4, 2024, at 8:38 PM, HomeSpan ***@***.***> wrote:﻿
No, it's currently hardcoded as 192.168.4.1.   But note that in AP mode HomeSpan is broadcasting its own WiFi network, so there is only one device on the network - there will be no conflict without anything else while you use the AP to input the WiFi Credentials for the network that HomeSpan will eventually connect to.   You can also skip the AP entirely and input your WiFi Credentials directly into the Serial Monitor or even hardcode them into the sketch (though not recommended).

**Comment by HomeSpan** [comment]
Can you provide more details.  What is it that you are trying to do.  What does your current JSON web server do?
