### ISSUE TITLE
Unresponsive after a few sec 

### ISSUE THREAD

**Issue by maragelis** [HomeSpan/HomeSpan#22]
Seems to be an issue with keep alive or something. After a device is controlled it and home app is closed returning to the app show the device, as not responding.  Checking the status it shows clearly the controller is not connected. 

Below you can see that 2.15 controller in the second log is missing, on that phone the device is registered as not responding. 
It takes about 30 to 60 sec for it to return to normal. 

*** HomeSpan Status ***

IP Address:        192.168.2.125

Accessory ID:      95:8E:CE:4F:73:00                               LTPK: 55C361B17165B82A090A9304EBA9A3CE0E4A7BE8FB4C0622472CE295B21637B6
Paired Controller: 4786C5AF-8575-4504-BA59-11D47F1A8A62   (admin)  LTPK: C3D78004B03BD1FB647A0060F95BEA3BA2A525F08787FFF182684E179CF719DE
Paired Controller: 6FAC7B87-87AB-4C2A-9D23-8662370E474A (regular)  LTPK: 6D4E135C9F5F5BF1AC50D39447E6A9F168AF17F7172A0C9CCBB6E82988162E0C
Paired Controller: 0ECE18E3-E7F4-4826-89A2-424F9E8143CE (regular)  LTPK: E737AC061F15244611BC78738F2575D33B36F8A0070A8AAD13C038C1B45BF680
Paired Controller: 52248C77-D74A-482E-944F-5A611B27F27E (regular)  LTPK: D6265CA92A929C122ECE223CF2D1A14C3E905F6D104F55C3772E58BA6B2345E0

Connection #0 192.168.2.87 ID=4786C5AF-8575-4504-BA59-11D47F1A8A62   (admin)
Connection #1 192.168.2.76 ID=6FAC7B87-87AB-4C2A-9D23-8662370E474A (regular)
Connection #2 192.168.2.92 ID=4786C5AF-8575-4504-BA59-11D47F1A8A62   (admin)
Connection #3 192.168.2.95 ID=52248C77-D74A-482E-944F-5A611B27F27E (regular)
Connection #4 192.168.2.15 ID=0ECE18E3-E7F4-4826-89A2-424F9E8143CE (regular)
Connection #5 (unconnected)
Connection #6 (unconnected)
Connection #7 (unconnected)

*** End Status ***

*** HomeSpan Status ***

IP Address:        192.168.2.125

Accessory ID:      95:8E:CE:4F:73:00                               LTPK: 55C361B17165B82A090A9304EBA9A3CE0E4A7BE8FB4C0622472CE295B21637B6
Paired Controller: 4786C5AF-8575-4504-BA59-11D47F1A8A62   (admin)  LTPK: C3D78004B03BD1FB647A0060F95BEA3BA2A525F08787FFF182684E179CF719DE
Paired Controller: 6FAC7B87-87AB-4C2A-9D23-8662370E474A (regular)  LTPK: 6D4E135C9F5F5BF1AC50D39447E6A9F168AF17F7172A0C9CCBB6E82988162E0C
Paired Controller: 0ECE18E3-E7F4-4826-89A2-424F9E8143CE (regular)  LTPK: E737AC061F15244611BC78738F2575D33B36F8A0070A8AAD13C038C1B45BF680
Paired Controller: 52248C77-D74A-482E-944F-5A611B27F27E (regular)  LTPK: D6265CA92A929C122ECE223CF2D1A14C3E905F6D104F55C3772E58BA6B2345E0

Connection #0 192.168.2.87 ID=4786C5AF-8575-4504-BA59-11D47F1A8A62   (admin)
Connection #1 192.168.2.92 ID=4786C5AF-8575-4504-BA59-11D47F1A8A62   (admin)
Connection #2 192.168.2.76 ID=6FAC7B87-87AB-4C2A-9D23-8662370E474A (regular)
Connection #3 192.168.2.95 ID=52248C77-D74A-482E-944F-5A611B27F27E (regular)
Connection #4 (unconnected)
Connection #5 (unconnected)
Connection #6 (unconnected)
Connection #7 (unconnected)

*** End Status ***

**Comment by maragelis** [comment]
*** HomeSpan Status ***

IP Address:        192.168.2.125

Accessory ID:      81:2E:28:43:F8:7C                               LTPK: 35FB34531E5363E76AE3A8C2EF30CD70B4959A843EB33AAEF3677DEC46B08979
Paired Controller: 4786C5AF-8575-4504-BA59-11D47F1A8A62   (admin)  LTPK: C3D78004B03BD1FB647A0060F95BEA3BA2A525F08787FFF182684E179CF719DE
Paired Controller: 6FAC7B87-87AB-4C2A-9D23-8662370E474A (regular)  LTPK: 6D4E135C9F5F5BF1AC50D39447E6A9F168AF17F7172A0C9CCBB6E82988162E0C
Paired Controller: 0ECE18E3-E7F4-4826-89A2-424F9E8143CE (regular)  LTPK: E737AC061F15244611BC78738F2575D33B36F8A0070A8AAD13C038C1B45BF680
Paired Controller: 52248C77-D74A-482E-944F-5A611B27F27E (regular)  LTPK: D6265CA92A929C122ECE223CF2D1A14C3E905F6D104F55C3772E58BA6B2345E0

Connection #0 192.168.2.92 ID=4786C5AF-8575-4504-BA59-11D47F1A8A62   (admin)
Connection #1 192.168.2.27 ID=0ECE18E3-E7F4-4826-89A2-424F9E8143CE (regular)
Connection #2 192.168.2.82 ID=52248C77-D74A-482E-944F-5A611B27F27E (regular)
Connection #3 (unconnected)
Connection #4 (unconnected)
Connection #5 (unconnected)
Connection #6 192.168.2.76 ID=6FAC7B87-87AB-4C2A-9D23-8662370E474A (regular)
Connection #7 (unconnected)

*** End Status ***
** Client #3 Connected: (553 sec) 192.168.2.95
** Client #4 Connected: (553 sec) 192.168.2.87
** Client #5 Connected: (554 sec) 192.168.2.15
In Get Accessories #3 (192.168.2.95)...
In Get Accessories #4 (192.168.2.87)...
In Get Accessories #5 (192.168.2.15)...
In Put Characteristics #4 (192.168.2.87)...
Notification Request for aid=1 iid=11: true
Notification Request for aid=1 iid=12: true
Notification Request for aid=1 iid=13: true
Notification Request for aid=1 iid=14: true
Notification Request for aid=1 iid=15: true
Notification Request for aid=1 iid=16: true
In Get Characteristics #4 (192.168.2.87)...

**Comment by HomeSpan** [comment]
Merged with #21
