### ISSUE TITLE
ESP32-C3 SHA-256 comparison failed (won't boot)

### ISSUE THREAD

**Issue by xkckyle** [HomeSpan/HomeSpan#220]
************************************************************
Welcome to HomeSpan!
Apple HomeKit for the Espressif ESP-32 WROOM and Arduino IDE
************************************************************

** Please ensure serial monitor is set to transmit <newlines>

Message Logs:     Level 0
Status LED:       Pin 5
Device Control:   Pin 6
Sketch Version:   n/a
HomeSpan Version: 1.4.2
Arduino-ESP Ver.: 2.0.2
ESP-IDF Version:  4.4.0
ESP32 Chip:       ESP32-C3 Rev 3 single-core 4MB Flash
ESP32 Board:      esp32c3
PWM Resources:    6 channels, 4 timers, max 14-bit duty resolution
Sodium Version:   1.0.12-idf  Lib 9.4
MbedTLS Version:  mbed TLS 2.16.11
Sketch Compiled:  Dec 30 2021 19:45:55

Device Name:      HomeSpan LEDs

ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x8 (TG1WDT_SYS_RST),boot:0xc (SPI_FAST_FLASH_BOOT)
Saved PC:0x403867b6
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd6100,len:0x420
load:0x403ce000,len:0x90c
load:0x403d0000,len:0x236c
SHA-256 comparison failed:
Calculated: ccb0d00bac7e84e1d90a12e4f75f4ab6c5f7e71bb209afd5819c4c9557a6db71
Expected: c9cf160580940ec7801c73b16423824e72ad12055c732e83ce66332240af42a7
Attempting to boot anyway...
entry 0x403ce000

************************************************************
Welcome to HomeSpan!
Apple HomeKit for the Espressif ESP-32 WROOM and Arduino IDE
************************************************************

**Comment by HomeSpan** [comment]
This error message seems to occur with any ESP32-C3 sketch, unrelated to HomeSpan.  However, it seems the error may be in the error message itself since programs seems to work fine anyway.  May want to make note of this on the Arduino-ESP32 GitHub site (if they are not already aware).

**Comment by xkckyle** [comment]
I ran a different example and it seems to work? I'm not sure why the first sketch continuously restarts..

ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x1 (POWERON),boot:0xc (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd6100,len:0x420
load:0x403ce000,len:0x90c
load:0x403d0000,len:0x236c
SHA-256 comparison failed:
Calculated: ccb0d00bac7e84e1d90a12e4f75f4ab6c5f7e71bb209afd5819c4c9557a6db71
Expected: c9cf160580940ec7801c73b16423824e72ad12055c732e83ce66332240af42a7
Attempting to boot anyway...
entry 0x403ce000

************************************************************
Welcome to HomeSpan!
Apple HomeKit for the Espressif ESP-32 WROOM and Arduino IDE
************************************************************

** Please ensure serial monitor is set to transmit <newlines>

Message Logs:     Level 0
Status LED:       Pin -  *** WARNING: Status LED Pin is UNDEFINED
Device Control:   Pin -  *** WARNING: Device Control Pin is UNDEFINED
Sketch Version:   n/a
HomeSpan Version: 1.4.2
Arduino-ESP Ver.: 2.0.2
ESP-IDF Version:  4.4.0
ESP32 Chip:       ESP32-C3 Rev 3 single-core 4MB Flash
ESP32 Board:      esp32c3
PWM Resources:    6 channels, 4 timers, max 14-bit duty resolution
Sodium Version:   1.0.12-idf  Lib 9.4
MbedTLS Version:  mbed TLS 2.16.11
Sketch Compiled:  Dec 30 2021 19:55:22

Device Name:      HomeSpan LightBulb


*** HomeSpan Info ***

➤ Accessory:  AID=1
   ➟ Service AccessoryInformation:  IID=1, UUID="3E"
      ⇨ Characteristic Name("My Table Lamp"):  IID=2, UUID="23"
      ⇨ Characteristic Manufacturer("HomeSpan"):  IID=3, UUID="20"
      ⇨ Characteristic SerialNumber("123-ABC"):  IID=4, UUID="30"
      ⇨ Characteristic Model("120-Volt Lamp"):  IID=5, UUID="21"
      ⇨ Characteristic FirmwareRevision("0.9"):  IID=6, UUID="52"
      ⇨ Characteristic Identify(0):  IID=7, UUID="14"
   ➟ Service HAPProtocolInformation:  IID=8, UUID="A2"
      ⇨ Characteristic Version("1.1.0"):  IID=9, UUID="37"
   ➟ Service LightBulb:  IID=10, UUID="43"
      ⇨ Characteristic On(0):  IID=11, UUID="25"

Range Check: No Warnings


Configured as Bridge: NO

Service                         UUID         AID  IID  Update  Loop  Button  Linked Services
------------------------------  ----  ----------  ---  ------  ----  ------  ---------------
AccessoryInformation              3E           1    1      NO    NO      NO  -
HAPProtocolInformation            A2           1    8      NO    NO      NO  -
LightBulb                         43           1   10      NO    NO      NO  -

*** End Info ***

Accessory ID:      2A:A8:2D:2A:94:27                               LTPK: 99AF5F879B2B4AAFA35AC6C0C00140860B964ABED189BDAF92829206C6411C08
No Paired Controllers

Accessory configuration number: 1

*** WIFI CREDENTIALS DATA NOT FOUND.  YOU MAY CONFIGURE BY TYPING 'W <RETURN>'.

HomeSpan LightBulb is READY!

**Comment by HomeSpan** [comment]
Check the pins you defined for the LED and Control in the first sketch. GPIO6 is a special pin and input enabled depending on fuse settings on the chip.  May want to try a different pin in case that is the issue.  GPIO5 for the LED should be fine.

In your second sketch the Control and LED pins are not defined, so no issue with picking a "bad" pin.

**Comment by xkckyle** [comment]
I'm such a noob, thanks!
