### ISSUE TITLE
extras/PwmPin.h: No such file or directory  #include "extras/PwmPin.h"

### ISSUE THREAD

**Issue by breitburg** [HomeSpan/HomeSpan#221]
I tried to compile a Dimmable LED example and got this fatal error.

**Comment by HomeSpan** [comment]
Are you compiling the example exactly (no modifications to anything)?  Perhaps the HomeSpan library did not install correctly?  Can you check your library to make sure the extras/PwmPin.h file is included?  I assume you are using Arduino IDE (I'm using 1.8.16).

**Comment by breitburg** [comment]
The issue was that .ino file and the directory must have same name
