### ISSUE TITLE
"No Response" after working for a while #2

### ISSUE THREAD

**Issue by aLAN-LDZ** [HomeSpan/HomeSpan#241]
Hi,

I decided to set up a separate topic so as not to disturb you in the previous one, I have the same problem as my colleague below, after some time the devices do not respond (other original ones work without a problem)

1) Unfortunately, my ESP device works without a computer connection - is there any log saving option? Do I just have to hook up my computer for a while and wait for the problem to occur?

2) It happens several times a day, and sometimes not at all, the ip on the router is permanently assigned. What can I throw here for a better diagnosis of the problem?

3) the program code is not complicated so I doubt it is causing the problem

4) Unfortunately, the device does not reconnect without restartin

Fresh start LOG:
`************************************************************
Welcome to HomeSpan!
Apple HomeKit for the Espressif ESP-32 WROOM and Arduino IDE
************************************************************

** Please ensure serial monitor is set to transmit <newlines>

Message Logs:     Level 1
Status LED:       Pin 2
Device Control:   Pin -  *** WARNING: Device Control Pin is UNDEFINED
Sketch Version:   n/a
HomeSpan Version: 1.4.2
Arduino-ESP Ver.: 2.0.2
ESP-IDF Version:  4.4.0
ESP32 Chip:       ESP32-D0WDQ6 Rev 1 dual-core 4MB Flash
ESP32 Board:      esp32
PWM Resources:    16 channels, 8 timers, max 20-bit duty resolution
Sodium Version:   1.0.12-idf  Lib 9.4
MbedTLS Version:  mbed TLS 2.16.11
Sketch Compiled:  Jan 25 2022 17:41:38

Device Name:      GrowBOX

Configuring Water Level Sensor

*** HomeSpan Info ***

➤ Accessory:  AID=1
   ➟ Service AccessoryInformation:  IID=1, UUID="3E"
      ⇨ Characteristic Name("GrowBOX"):  IID=2, UUID="23"
      ⇨ Characteristic Manufacturer("HomeSpan"):  IID=3, UUID="20"
      ⇨ Characteristic SerialNumber("123-ABC"):  IID=4, UUID="30"
      ⇨ Characteristic Model("HS Bridge"):  IID=5, UUID="21"
      ⇨ Characteristic FirmwareRevision("0.9"):  IID=6, UUID="52"
      ⇨ Characteristic Identify(0):  IID=7, UUID="14"
   ➟ Service HAPProtocolInformation:  IID=8, UUID="A2"
      ⇨ Characteristic Version("1.1.0"):  IID=9, UUID="37"
➤ Accessory:  AID=2
   ➟ Service AccessoryInformation:  IID=1, UUID="3E"
      ⇨ Characteristic Name("Light"):  IID=2, UUID="23"
      ⇨ Characteristic Manufacturer("HomeSpan"):  IID=3, UUID="20"
      ⇨ Characteristic SerialNumber("123-ABC"):  IID=4, UUID="30"
      ⇨ Characteristic Model("20mA LED"):  IID=5, UUID="21"
      ⇨ Characteristic FirmwareRevision("0.9"):  IID=6, UUID="52"
      ⇨ Characteristic Identify(0):  IID=7, UUID="14"
   ➟ Service LightBulb:  IID=8, UUID="43"
      ⇨ Characteristic On(1):  IID=9, UUID="25" (restored)
➤ Accessory:  AID=3
   ➟ Service AccessoryInformation:  IID=1, UUID="3E"
      ⇨ Characteristic Name("Fan"):  IID=2, UUID="23"
      ⇨ Characteristic Manufacturer("HomeSpan"):  IID=3, UUID="20"
      ⇨ Characteristic SerialNumber("123-ABC"):  IID=4, UUID="30"
      ⇨ Characteristic Model("20mA LED"):  IID=5, UUID="21"
      ⇨ Characteristic FirmwareRevision("0.9"):  IID=6, UUID="52"
      ⇨ Characteristic Identify(0):  IID=7, UUID="14"
   ➟ Service Switch:  IID=8, UUID="49"
      ⇨ Characteristic On(0):  IID=9, UUID="25" (restored)
➤ Accessory:  AID=4
   ➟ Service AccessoryInformation:  IID=1, UUID="3E"
      ⇨ Characteristic Name("Water"):  IID=2, UUID="23"
      ⇨ Characteristic Manufacturer("HomeSpan"):  IID=3, UUID="20"
      ⇨ Characteristic SerialNumber("123-ABC"):  IID=4, UUID="30"
      ⇨ Characteristic Model("20mA LED"):  IID=5, UUID="21"
      ⇨ Characteristic FirmwareRevision("0.9"):  IID=6, UUID="52"
      ⇨ Characteristic Identify(0):  IID=7, UUID="14"
   ➟ Service Switch:  IID=8, UUID="49"
      ⇨ Characteristic On(0):  IID=9, UUID="25"
➤ Accessory:  AID=5
   ➟ Service AccessoryInformation:  IID=1, UUID="3E"
      ⇨ Characteristic Name("Water Level Sensor"):  IID=2, UUID="23"
      ⇨ Characteristic Manufacturer("HomeSpan"):  IID=3, UUID="20"
      ⇨ Characteristic SerialNumber("123-ABC"):  IID=4, UUID="30"
      ⇨ Characteristic Model("Sensor"):  IID=5, UUID="21"
      ⇨ Characteristic FirmwareRevision("0.9"):  IID=6, UUID="52"
      ⇨ Characteristic Identify(0):  IID=7, UUID="14"
   ➟ Service ContactSensor:  IID=8, UUID="80"
      ⇨ Characteristic ContactSensorState(0):  IID=9, UUID="6A", Range=[0,1] (restored)

Range Check: No Warnings

Configured as Bridge: YES

Service                         UUID         AID  IID  Update  Loop  Button  Linked Services
------------------------------  ----  ----------  ---  ------  ----  ------  ---------------
AccessoryInformation              3E           1    1      NO    NO      NO  -
HAPProtocolInformation            A2           1    8      NO    NO      NO  -
AccessoryInformation              3E           2    1      NO    NO      NO  -
LightBulb                         43           2    8     YES    NO      NO  -
AccessoryInformation              3E           3    1      NO    NO      NO  -
Switch                            49           3    8     YES    NO      NO  -
AccessoryInformation              3E           4    1      NO    NO      NO  -
Switch                            49           4    8     YES   YES      NO  -
AccessoryInformation              3E           5    1      NO    NO      NO  -
ContactSensor                     80           5    8      NO   YES      NO  -

*** End Info ***

Accessory ID:      27:31:0B:DB:79:3E                               LTPK: 081906DB8C033513F750870029C250FC0642E87CCD432488AFEBF715CA706E20
Paired Controller: F57C0A28-93B6-44B9-9DAA-629E0C382500   (admin)  LTPK: 6B73B5F27465A7640BDD6FABDBE69C7306891B809766F7932D5F10EADE0A7EFF
Paired Controller: F8DF2638-67CF-4136-A1AC-6A8EFCE41649 (regular)  LTPK: 4430DA86683BF4B189764E1924FD26B09C227F554AA8AF3F4A915820AC7D8D4A

Accessory configuration number: 132

GrowBOX is READY!

Trying to connect to aLAN.  Waiting 1 second(s) for response...
Trying to connect to aLAN.  Waiting 2 second(s) for response...
Trying to connect to aLAN.  Waiting 4 second(s) for response...
Successfully connected to aLAN! IP Address: 192.168.50.246

Starting MDNS...

HostName:      HomeSpan-27310BDB793E.local:80
Display Name:  GrowBOX
Model Name:    HomeSpan-ESP32
Setup ID:      HSPN

Starting OTA Server: GrowBOX at 192.168.50.246
Authorization Password: Enabled

Starting Web (HTTP) Server supporting up to 8 simultaneous connections...

** Client #0 Connected: (14 sec) 192.168.50.143 on Socket 3/16
In Get Accessories #0 (192.168.50.143)...
In Get Characteristics #0 (192.168.50.143)...
In Get Characteristics #0 (192.168.50.143)...
In Get Characteristics #0 (192.168.50.143)...
In Get Characteristics #0 (192.168.50.143)...
In Get Characteristics #0 (192.168.50.143)...
In Put Characteristics #0 (192.168.50.143)...
Notification Request for aid=5 iid=9: true
In Get Characteristics #0 (192.168.50.143)...
In Get Characteristics #0 (192.168.50.143)...
In Put Characteristics #0 (192.168.50.143)...
Notification Request for aid=4 iid=9: true
In Get Characteristics #0 (192.168.50.143)...
In Put Characteristics #0 (192.168.50.143)...
Notification Request for aid=3 iid=9: true
In Get Characteristics #0 (192.168.50.143)...
In Get Characteristics #0 (192.168.50.143)...
In Get Characteristics #0 (192.168.50.143)...
In Get Characteristics #0 (192.168.50.143)...
In Get Characteristics #0 (192.168.50.143)...
In Get Characteristics #0 (192.168.50.143)...
`

**Comment by aLAN-LDZ** [comment]
It seems that after upgrading to Arduino-ESP Ver .: 2.0.2 the problem has been resolved.

**Comment by nicosandller** [comment]
Do you know how to upgrade `Arduino-ESP` on PlatformIO @aLAN-LDZ ?

**Comment by Jason2866** [comment]
@nicosandller  The platform is not compatible (using old toolchains) just updating platform_packages is NOT enough!

**Comment by nicosandller** [comment]
You're right in that case this would do it right?

```
platform = https://github.com/platformio/platform-espressif32.git#feature/arduino-upstream
platform_packages =
   framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.2
```
