### ISSUE TITLE
mDNS with Ethernet is possible

### ISSUE THREAD

**Issue by fredlcore** [HomeSpan/HomeSpan#243]
Hi, 

I just stumbled across this amazing project, thanks a lot for all your effort!
I saw in your FAQ that you are looking for a way to have mDNS support for an Ethernet-connected ESP32. In my project [BSB-LAN](https://github.com/fredlcore/BSB-LAN) we're using (among others) an Olimex EVB which comes with an Ethernet port and we use the ESPmDNS.h library which works well both over WiFi as well as Ethernet. So maybe this helps?

In that regard, I would really love to implement HomeSpan in our project, but this seems not to be possible because HomeSpan handles all WiFi-related matters and some other stuff (such as OTA-updates). Would it be possible to have a "stripped-down" version of HomeSpan which defines certain requirements (such as mDNS running etc.) that the "host" code has to provide and still be able to run it then? Otherwise, I don't see a possibility to implement it in a project like ours which has grown organically over the years to a size where pulling out all these functions and leave them to HomeSpan is probably not feasible (especially since users might want to disable HomeSpan functionality and then the other functions still have to be available). But if you have any ideas, I'd be more than happy to hear them!

**Comment by HomeSpan** [comment]
Thanks for the MDNS tip - I'll have to check it out.

In terms of integrating HomeSpan into your project, it sounds possible.  The code is highly commented and you should be able to replace key functions (such as MDNS) with your own calls.  Things like OTA are optional so those could either be ignored or deleted altogether.  The one thing to note is that although Apple HomeKit operates over WiFi, there are some specific protocols and requirements that may or may not be compatible with operating in an environment where WiFi is managed separately.  First, it uses HTTP with its own custom Apple-specified encryption requirements.  This means whatever methods you use to manage the WiFi (or Ethernet) stack provides sufficient flexibility for HomeSpan to encrypt/decrypt the data in a POST web command using its own protocol.  The second is that all connections must be left open indefinitely.  Unlike a web server, where the server may provide data to the client (such as a web page) and then close the connection, HomeKit connections are controlled by the client.  Once a client connects, a (complicated) Apple-specific protocol is run to perform various handshakes, keys are exchanged, and the connection remains open, which allows the HomeKit device to send updates to the clients at any time.  You'll need to make sure whatever WiFi libraries or logic you use provides sufficient flexibility to allow HomeSpan to manage its connections.

One thing you may want to consider is using HomeSpan on a standalone basis as an alternative your users can choose.  You still need to add all the customization to control your heating units, but it would avoid needing to merge distinct code bases.

**Comment by fredlcore** [comment]
Thank you very much for your fast, comprehensive and very helpful answer, very much appreciated! This will give me some starters where to look at (and I already realized that your code is exceptionally well documented, something I can't say about our project ;) ). Also the option to run HomeSpan as a standalone service is something I'll look into.

Thanks and keep up the great work!
