### ISSUE TITLE
TV controller doesn't work on Apple Watch

### ISSUE THREAD

**Issue by atban98** [HomeSpan/HomeSpan#245]
I am using the Television example and it works perfectly with my iPhone. I am also able to switch On/Off the accessory with my Apple Watch in the HomeKit app. The TV also appears in the Watch's remote app, but when I open its remote control and press a button, it freezes. The serial terminal (L2 log) is not printing anything, so I guess it doesn't get the commands.
Some screenshots:
The remote control appears:
![272083954_229652575933246_4700783881997245594_n](https://user-images.githubusercontent.com/62559545/151696795-ce643620-a71c-4c0d-92fc-5ef6112d6a5f.png)
After pressing a button:
![271886563_1543571499346589_7158809715323945209_n](https://user-images.githubusercontent.com/62559545/151696797-2843382f-b3dc-476f-b295-760100d9812a.png)

Apple Watch Series 5, watchOS 8.4

**Comment by HomeSpan** [comment]
Unfortunately I don't think this is a HomeSpan issue, but rather a communications issue between the Apple Watch and HomeKit (given that it works on the iPhone).
