### ISSUE TITLE
How to rename accessory in code?

### ISSUE THREAD

**Issue by tysonmatanich** [HomeSpan/HomeSpan#246]
When I change the name of the an accessory with `Characteristic::Name` it doesn't seem to update in the Home app.
```c
homeSpan.begin(Category::Lighting,"HomeSpan LightBulb");
new SpanAccessory();
new Service::AccessoryInformation();
new Characteristic::Name("My Renamed Table Lamp"); 
```

From Example 1:
https://github.com/HomeSpan/HomeSpan/blob/ce011de7679856497964a93ef219cea2eb977408/examples/01-SimpleLightBulb/01-SimpleLightBulb.ino#L80

The Home app allow for manually renaming it but I was wondering it there it any way to force a name change in code. Thanks!

**Comment by HomeSpan** [comment]
Once a device is paired, the Home App caches and remembers various parameters, including the original name used at pairing.  I have seen instances where after some time (minutes to hours) the Home App updates the name to reflect changes in the software, but sometimes it remains tied indefinitely to the original.

To force a change via the software you need to make the Home App somehow forget about your device.  To do so, first unpair the device from the Home App.  Then, before re-pairing, type "H" into the Serial Monitor, which instructs HomeSpan to reboot with a new randomly-generated HomeKit Device ID (this is separate from the Set-Up ID, which will be unaffected by the "H" command).  Finally, you can re-pair with HomeSpan.  The Home App will see a different Device ID and not use any info from its cache.

This is arguably a flaw (one of many) in how the HomeKit HAP-R2 protocol is implemented in the Home App.  When you change the Name() Characteristic, HomeSpan updates the HomeKit configuration-number for the device and, in accordance with HAP-R2 specs, broadcasts this new config number via MDNS.  The Home App is supposed to recognize this and reset any saved info.  It appears to do so for structural changes (such as adding a new accessory) but ignores changes to Names (at least initially).

**Comment by tysonmatanich** [comment]
Thanks for the reply, it confirms my suspicion. It would be great if the HomeSpan documentation had a list of known characteristics etc. prone to not update and how to resolve with the `H` command.
