### ISSUE TITLE
Output is inverted 

### ISSUE THREAD

**Issue by Aaru911** [HomeSpan/HomeSpan#248]
I'm trying do home automation and for that i use example 5 working LEDs and added 2 more accessories to control 4 relay module And i uploaded that code, now when i try to turn on LED it activates relays and leds. and when i turn it on it turns. I'm using version 1.4.2

**Comment by HomeSpan** [comment]
Sorry, can you clarify the question.  Not sure I understand the issue.

**Comment by Aaru911** [comment]
https://user-images.githubusercontent.com/70468123/152733719-393a0db6-c849-4cd0-aa64-070b4d8015ce.MOV

**Comment by Aaru911** [comment]
> Sorry, can you clarify the question.  Not sure I understand the issue. 

When i try to then the switch on the opposite thing happens i have please can you help me

**Comment by HomeSpan** [comment]
Without knowing the details of the relays and how you wired them it is not possible for me to know for sure, but my guess is that you are using relays that trigger on a LOW signal.  The example code is designed to produce a HIGH signal on the pins you specify when you turn ON a light, and a LOW signal when you turn OFF a light.  If an LED is connected (through a resistor) directly to those pins, the LED will operate properly.

But relays come in many forms - they can be normally open or normally closed.  They can be temporary or they can latch.  They can trigger on a HIGH signal or trigger on a LOW signal.  You'll have to look at your relays and determine what signals they expect to turn "on," and adjust the code accordingly, which likely will mean changing the logic of the digitalWrite() to produce the reverse.  Something like: `digitalWrite(ledPin,!power->getNewVal())`.

**Comment by Aaru911** [comment]
> Without knowing the details of the relays and how you wired them it is not possible for me to know for sure, but my guess is that you are using relays that trigger on a LOW signal.  The example code is designed to produce a HIGH signal on the pins you specify when you turn ON a light, and a LOW signal when you turn OFF a light.  If an LED is connected (through a resistor) directly to those pins, the LED will operate properly.
> 
> 
> 
> But relays come in many forms - they can be normally open or normally closed.  They can be temporary or they can latch.  They can trigger on a HIGH signal or trigger on a LOW signal.  You'll have to look at your relays and determine what signals they expect to turn "on," and adjust the code accordingly, which likely will mean changing the logic of the digitalWrite() to produce the reverse.  Something like: `digitalWrite(ledPin,!power->getNewVal())`.  
> 
> 
> 
> 

Thank you so much it worked
