### ISSUE TITLE
Automatically add accessory to network

### ISSUE THREAD

**Issue by oleksiikutuzov** [HomeSpan/HomeSpan#257]
First of all, thanks for your effort to create and maintain this great library!

I wonder, whether it's possible to implement that thing when you just scan the qr code and it uses credentials of wifi network you are currently connected to. I suppose it's also part of HomeKit protocol, isn't it?

<img width="211" alt="Screenshot 2022-02-15 at 23 20 59" src="https://user-images.githubusercontent.com/8535871/154161408-0e7a0cc9-4f44-47aa-807a-3dc1fd09233c.png">

**Comment by HomeSpan** [comment]
Unfortunately Apple implemented this only for commercial products and did not enable auto-config in the non-commercial HAP-R2 protocol.  I agree it would be great if they did as this would be a very useful feature to add to HomeSpan.
