### ISSUE TITLE
Multiple motion sensors

### ISSUE THREAD

**Issue by micahvdm** [HomeSpan/HomeSpan#291]
Hi, was wondering if it is possible to have 5-7 motion sensors on a single bridge?
I can't find any examples of motion sensors in the docs, so not quite sure where to start.

Do you have any examples of motion sensors?

**Comment by HomeSpan** [comment]
Yes, I don't see why this would be problem, though I'm not sure exactly how the sensors will be shown in the Home App.  Apple keeps changing the Home App display for things like sensors, but my guess is they will be displayed in the top row of the Home App whenever triggered.  More importantly, you should be able to set scenes and triggers directly in the Home App based on motion detection.

MotionSensor is a native service in HAP-R2 so it can be accessed as Service::MotionSensor in HomeSpan.  I recommend placing your code and logic to read the motion sensor and determine whether it is active or inactive (e.g. after some set period of time) inside the loop() function of a Service you derive from Service::MotionSensor.   See [Example 12 - Service Loops](https://github.com/HomeSpan/HomeSpan/tree/master/examples/12-ServiceLoops) for you how to do this with a temperature sensor.  The logic of a motion sensor would be quite similar.

**Comment by micahvdm** [comment]
Thanks, I managed to implement this now!

**Comment by jpasqua** [comment]
@micahvdm it would be great to see your code. I’ll be building a motion sensor soon.
