### ISSUE TITLE
Running a motor in loop is laggy

### ISSUE THREAD

**Issue by iKrushYou** [HomeSpan/HomeSpan#293]
Hey, love the library so far!

I am trying to create a controller for roller blinds. I am using the [AccelStepper](https://www.airspayce.com/mikem/arduino/AccelStepper/ConstantSpeed_8pde-example.html) library and it requires that the stepper be `run` in the `loop` function. It seems, though, that the `homeSpan.poll()` function tends to be blocking at times and is causing unexpected issues with driving the stepper motor. 

The issue I am seeing is that the stepper doesn't smoothly accelerate anymore due to what I am assuming is the `poll` function blocking the loop. Is there a recommended way of implementing something like this where the stepper run function can operate more smoothly? 

I will include my code although I don't know how much it will help. I have also added some extra debugging code to flip the target position outside of the update function.

```
#include <Arduino.h>
#include <AccelStepper.h>
#include <HomeSpan.h>

const float stepAngle = 1.8;
const int microStep = 16;
const int weirdMultiplier = 4;
const int stepsPerRevolution = 360 / stepAngle * microStep * weirdMultiplier;
const int maxSpeedRpm = 60;
const int maxStepsPerSecond = stepsPerRevolution * maxSpeedRpm / 60;
const float rotationsToClosed = 2;
const int closedPosition = stepsPerRevolution * rotationsToClosed;

int getStepPositionForPct(float positionPct) {
  return positionPct * closedPosition;
}

struct RollerBlind : Service::WindowCovering {

  int stepPin;
  int dirPin;     
  int enablePin;                          
  SpanCharacteristic *currentPosition;     
  SpanCharacteristic *targetPosition;      
  AccelStepper *stepper;     
  
  RollerBlind(int stepPin, int dirPin, int enablePin) : Service::WindowCovering() {
    currentPosition = new Characteristic::CurrentPosition();  
    targetPosition = new Characteristic::TargetPosition();    

    this->stepPin = stepPin;   
    this->dirPin = dirPin;   
    this->enablePin = enablePin;     

    stepper = new AccelStepper(AccelStepper::FULL2WIRE, stepPin, dirPin, enablePin);   

    Serial.println("stepsPerRevolution: " + String(stepsPerRevolution));
    stepper->setMaxSpeed(maxStepsPerSecond);
    stepper->setAcceleration(stepsPerRevolution);
  } 
  
  boolean update() {    
    float positionPct = targetPosition->getNewVal() / 100.0;   
    int position = getStepPositionForPct(positionPct);
    stepper->moveTo(position);
    Serial.println("Move To " + String(stepper->targetPosition()));

    return true;
  } 
  
};

RollerBlind *rollerBlind;

void setup() {
  Serial.begin(115200);

  homeSpan.setLogLevel(1);  
  homeSpan.begin();

  new SpanAccessory();

  new Service::AccessoryInformation();            
    new Characteristic::Name("Roller Blind");      
    new Characteristic::Manufacturer("HomeSpan");  
    new Characteristic::SerialNumber("123-ABC");   
    new Characteristic::Model("Blind");     
    new Characteristic::FirmwareRevision("0.9"); 
    new Characteristic::Identify();             

  new Service::HAPProtocolInformation();       
    new Characteristic::Version("1.1.0");      

  rollerBlind = new RollerBlind(32, 33, 25);     
  
}

void loop() {
  homeSpan.poll();

   // Debug CodeChange direction at the limits
  if (rollerBlind->stepper->distanceToGo() == 0) {
    if (rollerBlind->stepper->currentPosition() > 0) {
      rollerBlind->stepper->moveTo(0);
    } else {
      rollerBlind->stepper->moveTo(closedPosition);
    }
    Serial.println("Move To " + String(rollerBlind->stepper->targetPosition()));
  }
  rollerBlind->stepper->run();
}
```

Here's an example without HomeSpan that works as expected 

```
AccelStepper stepper1(AccelStepper::FULL2WIRE, 32, 33, 25);
void setup()
{      
  Serial.begin(115200);
    stepper1.setMaxSpeed(maxStepsPerSecond);
    stepper1.setAcceleration(maxStepsPerSecond);
    stepper1.moveTo(closedPosition); 
    Serial.println("Move To " + String(stepper1.targetPosition()));
}
void loop()
{
    // Change direction at the limits
    if (stepper1.distanceToGo() == 0) {
      if (stepper1.currentPosition() > 0) {
        stepper1.moveTo(0);
      } else {
        stepper1.moveTo(closedPosition);
      }
      Serial.println("Move To " + String(stepper1.targetPosition()));
    }
    stepper1.run();
}
```

**Comment by iKrushYou** [comment]
Also, as a second question (let me know if I should raise another issue)

What would be the recommended way to update the `PositionState` characteristic since it would need to be updated outside of the `update` method? My plan is to just updated it in the loop when I've detected that the position is either open or closed

**Comment by danilkorotkov** [comment]
you can try to put this code or homespan.poll() to 0 core
```
 if (rollerBlind->stepper->distanceToGo() == 0) {
    if (rollerBlind->stepper->currentPosition() > 0) {
      rollerBlind->stepper->moveTo(0);
    } else {
      rollerBlind->stepper->moveTo(closedPosition);
    }
    Serial.println("Move To " + String(rollerBlind->stepper->targetPosition()));
  }
  rollerBlind->stepper->run();
```
https://github.com/HomeSpan/HomeSpan/discussions/262

**Comment by HomeSpan** [comment]
Unfortunately AccelStepper may not be useable with HomeSpan since it requires frequent calls, which leads to lags as you've noticed.  The HomeSpan polling function needs to do a lot of work, monitor for incoming connections, requests, etc., and can be interrupted if needed.  But that requires libraries written using interrupts - AccelStepper seems to measure clock time and "bit-bang" using digital writes as needed.

A while ago I exploring using the ESP32's native Motor controller, but it was not as robust as I would have liked and I did not bother trying to embed into HomeSpan (I may revisit this and see how the MCPWM functions work with the ESP-S2 and -C3 chips).  Also, it seems that stepper motor controllers have become very cheap and I think the preferred method is to use a dedicated controller so that the main microcontroller does not have to manage the individual steps.

For some more info, see Discussion #58.  There is another library (https://github.com/gin66/FastAccelStepper) that may be better suited for use with HomeSpan, though I have not tried it myself.

As for your second question, in general I recommend adding this type of logic to the loop() function of the Service itself (see, [Tutorial Example-13](https://github.com/HomeSpan/HomeSpan/tree/master/examples/13-TargetStates) for an example using doors and windows).

**Comment by iKrushYou** [comment]
@danilkorotkov that was exactly the solution I needed! I configured `homeSpan.poll()` to occur in the prioritized core 0 and now all of my lag is gone from the stepper driver

**Comment by Olivierbkk** [comment]
Hello,

`For some more info, see Discussion https://github.com/HomeSpan/HomeSpan/discussions/58. There is another library (https://github.com/gin66/FastAccelStepper) that may be better suited for use with HomeSpan, though I have not tried it myself.`

Have you tested it already? Any good result? I am doing a smart curtain and I am planning to use a stepper motor.

**Comment by Olivierbkk** [comment]
> @danilkorotkov that was exactly the solution I needed! I configured `homeSpan.poll()` to occur in the prioritized core 0 and now all of my lag is gone from the stepper driver

that's interesting, how did you do that?
