### ISSUE TITLE
TargetTemperature, HeatingThresholdTemperature, CoolingThresholdTemperature characteristics and get/setVal

### ISSUE THREAD

**Issue by FannyLoi** [HomeSpan/HomeSpan#296]
I created a thermostat service and noticed when attempting to set the target temperatures (TargetTemperature, HeatingThresholdTemperature, CoolingThresholdTemperature) all set values were whole number in degrees C instead of giving the setpoint in degrees C with .1 degree precision.  This results in set points being a degree or two different (in Degrees F) than what I assume HomeKit really sent.  I confirmed that using setRange(min,max,stepValue) does not appear to resolve the issue, so my assumption is you have the correct stepValue set for these characteristics, although I was unable to find where in code this is maintained.

Here is what i see in debug log, where the trailing decimal seems to get lopped off:

> PUT /characteristics HTTP/1.1
> Host: HomeSpan\032Server-2._hap._tcp.local
> Content-Length: 93
> Content-Type: application/hap+json
> ------------ END BODY! ------------
> {"characteristics":[{"aid":1,"iid":12,"value":17.800000000000001}],"pid":3524024862036870145}
> ------------ END JSON! ------------
> In Put Characteristics #0 (192.168.68.113)...
> target: 17
> Updating aid=1 iid=12 (okay)

Any thoughts/insight on this would be great.  Thanks.

**Comment by HomeSpan** [comment]
Are you specifying the template parameter as float (or double) as such:  `getVal<float>()`, `getNewVal<double>()`, etc.  Note that if a template parameter is not specified, HomeSpan defaults to \<int\>, which would explain why the 17.8 is being cast to just 17.

**Comment by FannyLoi** [comment]
And there you have it.  Thanks again Gregg!
