### ISSUE TITLE
Delayed Response and Low Value Transition Granularity

### ISSUE THREAD

**Issue by Zacknetic** [HomeSpan/HomeSpan#298]
Hi there! Really appreciate how straightforward this project is to implement and modify. Thank you for creating this.

Some background info:
- Using Arduino IDE, I compiled the "Pixel" example and flashed it to an ESP32 development board.
- Both iPhone and ESP32 board are connected to the same 2.4Ghz SSID on a stock Netgear router without complicated network settings such as VLAN etc... Pretty standard setup
- To troubleshoot this issue, I have set the logging level to maximum (2);

Issues:
- Speed: Commands sent to the ESP32 are delayed. Usually about 300-500ms but sometimes up to 1000ms. The same goes for responses back to HomeKit; In HomeKit, the accessory displays an animated "standby" icon after being clicked on/off. While using the brightness slider, commands will not arrive smoothly. Instead they are delayed and then suddenly arrive and processed quickly in succession.
- Granularity: Commands are sent infrequently, causing values to jump 10-20 at a time. Again using the brightness slider and an example: sliding the brightness slowly from 0-100, I can see in the logs the commands received by the ESP32 are: 5,23,37,54,65,76,85,100. Definitely far from smooth.

Is expected behavior for this library or could it be I have setup something incorrectly? What can I do to test this further?
I have successfully used other HomeKit libraries in the past that were quite smooth. I would very much like to use HomeSpan due to its ease of use and robust features. Let me know if there is any way I can help.

Thank you!

**Comment by HomeSpan** [comment]
This is not expected.  Can you try one of the basic examples (such as tutorial 1) and see if the same issues exist?  You may also want to unpair the device, issues a 'H' command from the CLI to refresh the device ID, and then re-pair.

**Comment by HomeSpan** [comment]
Have you ben able to resolve the issue?

**Comment by Kameeno** [comment]
i'm facing the same issue at the moment, i got a basic example for a led dimmer with a short fading.. but still having the problem of the granularity.
i tried to look into the source code if there's a update timer and what is the frequency but i didnt solved the issue... :/

**Comment by HomeSpan** [comment]
What do you mean by short fading?  Did you program the sketch to automatically fade the LED through multiple dimming levels?  If so, you should only send an update to HomeKit when the fade is completed, not for at every step in the fading.
