### ISSUE TITLE
PlatformIO support

### ISSUE THREAD

**Issue by aaaidan** [HomeSpan/HomeSpan#3]
Great work so far! Absolutely mammoth effort in design and great docs. Very promising library. 👍

I'm having problems building HomeSpan projects on PlatformIO, due to a failed build. I notice only Arduino is mentioned in the docs, so I understand that PIO may not be a supported platform.

Is PlatformIO expected to work? If not, are you interested in having HomeSpan support PlatformIO eventually?

**Comment by HomeSpan** [comment]
I've not used PlatformIO but will check it out and see what modifications might be needed.  The changes may be extensive since HomeSpan draws on the Arduino-ESP32 library.

**Comment by stepanyurkiv** [comment]
I didn't have any problems with PlatformIO.
Everything passed from the first time.

**Comment by stepanyurkiv** [comment]
Very wonderful work and library.
I will observe the development.

**Comment by aaaidan** [comment]
@stepanyurkiv Thank you for letting me know it worked for you! I will try again. Could you paste your `platformio.ini` here?

**Comment by stepanyurkiv** [comment]
I tried 3 different options to connect the library, all worked without error.
one of the options
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:vintlabs-devkit-v1]
platform = espressif32
board = vintlabs-devkit-v1
framework = arduino
lib_extra_dirs = ~/Documents/Arduino/libraries

**Comment by stepanyurkiv** [comment]
https://drive.google.com/file/d/15uN8z2jaaH333hAfkjG7NP8nkxL7irs_/view?usp=sharing

**Comment by stepanyurkiv** [comment]
https://drive.google.com/file/d/1wldp272WvH8dipAFkheH-7_gEOim_m-a/view?usp=sharing

**Comment by stepanyurkiv** [comment]
or try so.
https://drive.google.com/file/d/1piJeFCzsuPsMWrZvj8yXX_9QzYz0jqRr/view?usp=sharing

**Comment by aaaidan** [comment]
Great news! I can confirm HomeSpan compiles, builds, uploads on platformio. I'm not sure what I was doing wrong before, but I may have installed some extra dependencies that were conflicting with HomeSpan. I guess we'll never know.  🤷‍♀️ 

For posterity, my successful project config looks like this:
```
[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
upload_port = /dev/cu.SLAB_USBtoUART
monitor_port = /dev/cu.SLAB_USBtoUART
monitor_speed = 115200
lib_deps = 
	homespan/HomeSpan@^1.1.1
	thomasfredericks/Bounce2@^2.55
```

Closing this with glee.
