### ISSUE TITLE
„Not supported“ Info in Home App when using Doorbell

### ISSUE THREAD

**Issue by DwieDave** [HomeSpan/HomeSpan#301]
Hello,

I tried setting up a ESP32 as a combined doorbell and door opener (Bridge with Switch Service and Doorbell service) but im getting an information in the home app that the doorbell is not supported.
(The Switch works fine)

Is there something I can do about it to have a working Homekit Doorbell with homepod ringtone support?

**Comment by HomeSpan** [comment]
I just tried this myself and can confirm that the Home App seems to no longer support the Doorbell Service.   Unfortunately Apple continues to make changes to HomeKit but does not publish any changes to the specs.  The HAP-R2 document was last updated in 2019, and both the Apple and Espressif HomeKit SDKs are built off that spec.   As an aside, I am trying to compile a list of all changes in HAP-R2 (by experimentation) and will publish them on the HomeSpan site in the coming weeks.

That said, you should be able to create a HomeKit Doorbell by using the Service::StatelessProgrammableSwitch instead of Service::Doorbell.  Both use the ProgrammableSwitchEvent

**Comment by DwieDave** [comment]
Thanks for the fast response!
I switched to the following setup:
Bridge with SwitchService (that triggers a relay and opens my door) and StatelessProgrammableSwitch that detects when a pin is grounded (eg from a button or relay) and everything works as expected. But sadly not very reliably: After a certain amount of time (20min to an hour) the device is not responsible anymore and only recovers after a reset. I tried to reproduce it with a Serial Monitor connected but I did not get any error messages: in fact no output at all.

Do you have an idea what could be the error? 
I can comment with my code if that helps.

**Comment by HomeSpan** [comment]
Does the device become fully non-responsive.  For example, if you type 's' into the Serial Monitor does it output the status of connections, or is the whole thing frozen?  Also, what version of HomeSpan and what version of the Arduino-ESP libraries are you using?

**Comment by DwieDave** [comment]
I haven't tried the CLI when frozen yet, but sometimes it keeps responsive longer (multiple hours) and sometimes less long.
Im using the current 1.5.0 via PlatformIO and I am using an AZ-Delivery ESP32 D1 Mini because the ESP32 replaces an existing D1 Mini Project.
I am using no other library other than HomeSpan.

**Comment by HomeSpan** [comment]
There are some issues with regard to MDNS in the Arduino-ESP32 board managers that were solved more recently in version 2.0.2 which caused connectivity problems.  When you first start the script, what version of the ESP32 library does HomeSpan report to the CLI?

**Comment by DwieDave** [comment]
In PlatformIO it shows Version 3.5.0
<img width="848" alt="image" src="https://user-images.githubusercontent.com/15933094/163714662-337e44c1-e46e-416e-a3f1-d718fc39aaed.png">

**Comment by HomeSpan** [comment]
That's probably the version number of the underlying ESP32 IDF, in which case you are using older version 3 (I think 3.5.0 may have been the last update of version 3).  If possible, you should switch to the latest ESP32 IDF which is 4.4.   However, this assumes that the problem is indeed related to MDNS connectivity.  Have you been able to check that typing 's' into the CLI after the system hangs provided the expected response?  If the whole device is frozen that suggests a memory leak in your sketch somewhere.

**Comment by DwieDave** [comment]
Just got the versions from HomeSpan start:

```
Arduino-ESP Ver.: 1.0.6
ESP-IDF Version:  3.3.5  
ESP32 Chip:       ESP32-D0WDQ6 Rev 1 dual-core 4MB Flash  
ESP32 Board:      d1_mini32 
```
So I need to find out how to update the ESP-IDF... PlatformIO apparently provides a layered board-manager solution which is updated much later than the original... 3.5.0 is the most current there.

**Comment by DwieDave** [comment]
After (hopefully) updating the framework-arduinoespressif32 I'm getting this error from Settings.h in HomeSpan src:

<img width="998" alt="image" src="https://user-images.githubusercontent.com/15933094/163715771-3d03429f-dc07-4e7b-9615-aec84ebd4b07.png">

**Comment by HomeSpan** [comment]
This is usually a problem with the Platform IO update.  Others have reported the same issue and solved by deleting previous ESP32 installs and starting from a fresh import of the ESP32 libraries.  I don't have Platform IO and unfortunately can't test directly.  The file "core_version.h" is definitely in the ESP32 library.

**Comment by DwieDave** [comment]
I have now reinstalled everything PlatformIO ESP32 related. When Building it shows that it uses the most current 2.0.3 of the framework-arduinoespressif32 package. Only then the error above occurs. When using the default framework-arduinoespressif32 version for the most current version of platformios ESP-32 platform version (2.0.0) everything compiles correctly.

**Comment by HomeSpan** [comment]
The latest production version is 2.0.2 (recommended).  Version 2.0.3 is still in beta from Espressif.  That version is supposed to support ESP32-S3 chips.

**Comment by DwieDave** [comment]
Is the 2.0.2 link I commented wrong and a pre release? since I tried it with excactly that release-commit.

**Comment by HomeSpan** [comment]
That is the correct release.  However, I generally install using the Board Manager in the Arduino IDE.  I've not tried to install directly from that link.

**Comment by DwieDave** [comment]
Which version does the ArduinoIDE Board Manager display for your esp32 boards?  
1.0.6 is the most current if I add the boards via _https://dl.espressif.com/dl/package_esp32_index.json_

**Comment by DwieDave** [comment]
Phew Okay theres something strange with the Arduino ESP32 Github releases.
When I download the Source code (ZIP) (just like PlatformIO would) the package does not include the core_version.h file.
When I download the esp32-2.0.2.zip listed along the Source Code ZIP (This is the one ArduinoIDE uses) the core_version.h file is included but a file necessary for PlatformIO (package.json) is not included in that ZIP.
So I will now try to Frankenstein the two ZIP releases and try to use it with PlatformIO.

**Comment by HomeSpan** [comment]
I use https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json.

Also, I think I see the discrepancy on the ESP32 Github web site.  If you download the zip file of 2.0.2 under the releases page, the core_version.h file is missing.  But if you download the master branch from the main page, the file is indeed present.

**Comment by DwieDave** [comment]
> I use https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json.
> 
> Also, I think I see the discrepancy on the ESP32 Github web site. If you download the zip file of 2.0.2 under the releases page, the core_version.h file is missing. But if you download the master branch from the main page, the file is indeed present.

I think we found the same issue 😅

**Comment by HomeSpan** [comment]
Looks like our messages crossed!  Not sure why core_version.h only shows up in some packages, but I did notice there is a similar file with a different name that contains version numbers.  I will explore and if it is present in all packages will use that instead of core_version.h in an upcoming HomeSpan release (v1.5.1 - hopefully within the next week or so).

**Comment by DwieDave** [comment]
Great! Thanks for your feedback.
For now everything seems to work when I just copy the `core_version.h` file to the current github version.

HomeSpan now reports:
```
HomeSpan Version: 1.5.0
Arduino-ESP Ver.: 2.0.2
ESP-IDF Version:  4.4.0
``` 
And now HomeSpan reports
Starting HAP Server on port 80 supporting 13 simultaneous HomeKit Controller Connections...

instead of 7 simultaneous connections!

Thanks again for your help! 
I really love the possibilities of your library!
