### ISSUE TITLE
Change 'Single Time' for press with a real button

### ISSUE THREAD

**Issue by gaboskar001** [HomeSpan/HomeSpan#305]
Hi
Thanks for this awersome library. I want to change the single press time (default 5ms) to 10ms because sometimes the system doesn't recognise the presses. How do I do this?

Thanks in advance

[CurtainsV5.4.zip](https://github.com/HomeSpan/HomeSpan/files/8511515/CurtainsV5.4.zip)

**Comment by gaboskar001** [comment]
Is this correct?
**new SpanButton(powerPin, x, y, z);**
with:
 x=long time for example 2000 (long press)
y = single time 
z = the maximum length of time (in milliseconds) between button presses to create a DOUBLE press 

So in my code:

**new SpanButton(powerPin, 2000, _10_, 200);**

**Comment by HomeSpan** [comment]
Yes, that's right. However, that only makes it so you need to hold the button a little longer before it will recognize a press.  Not sure why it sometimes ignores presses.  Nevertheless, give it a try - it may address the issue.  Also, ensure the button is connects to GROUND (not to +V).

**Comment by gaboskar001** [comment]
![image](https://user-images.githubusercontent.com/79223544/164008749-6e789d26-2034-4e9e-8ecf-54b0281ed3b9.png)
Like this? 
I couldn't solve the problem by increasing the time...

It looks like I have to push twice between the 'long' press time.... 
I set the double press time on 0 to eliminate that. Can I eliminate the long press ? 
When I write the status of the buttons to the serial monitor, it does recognise the pulses directly.

**Comment by gaboskar001** [comment]
after a lot of messing around, it seems to work. I don't get it but it works for me


#include "extras/PwmPin.h"                          // allows PWM control of LED brightness

struct DEV_LED : Service::LightBulb {               // ON/OFF LED

  int ledPin;                                       // pin number defined for this LED
  int powerPin;
  SpanCharacteristic *power;                        // reference to the On Characteristic
  
  DEV_LED(int ledPin , int powerPin) : Service::LightBulb(){       // constructor() method

    power=new Characteristic::On();                 
    this->ledPin=ledPin; 
    digitalWrite(ledPin,HIGH);                           
    pinMode(ledPin,OUTPUT);                         

    new SpanButton(powerPin, ### 58367, 5, 0);

    this->powerPin=powerPin;                
  } // end constructor

  boolean update(){                              // update() method

    digitalWrite(ledPin,!power->getNewVal());      
   
    return(true);                               // return true
  
  } // update

  void button(int pin, int pressType) override {
###    //if(pin==powerPin){
       if(pressType==SpanButton::SINGLE){                      // only respond to SINGLE presses
          power->setVal(1-power->getVal());     // update the physical LED to reflect the new values
          Serial.print("button is pressed");
          Serial.print("Found button press on pin: ");            // always a good idea to log messages
          Serial.print(pin);
          Serial.print("\n");
          delay(150);
            // }   
   }

    
    digitalWrite(ledPin,!power->getVal()); 
   
  } // button
};
