### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by zuozhehao** [HomeSpan/HomeSpan#310]
```
In file included from /Users/work/Documents/Arduino/libraries/HomeSpan/src/Network.h:32:0,
                 from /Users/work/Documents/Arduino/libraries/HomeSpan/src/Network.cpp:30:
/Users/work/Documents/Arduino/libraries/HomeSpan/src/Network.cpp: In member function 'void Network::apConfigure()':
/Users/work/Documents/Arduino/libraries/HomeSpan/src/Settings.h:108:56: error: 'class HardwareSerial' has no member named 'print__VA_OPT__'
 #define LOG2(format,...) if(homeSpan.logLevel>1)Serial.print ##__VA_OPT__(f)(format __VA_OPT__(,) __VA_ARGS__)
                                                        ^
/Users/work/Documents/Arduino/libraries/HomeSpan/src/Network.cpp:189:7: note: in expansion of macro 'LOG2'
       LOG2("=======================================\n");
       ^
/Users/work/Documents/Arduino/libraries/HomeSpan/src/Settings.h:108:75: error: 'f' was not declared in this scope
 #define LOG2(format,...) if(homeSpan.logLevel>1)Serial.print ##__VA_OPT__(f)(format __VA_OPT__(,) __VA_ARGS__)
                                                                           ^
/Users/work/Documents/Arduino/libraries/HomeSpan/src/Network.cpp:189:7: note: in expansion of macro 'LOG2'
       LOG2("=======================================\n");
       ^
/Users/work/Documents/Arduino/libraries/HomeSpan/src/Settings.h:108:85: error: expected ')' before '__VA_OPT__'
 #define LOG2(format,...) if(homeSpan.logLevel>1)Serial.print ##__VA_OPT__(f)(format __VA_OPT__(,) __VA_ARGS__)
```

**Comment by HomeSpan** [comment]
Did this error arise only in HomeSpan 1.5.1?  Are you using the Arduino IDE (version?) or Platform IO?  Form the error message above it looks like the compiler does not recognize the VA_OPT macro.

**Comment by zuozhehao** [comment]
Yes, HomeSpan  1.5.1 with Arduino

**Comment by zuozhehao** [comment]
> Did this error arise only in HomeSpan 1.5.1? Are you using the Arduino IDE (version?) or Platform IO? From the error message above it looks like the compiler does not recognize the VA_OPT macro.

```
"WiFi.h" Corresponding to multiple libraries
 Used： /Users/work/Library/Arduino15/packages/esp32/hardware/esp32/1.0.6/libraries/WiFi
 not used：/Applications/Arduino.app/Contents/Java/libraries/WiFi
```

**Comment by MnemonicFish** [comment]
I see you are using ESP32 build 1.0.6, 

Upgrade your ESP32 board to 2.0 or above and HomeSpan 1.5.1 should build.

**Comment by zuozhehao** [comment]
> I see you are using ESP32 build 1.0.6,
> 
> Upgrade your ESP32 board to 2.0 or above and HomeSpan 1.5.1 should build.

Upgrade to 2.0.2 and you can build it normally. Thank you. @MnemonicFish @HomeSpan

**Comment by HomeSpan** [comment]
Glad the problem was solved - In the next patch release I will add a check to ensure version 2 of the board manager is being used.

**Comment by rottifant** [comment]
I've had the same problem because I was on ESP32-build 1.0.6. (This was because of an outdated board-manager-URL - but that's another "story")
I updated to 2.0.3 and it works fine now!

Thank you! 👍

**Comment by MauricioNO** [comment]
Hey guys, I know this has been closed, but I am having the hardest time to update to 2.0.2 (or any v2 for the matter).
My Board manager only displays up to 1.0.6, and I've even added the stable version link found in https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html
Which is 
https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
to my Arduino "Additional Boards Manager URLs".
Then I open the manager, look for "esp32" and still all I see is the one that only goes up to 1.0.6.

Any ideas?
Thanks!

**Comment by rottifant** [comment]
Hey, @MauricioNO 
Are you sure that you only have the GitHub link (the link mentioned) in the Boards Manager URLs and **NOT** _https://dl.espressif.com/dl/package_esp32_index.json_?
The "direct-URL" from espressif is outdated and the latest version there is 1.0.6 😉.
Just check if you have that espressif-URL in your Additional Boards Manager URLs and if so, delete it.
Hope that helps!

**Comment by MauricioNO** [comment]
> Hey, @MauricioNO
> Are you sure that you only have the GitHub link (the link mentioned) in the Boards Manager URLs and **NOT** _https://dl.espressif.com/dl/package_esp32_index.json_?
> The "direct-URL" from espressif is outdated and the latest version there is 1.0.6 😉.
> Just check if you have that espressif-URL in your Additional Boards Manager URLs and if so, delete it.
> Hope that helps!

I figured that might have been the problem 10 minutes ago, and was just waiting all the downloads to finish before coming here to update to anybody in the future. That was indeed the problem, I had past outdated links there, which I guess clashed with the 'esp32' label, so the updated one didn't show it's results.
You were right on the stop, thanks @rottifant !
