### ISSUE TITLE
some little bugs

### ISSUE THREAD

**Issue by EinRainerZufall** [HomeSpan/HomeSpan#315]
It seams that `HardwareRevision` and the battery characteristic `ChargingState(2)` didn't work.

**Comment by EinRainerZufall** [comment]
ok the `HardwareRevision` is not shown in the Home App, but in the Eve App it is shown. But the `ChargingState` 2 does not work in both apps.

**Comment by HomeSpan** [comment]
I can confirm this. It appears the Home App no longer (or maybe never did?) recognize a `ChargingState` value of 2.  Under iOS 15.5 the HomeApp treats a state=2 the same as state=0 (Not charging).  I guess technically that's correct since if a device is not chargeable (state 2) than by definition it is _not charging_.  But it would be better if the Home App indicated _unchargeable_ specifically.

I'll add this to my list of HomeKit "errata," which unfortunately seems to grow a little with every release of iOS as the HAP-R2 spec continues to become more and more out-of-date.

Thanks for identifying this issue.

**Comment by EinRainerZufall** [comment]
But if I look for example at a door sensor (Eve) in the Home app then there is the indication "is charging " and "is not charging" not, so you would still have to be able to turn it on that it is a non-rechargeable battery.
![image](https://user-images.githubusercontent.com/77112619/169684214-352e7f7e-356e-423d-9701-77821dc04158.jpeg)

**Comment by HomeSpan** [comment]
Sorry, I'm not sure I'm following.  Battery status "Charging" and "Not charging" both work fine.  It's the status "Not chargeable" that does not seem to work.  The "Battery Level" Characteristic also works fine.

Not sure what Eve door sensor is doing, but the above graphic does not show anything about the sensor not being chargeable.  Is it showing that explicitly?

**Comment by EinRainerZufall** [comment]
The Eve sensor has a replaceable battery, so it is not chargeable

And this is a HomeSpan device
`ChargingState` value of 0
![state 0](https://user-images.githubusercontent.com/77112619/169695838-3223449b-8f50-4f65-8aed-41ac8013f8b6.jpeg)

`ChargingState` value of 1
![state 1](https://user-images.githubusercontent.com/77112619/169695845-90f5c36f-4f32-46b5-b884-334558eaa6a9.jpeg)

`ChargingState` value of 2
![state 2](https://user-images.githubusercontent.com/77112619/169695853-cbccd5e8-4824-4369-acce-02396fbcf7f2.jpeg)

**Comment by HomeSpan** [comment]
Yes, the above is as described in my initial response - charging state=2 replicated charging state=0 (not charging) instead of showing "not chargeable."   This seems to be a problem with HomeKit and the Home App itself, as opposed to HomeSpan.  Does the Eve Door sensor show a different result?

**Comment by EinRainerZufall** [comment]
Yes the text field "Batterie wird geladen" (Charging) is not visible.

**Comment by HomeSpan** [comment]
Try leaving out ChargingState as a Characteristic.  Though HAP-R2 says it is required, it may work fine without it.  HomeSpan will warn you that you are missing the required Characteristic, but it's just a warning message.  This may be what the Eve Sensor is doing.

**Comment by EinRainerZufall** [comment]
ok thanks for your help
