### ISSUE TITLE
NeoPixel as Status Light

### ISSUE THREAD

**Issue by JohnWickham** [HomeSpan/HomeSpan#316]
Hey all, been using HomeSpan for about a year and want to thank everyone who has contributed.

I want to gauge the community's interest in adding support for using a NeoPixel as the status light for HomeSpan. A good number of boards (like Adafruit’s [ESP32 QT Pys](https://www.adafruit.com/product/5405) and [Feathers](https://www.adafruit.com/product/5400), [Unexpected Maker’s](https://unexpectedmaker.com) boards, and others) include onboard RGB LEDs that are just begging to be put to use by something like this.

My proposal is an API similar to the existing `setStatusPin` (e.g. `setStatusPixel`) that takes the pin and pixel type (e.g. `PixelRGB`, `PixelRGBW`, or `Dot`). HomeSpan could different colors to indicate status; these options may depend on what everyone agrees is useful, but some ideas:
* Red when power is on, but WiFi is not connected (the access point is running)
* Amber when WiFi is connected, but a controller is not paired
* Blue when WiFi is connected and a controller is paired (normal status)

HomeSpan already includes [an interface for addressable pixels](https://github.com/HomeSpan/HomeSpan/blob/master/docs/Pixels.md) so I don't foresee a feature like this adding much bloat. What other uses cases might this work for? Is there any appetite for something like this?

**Comment by HomeSpan** [comment]
I've been thinking about adding something like this. But rather than create a fixed set of colors I could create a generic interface that calls a user-defined statusLight function with a parameter indicated the specific homeSpan status that needs to be represented. If statusLight is weakly-defined, the base case can be the current logic, and users can override with anything else (such as setting colors of a NeoPixel).

**Comment by JohnWickham** [comment]
I really like that idea, more of a generic `statusChange` callback.

**Comment by HomeSpan** [comment]
HomeSpan 1.7.0 (just released) now allows the use of a NeoPixel LED as a status light.  See `homeSpan.setStatusPixel()` in the API Reference for details.  In addition, a new generic callback method has been added `homeSpan.setStatusCallback()` that allows you to add your own code to control any other devices (an LED, an LCD display, etc.) based on changes to the HomeSpan status.  See the release notes and API Reference for details.
