### ISSUE TITLE
Unable to save WiFi creds on ESP32-C3

### ISSUE THREAD

**Issue by JohnWickham** [HomeSpan/HomeSpan#317]
I've been messing with Adafruit's new [ESP32-C3](https://www.adafruit.com/product/5405) boards. No issues compiling and uploading my HomeSpan sketches to them, but it seems there's an issue saving WiFi credentials. Using either the `W` command from the CLI, or the automatic access point, the console says "Credentials saved! … Re-starting", but as soon as it starts up, "WIFI CREDENTIALS DATA NOT FOUND". 

[I saw it mentioned](https://github.com/HomeSpan/HomeSpan/issues/220) that HomeSpan is known to work just fine on C3, is anyone else able to reproduce this issue?

**Comment by HomeSpan** [comment]
What version of the Arduino-ESP32 board managers are you using.  I've not yet tested under 2.0.3, but this should work under 2.0.2.  One thing to try is to erase the entire NVS using the 'E' command from the CLI in case something has been corrected in the NVS index tables.

**Comment by JohnWickham** [comment]
I am using Arduino-ESP32 2.0.3 — version 2.0.2 has [issues with ESP32-C3 Rev 3](https://github.com/espressif/arduino-esp32/issues/6519).

No dice using the E command to erase it, same result.

**Comment by HomeSpan** [comment]
Any issues with the ESP32 or ESP32-S2 (if you've been able to try them, that is)?  I'll be testing 2.0.3 over the next few weeks and will hopefully be able to resolve the issue - every new release of the Arduino-ESP32 board manager seems to always break something.

In the interim you can try setting the WiFi Credential programmatically in the sketch itself (see the API for details).

**Comment by JohnWickham** [comment]
ESP32-S2 is working flawlessly! I think I jumped the gun on giving C3 a try 😅. Thanks for looking into it.

**Comment by JohnWickham** [comment]
Also, if it helps your work on it: `setWifiCredentials` is a good workaround for storing WiFi crews, but controller pairing data also doesn't persist.

**Comment by HomeSpan** [comment]
I just double-checked and it turns out I have been using Rev 3 of the ESP32-C3.   This has worked fine under Board Manager versions 2.0.0 through the latest 2.0.3.  However, my specific board is the ESP32C3 Dev Module, not the QT Py, so that might be the difference.

One thing to check:  Under the Arduino -> Tools menu, make sure your Partition Scheme is set to something that includes "spiffs" _not_ "ffat".

**Comment by JohnWickham** [comment]
Thanks for the tip. Seems that choosing "Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS)" or "Minimal SPIFFS (1.9MB APP with OTA/190KB SPIFFS)" has no effect unfortunately.

For anyone who might be reading along: I've decided to stick with ESP32-S2 for now (so this issue isn't urgent or a request for support at the moment).

**Comment by HomeSpan** [comment]
I did come across a thread related to the QT PY -- I think the device only has 2MB of Flash, which means none of the Partition Schemes match.   One solution was to create an additional partition scheme that accurately reflected the 2MB flash memory.  According to the thread, this was causing SPIFFS initialization to fail.
