### ISSUE TITLE
Custom fields during setup

### ISSUE THREAD

**Issue by oleksiikutuzov** [HomeSpan/HomeSpan#318]
I am using HomeSpan for a couple of devices and there is a thing that would be neat to have: custom fields during the setup process (let's say along with homekit password) that would store values to NVS. 

Use cases: I have a sensor and controllers for the LED strips:
* For the first, the threshold value for an alarm to be triggered can be set.
* For the second, there might be animations, dependent on the number of LEDs or if you add more strips to the chain.

If you have multiple devices, it would be messy, to compile the firmware with different values for each device separately, especially if you want to update the software on all of them. In case these values are stored in the memory and aren't overridden by updates, it would make life much easier :)

As I see this to myself, a method like `addCustomSetting("field name", default_value)` would add a new field to the setup page and if not overridden during setup, just save the default value.

**Comment by zuozhehao** [comment]
You can use NVS to achieve this requirement

**Comment by HomeSpan** [comment]
I think it would be too complicated to generalize functionality to include custom fields on the HomeKit setup page in a robust fashion - each field needs to be error checked, and the method for saving fields in the NVS depends on the variable type (int, float, etc.).   At present the setup fields are part of a specific HomeSpan structures.

As an alternative, you can create you own custom "Configuration" page by added a web server to your device.  This allows you to pick interface elements most appropriate for your config data, such as dropdown boxes or radio buttons.  See the [Programmable Hub](https://github.com/HomeSpan/ProgrammableHub) project for some ideas on how to do this.

**Comment by oleksiikutuzov** [comment]
Currently I have a workaround with custom characteristics which are only visible in eve app, but now I see why it would be complicated to integrate to the library. Thanks for the explanation.
