### ISSUE TITLE
'struct ledc_channel_config_t' has no member named 'flags'

### ISSUE THREAD

**Issue by TheLPCheat** [HomeSpan/HomeSpan#331]
When compiling i always get this error. Using Arduino 1.8.19 and a ESP32. Tried both versions 1.5.1 and 1.5.0 and both got me the same error code. 

```
C:\Users\xxx\Documents\Arduino\libraries\HomeSpan-1.5.0\src\extras\PwmPin.cpp: In constructor 'LedC::LedC(uint8_t, uint16_t)':
C:\Users\xxx\Documents\Arduino\libraries\HomeSpan-1.5.0\src\extras\PwmPin.cpp:72:43: error: 'struct ledc_channel_config_t' has no member named 'flags'

             channelList[nChannel][nMode]->flags.output_invert=0;
                                           ^~~~~
```

**Comment by HomeSpan** [comment]
What specific ESP32 chip are you using?  Also, please check the version of your Arduino-ESP32 Board Manager.  Needs to be 2.0.0 or later from Espressif.

**Comment by TheLPCheat** [comment]
I am using ESP32-WROOM-32 i will check board manager

**Comment by TheLPCheat** [comment]
Thank you, updated my boards manager and its working fine!
