### ISSUE TITLE
Pi Pico W Support

### ISSUE THREAD

**Issue by Renondedju** [HomeSpan/HomeSpan#357]
How compatible would it be with the new Raspberry Pi Pico W?
Are there any plans to support it?
And how heavy would the changes be?

**Comment by HomeSpan** [comment]
HomeSpan relies heavily on the ESP32 RTOC framework and associated libraries.  Porting to the RPi would be a very heavy lift.  Also, the Pi is not really designed for low-level interfacing with other hardware, which is the purpose of HomeSpan.  For simply bridging existing IOT devices that have a web or other open interface, HomeBridge is a good choice.

**Comment by Renondedju** [comment]
The [pi pico w](https://www.raspberrypi.com/products/raspberry-pi-pico/) is quite similar to the ESP32 and has nothing to do with the PI 1/2/3/4 or zero. It also seems to be [supporting RTOS as well](https://www.freertos.org/smp-demos-for-the-raspberry-pi-pico-board.html).

**Comment by HomeSpan** [comment]
It's probably possible, and there does seem to be support in the Arduino IDE for programming the RP2040, but I'm not familiar enough with the chip to know whether it has all the crypto libraries needed, or if they need to be loaded separately.

**Comment by Renondedju** [comment]
I have a strong background in C/C++ but I'm kind of new to the embedded development world, except for Arduino that I know quite well. Do you think I could be able to make an RP2040 version? What amount of work would that represent?

**Comment by HomeSpan** [comment]
The code is all straight C++, and I tend to add a lot of comments, so the bulk of the logic should work.  The harder part will be all the libraries.  They are all listed in the *.h files, so that will give you a good place to start on the components you'll need to gather from either existing RP2040 libraries or other sources.  A lot of the hardware-specific HomeSpan functionality is in the extra.h library - you can leave that out completely for now since it stands alone.

My guess is it would be a good deal of work.

**Comment by Renondedju** [comment]
I only need it to control a WS2812b led strip, would that allow me to just delete things and save on time?
If the led strip is not supported I found a library with all the support I need already [PicoLED](https://github.com/ForsakenNGS/PicoLED)

**Comment by HomeSpan** [comment]
Not really - HomeSpan uses a custom LED driver, so you would need to replace it in any case.  The bigger lift will be all the crypto stuff - it's really in-the-weeds and you'll need to be able to either find the same libraries HomeSpan uses (in which case all the same functions will work) or you'll need to use different libraries (in which case you'll need to figure out how to map the different functions for each library).

**Comment by Renondedju** [comment]
Do you think you could provide me with the name of all the libraries used?
I'm gonna look for alternatives, do you want me to make a pull request if I manage to do it by any chance?
