### ISSUE TITLE
ESP32-H2

### ISSUE THREAD

**Issue by aLAN-LDZ** [HomeSpan/HomeSpan#367]
Hi 

I want to build thermostat but i want use the aqara temp sensor for reading temp in room. I read is possible to read it by zigbee. But only h2 esp have it. Does homespan work with h2?

**Comment by HomeSpan** [comment]
No, HomeSpan relies on the Arduino-ESP32 library which does not (yet) support the H2.

**Comment by aLAN-LDZ** [comment]
Ok, my workaround for this is to use the esp-now library. Is it compatible with yours? Thanks again for what you are doing!

**Comment by aLAN-LDZ** [comment]
this is exactly what i need zigbee or esp-now for.

Thanks to zigbee, you can communicate with aqara sensors - battery operated and very energy-saving. Maybe it would be worth adding zigbee communication - there are already a lot of devices (sensors) that we can use

**Comment by aLAN-LDZ** [comment]
So I understand correctly that it will be possible to make a few temperature sensors that will connect to the homespan hub master? Jesus, I can't wait for it because I have a floor heating control project waiting for me and I haven't come up with anything sensible.

**Comment by HomeSpan** [comment]
That's the goal - I'll be working on the code for this over the next few weeks.

**Comment by HomeSpan** [comment]
Note that HomeSpan version 1.7.0 (released a few weeks ago) now includes an embedded ESP-NOW library with examples of how to create remote, battery-operated sensors.
