### ISSUE TITLE
getVal() for custom float characteristic returns integer value

### ISSUE THREAD

**Issue by oleksiikutuzov** [HomeSpan/HomeSpan#372]
I created a custom characteristic with float values
`CUSTOM_CHAR(OffsetTemperature, 00000001-0001-0001-0001-46637266EA00, PR + PW + EV, FLOAT, 0.0, -5.0, 5.0, false)`

`Characteristic::OffsetTemperature offsetTemp{0.0, true}`

And set its range to have step of 0.2
`offsetTemp.setRange(-5.0, 5.0, 0.2)`

Value seems to be saved and restored from nvs correctly, as well as in Eve app
```
      ⇨ Characteristic OffsetTemperature(2.4):  IID=5, Custom-UUID="00000001-0001-0001-0001-46637266EA00", 
Perms=PR+PW+EV, Custom-Range=[-5,5,0.2] (nvs)
```

However, when I am getting the value for offset
```
float temperature = ((data[0] * 256.0) + data[1]);
temperature = ((175.72 * temperature) / 65536.0) - 46.85;
float offset = offsetTemp.getVal();

LOG1("Current temperature: ");
LOG1(temperature);
LOG1("\n");

LOG1("Offset: ");
LOG1(offset);
LOG1("\n");

LOG1("Current corrected temperature: ");
LOG1(temperature + offset);
LOG1("\n");
```

It looks like the `getVal()` function returns an integer value as it should be 2.4
```
Current temperature: 30.91
Offset: 2.00
Current corrected temperature: 32.91
```

Is it a bug or am I doing anything wrong?

**Comment by HomeSpan** [comment]
getVal is a template function which defaults to <int> if unspecified.  To return a float, use offsetTemp.getVal<float>();

**Comment by oleksiikutuzov** [comment]
Ah I see, I missed this moment in the Reference. Thanks!
