### ISSUE TITLE
Thermostat default ranges adjustment 

### ISSUE THREAD

**Issue by iKrushYou** [HomeSpan/HomeSpan#373]
I have discovered a display bug in the current temperature tickmark on cool and heat. It seems that this is caused when there is a difference between the range displayed in heat/cool vs auto

<img width="532" alt="image" src="https://user-images.githubusercontent.com/1500721/188234477-802377de-bbe6-4a5a-b864-8657467a73f5.png">

I have resolved this display issue by adjusting the `TargetTemperature` range to `[0, 35]` to reflect the combined ranges of `CoolingThresholdTemperature` - `[10, 38]` and `HeatingThresholdTemperature` - `[0, 25]`

I am making a recommendation to adjust the defaults for these characteristics to make them line up to avoid this visual bug (at least by default)

I would love to raise a PR but I unfortunately cannot and this is not a contribution

**Comment by HomeSpan** [comment]
Thanks for the insights --- let's see if Apple addresses this in the next iOS release.
