### ISSUE TITLE
Led (Bulb) Control via Homekit or Manually Button

### ISSUE THREAD

**Issue by ismail-ozturk** [HomeSpan/HomeSpan#383]
Hi I am doing a development for ESP32. I really like your library. Just to be sure, I'm sharing my scenario with you.
The materials I use
two buttons (On Off) or two push buttons
two leds

scenario-1: the led can be controlled via homekit, at the same time Led should light up when the button is pressed (On-Off Button)

scenario-2: the led can be controlled via homekit, at the same time, Led should turn on when the button is pressed and pulled, then Led should turn off when the button is pressed and pulled (Push Button)

Could you send me please a code sample for this? to fully understand the system.

**Comment by HomeSpan** [comment]
All of these scenarios are covered on the tutorials. Recommend you start with Examples 1 through 5 and then jump to Example 15.

**Comment by ismail-ozturk** [comment]
I've really been looking for days.
I'm starting to understand the logic. but I am not sure how to proceed with these scenarios. Can you guide me with an example? I am in a very difficult situation. :/
