### ISSUE TITLE
Unable to add accessory, the setup code is incorrect 

### ISSUE THREAD

**Issue by FOSV** [HomeSpan/HomeSpan#385]
I am trying to run this project: [https://github.com/unreality/FujiHK](url)  which has a dependency on this HomeSpan repository.
When I try to do the procedure to add the accessory, both iPhone and iPad (iOS 16 and iOS 15.7 respectively) return the error "Unable to add accessory, the setup code is incorrect" and the terminal tells me "SRP Proof Verification Failed".

Could these warnings during compilation be related to the problem?

![Immagine 2022-09-17 180942](https://user-images.githubusercontent.com/80490825/190897545-b1564287-b5ce-4b2a-b72a-5bf473be024a.png)

Am I doing something wrong? Can you help me out?

**Comment by HomeSpan** [comment]
What pairing code are you using?  Also, you may want to run some of the HomeSpan tutorials first - they are designed to test out various components of the system.

**Comment by FOSV** [comment]
I'm using a custom pairing code because I changed it following the instructions in the repository I linked to earlier, and i've even tried 11122333 without success. What code should I try?

**Comment by HomeSpan** [comment]
If you type 'S' into the Serial Monitor you can reset the code to whatever you want. Then, type that code into the Home App when pairing.

**Comment by FOSV** [comment]
That's exactly what I did but it doesn't work!

**Comment by HomeSpan** [comment]
One other thing to check: when HomeSpan first starts it will print out its LPK. It's a really long hexadecimal number.  Does it happen to begin with more than one zero?
