### ISSUE TITLE
Function returning current configuration mode

### ISSUE THREAD

**Issue by oleksiikutuzov** [HomeSpan/HomeSpan#397]
A small feature proposal. I thought it might be useful to have a function that returns the current configuration mode. In this case, devices with a screen can show the current configuration mode before selecting (not only LED blinks) or offer hints of what the current mode does rather than looking into the reference each time. I see this as a function that just returns the number of the current setting:
0 - Not entered Configuration Mode
1 -  Exit Device Configuration Mode
... and so on with 5 modes.

**Comment by HomeSpan** [comment]
That's a good idea. I'll add something like this in the next release.  Thanks much for the suggestion.

**Comment by HomeSpan** [comment]
This feature has been released in version 1.7.0 as part of a new method  `homeSpan.setStatusCallback()`.  See the release notes and API Reference for details.  Thanks for the great suggestion.

**Comment by oleksiikutuzov** [comment]
Thanks for implementing it. Already tried from dev branch — works great
