### ISSUE TITLE
Issue Pairing to HomeKit

### ISSUE THREAD

**Issue by c-rust** [HomeSpan/HomeSpan#398]
I am unable to get Example 01-SimpleLightBulb to pair to HomeKit.  I added the optional LED and SWITCH to observe the behavior of the ESP32.  I selected my WiFi network and added the password in the Serial Monitor.  The LED is blinking twice showing it is connected to my WiFi. My iPhone is connected to the same WiFi network.

In the Home App under My Home I am clicking on Add Accessory, More Options, My Accessory Isn't Shown Here, Enter a Setup Code, Enter Code...   I am using 46637726.  After entering the code, the Home App just defaults back to the Select an Accessory to Add to My Home.  

I am using the following software versions.

Arduino IDE 1.8.19
Library: HomeSpan by Greg Version 1.6.0
Sketch: Example 01-SimpleLightBulb
esp32 version 2.0.4 board manager

My iPhone 13 Pro is running iOS Version 16.0.2

<img width="700" alt="Screen Shot 2022-09-28 at 9 13 42 AM" src="https://user-images.githubusercontent.com/11469813/192805672-e713fe35-c9a1-4f6f-823d-a1cf31beb184.png">
<img width="985" alt="Screen Shot 2022-09-28 at 9 13 54 AM" src="https://user-images.githubusercontent.com/11469813/192805703-00dc51d1-7d38-4972-b85f-fa44b686b478.png">
![IMG_4810](https://user-images.githubusercontent.com/11469813/192805796-5914127a-ad0d-46a0-abf2-1289015675fe.PNG)
![IMG_4812](https://user-images.githubusercontent.com/11469813/192807056-64e3b279-b397-4ed5-92ef-05f11f06923a.PNG)
![IMG_4817](https://user-images.githubusercontent.com/11469813/192809475-c4d5ed40-49df-49cc-93e5-5f382f444a77.jpeg)
<img width="385" alt="Screen Shot 2022-09-28 at 9 45 06 AM" src="https://user-images.githubusercontent.com/11469813/192810003-a1dd801f-a48f-4e5c-9737-e1cb98876d1d.png">
<img width="383" alt="Screen Shot 2022-09-28 at 9 46 07 AM" src="https://user-images.githubu
<img width="360" alt="Screen Shot 2022-09-28 at 9 46 47 AM" src="https://user-images.githubusercontent.com/11469813/192810353-63cddfd4-37af-4caa-8f99-9dd9a52327b0.png">
sercontent.com/11469813/192810267-e4aedfe7-6514-4b90-a143-0566c1c2ad6d.png">
<img width="383" alt="Screen Shot 2022-09-28 at 9 46 07 AM" src="https://user-images.githubusercontent.com/11469813/192813509-f043e94d-633f-425f-9e48-18736bf20ea0.png">
<img width="360" alt="Screen Shot 2022-09-28 at 9 46 47 AM" src="https://user-images.githubusercontent.com/11469813/192813562-17cb66b4-d466-4a34-8ac2-c5f4396a9757.png">

**Comment by HomeSpan** [comment]
The HomeSpan device should show up in the list - you should not have to press "My Accessory Isn't Shown Here."  If it does not show up there are a few things to try.

1) Open a terminal window and try pinging your device (*ping 192.168.1.72*).  If no reply, that suggests a WiFi connectivity problem.  If there is a reply, that ensures WiFi is properly connected.

2) Download a bonjour discovery app on your iPhone.  I use "Discovery DNS".  It's free from the App Store.  Once downloaded, open the app and click on the *_hap._tcp.* local service.  This should show all the devices broadcasting HomeKit compatibility.  If you don't see your Accessory that suggests a problem with the MDNS service for your chip.  If you do see your Accessory, click on it and verify that ***sf=1***.  The Home App looks for this value to decide which Accessories to show when pairing.

3) If everything above looks correct, it may be an issue with your router.  Does your router support both 5GHz and 2.4GHz networks?  If so, the iPhone will usually connect via the 5GHz.  However, the ESP32 chips only have a 2.4GHz radio, so the Home App will NOT be able to find the Accessory UNLESS your router is configured to cross-route all traffic between the 5GHz and 2.4GHz bands.  This is usually something that can be set in the router config.
