### ISSUE TITLE
Expose RSSI

### ISSUE THREAD

**Issue by gpabdo** [HomeSpan/HomeSpan#411]
Love this HomeSpan lib. I was wondering if it would be possible to expose the signal strength of the WIFI connection in the homeSpan object? homeSpan.RSSI or something. Would be nice to log signal strength, or even better collect it somehow. 

WiFi.RSSI()

Thanks!

**Comment by HomeSpan** [comment]
Why not just call WiFi.RSSI() whenever needed?

**Comment by gpabdo** [comment]
I see, not quite sure how that works, but it does. Thanks!
