### ISSUE TITLE
esp8266

### ISSUE THREAD

**Issue by AugustinMauroy** [HomeSpan/HomeSpan#418]
with an esp8266 is it possible to do something? Or is there another lib?

**Comment by AugustinMauroy** [comment]
Do you know a lib?

**Comment by AugustinMauroy** [comment]
mmm
And it could become a feature

**Comment by timoneff** [comment]
@AugustinMauroy this mostly worked for me: https://github.com/Mixiaoxiao/Arduino-HomeKit-ESP8266

**Comment by AugustinMauroy** [comment]
Ok thanks but the lib is little lost
