### ISSUE TITLE
15-RealPushButtons "Control HomeKit Devices?"

### ISSUE THREAD

**Issue by jaxongatza** [HomeSpan/HomeSpan#434]
Hello, Jaxon here! Under example [15-RealPushButtons] I see the button is used to control an LED on the same board. Is there anyway to create a button to toggle/ control other HomeKit devices (Simple Remote). Maybe "if button = true, Toggle [HOMEKIT DEVICE: Living Room Outlet 1 {CODE: 1234} ]. I am very new to coding so I hope my question is clear enough. Thank you for your help in advance! Very impressed what Ive been able to do with my experience. I appreciate well written code.

**Comment by HomeSpan** [comment]
Yes, see Example 16.  It describes what I think you are trying to do.
