### ISSUE TITLE
WindowShade Service; Disconnecting Client

### ISSUE THREAD

**Issue by MnemonicFish** [HomeSpan/HomeSpan#440]
Hi, 

I'm using the WindowsShade service which works great with custom A4988 driver for a stepper motor as long has the steps are kept below and certain threshold if the time is longer the slider becomes unresponsive after the travel completes and I get the "Disconnecting Client"  message (see below) is there anyway I can keep the connection open longer? 

PRINT OUT from Serial Monitor

Lowering Shade
current position :75 %
New target position %: 50 %
Stepper target No. steps: 250
Updating aid=2 iid=7 (okay)
In Put Characteristics #0 (10.138.41.15)...

Lowering Shade
current position :50 %
New target position %: 0 %
Stepper target No. steps: 500
Updating aid=2 iid=7 (okay)
In Put Characteristics #0 (10.138.41.15)...

Raising Shade
current position 0 %
New target position 100 %
Stepper target No. steps: -1000
Updating aid=2 iid=7 (okay)
** Disconnecting Client #0  (105 sec)

**Comment by HomeSpan** [comment]
This message means the client (i.e. the Home App) dropped the connection.  I'm unaware of how to extend this time out, though there may be setting deeper within one of Espressif's WiFi APIs.  When operating your stepper motor, does it block the rest of the code from running?  If so, I think you are seeing a time-out from the Home App itself.

**Comment by MnemonicFish** [comment]
Yep it was the stepper motor blocking the rest of code, I moved the Stepper motor drive logic into a service loop, then passed +/-numberOfSteps into two separate dedicated helper functions one to drive the motor forward (lower Window shade) and the other to reverse (Raise Window shade). 

I'm constructing a Sky Lantern shade for a 3m x 2m opening so was concerned about timing-out but recently tested the code with 10,000 step and didn't experience any time-out or dropped connections. 

The WindowsShade is configured in STEPS of 25%, I have two homing functions which resets the currentPosition once the shade reaches the fully open or fully closed limits switches in case of any motor skip steps.

The issue I need to resolve is preventing the user from pressing multiple Slides (putting the motor and slider positioning out of sync) before the motor has arrived at target. 

Q. do you know if they is anyway to freeze/unfreeze the Home APP; WindowShade Slider?  

Thanks bro!

**Comment by HomeSpan** [comment]
I don't know of any way to freeze the slider in the Home App to prevent a user from pressing while in motion.  However, for my own setup I keep track of the absolute position of the shade so that is the user changes direction, the sketch can make adjustments accordingly.  This does require a known starting point (such as fully open or fully closed), but if you know it's 10,000 steps to go from one to the other, you can move the shade only the absolute number of steps needed to properly set the position.

**Comment by Olivierbkk** [comment]
@MnemonicFish Hi, I am starting a similar project and if it's not too much asking I would love to get your code to get started... I have read through a few pages here and there and it seems like there are many issues 

your project is pretty much exactly what I am looking for including the end limit switches to reset the position

Thanks in advance!
