### ISSUE TITLE
ISO 16.1.1 Update- breaks HomeSpan  

### ISSUE THREAD

**Issue by MnemonicFish** [HomeSpan/HomeSpan#447]
just a heads up.... IOS 16.1.1 update has caused my accessories to stop work correctly, Lights Switches in the HomeApp do not stay at the on position and WindowsShade slider has the same issue.... however the accessories work as they should on my second device running on IOS 16.0.3.

**Comment by HomeSpan** [comment]
I've been on 16.1.1 for a few weeks and have not had any issues.  Are you using any homePods?  If so, have they also been updated?  Any problems with commercial accessories?

**Comment by MnemonicFish** [comment]
now don't I feel stupid, on that news I thought I'd reboot the updated iPhone and it's working correctly! duh..  

thanks man!

**Comment by MnemonicFish** [comment]
that's good news. 

No I'm using iPhone's directly with HomeSpan 1.7.0, with multiple ESP's. iPhone 16.0.3 works as normal.

**Comment by MnemonicFish** [comment]
"Removing Home" from Homekit then starting over re-pairing accessories fixed the issue, Homekit lights, switches, sliders are working as they should.

**Comment by MnemonicFish** [comment]
'Removing Home" from HomeKit App and re-pairing accessories and devices fixed the issue
