### ISSUE TITLE
Platformio Inspector shows 2 warnings

### ISSUE THREAD

**Issue by homonto** [HomeSpan/HomeSpan#448]
Hi, I am not sure if that is important or not but while using Platformio inspector it shows 2 HIGH priority errors/warnings (but it compiles without problem):

<img width="1161" alt="Screenshot 2022-11-27 at 06 59 16" src="https://user-images.githubusercontent.com/46562447/204123393-a63f9aa5-3f0e-4bad-9c34-935a72080125.png">
<img width="1143" alt="Screenshot 2022-11-27 at 06 59 50" src="https://user-images.githubusercontent.com/46562447/204123398-ac880722-f200-44f4-b816-5a7146126225.png">
<img width="514" alt="Screenshot 2022-11-27 at 07 00 01" src="https://user-images.githubusercontent.com/46562447/204123400-6f7a39ad-8c0e-4865-a9c2-9ea0928c9de5.png">

**Comment by HomeSpan** [comment]
I cleaned up some miscellaneous compiler warnings and think I've addressed the issue above.  Updated code is in the dev branch.  Can you check to see if issue above is resolved?

**Comment by homonto** [comment]
It still complains:

<img width="1241" alt="Screenshot 2022-12-03 at 21 01 52" src="https://user-images.githubusercontent.com/46562447/205461987-8868993d-e2da-4d5f-890f-56725a9b0e67.png">
<img width="707" alt="Screenshot 2022-12-03 at 21 02 04" src="https://user-images.githubusercontent.com/46562447/205461986-3f17601f-52e5-4d02-8a6c-821f1d30fe23.png">

**Comment by HomeSpan** [comment]
Does this occur even when compiling tutorial example 1?

**Comment by homonto** [comment]
I will check it later but please remember these errors are not errors - this is when you click "Inspect" on Platformio. During normal compilation it is not showing . Normal compilation looks like this:

`Processing esp32 (platform: espressif32; board: esp32dev; framework: arduino)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 (5.2.0) > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 3.20005.220925 (2.0.5) 
 - tool-esptoolpy @ 1.40201.0 (4.2.1) 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 40 compatible libraries
Scanning dependencies...
Dependency Graph
|-- WiFi @ 2.0.0
|-- HomeSpan @ 1.7.0
|   |-- ESPmDNS @ 2.0.0
|   |   |-- WiFi @ 2.0.0
|   |-- DNSServer @ 2.0.0
|   |   |-- WiFi @ 2.0.0
|   |-- ArduinoOTA @ 2.0.0
|   |   |-- Update @ 2.0.0
|   |   |-- WiFi @ 2.0.0
|   |   |-- ESPmDNS @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|   |-- WiFi @ 2.0.0
|-- HttpClient @ 2.2.0
|-- AsyncElegantOTA @ 2.2.7
|   |-- AsyncTCP-esphome @ 2.0.0
|   |-- ESPAsyncWebServer-esphome @ 2.1.0
|   |   |-- AsyncTCP-esphome @ 2.0.0
|   |   |-- FS @ 2.0.0
|   |   |-- WiFi @ 2.0.0
|   |-- FS @ 2.0.0
|   |-- Update @ 2.0.0
|   |-- WiFi @ 2.0.0
|-- AsyncTCP-esphome @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- AsyncTCP-esphome @ 2.0.0
|   |-- FS @ 2.0.0
|   |-- WiFi @ 2.0.0
|-- SparkFun MAX1704x Fuel Gauge Arduino Library @ 1.0.4
|   |-- Wire @ 2.0.0
|-- Wire @ 2.0.0
|-- AsyncTCP-esphome @ 1.2.2
|-- HTTPClient @ 2.0.0
|   |-- WiFi @ 2.0.0
|   |-- WiFiClientSecure @ 2.0.0
|   |   |-- WiFi @ 2.0.0
|-- Update @ 2.0.0
Building in release mode
Compiling .pio/build/esp32/src/main.cpp.o
Compiling .pio/build/esp32/lib1e0/WiFi/WiFi.cpp.o
Compiling .pio/build/esp32/lib1e0/WiFi/WiFiAP.cpp.o
Compiling .pio/build/esp32/lib1e0/WiFi/WiFiClient.cpp.o
Compiling .pio/build/esp32/lib1e0/WiFi/WiFiGeneric.cpp.o
Compiling .pio/build/esp32/lib1e0/WiFi/WiFiMulti.cpp.o
Compiling .pio/build/esp32/lib1e0/WiFi/WiFiSTA.cpp.o
Compiling .pio/build/esp32/lib1e0/WiFi/WiFiScan.cpp.o
Compiling .pio/build/esp32/lib1e0/WiFi/WiFiServer.cpp.o
Compiling .pio/build/esp32/lib1e0/WiFi/WiFiUdp.cpp.o
In file included from .pio/libdeps/esp32/1-HomeSpan/src/HomeSpan.h:46,
                 from src/main.cpp:47:
.pio/libdeps/esp32/1-HomeSpan/src/Settings.h:46: warning: "VERSION" redefined
 #define     VERSION(major,minor,patch) major*10000+minor*100+patch
 
<command-line>: note: this is the location of the previous definition
Compiling .pio/build/esp32/lib82c/ESPmDNS/ESPmDNS.cpp.o
Compiling .pio/build/esp32/libd97/DNSServer/DNSServer.cpp.o
Compiling .pio/build/esp32/libb82/Update/HttpsOTAUpdate.cpp.o
Compiling .pio/build/esp32/libb82/Update/Updater.cpp.o
Compiling .pio/build/esp32/lib193/ArduinoOTA/ArduinoOTA.cpp.o
Compiling .pio/build/esp32/lib801/1-HomeSpan/HAP.cpp.o
Compiling .pio/build/esp32/lib801/1-HomeSpan/HKDF.cpp.o
Compiling .pio/build/esp32/lib801/1-HomeSpan/HomeSpan.cpp.o
Archiving .pio/build/esp32/lib1e0/libWiFi.a
Compiling .pio/build/esp32/lib801/1-HomeSpan/Network.cpp.o
Indexing .pio/build/esp32/lib1e0/libWiFi.a
Compiling .pio/build/esp32/lib801/1-HomeSpan/SRP.cpp.o
Compiling .pio/build/esp32/lib801/1-HomeSpan/Utils.cpp.o
Archiving .pio/build/esp32/libd97/libDNSServer.a
Archiving .pio/build/esp32/lib82c/libESPmDNS.a
Indexing .pio/build/esp32/libd97/libDNSServer.a
Indexing .pio/build/esp32/lib82c/libESPmDNS.a
Compiling .pio/build/esp32/lib801/1-HomeSpan/src/extras/Blinker.cpp.o
Compiling .pio/build/esp32/lib801/1-HomeSpan/src/extras/Pixel.cpp.o
In file included from .pio/libdeps/esp32/1-HomeSpan/src/HomeSpan.h:46,
                 from .pio/libdeps/esp32/1-HomeSpan/src/HAP.h:32,
                 from .pio/libdeps/esp32/1-HomeSpan/src/HAP.cpp:32:
.pio/libdeps/esp32/1-HomeSpan/src/Settings.h:46: warning: "VERSION" redefined
 #define     VERSION(major,minor,patch) major*10000+minor*100+patch
 
<command-line>: note: this is the location of the previous definition
In file included from .pio/libdeps/esp32/1-HomeSpan/src/Network.h:32,
                 from .pio/libdeps/esp32/1-HomeSpan/src/Network.cpp:30:
.pio/libdeps/esp32/1-HomeSpan/src/Settings.h:46: warning: "VERSION" redefined
 #define     VERSION(major,minor,patch) major*10000+minor*100+patch
 
<command-line>: note: this is the location of the previous definition
In file included from .pio/libdeps/esp32/1-HomeSpan/src/HomeSpan.h:46,
                 from .pio/libdeps/esp32/1-HomeSpan/src/HomeSpan.cpp:40:
.pio/libdeps/esp32/1-HomeSpan/src/Settings.h:46: warning: "VERSION" redefined
 #define     VERSION(major,minor,patch) major*10000+minor*100+patch
 
<command-line>: note: this is the location of the previous definition
Archiving .pio/build/esp32/libb82/libUpdate.a
Indexing .pio/build/esp32/libb82/libUpdate.a
In file included from .pio/libdeps/esp32/1-HomeSpan/src/HomeSpan.h:46,
                 from .pio/libdeps/esp32/1-HomeSpan/src/HAP.h:32,
                 from .pio/libdeps/esp32/1-HomeSpan/src/SRP.cpp:32:
.pio/libdeps/esp32/1-HomeSpan/src/Settings.h:46: warning: "VERSION" redefined
 #define     VERSION(major,minor,patch) major*10000+minor*100+patch
 
<command-line>: note: this is the location of the previous definition
Compiling .pio/build/esp32/lib801/1-HomeSpan/src/extras/PwmPin.cpp.o
Compiling .pio/build/esp32/lib801/1-HomeSpan/src/extras/RFControl.cpp.o
Archiving .pio/build/esp32/lib193/libArduinoOTA.a
Indexing .pio/build/esp32/lib193/libArduinoOTA.a
Compiling .pio/build/esp32/lib7f3/HttpClient/HttpClient.cpp.o
Compiling .pio/build/esp32/lib7f3/HttpClient/b64.cpp.o
.pio/libdeps/esp32/HttpClient/b64.cpp: In function 'int b64_encode(const unsigned char*, int, unsigned char*, int)':
.pio/libdeps/esp32/HttpClient/b64.cpp:69:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Compiling .pio/build/esp32/lib03e/AsyncTCP-esphome/AsyncTCP.cpp.o
Compiling .pio/build/esp32/lib7f8/FS/FS.cpp.o
Compiling .pio/build/esp32/lib7f8/FS/vfs_api.cpp.o
Compiling .pio/build/esp32/libae6/ESPAsyncWebServer-esphome/AsyncEventSource.cpp.o
Compiling .pio/build/esp32/libae6/ESPAsyncWebServer-esphome/AsyncWebSocket.cpp.o
Compiling .pio/build/esp32/libae6/ESPAsyncWebServer-esphome/WebAuthentication.cpp.o
Compiling .pio/build/esp32/libae6/ESPAsyncWebServer-esphome/WebHandlers.cpp.o
Archiving .pio/build/esp32/lib7f3/libHttpClient.a
Indexing .pio/build/esp32/lib7f3/libHttpClient.a
Compiling .pio/build/esp32/libae6/ESPAsyncWebServer-esphome/WebRequest.cpp.o
Compiling .pio/build/esp32/libae6/ESPAsyncWebServer-esphome/WebResponses.cpp.o
Compiling .pio/build/esp32/libae6/ESPAsyncWebServer-esphome/WebServer.cpp.o
Archiving .pio/build/esp32/lib03e/libAsyncTCP-esphome.a
Archiving .pio/build/esp32/lib7f8/libFS.a
Indexing .pio/build/esp32/lib03e/libAsyncTCP-esphome.a
Indexing .pio/build/esp32/lib7f8/libFS.a
Compiling .pio/build/esp32/libb12/Wire/Wire.cpp.o
Compiling .pio/build/esp32/libbbd/SparkFun MAX1704x Fuel Gauge Arduino Library/SparkFun_MAX1704x_Fuel_Gauge_Arduino_Library.cpp.o
Compiling .pio/build/esp32/lib8e7/AsyncTCP-esphome@1.2.2/AsyncTCP.cpp.o
Compiling .pio/build/esp32/lib336/WiFiClientSecure/WiFiClientSecure.cpp.o
Compiling .pio/build/esp32/lib336/WiFiClientSecure/esp_crt_bundle.c.o
Archiving .pio/build/esp32/lib801/lib1-HomeSpan.a
Indexing .pio/build/esp32/lib801/lib1-HomeSpan.a
Compiling .pio/build/esp32/lib336/WiFiClientSecure/ssl_client.cpp.o
Compiling .pio/build/esp32/lib301/HTTPClient/HTTPClient.cpp.o
Archiving .pio/build/esp32/libb12/libWire.a
Indexing .pio/build/esp32/libb12/libWire.a
Compiling .pio/build/esp32/FrameworkArduino/Esp.cpp.o
Archiving .pio/build/esp32/libbbd/libSparkFun MAX1704x Fuel Gauge Arduino Library.a
Archiving .pio/build/esp32/libae6/libESPAsyncWebServer-esphome.a
Compiling .pio/build/esp32/FrameworkArduino/FirmwareMSC.cpp.o
Indexing .pio/build/esp32/libbbd/libSparkFun MAX1704x Fuel Gauge Arduino Library.a
Indexing .pio/build/esp32/libae6/libESPAsyncWebServer-esphome.a
Compiling .pio/build/esp32/FrameworkArduino/FunctionalInterrupt.cpp.o
Compiling .pio/build/esp32/FrameworkArduino/HWCDC.cpp.o
Compiling .pio/build/esp32/FrameworkArduino/HardwareSerial.cpp.o
Compiling .pio/build/esp32/FrameworkArduino/IPAddress.cpp.o
Compiling .pio/build/esp32/FrameworkArduino/IPv6Address.cpp.o
Compiling .pio/build/esp32/FrameworkArduino/MD5Builder.cpp.o
Compiling .pio/build/esp32/FrameworkArduino/Print.cpp.o
Archiving .pio/build/esp32/lib8e7/libAsyncTCP-esphome@1.2.2.a
Indexing .pio/build/esp32/lib8e7/libAsyncTCP-esphome@1.2.2.a
Compiling .pio/build/esp32/FrameworkArduino/Stream.cpp.o
Archiving .pio/build/esp32/lib336/libWiFiClientSecure.a
Compiling .pio/build/esp32/FrameworkArduino/StreamString.cpp.o
Indexing .pio/build/esp32/lib336/libWiFiClientSecure.a
Compiling .pio/build/esp32/FrameworkArduino/Tone.cpp.o
Compiling .pio/build/esp32/FrameworkArduino/USB.cpp.o
Compiling .pio/build/esp32/FrameworkArduino/USBCDC.cpp.o
Compiling .pio/build/esp32/FrameworkArduino/USBMSC.cpp.o
Compiling .pio/build/esp32/FrameworkArduino/WMath.cpp.o
Compiling .pio/build/esp32/FrameworkArduino/WString.cpp.o
Compiling .pio/build/esp32/FrameworkArduino/base64.cpp.o
Compiling .pio/build/esp32/FrameworkArduino/cbuf.cpp.o
Compiling .pio/build/esp32/FrameworkArduino/esp32-hal-adc.c.o
Compiling .pio/build/esp32/FrameworkArduino/esp32-hal-bt.c.o
Compiling .pio/build/esp32/FrameworkArduino/esp32-hal-cpu.c.o
Compiling .pio/build/esp32/FrameworkArduino/esp32-hal-dac.c.o
Archiving .pio/build/esp32/lib301/libHTTPClient.a
Compiling .pio/build/esp32/FrameworkArduino/esp32-hal-gpio.c.o
Indexing .pio/build/esp32/lib301/libHTTPClient.a
Compiling .pio/build/esp32/FrameworkArduino/esp32-hal-i2c-slave.c.o
Compiling .pio/build/esp32/FrameworkArduino/esp32-hal-i2c.c.o
Compiling .pio/build/esp32/FrameworkArduino/esp32-hal-ledc.c.o
Compiling .pio/build/esp32/FrameworkArduino/esp32-hal-matrix.c.o
Compiling .pio/build/esp32/FrameworkArduino/esp32-hal-misc.c.o
Compiling .pio/build/esp32/FrameworkArduino/esp32-hal-psram.c.o
Compiling .pio/build/esp32/FrameworkArduino/esp32-hal-rgb-led.c.o
Compiling .pio/build/esp32/FrameworkArduino/esp32-hal-rmt.c.o
Compiling .pio/build/esp32/FrameworkArduino/esp32-hal-sigmadelta.c.o
Compiling .pio/build/esp32/FrameworkArduino/esp32-hal-spi.c.o
Compiling .pio/build/esp32/FrameworkArduino/esp32-hal-time.c.o
Compiling .pio/build/esp32/FrameworkArduino/esp32-hal-timer.c.o
Compiling .pio/build/esp32/FrameworkArduino/esp32-hal-tinyusb.c.o
Compiling .pio/build/esp32/FrameworkArduino/esp32-hal-touch.c.o
Compiling .pio/build/esp32/FrameworkArduino/esp32-hal-uart.c.o
Compiling .pio/build/esp32/FrameworkArduino/firmware_msc_fat.c.o
Compiling .pio/build/esp32/FrameworkArduino/libb64/cdecode.c.o
Compiling .pio/build/esp32/FrameworkArduino/libb64/cencode.c.o
Compiling .pio/build/esp32/FrameworkArduino/main.cpp.o
Compiling .pio/build/esp32/FrameworkArduino/stdlib_noniso.c.o
Compiling .pio/build/esp32/FrameworkArduino/wiring_pulse.c.o
Compiling .pio/build/esp32/FrameworkArduino/wiring_shift.c.o
Archiving .pio/build/esp32/libFrameworkArduino.a
Indexing .pio/build/esp32/libFrameworkArduino.a
Linking .pio/build/esp32/bridge.esp32.elf
Retrieving maximum program size .pio/build/esp32/bridge.esp32.elf
Checking size .pio/build/esp32/bridge.esp32.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [==        ]  17.8% (used 58468 bytes from 327680 bytes)
Flash: [======    ]  59.3% (used 1165821 bytes from 1966080 bytes)
Building .pio/build/esp32/bridge.esp32.bin
esptool.py v4.2.1
Creating esp32 image...
Merged 25 ELF sections
Successfully created esp32 image.
========================================================================= [SUCCESS] Took 15.40 seconds =========================================================================

Environment    Status    Duration
-------------  --------  ------------
esp32          SUCCESS   00:00:15.399
========================================================================= 1 succeeded in 00:00:15.399 =========================================================================
 *  Terminal will be reused by tasks, press any key to close it. 
`
