### ISSUE TITLE
Unresponsive serial input on example 5

### ISSUE THREAD

**Issue by hillset** [HomeSpan/HomeSpan#450]
I've got an esp32 pico D4 that I'm trying to use to control a few basic rgb leds on a custom pcb.  I've been working through the tutorials in arduino ide and everythings been going fine (I'm able to compile and upload the code successfully, no issues configuring the wifi, able to add the device on homekit).

I'm working on example 5 (and I've also tried additional examples after this), and for some reason the serial monitor stops being responsive to input on example 5 and beyond.  The serial monitor just keeps printing the following:

************************************************************
Welcome to HomeSpan!
Apple HomeKit for the Espressif ESP-32 WROOM and Arduino IDE
************************************************************

ESP-IDF Version:  4.4.2
ESP32 Chip:       ESP32-PICO-D4 Rev 1 dual-core 4MB Flash
ESP32 Board:      pico32
PWM Resources:    16 channels, 8 timers, max 20-bit duty resolution
Sodium Version:   1.0.12-idf  Lib 9.4
MbedTLS Version:  mbed TLS 2.28.1
Sketch Compiled:  Nov 29 2022 19:21:13
Partition:        app0

Device Name:      HomeSpan LED

Anytime I try to send an input to restart, configure the wifi, etc. it just repeats the above over and over.  Can anyone help me figure out what I'm doing wrong or how to fix this?  Thank you!!

**Comment by HomeSpan** [comment]
check to make sure you are not using a pin for the LED that is reserved for some other function on your specific board
