### ISSUE TITLE
Cannot turn on/off my accessories

### ISSUE THREAD

**Issue by quocsinh09** [HomeSpan/HomeSpan#452]
Hi, i've uploaded code into my ESP32.
I've seen the accessory in my Home Application, but when i try to turn on/off my light, it didn't work
Do you guys have the guide for my issue.
Thank you

**Comment by quocsinh09** [comment]
i used example 05 : workingLED btw

**Comment by HomeSpan** [comment]
I assume that the Accessory is functioning correctly in the Home App such that when you turn the light on/off it changes to on/off in the Home App?  If so, and it is only the LED itself that is not turning on/off, this suggests a problem with the LED, the way you've connected it your ESP32, or the pin that you used.  Have you verified the LED operates correctly on the pin you chose without HomeSpan (to test this you can write a simple script that turn on/off the LED every second)?
