### ISSUE TITLE
Get the name of an accessory

### ISSUE THREAD

**Issue by mike-jl** [HomeSpan/HomeSpan#453]
Is there a way to get the name a accessory was assigned in the Home app?
I tried to check the Name Characteristic of the AccessoryInformation Service, but it doesn't seem to reflect the changes made in the app...

**Comment by HomeSpan** [comment]
Unfortunately not.  Apple designed the Name Characteristic as read-only, meaning the Home App can read it (just once when first pairing) but the Home App does not "write" any changes you make in the Home App back to the device.   Apple did introduce a new, undocumented Characteristic called "ConfiguredName" that can is automatically written from the Home App back to the device whenever it is changed, but this Characteristic is only supported by the (undocumented) Television Service.  I've tried using it with other Services (Light, Switch, etc.) but no luck.
