### ISSUE TITLE
Get elapsed real-world time for an accessory with auto shutoff

### ISSUE THREAD

**Issue by z3ugma** [HomeSpan/HomeSpan#459]
Hi there - I'm integrating an Electric Heated Mattress Cover with HomeSpan and an ESP32 based controller.

This heater implements an auto-shutoff after 10 hours. 
I'm wondering how, during the `loop()` method of my dedicated subclass of  `Service::Fan`, I can check the amount of real-world time that has elapsed since the blanket was turned on and reflect the `Characteristic::Active()` state when it turns Off automatically. 

If it helps, I can use one of the input pins of the ESP32 to monitor when the device's screen is on or off.

**Comment by HomeSpan** [comment]
Yes, you can do this with the `setVal()` and `timeVal()` methods.  See for example [Tutorial 14](https://github.com/HomeSpan/HomeSpan/tree/master/examples/14-EmulatedPushButtons).
