### ISSUE TITLE
Negative temperature values do not register

### ISSUE THREAD

**Issue by noblecloud** [HomeSpan/HomeSpan#46]
Setting the characteristic CurrentTemperature for the service TemperatureSensor to a negative value results in the service becoming unresponsive.  According to the log, it appears the value is being sent, but anything less than 0ºC or 32ºF causes the sensor to show "This accessory is not responding" in the Home app.

    >>>>>>>>>> 10.0.1.197 >>>>>>>>>>
    EVENT/1.0 200 OK
    Content-Type: application/hap+json
    Content-Length: 52
    
    {"characteristics":[{"iid":10,"value":281,"aid":3}]}
    -------- SENT ENCRYPTED! --------
    Temperature Update: 33.80
    
    >>>>>>>>>> 10.0.1.197 >>>>>>>>>>
    EVENT/1.0 200 OK
    Content-Type: application/hap+json
    Content-Length: 77
    
    {"characteristics":[{"iid":9,"value":1,"aid":2},{"iid":9,"value":5,"aid":3}]}
    -------- SENT ENCRYPTED! --------
    Temperature Update: 32.90
    
    >>>>>>>>>> 10.0.1.197 >>>>>>>>>>
    EVENT/1.0 200 OK
    Content-Type: application/hap+json
    Content-Length: 79
    
    {"characteristics":[{"iid":9,"value":0.5,"aid":2},{"iid":9,"value":0,"aid":3}]}
    -------- SENT ENCRYPTED! --------
    
    >>>>>>>>>> 10.0.1.197 >>>>>>>>>>
    EVENT/1.0 200 OK
    Content-Type: application/hap+json
    Content-Length: 52
    
    {"characteristics":[{"iid":10,"value":385,"aid":3}]}
    -------- SENT ENCRYPTED! --------
    Temperature Update: 32.00
    
    >>>>>>>>>> 10.0.1.197 >>>>>>>>>>
    EVENT/1.0 200 OK
    Content-Type: application/hap+json
    Content-Length: 77
    
    {"characteristics":[{"iid":9,"value":0,"aid":2},{"iid":9,"value":1,"aid":3}]}
    -------- SENT ENCRYPTED! --------
    Temperature Update: 31.10
    
    >>>>>>>>>> 10.0.1.197 >>>>>>>>>>
    EVENT/1.0 200 OK
    Content-Type: application/hap+json
    Content-Length: 80
    
    {"characteristics":[{"iid":9,"value":-0.5,"aid":2},{"iid":9,"value":2,"aid":3}]}
    -------- SENT ENCRYPTED! --------
    
    >>>>>>>>>> 10.0.1.197 >>>>>>>>>>
    EVENT/1.0 200 OK
    Content-Type: application/hap+json
    Content-Length: 52
    
    {"characteristics":[{"iid":10,"value":321,"aid":3}]}
    -------- SENT ENCRYPTED! --------
    Temperature Update: 30.20
    
    >>>>>>>>>> 10.0.1.197 >>>>>>>>>>
    EVENT/1.0 200 OK
    Content-Type: application/hap+json
    Content-Length: 78
    
    {"characteristics":[{"iid":9,"value":-1,"aid":2},{"iid":9,"value":3,"aid":3}]}
    -------- SENT ENCRYPTED! --------
    Temperature Update: 29.30
    
    >>>>>>>>>> 10.0.1.197 >>>>>>>>>>
    EVENT/1.0 200 OK
    Content-Type: application/hap+json
    Content-Length: 80
    
    {"characteristics":[{"iid":9,"value":-1.5,"aid":2},{"iid":9,"value":4,"aid":3}]}
    -------- SENT ENCRYPTED! --------
    
    >>>>>>>>>> 10.0.1.197 >>>>>>>>>>
    EVENT/1.0 200 OK
    Content-Type: application/hap+json
    Content-Length: 52
    
    {"characteristics":[{"iid":10,"value":331,"aid":3}]}
    -------- SENT ENCRYPTED! --------
    Temperature Update: 28.40
    
    >>>>>>>>>> 10.0.1.197 >>>>>>>>>>
    EVENT/1.0 200 OK
    Content-Type: application/hap+json
    Content-Length: 78
    
    {"characteristics":[{"iid":9,"value":-2,"aid":2},{"iid":9,"value":5,"aid":3}]}
    -------- SENT ENCRYPTED! --------
    Temperature Update: 27.50
    
    >>>>>>>>>> 10.0.1.197 >>>>>>>>>>
    EVENT/1.0 200 OK
    Content-Type: application/hap+json
    Content-Length: 80
    
    {"characteristics":[{"iid":9,"value":-2.5,"aid":2},{"iid":9,"value":0,"aid":3}]}
    -------- SENT ENCRYPTED! --------
    
    >>>>>>>>>> 10.0.1.197 >>>>>>>>>>
    EVENT/1.0 200 OK
    Content-Type: application/hap+json
    Content-Length: 52
    
    {"characteristics":[{"iid":10,"value":399,"aid":3}]}
    -------- SENT ENCRYPTED! --------
    Temperature Update: 26.60
    
    >>>>>>>>>> 10.0.1.197 >>>>>>>>>>
    EVENT/1.0 200 OK
    Content-Type: application/hap+json
    Content-Length: 78
    
    {"characteristics":[{"iid":9,"value":-3,"aid":2},{"iid":9,"value":1,"aid":3}]}
    -------- SENT ENCRYPTED! --------

**Comment by HomeSpan** [comment]
As unlikely as this sounds, HomeKit does not accept negative values for the temperature.  According to the HAP-R2 spec, the Current Temperature Characteristic is a float ranging from 0-100 in steps of 0.1.  My guess is that Apple intended this for indoor temperatures only, not recognizing that it gets a lot colder than 0 Celsius outside!

In a future update I will update the Characteristics with their min/max ranges so that HomeSpan can throw a warning when a setVal() is trying to set a value that HomeKit will not accept.

**Comment by noblecloud** [comment]
I was worried that was going to be the issue.  I agree with your reasoning for why they have the limitation, but it's a bit silly that it allows up to 100ºC.  However, it sounds exactly like something Apple would do.

**Comment by HomeSpan** [comment]
Solved!  Not sure why I did not think of this before, but you can override the HomeKit ranges.  I had thought you can only narrow them so that they are more restrictive, but apparently they can be expanded, at least for the temperature sensor.

To reset the allowable range for any Characteristic, use the HomeSpan method `new SpanRange(min, max,stepsize);`

In Example 12, I added SpanRange(-50,100,1) right after declaration of the temperature Characteristic as follows:

```C++
    temp=new Characteristic::CurrentTemperature(30.0);        // instantiate the Current Temperature Characteristic
    new SpanRange(-50,100,1);   // <---- NEW LINE
    
    Serial.print("Configuring Temperature Sensor");           // initialization message
    Serial.print("\n");
```

Then, to test I changed to loop() function to start at -30.0:

```C++
  void loop(){

    if(temp->timeVal()>5000){                               // check time elapsed since last update and proceed only if greater than 5 seconds
      float temperature=temp->getVal<float>()+0.5;          // "simulate" a half-degree temperature change...
      if(temperature>35.0)                                  // ...but cap the maximum at 35C before starting over at 10C
        temperature=-30.0;   // <--- NOTE NEGATIVE TEMP
      
      temp->setVal(temperature);                            // set the new temperature; this generates an Event Notification and also resets the elapsed time
      
      LOG1("Temperature Update: ");
      LOG1(temperature*9/5+32);
      LOG1("\n");            
    }
    
  } // loop
```

Works exactly as expected.  Sorry to initially steer us in the wrong direction.  Don't know why I never thought of using SpanRange to *expand* the allowable range.  Glad I tried it!

**Comment by HomeSpan** [comment]
I will update Example 12 to explicitly show negative temperatures using the method above.

**Comment by noblecloud** [comment]
Wow, that was incredibly and almost frustratingly simple.  Thank you so much for taking the time to figure it out!
