### ISSUE TITLE
iOS16.2 Home architecture upgrade broke all my homespan installs

### ISSUE THREAD

**Issue by JLIspace** [HomeSpan/HomeSpan#460]
iOS16.2 Home architecture upgrade broke all my homespan installs

Keeps spamming "*** ERROR: Device not yet paired!"

Pairing also isn't possible anymore..

**Comment by JLIspace** [comment]
`00:33:39.978 -> Starting Web (HTTP) Server supporting up to 7 simultaneous connections...
00:33:39.978 -> 
00:33:39.978 -> DEVICE NOT YET PAIRED -- PLEASE PAIR WITH HOMEKIT APP
00:33:39.978 -> 
00:33:51.771 -> 
00:33:51.771 -> *** ERROR: Unrecognized Controller PairingID
00:33:51.771 -> 
00:33:52.464 -> 
00:33:52.464 -> *** ERROR: Device not yet paired!
00:33:52.464 -> 
00:33:52.510 -> 
00:33:52.510 -> *** ERROR: Device not yet paired!
00:33:52.510 -> 
00:33:54.122 -> 
00:33:54.122 -> *** ERROR: Device not yet paired!
00:33:54.122 -> 
00:33:54.354 -> 
00:33:54.354 -> *** ERROR: Device not yet paired!
00:33:54.354 -> 
00:33:54.817 -> 
00:33:54.817 -> *** ERROR: Device not yet paired!
00:33:54.817 -> 
00:33:55.978 -> 
00:33:55.978 -> *** ERROR: Device not yet paired!
00:33:55.978 -> 
00:33:56.814 -> 
00:33:56.814 -> *** ERROR: Device not yet paired!`

**Comment by JLIspace** [comment]
00:33:39.978 -> Starting Web (HTTP) Server supporting up to 7 simultaneous connections...
00:33:39.978 -> 
00:33:39.978 -> DEVICE NOT YET PAIRED -- PLEASE PAIR WITH HOMEKIT APP
00:33:39.978 -> 
00:33:51.771 -> 
00:33:51.771 -> *** ERROR: Unrecognized Controller PairingID
00:33:51.771 -> 
00:33:52.464 -> 
00:33:52.464 -> *** ERROR: Device not yet paired!
00:33:52.464 -> 
00:33:52.510 -> 
00:33:52.510 -> *** ERROR: Device not yet paired!
00:33:52.510 -> 
00:33:54.122 -> 
00:33:54.122 -> *** ERROR: Device not yet paired!
00:33:54.122 -> 
00:33:54.354 -> 
00:33:54.354 -> *** ERROR: Device not yet paired!
00:33:54.354 -> 
00:33:54.817 -> 
00:33:54.817 -> *** ERROR: Device not yet paired!
00:33:54.817 -> 
00:33:55.978 -> 
00:33:55.978 -> *** ERROR: Device not yet paired!
00:33:55.978 -> 
00:33:56.814 -> 
00:33:56.814 -> *** ERROR: Device not yet paired!

**Comment by HomeSpan** [comment]
Are you running the latest version of HomeSpan - 1.7.0?

**Comment by JLIspace** [comment]
> Are you running the latest version of HomeSpan - 1.7.0?

I am now. Had to reflash/remove/pair all of them again. 

Thanks!
