### ISSUE TITLE
"*** ERROR: Device not yet paired!" after updating to new iOS 16.2 HomeKit Architecture 

### ISSUE THREAD

**Issue by HomeSpan** [HomeSpan/HomeSpan#461]
Thanks to user-testing of a beta version of iOS 16.2, a latent bug in HomeSpan was identified that would cause HomeSpan to reject connections because it thought the device was unpaired when it actually was paired.

**This bug was fixed in HomeSpan version 1.7.0.**

If you have not yet migrated to the new iOS 16.2 HomeKit Architecture, please make sure to update your HomeSpan devices to version 1.7.0 (or later) before updating to the new HomeKit Architecture.  Your HomeSpan devices should work fine under iOS 16.2.

If you have already migrated to the new HomeKit Architecture and are receiving "*** ERROR: Device not yet paired!", you will need to update your devices to HomeSpan 1.7.0 (or later), and then unpair/repair each device to clear the error.  As a reminder, to clear a HomeSpan device of any saved pairing data, enter "U" in the Serial Monitor, or "H" if you'd like to unpair and reset the device ID completely.

**Comment by pun0000** [comment]
after I update it still not work I got 
*** ERROR: Unrecognized Controller PairingID after a few minutes connection

**Comment by HomeSpan** [comment]
Did you unpair and re-pair the device, after resetting the device ID?

Also, the error: "*** ERROR: Unrecognized Controller PairingID" is not the same.  This error is reported by HomeSpan if a controller tries to use a prior pairing ID.  If you have a HomeKit Hub, it takes some time to for all the controllers to be made aware of the new pairing IDs.  

After re-pairing, has your device actually stopped responding to commands from the Home App?

**Comment by pun0000** [comment]
I did the re-pair, or I might be cause by my HomePod mini is the Hub and yes my device stopped responding to command after re-pairing

**Comment by HomeSpan** [comment]
This may be an issue with the new architecture itself.  Note that Apple has disabled this feature because of problems with many devices.  I had to power cycle many of my HomePods before everything would work again with my commercial devices.

**Comment by pun0000** [comment]
So I have to restart my HomePod every time with new device?

**Comment by HomeSpan** [comment]
No, it's just that I needed to reboot my devices a few times before everything worked again.  I'm not sure I can debug, but if you want to post a full log file I can try to take a look.

**Comment by pun0000** [comment]
Oh I just rebooted again and it worked thank😁
