### ISSUE TITLE
SpanButton in LightBulb Service not updating

### ISSUE THREAD

**Issue by ronny-antoon** [HomeSpan/HomeSpan#471]
hey, its really nice library and I am in love with your work.
I tried to do a simple sketch with one LightBulb and a SpanButton related to it, 
All working Good as expected, press in the Home App the light change state, press the push-button also the light change state and the Home App update the Characters, but the problem start if I press 5 or more times in less than 15 sec on the push button, the Home App stop update the Characters, until I press in the Home App to change the state and get all working again.

sorry i dont have the skecth

![main](https://user-images.githubusercontent.com/90724911/210116568-4432c686-1933-482f-9dcd-e453ceeba623.png)

![accessory](https://user-images.githubusercontent.com/90724911/210116566-02994c26-1ac6-46eb-9d9e-3aba51ec41e0.png)

try to run this code and then press the push button more than 5 times in  a 15 sec, the Home App will not Update the Characters.

thank you.

**Comment by ronny-antoon** [comment]
sorry guys, its not a HomeSpan problem, its a HomeKit (Home App) problem.

if I am in the Home Screen, not in the Room Screen, it will not change the state.
but if I am in the Room Screen it will always change state.
and I tried it with automations, if this on then that on and if this off then that off, it triggered always even when the Home Screen didn't change state, the Automation always worked, so its not a problem. it is just a Mistake with the UI in the Home Screen.

**Comment by HomeSpan** [comment]
The Home App UI can be quite flaky.  For example, if I change the color of an LED on my device by using a button, it is often not reflected on the Home App if I have the Accessory Tile open.  But if I close the Tile I can see the changes I made correctly reflected in either the Room or Home Screen.  Once I re-open the Tile I see the changes reflected there as well.   Other times changes are reflected more immediately.

I was hoping the new 16.2 architecture Apple released a few weeks ago would improve things, but I still see this problem occurring once in a while.

The same issue sometimes occurs if you update an Accessory using one device (e.g. a Mac) and wait to see the changes reflected on your iPhone.  Sometimes they are, and sometimes they are not if the Accessory Tile is open.

**Comment by ronny-antoon** [comment]
Thank you for replaying. XD
