### ISSUE TITLE
esp32 crashes when running the blinkerLED sketch

### ISSUE THREAD

**Issue by TIMESTICKING** [HomeSpan/HomeSpan#477]
1. after I pair the devices for the first time, it wont crash, the monitor outputs things like:
```
>starts blink
>reset control
>starts blink
>reset control
...
```
Looks well, *BUT* the LED didnt light up, thats odd.

2. I tried typing "R" in the CLI, it restarted but nothing changed. Of course, I tried the other commands like "U" and repaired them.
3. I pushed the boot button on the esp32 and it rebooted, this time the LED lighted up! *But* it blinks forever! And the monitor only  printed 
```
>starts blink
```
then it became no responding, as well as its in home app.
4. Like No.3, but if LED doesnt light up, the situation became same like No.1.

Anyway, I dont know why LED doesnt light up sometimes and why it blinks forever when it lights up.

**Comment by HomeSpan** [comment]
What is the blinkerLED sketch?  Are you referring to Tutorial Example 14?

**Comment by TIMESTICKING** [comment]
Yes, example 14!

**Comment by HomeSpan** [comment]
Do the other tutorials work (tutorial 1 and tutorial 5 in particular?)

**Comment by TIMESTICKING** [comment]
yes, they work perfectly fine. It seems like a big difference between them is the `setval()` in example 14...
I'm really confused by the forever blinking, seems like the thread was stuck in the for loop...idk...

**Comment by HomeSpan** [comment]
I just tested this and it seems to be working fine using an ESP32.  What chip are you using?  Also, if you can control an LED on the same exact pin (per Example 5) by turning it on and off through the Home App, the logic is almost exactly the same in Example 14.   If you changed the pin number in Example 5 to point to wherever you have attached an LED, make sure you made the same change also in Example 14.

What should happen is this:  After pairing you should see the same type of on/off control for an LED Light as in Example 5.  When you press the ON button in the Home App (just once), the "tile" in the Home App will indicate the LED is on, and the LED attached to the pin you specified should blink rapidly three times.  Then, a few seconds after that the "tile" in the Home App will change from ON to OFF.

**Comment by TIMESTICKING** [comment]
Dang! It's my problem, I forgot to assign the class property "nBlinks"!
