### ISSUE TITLE
Unable to pair with second iphone

### ISSUE THREAD

**Issue by chandime** [HomeSpan/HomeSpan#48]
I am trying to pair a second iPhone to the HomeSpan, however, once it is paired with one iPhone it stops broadcasting the device, and manually entering setup code on the second iPhone doesn't work. Tried Factory Resetting the device as well. A pairing request doesn't show up in the system logs.

**Comment by HomeSpan** [comment]
HomeKit generally only allows for a single device to initiate and be paired directly to a HomeKit accessory.  Once a HomeKit device is paired it continues to broadcast its existence over MDNS/Bonjour but the field "sf" changes from a 1 (not-yet paired) to a 0 (now paired).  

All other devices (second phones, iPads, etc.) using the same Apple ID should be able to see this HomeKit Accessory once it has been centrally paired with that first device.  You'll see these using the 's' command of the HomeSpan CLI.

Devices that don't shares your Apple ID can be invited to join your HomeKit network via the Home App.  This allows you add other users (and all of their devices).  These devices will then start showing up under the 's' command as well.

**Comment by chandime** [comment]
Thanks for the explanation! I believe that resolves my issue. Wonderful Library btw!
