### ISSUE TITLE
I got no response from new version of homespan

### ISSUE THREAD

**Issue by pun0000** [HomeSpan/HomeSpan#488]
I use homespan with 4 esp32 and I got homepod mini (version 16.2 also my ios is 16.2too)as hub but only2 esp which use the new version(1.7.0) of library got no response but been using it for weeks but I no response every day but only some hours it work. But I’m not sure which version of the other 2 esp use that it works (I look up in my trash I got many of homespan one of them is 1.5.0) Could you please help me with this problem?

**Comment by HomeSpan** [comment]
There should not be anything in the latest version that would cause an issue.  Debugging no-response problems can be difficult.  Are you running the exact same sketch as you were when it was working?  Are the devices that work in the same area as the devices that don't work (i.e. they are both getting good WiFi signal?)
