### ISSUE TITLE
OTA Password

### ISSUE THREAD

**Issue by lukasa1993** [HomeSpan/HomeSpan#503]
hello, could you please allow setting OTA password programatically as we do for wifi and pairing code

**Comment by HomeSpan** [comment]
will add in to next release and let you know when available in dev

**Comment by HomeSpan** [comment]
A new form of enableOTA() has been added to the dev branch that allows you to set the password programmatically from within a sketch.  See the dev branch version of the API Reference page for details.  Please feel free to give it a try. I will add to the main branch in next release.

**Comment by lukasa1993** [comment]
> A new form of enableOTA() has been added to the dev branch that allows you to set the password programmatically from within a sketch. See the dev branch version of the API Reference page for details. Please feel free to give it a try. I will add to the main branch in next release.

thank you will try on Monday

**Comment by lukasa1993** [comment]
my board isn't ready smith couldn't finish final metal part will test as soon as its ready
