### ISSUE TITLE
HKDF library may need to be updated

### ISSUE THREAD

**Issue by FannyLoi** [HomeSpan/HomeSpan#506]
Hi Gregg,
     I noticed the HKDF source has changed a bit and includes some additional error checking.  It may be advantageous to adopt the newer code, but not sure how much effort would be involved, or if any serious bug has been addressed.  It may not be worth the effort if it was just refactor work.  The calls seem largely the same.

https://github.com/Mbed-TLS/mbedtls/blob/development/library/hkdf.c

**Comment by HomeSpan** [comment]
Thanks - I took a look and the changes are only cosmetic (spacing, position of braces, etc.).
