### ISSUE TITLE
Warning messages during startup: available(): fail on fd 0, errno: 9, "Bad file number"

### ISSUE THREAD

**Issue by rubillos** [HomeSpan/HomeSpan#508]
I'm working on a [HomeKit to CAN-Bus bridge](https://github.com/rubillos/RV-Bridge) to connect the lights, fans, and climate control in my RV to HomeKit.

Each time that HomeSpan starts up I see 14 warning logs:
[  7197][E][WiFiClient.cpp:495] available(): fail on fd 0, errno: 9, "Bad file number"

I believe this is caused by the initialization of the **_client_** member of HapClient to 0:

Hap.h line 93:
`  WiFiClient client=0;            // handle to client`

WiFiClient overrides the boolean operator, mapping it to the method **_connected()_**. The first time the client member is accessed in HomeSpan.cpp there's a boolean test and then a call to **_available()_**. The WiFiClient class isn't set up for the first test, so a simple boolean test takes place, which is true, so the **_available()_** call happens, causing the warning log. This also sets up the WiFiClient class to properly handle future boolean tests.

HomeSpan.cpp line 264:
`    if(hap[i]->client && hap[i]->client.available()){       // if connection exists and data is available`

Removing the "=0" from Hap.h appears to eliminate the warnings.

(Thanks very much for the library, it's great!)

**Comment by HomeSpan** [comment]
Thanks so much for tracking this down.  I've always wondered about the source of that error message.  I've made the change in the dev branch and it will carry through to the next release.

Also, your CAN-Bus bridge project looks terrific.
