### ISSUE TITLE
 Naming: Settings.h & Utils.h can conflict in many projects

### ISSUE THREAD

**Issue by tueddy** [HomeSpan/HomeSpan#510]
Just stumbled while compiling about the naming of these units & conflicting in common projects.
Maybe you can rename & give e.g. a proper homespan-prefix for these common names?

Suggestion:
Settings.h -> hsSettings.h
Utils.h -> hsUtils.h

Btw. great project! 
Best Dirk

**Comment by HomeSpan** [comment]
I may consider that in a later version but for now I'm trying to keep the code structure as stable as possible.
