### ISSUE TITLE
Device won't reconnect after rebooting

### ISSUE THREAD

**Issue by paulstraw** [HomeSpan/HomeSpan#512]
Hi there, thanks for your work with HomeSpan, it seems really fantastic. Unfortunately, I'm hitting an issue when trying to actually deploy accessories. I'm able to connect them with the Home app and use my defined accessories as expected. However, after the microcontroller is rebooted, it will often (though not always) never reconnect to HomeKit.

Here's all the relevant debugging info I could think of. Please let me know if there's any additional information I can provide, and thanks for your time!

* Board: TinyPICO (ESP32-PICO-D4)
* Script: I've tried this with a few of the examples, most notably 16. The script doesn't appear to have any effect on the behavior I'm seeing.
* IDE: I was originally using PlatformIO in VSC, but switched to Arduino after reading some issues here talking about problems in `Arduino-ESP32 < 2.0.2`. It looks like PIO is using `2.0.4` now anyway, but I tried Arduino to be safe. I installed `2.0.7` from the Boards Manager there, but sadly this seemed to have no effect.
* I've tried force quitting and re-opening the Home app on multiple devices after rebooting the microcontroller in hopes that it would force it to show back up, but this doesn't seem to have an effect.
* I'm using a Netgear Orbi mesh system. To help eliminate this as a source of problems, I…
  * Have disconnected the satellite from power, so it's currently working as a normal single router system.
  * Have disabled the "Enable 20/40 MHz Coexistence" and "Enable WMM" features (my understanding is that these are airtime fairness related, and can cause HomeKit issues).
  * Have tried this on a secondary wi-fi router (MoFi 4500) I have and got the same behavior. This network has a separate HomeKit house configured.
  * Probably worth noting: If I reboot the router so everything has to reconnect, the HomeSpan device seems to more reliably pick up at least one HomeKit connection again. I'm not sure whether this is 100% consistent yet.
* If I execute the CLI `H` command and re-pair, everything works as expected again until the microcontroller is rebooted.
* The board reconnects to wi-fi without issue, and appears to broadcast MDNS as expected. I've used the "Discovery" app on iOS to verify that the accessory is still being broadcast as expected under `_hap._tcp.` when in this state.
```
Doorbell._hap._tcp.local.

HomeSpan-F71D348E1CDD.local:80
192.168.40.182:80

ard-esp32 = 2.0.4
board = um_tinypico
c# = 1
ci = 18
ff = 0
hspn = 1.7.1
id = F7:1D:34:8E:1C:DD
md = HomeSpan-ESP32
ota = no
pv = 1.1
s# = 1
sf = 0
sh = Oq0apA==
sketch = n/a
```
* I've tried this with two different TinyPICO boards, so I don't believe it's a hardware issue.
* When in the broken state, the CLI `s` command gives the following:
```
*** HomeSpan Status ***

IP Address:        192.168.40.182

Accessory ID:      F7:1D:34:8E:1C:DD                               LTPK: 8ACB09F528E1B423DA0B3212B9D3071F54ABA3BB328A261F101C768D071155A5
Paired Controller: 24BB021A-4BD9-423E-97AB-1F43278A9026   (admin)  LTPK: 6706B20498132D18F8D6B8F4F15AC22D76F9E014F1FABF0C37A46F5EBAB6C8B9
Paired Controller: 94D143FE-0865-4895-AC19-060E2ED36308 (regular)  LTPK: 733E65358FD78434C767DA7739D56AE87B29B63E79372B36B76FFF23C6585D00

Connection #0 (unconnected)
Connection #1 (unconnected)
Connection #2 (unconnected)
Connection #3 (unconnected)
Connection #4 (unconnected)
Connection #5 (unconnected)
Connection #6 (unconnected)
Connection #7 (unconnected)
Connection #8 (unconnected)
Connection #9 (unconnected)
Connection #10 (unconnected)
Connection #11 (unconnected)
Connection #12 (unconnected)
Connection #13 (unconnected)

*** End Status ***
```

**Comment by HomeSpan** [comment]
I've not heard of this type of error before in which everything works fine until the device is rebooted.  You've already tried most of the thing I would have recommended to debug.  A few other things to consider/check:

1) Are you deploying only a single device (as opposed to multiple HomeSpan devices, which depending on how you configured them may not be unique)?
2) Are you operating with a HomeKit Hub (i.e. HomePod), or on a pure standalone basis?  If with a HomePod Hub, every HomePod needs to have been updated to the same version of iOS that your phone is on.
3) Does this issue occur with any commercial HomeKit devices (i.e. trying to see if this is specific to HomeSpan)?
4) Try enabling the webLog functionality in HomeSpan.  This will allow to verify that you can reach the HomeSpan device from a browser, which tests not just connectivity but also MDNS.

**Comment by paulstraw** [comment]
Thanks for the response and ideas!

1. Correct, just a single device. When I've tried with different boards, I've removed the old accessory from HomeKit first.
2. Yes. I've got several devices set up as HomeKit Hubs. Three HomePod Minis, and an Apple TV. According to the Home app on iOS 16.3.1, all the Minis are up to date. The TV reports 16.3.2, so all seem to be up to date. I got these same results about a year ago as well though, so I don't really think tied to an iOS version issue.
3. This doesn't seem to happen with commercial HomeKit devices, no.
4. I added `homeSpan.enableWebLog();`, and am able to access it fine when in the disconnected from HomeKit state:

<img width="690" alt="Screenshot 2023-02-25 at 12 13 59 PM" src="https://user-images.githubusercontent.com/117288/221377723-a16643a9-bf4b-40bb-a390-f69a80a0d2e8.png">

I also got a friend to try this with another ESP32 board (just a random Chinese dev board). He's not experiencing any similar problems after rebooting, which makes me wonder if this could be something specific to the TinyPICO hardware? He was just using example 01-SimpleLightBulb, and said "ESP32 still seems to be working as expected with lots of restarts and running overnight … it seems to have less dips than my Hue stuff". Unfortunately, I don't have any other ESP32 boards handy to test with at the moment.

**Comment by HomeSpan** [comment]
Based on the above, I think this might indeed be an issue with the TinyPICO hardware.  Unfortunately the only way to know for sure is to test with a different board.  I've had very good success with the Adafruit "Huzzah" boards, as well as the Dev boards from Espressif (which I use for testing the S2, S3, and C3 chips).

**Comment by HomeSpan** [comment]
One more thing - the name of your device is "Doorbell".  Are you using the doorbell Service itself?  Apple seems to have stopped supporting this a while back.  Or are you using a Switch Service and simply naming the device "Doorbell" (which should be fine).

**Comment by paulstraw** [comment]
I've tried both Doorbell and StatelessProgrammableSwitch, both seem to have the same behavior. I also see this with example sketches, e.g. LEDs.

I ordered a few different ESP32 dev boards and will report back here when I test with them. Specifically:

* Adafruit ESP32 Feather V2
* "Teyleten Robot ESP-WROOM-32" from Amazon
* TinyS3 - an updated version of the TinyPICO based on ESP32-S3

**Comment by paulstraw** [comment]
Hi there! Just wanted to give an update on this issue. I've been continuing to mess with things since my last comment.

I had been occasionally plugging in the TinyPICO, and noticed that every time it had been sitting unplugged for a while, it would connect to HomeKit just fine the first time it was powered back on. I did a binary search starting from 4 hours to find the smallest increment where it worked. I got to 1 minute unplugged gaps without a failure, and got my first failure at 30 seconds. Then, I switched to stopwatch trials on a switched USB hub.

At 55 seconds unplugged, 6/10 trials reconnected to HomeKit. At 60 seconds, 7/10. 90 seconds also gave a 6/10 success rate. After this, I went up to 5 minutes. I've tested at this duration numerous (20+) times without failure.

I got the "Teyleten Robot ESP-WROOM-32" boards, and they seem to have the same behavior. I haven't been able to test with other boards though, will update if I do that.

Honestly, I'm fine with just closing this since I know an easy fix (unplug and wait for five minutes). However, if you'd like to keep it open, I'm happy to help with more debugging.

**Comment by HomeSpan** [comment]
Thanks much for the update.  Unfortunately, I'm not sure there is much debugging I can do since the issue seems to be somewhat unique.  Feel free to close for now, but if you identify anything that seems to be the source of the issue please re-open so we can document the solution.

**Comment by prigei** [comment]
hi,
i have exactly the same behaviour. although the programmableswitch works fine. the doorbell stops working after some time. i also need to wait for some minutes to reconnect again. i am on a makerfabs esp32s3 display module. also tried on multiple boards. maybe you have found a solution meanwhile.
