### ISSUE TITLE
ESP32-Unable to add the accessory - an unknown error occurred.

### ISSUE THREAD

**Issue by colussim** [HomeSpan/HomeSpan#516]
Hi,
I'm having a problem adding an accessory in the Apple Home application.
The application recognizes it, when I enter the code or scan the QR it tries to connect to the device. 
and after a while I get the following error:  Unable to add the device - an unknown error occurred.
I have activated the logs in alert 2 but I have nothing on the terminal output ...
The wifi is well initialized, ESP32 responds well to ping.

My accessory is a switch type.
I use the following versions:
HomeSpan Version: 1.7.1
Arduino-ESP Ver.: 2.0.7
 ESP-IDF Version:  4.4.4
 ESP32 Chip:       ESP32-D0WDQ6 Rev 1 dual-core 4MB Flash
ESP32 Board:      esp32
PWM Resources:    16 channels, 8 timers, max 20-bit duty resolution
Sodium Version:   1.0.12-idf  Lib 9.4
 MbedTLS Version:  mbed TLS 2.28.1
IOS : 16.3.1

Do you have an idea where I can direct my research ?

Thanks,
Emmanuel

**Comment by HomeSpan** [comment]
Does this problem occur if you use Tutorial Example 1?  To check, please make sure to first type 'H' into the Serial Monitor to clear any pairing info on the device.

**Comment by colussim** [comment]
No, I use this code :

 void setup() { 
  
Serial.begin(9600);
homeSpan.setLogLevel(2);
new SpanAccessory();  
new DEV_Identify("EPS HomeKit","SmartHomeFactory","123-ABC","HS Bridge","0.9",3);
new Service::HAPProtocolInformation();
new Characteristic::Version("1.1.0");
       
new SpanAccessory();                                                          
new DEV_Identify("DS18B20 Temp Sensor","SmartHomeFactory","123-ABC","Sensor","0.9",0);
}

void loop() {
...
 homeSpan.poll();
} 


struct DEV_Identify : Service::AccessoryInformation {
   
   SpanCharacteristic *identify;   // reference to the Identify Characteristic
   
   DEV_Identify(const char *name, const char *manu, const char *sn, const char *model, const char *version, int nBlinks) : Service::AccessoryInformation(){
     
     new Characteristic::Name(name);                   // create all the required Characteristics with values set based on above arguments
     new Characteristic::Manufacturer(manu);
     new Characteristic::SerialNumber(sn);    
     new Characteristic::Model(model);
     new Characteristic::FirmwareRevision(version);
     identify=new Characteristic::Identify();          // store a reference to the Identify Characteristic for use below
    
  }

 }; 

What is strange is that I initialize the log level to 2 and I see no trace on the console ...
It is as if there was a network problem, communication between the iPhone and the ESP32.
I will try to trace the network .

**Comment by HomeSpan** [comment]
The sketch above won't work.  You've implemented a device with no functionality.

The first SpanAccessory() has no functional services.  But by itself that's okay - if you have no functional services in the *very first* accessory then HomeKit assumes you are configuring your device as a bridge.

However, your second SpanAccessory() also only contains DEV_Identify.  You need to add in some sort of functional service, light a LightBulb, Switch, Temperature Sensor, etc.  Without at least one functional service, HomeKit has no idea what the device is supposed to do.

Highly recommend you start with Example 1 of the Tutorials, test it out to make sure it is working as expected, and then step through the other tutorials as needed.

**Comment by colussim** [comment]
Thanks you for this information,indeed it works better by adding a service 👍😀
