### ISSUE TITLE
is there a ping function implemented?

### ISSUE THREAD

**Issue by Olivierbkk** [HomeSpan/HomeSpan#518]
I would like to check at regular intervals if my internet connection is working. I am thinking to ping an external IP address but can't find a ping function in homespan. Is there such thing? I would set a motion sensor ON if internet is down to trigger an automation to restart my modem.

**Comment by HomeSpan** [comment]
HomeSpan does not have a ping function but there are likely external libraries that you could use for the ESP32.

**Comment by Olivierbkk** [comment]
yes I found something that works thanks
