### ISSUE TITLE
Garage door opener error

### ISSUE THREAD

**Issue by Mup3nda** [HomeSpan/HomeSpan#523]
Hello,

I've used example 13 to control a DC motor like a garage door opener, but I've run into a problem. I don't get any errors during compilation, but errors occur while testing it in the home kit. Here is the error I keep getting: **gpio_set_level(226): GPIO output gpio_num error.**

Here's my code: 

#include "esp32-hal-gpio.h"

struct DEV_GarageDoor : Service::GarageDoorOpener {     // A Garage Door Opener
  int motorPin1 = 34;
  int motorPin2 = 35;

  SpanCharacteristic *current;            // reference to the Current Door State Characteristic (specific to Garage Door Openers)
  SpanCharacteristic *target;             // reference to the Target Door State Characteristic (specific to Garage Door Openers)  
  SpanCharacteristic *obstruction;        // reference to the Obstruction Detected Characteristic (specific to Garage Door Openers)

  DEV_GarageDoor() : Service::GarageDoorOpener(){       // constructor() method
        
    current = new Characteristic::CurrentDoorState(1);              // initial value of 1 means closed
    target = new Characteristic::TargetDoorState(1);                // initial value of 1 means closed
    obstruction = new Characteristic::ObstructionDetected(false);   // initial value of false means NO obstruction is detected

    this->motorPin1=motorPin1;
    this->motorPin2=motorPin2;

    pinMode(motorPin1, OUTPUT);
    pinMode(motorPin2, OUTPUT);

    Serial.print("Configuring Garage Door Opener");   // initialization message
    Serial.print("\n");

  } // end constructor

  boolean update(){                              // update() method

  int targetVal = target->getNewVal();
  int currentVal = current->getNewVal();

  if(targetVal == 0){
    LOG1("Opening Garage Door\n");
    digitalWrite(motorPin1, current->getNewVal());
    digitalWrite(motorPin2, !current->getNewVal());

    obstruction->setVal(false);
  } else if(targetVal == 1){
    LOG1("Closing Garage Door\n"); 

    digitalWrite(motorPin1, !current->getNewVal());
    digitalWrite(motorPin2, current->getNewVal());

    obstruction->setVal(false);
  }
    return(true);                               // return true
  
  } // update

  void loop(){                                     // loop() method

    if(current->getVal()==target->getVal())        // if current-state matches target-state there is nothing do -- exit loop()
      return;

    if(current->getVal()==3 && random(100000)==0){    // here we simulate a random obstruction, but only if the door is closing (not opening)
      digitalWrite(motorPin1, LOW);
      digitalWrite(motorPin2, LOW);
      current->setVal(4);                             // if our simulated obstruction is triggered, set the curent-state to 4, which means "stopped"
      obstruction->setVal(true);                      // and set obstruction-detected to true
      LOG1("Garage Door Obstruction Detected!\n");
    }

    if(current->getVal()==4)                       // if the current-state is stopped, there is nothing more to do - exit loop()     
      return;

    // This last bit of code only gets called if the door is in a state that represents actively opening or actively closing.
    // If there is an obstruction, the door is "stopped" and won't start again until the HomeKit Controller requests a new open or close action

    if(target->timeVal()>5000)                     // simulate a garage door that takes 5 seconds to operate by monitoring time since target-state was last modified
      current->setVal(target->getVal());           // set the current-state to the target-state
  } // loop
  
};

**Comment by HomeSpan** [comment]
This is not a HomeSpan error.  It is an Espressif error, likely caused by trying to set pins 34 and 35 as output.  On the ESP32 these can only be used for an input.   Here is a good reference to consult that explains which pins are generally useable:  https://randomnerdtutorials.com/esp32-pinout-reference-gpios/
