### ISSUE TITLE
Doorbell and lock mechanism

### ISSUE THREAD

**Issue by barisonal** [HomeSpan/HomeSpan#525]
Hello, I have just checked the issues and saw your explanation which says Apple does not support "Doorbell" service and you have suggested to use as contact sensor, that's fine.

But the problem is that, I just want to use ESP32 for my apartment door with the features below;
- I want to get notified (with camera view if possible) when doorbell pressed (from iPhone, AppleTV, iPad)
- I want to unlock the door by sending "open" command from the device (AppleTV, iPhone, iPad).

I want to ask you that what the best option for my use case is?

**Comment by HomeSpan** [comment]
HomeSpan does not support camera services, so the notification could only be via the iPhone pinging you.  Unlocking the door is possible but unless you have an existing electronic mechanism that is easy to activate remotely, you would need to build custom hardware for your door.

**Comment by barisonal** [comment]
Here is the good news! I tried to use **Doorbell** with **LockMechanism** at the same time and Apple Home detected it correctly under the security system! 

So, now it sends notification when doorbell rings ( to my AppleTv as well).

![CleanShot 2023-03-07 at 18 58 58](https://user-images.githubusercontent.com/5008507/223477009-14a5c4fc-6803-4959-a9a3-ee50453697f2.png)

When I click the notification, it redirects to the LockMechanism in this room and I'm able to trigger apartment lock via ESP32 pins. 

![CleanShot 2023-03-07 at 19 02 03](https://user-images.githubusercontent.com/5008507/223477851-7ca1ab4b-9f09-4b87-a6b6-1f6daab3f6d0.png)

**Comment by HomeKidd** [comment]
> Here is the good news! I tried to use **Doorbell** with **LockMechanism** at the same time and Apple Home detected it correctly under the security system!

The doorbell service [can be added](https://nrchkb.github.io/wiki/service/doorbell/#implementation-with-a-camera-and-a-light) to any other accessory and will work. I'm using it for the same thing as you, unlocking my electric door strike!

**Comment by HomeSpan** [comment]
Thanks for this feedback!  I was unaware that the doorbell service would work if used in conjunction with another service.  

I'll add an example of this for others to use as well.

**Comment by HomeSpan** [comment]
I added this topic to the HomeSpan FAQ page.

**Comment by rubensx** [comment]
can someone put a example code from a doorbel with a lockstrike? you use a comment name as doorbell or a stateless programmable switch?

**Comment by HomeSpan** [comment]
Here is an example of a Doorbell Service with with a commented-out Lock Service.  The Lock Service is only a stub and would need to be built out in typical HomeSpan fashion:

```C++

#include "HomeSpan.h"

struct DoorBell : Service::Doorbell { 
 
  SpanCharacteristic *switchEvent;                  // reference to the ProgrammableSwitchEvent Characteristic
  
  DoorBell(int buttonPin) : Service::Doorbell(){

    switchEvent=new Characteristic::ProgrammableSwitchEvent();  // Programmable Switch Event Characteristic (will be set to SINGLE, DOUBLE or LONG press)
                
    new SpanButton(buttonPin);                                  // create new SpanButton

    Serial.print("Configuring Programmable Pushbutton: Pin=");  // initialization message
    Serial.print(buttonPin);
    Serial.print("\n");
    
  } // end constructor

  // We do NOT need to implement an update() method or a loop() method - just the button() method:

  void button(int pin, int pressType) override {

    LOG1("Found button press on pin: ");            // always a good idea to log messages
    LOG1(pin);
    LOG1("  type: ");
    LOG1(pressType==SpanButton::LONG?"LONG":(pressType==SpanButton::SINGLE)?"SINGLE":"DOUBLE");
    LOG1("\n");

    // All the action occurs in this single line below.  We simply set the value of the Programmable Switch Event Characteristic
    // to the value provided by pressType.  The values of pressType (0=SpanButton::SINGLE, 1=SpanButton::DOUBLE, and 2=SpanButton::LONG)
    // were designed to match the required values of the Programmable Switch Event Characteristic.

    switchEvent->setVal(pressType);                // set the value of the switchEvent Characteristic

  }

};

void setup() {
 
  Serial.begin(115200);
  homeSpan.setLogLevel(2);

  homeSpan.begin(Category::Other,"HomeSpan Doorbell");
 
  new SpanAccessory();  
    new Service::AccessoryInformation();
      new Characteristic::Identify();
      new Characteristic::Name("Doorbell");

    new DoorBell(4);

//    new Service::LockMechanism();
//      new Characteristic::LockCurrentState();
//      new Characteristic::LockTargetState();
      
} // end of setup()

//////////////////////////////////////

void loop(){
  
  homeSpan.poll();         // run HomeSpan!
  
} // end of loop()
```

**Comment by rubensx** [comment]
Wow thankyou! I will try in my esp32 but, I don’t understand clearly about the lock service

**Comment by rubensx** [comment]
I'm little confuse, doorbell as mentioned above appers like a "not supported" if I put in lock mechanism appers 2 switches with lock. Now I need to create a two funtions but I'm "stuck" here...

ESP 32 + 2 relay module, one to "pulse" a simple doorbell 127v and another to pulse a lock mechanism to open the door remotly (I'm using a wifi camera to see who is).

with a example above I almost do that but still confuse how I can make the correct struct! can help?

**Comment by giuliolibrando** [comment]
I uploaded a project that does exactly what's in the topic. I hope someone will find it useful.
Link to the repo:
[](https://github.com/giuliolibrando/HomeSpanDoorLock)

**Comment by noaimbs** [comment]
Is there any possibility to mute the homepod if it is need (sleeping time). Thanks

**Comment by HomeKidd** [comment]
> Is there any possibility to mute the homepod if it is need (sleeping time). Thanks

As I know there's no way to mute it or turn it off. The best way is to use DND (or other Focus mode).

**Comment by HomeSpan** [comment]
Not that I know of from the HomePod itself, but as suggested above, DND my me useful (I'm not sure how the DND rules transfer to the HomePod though).

One thing you can try is adding some logic to your sketch to ignore doorbell presses during certain hours, or add a Switch Service as a button you can control from the Home App that the sketch uses as a "mute."   HomeKit does have a Mute Characteristic but I'm not sure the Home App will recognize it in the Doorbell Service.  You can also try adding a Volume Characteristic --- will require some experimentation to figure out which Characteristic will properly display in the Home App when included with the Doorbell Service.

**Comment by HomeKidd** [comment]
> One thing you can try is adding some logic to your sketch to ignore doorbell presses during certain hours, or add a Switch Service as a button you can control from the Home App that the sketch uses as a "mute." HomeKit does have a Mute Characteristic but I'm not sure the Home App will recognize it in the Doorbell Service.

Or adding [LockPhysicalControls]( https://nrchkb.github.io/wiki/characteristic/lock-physical-controls/#title) which disables the button used for the DoorBell itself. I'm using this method in many of my sketches. You can make then automations (in the Eve app) to turn of and turn off this.

**Comment by noaimbs** [comment]
One thing you can try is adding some logic to your sketch to ignore doorbell presses during certain hours, or add a Switch Service as a button you can control from the Home App that the sketch uses as a "mute.

Like here...  https://gitlab.com/ca-iot/homebridge-shelly-doorbell/

I will try that. Thanks in advance

**Comment by saeshimi** [comment]
> I uploaded a project that does exactly what's in the topic. I hope someone will find it useful. Link to the repo: https://github.com/giuliolibrando/HomeSpanDoorLock

Wow, thank you. Works perfectly :). Am I missing something to get directed to the lock when clicking on the push notification? Everything works, the bell and the lock but when I click on the "ring" notification it opens just the home app with the overview screen.

**Comment by delingren** [comment]
I have been playing with doorbell a little bit. It looks like if you have 2 consecutive pressed of the same type (e.g. two single presses or two long presses), the second one does not trigger a notification in Home app. But if they are of different types, both trigger notifications. Has anyone else observed this behavior?
