### ISSUE TITLE
Idea: Add option to define start LED for Pixel class

### ISSUE THREAD

**Issue by Keyes** [HomeSpan/HomeSpan#532]
Why would this make sense? This allows users to split one physical LED strip into multiple HomeKit devices like so (Based on the[ Pixel example](https://github.com/HomeSpan/HomeSpan/blob/master/examples/Other%20Examples/Pixel/Pixel.ino)):

```
// create three 10-LED NeoPixel RGB Strands
SPAN_ACCESSORY("Segment 1");
    new NeoPixel_RGB(NEOPIXEL_RGB_PIN, 10, 0);   
SPAN_ACCESSORY("Segment 2");
    new NeoPixel_RGB(NEOPIXEL_RGB_PIN, 10, 10);   
SPAN_ACCESSORY("Segment 3");
    new NeoPixel_RGB(NEOPIXEL_RGB_PIN, 10, 20);   
```

**Comment by HomeSpan** [comment]
NeoPixels work by cascading data from one pixel to the next.  It is not possible to set just the colors of, say pixels 11-20, without setting pixels 1-10.  You can create logic to store the colors for pixels 1-10 and resend them as the first 10 colors of a 20-pixel strand, but that means that Segment 2 as defined above need to know the colors of Segment 1, and Segment 3 needs to know the colors of both Segment 2 and Segment 1.  In other words, they can not operate independently.

Thus, to accomplish the above, you would have to create a single, class-level, instance of the Pixel class that stored all 30 colors, and then have each instance of NeoPixel_RGB update the values stored in its specific segment, followed by a transmission of all 30 colors to the Pixel.  Definitely possible to do, just requires some cross-object logic.
