### ISSUE TITLE
SpanButton continuously fires press event 

### ISSUE THREAD

**Issue by barisonal** [HomeSpan/HomeSpan#535]
Hello, I'm going to use Doorbell service with my ESP32-CAM setup. But `button` function is being called every second even I don't click button on my breadboard.

**Here is DEV_Doorbell.h;**
```
struct DEV_Doorbell : Service::Doorbell {
  int buttonPin;    
  SpanCharacteristic *switchEvent;
  SimpleTimer timer;

  DEV_Doorbell(int buttonPin, int index) : Service::Doorbell(){
    this->buttonPin=buttonPin;
    switchEvent = new Characteristic::ProgrammableSwitchEvent(); 
    new SpanButton(buttonPin);
  } // end constructor

  void button(int pin, int pressType) override {
    
      Serial.print("PRESS TYPE:");
      Serial.print(pressType);
      Serial.print("\n");
      switchEvent->setVal(pressType);                 
      

  }

};
```

**Output:**
```
Starting MDNS...

HostName:      HomeSpan-02DB7EB82017.local:80
Display Name:  HomeSpan Bridge
Model Name:    HomeSpan-ESP32
Setup ID:      HSPN

Starting HAP Server on port 80 supporting 14 simultaneous HomeKit Controller Connections...

PRESS TYPE:2
PRESS TYPE:2
PRESS TYPE:2
PRESS TYPE:2
PRESS TYPE:2
PRESS TYPE:2
PRESS TYPE:2
PRESS TYPE:2
PRESS TYPE:2
```

**Comment by HomeSpan** [comment]
Does this occur even if you disconnect the button and all other wires from the esp-32?

**Comment by barisonal** [comment]
No, it stops to fire event when I disconnect the button from ESP32. It's on PIN15 by the way and I tested all setup (wires, button and ESP32) in different project it works fine which means there is no any problem on hardware.

**Comment by ronny-antoon** [comment]
try to change the constructor for "spanButton" and put this code ->
new SpanButton(buttonPin, SpanButton::TRIGGER_ON_HIGH);

**Comment by barisonal** [comment]
> try to change the constructor for "spanButton" and put this code -> new SpanButton(buttonPin, SpanButton::TRIGGER_ON_HIGH);

Yes it worked, thank you! 



> Is the button normally open or normal closed? If it stops firing when you disconnect the button, and starts to repeatedly fire when you reconnect the button, it sounds like the button is normally closed, which is the wrong type of button. Or perhaps you wired the button incorrectly so that the leads are always connected (instead of across the switch)? Try using a plain jumper wire and manually touch your pin to ground - that should trigger a short press or long press depending on how long you touch ground. Having a repeated Press Type = 2 (Long) would occur if the pin is connected to ground permanently.

By the way this is a digital pin button, I have tested this wired setup with a different project and it works fine. But by using the code @ronny-antoon shared it works fine.
