### ISSUE TITLE
homeSpan.autoPoll()

### ISSUE THREAD

**Issue by ronny-antoon** [HomeSpan/HomeSpan#536]
Hello I have an idea for better performance, after making some programs for esp32, 5 deferent boards for my home with your library, I am in love with this library. good job.
My suggest is to change the priority in this function "xTaskCreateUniversal". in your code "HomeSpan.h" line 342 :-

  void autoPoll(uint32_t stackSize=CONFIG_ARDUINO_LOOP_STACK_SIZE){xTaskCreateUniversal([](void *parms){for(;;)homeSpan.pollTask();}, "pollTask", stackSize, NULL, 1, &pollTaskHandle, 0);}     // start pollTask()

change it to :-

  void autoPoll(uint32_t stackSize=CONFIG_ARDUINO_LOOP_STACK_SIZE){xTaskCreateUniversal([](void *parms){for(;;)homeSpan.pollTask();}, "pollTask", stackSize, NULL, configMAX_PRIORITIES - 1, &pollTaskHandle, 0);}     // start pollTask()

your code set the priority to 1 for the task, in my opinion this task should take the max priority (first to run), and this method xTaskCreateUniversal define that the max priority is "configMAX_PRIORITIES - 1". in my project when i use the autoPoll it will delay the tasks until finish other tasks. when i changed it to the max priority it made it more responsive and faster.

**Comment by HomeSpan** [comment]
Thanks for the suggestion. Depending on what other libraries are running, it may be that user wants HomeSpan to run at a higher priority, but not necessarily the max.  Instead of hardcoding this, I'll make it a parameter so users can choose the priority needed.

**Comment by ronny-antoon** [comment]
You are right, good job my friend

**Comment by HomeSpan** [comment]
The autoPoll method has been updated in the dev branch to allow for the setting of stack size, priority, and cpu.  Please feel free to give it a try.  Will be rolled out to production in next release.
