### ISSUE TITLE
Serial.write crashes Homespan

### ISSUE THREAD

**Issue by SparrowHacker** [HomeSpan/HomeSpan#546]
I'm attempting to use the Television example along with an IR transmitter module to control my TV. (I know I can do it with just the IR led but I don't have the correct transistor on hand.) The transmitter works by sending the HEX codes over serial using Serial.write in the following code:
`uint8_t on_code[5]={0xA1, 0xF1, 0x00, 0xFF, 0x47};
void setup() {
        Serial.begin(9600);
}
void loop() {
        Serial.write(on_code,sizeof(on_code));
}`

I have added the Serial.write line just below the Serial.printf in each RemoteKey switch case and changed the serial rate to 9600 as that is what the transmitter requiers. Every time I trigger it however, Homespan stops responding and I have to restart the ESP32.

Any help would be appreciated, thanks!

**Comment by HomeSpan** [comment]
You are trying to write to the main Serial port?  This is already used by HomeSpan.  You need to use Serial1 or Serial2 instead.

-Gregg

**Comment by SparrowHacker** [comment]
That worked, thank you! I didn't even know there were multiple serial ports as I haven't seen that before. Thanks for the quick response.
