### ISSUE TITLE
Temperature Sensor: negative values

### ISSUE THREAD

**Issue by Radek-Suski** [HomeSpan/HomeSpan#550]
Hi,

I'm getting this warning:

`*** WARNING:  Attempt to update Characteristic::CurrentTemperature with setVal(-0.06) is out of range [0,100].  This may cause device to become non-reponsive!`

Does it means I cannot set temperatures below zero?

Regards,
Radek

PS: Many, many, many thanks for providing this library. It is amazing!

**Comment by HomeSpan** [comment]
You just have to expand the range with `setRange()` to allow negative temperatures.  See [Example 12](https://github.com/HomeSpan/HomeSpan/tree/master/examples/12-ServiceLoops) for a sample of how to do this.

**Comment by Radek-Suski** [comment]
Fabulous!!

Thank you very much!
