### ISSUE TITLE
Question about SpanToggle

### ISSUE THREAD

**Issue by Olivierbkk** [HomeSpan/HomeSpan#554]
I am trying to use SpanToggle but can't make it work, here is the sketch, can you tell me what I'm doing wrong?

.ino file
```C++
  new SpanAccessory();
    new Service::AccessoryInformation();
      new Characteristic::Identify();
      new Characteristic::Name("HomeSpan Toggle Switch Button");
    new DEV_ProgToggle(5,1);                                      // (Button pin, button number)
```

.h file
```C++
struct DEV_ProgToggle : Service::StatelessProgrammableSwitch {       
  SpanCharacteristic *switchEvent; 
  
  DEV_ProgToggle(int buttonPin, int index) : Service::StatelessProgrammableSwitch(){
    switchEvent = new Characteristic::ProgrammableSwitchEvent(); 
    new Characteristic::ServiceLabelIndex(index); 
    new SpanToggle(buttonPin); 
  } // end constructor

    void button(int pin, int pressType) override {
    switchEvent->setVal(pressType);                               // set the value of the switchEvent Characteristic

  } // end button
};
```

Home shows the button but still displays double press and long press and whatever I program on single press does not work.

I have tried many things and tried finding a sample sketch but I am running out of ideas. Note that if I use SpanButton instead it's working fine.

Thanks in advance.

**Comment by HomeSpan** [comment]
SpanToggle and SpanButton create internal triggers within HomeSpan.  What determines how these are presented in the HomeApp depends on the Services you choose.  Above you chose a StatelessProgrammableSwitch.  This item always has double press, long press, regardless of whether you use SpanToggle, SpanButton, or something completely different.

SpanToggle is suitable for Services where you have an on/off switch, such as a ContactSensor.

**Comment by Olivierbkk** [comment]
thanks for the info, is there an example somewhere that I could use to understand how it's used?
