### ISSUE TITLE
Wifi config page does not work on android phones.

### ISSUE THREAD

**Issue by planevina** [HomeSpan/HomeSpan#556]
VER 1.7.1

In ap config wifi mode .the page does not work on android phones.
It stucked after display the title "Homespan setup".   
It works fine on iphone.

![QQ图片20230412105353](https://user-images.githubusercontent.com/70463000/231337492-9dd8f4a9-6a0e-4729-836b-855dae58d3f9.jpg)

A temporary solution, I use another config wifi page code myself . It works fine on both  phone.

**Comment by HomeSpan** [comment]
Sorry, android phones are not directly supported by HomeSpan (since you need an iPhone to pair HomeKit devices).

**Comment by planevina** [comment]
> Sorry, android phones are not directly supported by HomeSpan (since you need an iPhone to pair HomeKit devices).

Thanks for reply。
And....android user can use homekit device bridged by HASS（Home Assistant）。 (such as my friend )

**Comment by HomeSpan** [comment]
Thanks for the info.  Once you configure WiFi, are you able to pair the HomeSpan device and get it working with HASS?

**Comment by planevina** [comment]
> Thanks for the info. Once you configure WiFi, are you able to pair the HomeSpan device and get it working with HASS?

Yes ,It working fine . 
In fact ,many diyer use HASS as a smart home center .
 HASS is compatible  with homekit ,xiaomi...and some other api.
This is the lib   https://github.com/home-assistant/home-assistant.io

**Comment by danilkorotkov** [comment]
Hass isn’t fully compatible. Only simple switches, fans and lights…

**Comment by HomeSpan** [comment]
Unfortunately, I don't have an android phone so won't readily be able to address this.

**Comment by danilkorotkov** [comment]
> 

https://www.home-assistant.io/integrations/homekit_controller/
