### ISSUE TITLE
Implementing log/history for Eve

### ISSUE THREAD

**Issue by Radek-Suski** [HomeSpan/HomeSpan#557]
Hi,

firstly; sorry for misusing your issue tracker as support forum but I don't really know where can I ask question otherwise.

I read that you implemented [DATA value format for custom characteristics](https://github.com/HomeSpan/HomeSpan/issues/451).
I'd like to use it for implementing the history feature for the Eve app but I'm simply not able to find the API for Eve.

Could someone please point me to the documentation?

Regards,
Radek

**Comment by HomeSpan** [comment]
Unfortunately, Eve does not publish an API for its interface or devices.  However, others have tried to reverse-engineer Eve-specific Services and Characteristics and provided examples on various other web sites.  I added the DATA format and ability to customize to allow folks to experiments.  I experimented a bit based on what others have published but was not able to get the history feature to work.  Please feel free to experiment as well and post any results if you get it working.

**Comment by Radek-Suski** [comment]
Thanks a lot for your answer. 
I'll try to play with it a bit but frankly my latest serious project in C++ was during my university time so not sure if I will be able to achieve anything. Also I am going through some turbulences right now so there is that,

> Also, note that there is a discussion section where you can post non-issue-related questions

How the heck I missed that? Sorry :( 

Regards,
Radek

**Comment by Radek-Suski** [comment]
I now spent several hour studying the case and to be honest I think I can write an iOs app that is able to present the history with less effort than trying to implement (hack?) aproprietary and most likely unreliable protocol. 

So I'll give up on that

**Comment by danilkorotkov** [comment]
> Regards, Radek
Have you see?
https://gist.github.com/simont77/3f4d4330fa55b83f8ca96388d9004e7d?permalink_comment_id=3804953

**Comment by danilkorotkov** [comment]
https://github.com/2610/fakegato-history/blob/master/fakegato-history.js
