### ISSUE TITLE
ios16 iPhone kills all homespan devices

### ISSUE THREAD

**Issue by richonguzman** [HomeSpan/HomeSpan#562]
Hi,

was working with 3 homespan devices for a while now, ... all could be controlled with 3 iPhones and a Macbook

but as soon as I updated all iPhones to ios16 the homespan devices works with iPhone and not with MacBook

when reseting , works with MacBook and when opening with iPhone home app , all died....

so it seems that MacBook and iPhone stop the other to work : resulting in no homespan working/accesible 

iPhones on IOS16 and Macbook on 12.6.1

**Comment by HomeSpan** [comment]
Apple made huge updates to the HomeKit protocol in the latest versions of iOS16.  It is likely incompatible with iOS12 - you may need to upgrade your MacBook to iOS13

**Comment by richonguzman** [comment]
will do! 🙁

Thanks a lot!
________________________________
De: HomeSpan ***@***.***>
Enviado: miércoles, 19 de abril de 2023 21:22
Para: HomeSpan/HomeSpan ***@***.***>
Cc: Ricardo Guzman (Richonguzman) ***@***.***>; Author ***@***.***>
Asunto: Re: [HomeSpan/HomeSpan] ios16 iPhone kills all homespan devices (Issue #562)


Apple made huge updates to the HomeKit protocol in the latest versions of iOS16. It is likely incompatible with iOS12 - you may need to upgrade your MacBook to iOS13

**Comment by bartosz-777** [comment]
Try running 'U' option on devices, and then add them to HomeKit, might work

**Comment by richonguzman** [comment]
this was all good when updating the Macbook in the Wifi to the newest OS.

now it work flawlessly
________________________________
De: bartosz-777 ***@***.***>
Enviado: jueves, 1 de junio de 2023 18:23
Para: HomeSpan/HomeSpan ***@***.***>
Cc: Ricardo Guzman (Richonguzman) ***@***.***>; Author ***@***.***>
Asunto: Re: [HomeSpan/HomeSpan] ios16 iPhone kills all homespan devices (Issue #562)


Try running 'U' option on devices, and then add them to HomeKit, might work
