### ISSUE TITLE
the state of the paired controller

### ISSUE THREAD

**Issue by AGRO666** [HomeSpan/HomeSpan#577]
Give advice on how best to determine the state of the paired controller (true - false)? It seems that this is only possible with its own procedure using setPairCallback and writing the value to flash.

**Comment by HomeSpan** [comment]
Use `setStatusCallback(void (*func)(HS_STATUS status))` instead.  This will be called with the value of **HS_PAIRED** after WiFi connectivity has been established if the device is already paired.  If not, after WiFi is connected it will be called with the value of **HS_PAIRING_NEEDED**.
