### ISSUE TITLE
Not able to add Device

### ISSUE THREAD

**Issue by CivanUzumaki** [HomeSpan/HomeSpan#585]
I updated my Homekit app today so i could add my parents to my home. After i updated it, i wasn't able to add anyone or even Devices without a control center. Is there a way to bypass the control center and still add Devices to my home?

**Comment by HomeSpan** [comment]
Not sure I understand the specific issues.  What do you mean you updated HomeKit?  Did you update iOS?  If so, from what old version to what new version?  Also, what do you mean by a control center?  A HomeKit Hub?

**Comment by CivanUzumaki** [comment]
Sorry for the confusion with the control center. My phone is set to German and in German it's called "Steuerzentrale". I don't know which version I was before but, i am not able to add any devices without an homehub. It wasn't an IOS update but an update in homekit itself. ![image](https://github.com/HomeSpan/HomeSpan/assets/54710724/14d7a027-a087-43f4-b4bd-c24d91fd3ab0)![image](https://github.com/HomeSpan/HomeSpan/assets/54710724/1f2be734-f132-4403-bd6a-b5e17790573f)![image](https://github.com/HomeSpan/HomeSpan/assets/54710724/58d6941f-1234-433b-bcb1-115bf3952f4c)

**Comment by HomeSpan** [comment]
Thanks for the clarification - please see my response to issue #587, which sounds very similar.
