### ISSUE TITLE
Inverted logic Status LED & Identify

### ISSUE THREAD

**Issue by HomeKidd** [HomeSpan/HomeSpan#590]
Hi! 
Is there any option to configure `void setStatusPin(uint8_t pin)` for inverted operation? Currently i'm using an an ESP32 based Sonoff and it has inverted logic status LED, but i want to use this LED for HomeSpan Status. An (optional) argument for changing the logic of the LED would be great  like using [LedPin](https://github.com/HomeSpan/HomeSpan/blob/master/docs/PWM.md#ledpinuint8_t-pin-float-level-uint16_t-frequency-boolean-invert) 😄

Other minor thing which would be helpful is adding an [LED function](https://github.com/HomeSpan/HomeSpan/blob/7ceee3fda066005aeb3dd90678dd25524d6d8244/src/Settings.h#L95) by default for the Identify routine, since it could be helpful for anyone to identify the accessory using the (HomeSpan status) builtin LED. Instead of implementing each time a custom blinking for the Identify 😄

**Comment by HomeSpan** [comment]
There is no option for doing this at present but the underlying structure for the statusPin is quite generic.  I should be able to expose this structure, which will allow for an arbitrary object to be used as the status pin, including a simple LED that requires an inverted signal.  Will let you know when I make the changes in dev so you can test (probably over the next week or so).

**Comment by HomeSpan** [comment]
Sorry for the delay in this.  I've added a new method `void setStatusDevice(Blinkable *sDev)` to `homeSpan` that allows you to set the Status LED to any generic object that implements the Blinkable Interface.  This feature is now available in the dev branch for testing and will be added to the next production release.  Details on how to create a Blinkable object, including an example that implements an inverted LED, can be found [here](https://github.com/HomeSpan/HomeSpan/blob/dev/docs/Blinkable.md).

I realize this is mechanism is a bit of an overkill for creating an inverted Status LED, but it is generic and would allow the use of any other type of device, or an LED connected through a pin expander, to be used as well.  Let me know if you have any questions.
