### ISSUE TITLE
homespan.poll() taking too much storage space

### ISSUE THREAD

**Issue by guigoruiz1** [HomeSpan/HomeSpan#591]
Hello,

I have a sketch that I have been using with my ESP32 for a while. Recently I have upgraded my libraries and now I get an error compiling that the sketch is too big:

`Compilation error: text section exceeds available space in board`

I have traced the issue back to the `homespan.poll()` call on `void loop()`

Commenting out `homespan.poll()` and nothing more, the sketch uses 1244957 bytes (94%) of program storage space.

Without commenting out `homespan.poll()`, the sketch uses 1430061 bytes (109%) of program storage space.

I am not an expert on C++, but I assumed once I imported the library it would come with all its contents, not include more code depending on the functions I call. 

Before upgrading libraries I didn't have this issue as I have the old version of the sketch currently loaded and running on the ESP32.

It is also worth noting that the whole homespan setup (creating devices, homespan.begin(), etc...) doesn't take up much space. Only homespan.poll() do.

Could you advise me on this issue? 

Thank you

**Comment by HomeSpan** [comment]
Which libraries did you update?  HomeSpan or something else?  A complex HomeSpan sketch takes up about 1MB of flash space (using HomeSpan 1.7.2 and Arduino-ESP32 version 2.0.9).  Are you using any other external libraries?  

Note if you need more space you can compile with a different partition structure.  Based on your statistics above, it seems like you may be compiling with the default partition, which divides the ESP32's 4MB of flash into two program partitions (APP) of 1.2 MB each (two are needed to support OTA), and one 1.5 MB SPIFFS data partition (which is much bigger than needed for HomeSpan).  You can try compiling with the Minimal SPIFFS option, which yield 1.9 MB for each program partition.  Alternatively, if you don't use OTA you only need one program partition and can compile with the No OTA option that provided for 2 MB APP and 2 MB SPIFFS.

**Comment by guigoruiz1** [comment]
These are all the includes from libraries I use in the sketch:
```
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
// HomeSpan - Version: Latest
#include <HomeSpan.h>
// ESP8266 Influxdb - Version: Latest
#include <InfluxDbClient.h>
// DHT sensor library - Version: Latest
#include <DHT.h>
#include <DHT_U.h>
#include <uptime_formatter.h>
#include <uptime.h>
```


They are all the latest versions. I updated all libraries, but only HomeSpan had this big change in size.

I need OTA for this project. Also, my board is DOIT ESP32 DEVKIT V1 and it doesn't show me the partition scheme option. Can I use ESP32 Dev Module instead in the board options?

**Comment by HomeSpan** [comment]
Were you able to resolve this by choosing the ESP32 Dev Module and selecting one of the larger partition schemes?

**Comment by guigoruiz1** [comment]
I have managed to compile the code without errors or warnings, but I have not yet loaded it into the ESP32 as I am afraid I won't be able to revert back to how it was originaly

**Comment by guigoruiz1** [comment]
I have just uploaded the sketch using the minimal SPIFFS partition scheme and it seems to have worked.

**Comment by guigoruiz1** [comment]
I have just uploaded the sketch using the minimal SPIFFS partition scheme and it seems to have worked.
