### ISSUE TITLE
how to disable webserver

### ISSUE THREAD

**Issue by lukasa1993** [HomeSpan/HomeSpan#593]
hey, i haven't enabled weblog but 80 is still open is there any way to disable listening to 80 port ?

**Comment by HomeSpan** [comment]
Port 80 is used for all HomeKit communication (the weblog does not use a separate port, but simply listens on the same port as HomeKit). 

Note you can change the TCP port number used for HomeKit communication, but you can't disable it (else the device could not communicate with HomeKit).

**Comment by lukasa1993** [comment]
so way i am looking is port scanner, and other homekit devices on my network doesn't come up only this one does

**Comment by lukasa1993** [comment]
i only have wifi devices, i scan all possible ports tho none of them have listeners set

**Comment by lukasa1993** [comment]
i set `homeSpan.setPortNum(22308);` and 80 port is still being listened

**Comment by lukasa1993** [comment]
with custom port it works after paired but pairing doesn't work with custom port

**Comment by HomeSpan** [comment]
I'm not really sure what you mean by a listener - details of port use is not something I've worked with before.  HomeSpan uses core ESP32 functions to open up an http port on 80. It may be that the ESP32 acts differently?

**Comment by lukasa1993** [comment]
> I'm not really sure what you mean by a listener - details of port use is not something I've worked with before.  HomeSpan uses core ESP32 functions to open up an http port on 80. It may be that the ESP32 acts differently?  

so for simplest thing when i set different port it still answers to browser on 80 so there is somewhere hardcoded 80 listening

**Comment by lukasa1993** [comment]
@HomeSpan i think i have some clue, i am using `setWifiCredentials`  to set wifi credentials maybe setting this doesn't disable wifi config http ?

**Comment by lukasa1993** [comment]
o i think its just even simpler `homeSpan.setPortNum` this method is not implemented i can't find it

**Comment by lukasa1993** [comment]
> It's implemented inline in the HomeSpan.h file. Are you calling homeSpan.setPortNum before the call to homeSpan.begin? Also, note that the Serial Monitor will show you the port number HomeSpan is using at startup.

i am calling it before begin, and yes in serial monitor it shows port i give it but 80 port still responds to http

**Comment by HomeSpan** [comment]
I'll look into this more detail to see what might be causing this.

**Comment by HomeSpan** [comment]
I've tried reproducing this and can't.  If I use setPortNum() to change the port from 80 (the default) to 88, I am able to pair with HomeKit and no longer get any responses to an http request on port 80 (browser shows it can't connect as expected).  Do you have anything else in your sketch that may be establishing a server?  Also, what port number are you trying to set the device to?  Have you tried this with a simple sketch (using Tutorial Example 1 as a test)?

**Comment by lukasa1993** [comment]
``` C++
#include "HomeSpan.h"  // HomeSpan sketches always begin by including the HomeSpan library

void setup() {  // Your HomeSpan code should be placed within the standard Arduino setup() function

  Serial.begin(115200);  // Start a serial connection so you can receive HomeSpan diagnostics and control the device using HomeSpan's Command-Line Interface (CLI)

  homeSpan.setPortNum(3334);
  homeSpan.begin(Category::Lighting, "HomeSpan LightBulb");  // initializes a HomeSpan device named "HomeSpan Lightbulb" with Category set to Lighting

  homeSpan.enableOTA("1234", true);
  homeSpan.setPairingCode("11111111");
  homeSpan.setWifiCredentials("wifi", "1234");
  homeSpan.setStatusPin(2);

  new SpanAccessory();  // Begin by creating a new Accessory using SpanAccessory(), no arguments needed

  new Service::AccessoryInformation();  // HAP requires every Accessory to implement an AccessoryInformation Service

  new Characteristic::Identify();  // Create the required Identify Characteristic


  new Service::LightBulb();  // Create the Light Bulb Service
  new Characteristic::On();  // This Service requires the "On" Characterstic to turn the light on and off

  homeSpan.autoPoll();

}  // end of setup()

//////////////////////////////////////

void loop() {


}  // end of loop()

// Congratulations!  You've created your first HomeSpan sketch, ready to be uploaded to your ESP32 board and paired with HomeKit.
//
//
```

this example still responds to 80 port 

heres example curl response


```
❯ curl -v 192.168.5.167
*   Trying 192.168.5.167:80...
* Connected to 192.168.5.167 (192.168.5.167) port 80 (#0)
> GET / HTTP/1.1
> Host: 192.168.5.167
> User-Agent: curl/8.0.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
* no chunk, no close, no size. Assume close to signal end
<
* Closing connection 0
```

**Comment by lukasa1993** [comment]
@HomeSpan heres also port scanner result 

```
❯ sudo nmap -sS 192.168.5.167
Password:
Starting Nmap 7.94 ( https://nmap.org ) at 2023-06-19 10:52 +04
Nmap scan report for esp32-475B20 (192.168.5.167)
Host is up (0.0035s latency).
Not shown: 999 closed tcp ports (reset)
PORT   STATE SERVICE
80/tcp open  http
MAC Address: 3C:B3:0A:87:3K:90 (Espressif)

Nmap done: 1 IP address (1 host up) scanned in 12.97 seconds
```

**Comment by HomeSpan** [comment]
Sorry, I still can't reproduce.  I've run your exact code above (replacing the WiFi Credentials accordingly) with the one change that I used pin 13 for my statusPin.  The results of curl are as follows:

```
> curl -v 192.168.1.72
*   Trying 192.168.1.72:80...
* connect to 192.168.1.72 port 80 failed: Connection refused
* Failed to connect to 192.168.1.72 port 80 after 228 ms: Couldn't connect to server
* Closing connection 0
curl: (7) Failed to connect to 192.168.1.72 port 80 after 228 ms: Couldn't connect to server
> 
> curl -v 192.168.1.72:3334
*   Trying 192.168.1.72:3334...
* Connected to 192.168.1.72 (192.168.1.72) port 3334 (#0)
> GET / HTTP/1.1
> Host: 192.168.1.72:3334
> User-Agent: curl/7.88.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
* no chunk, no close, no size. Assume close to signal end
< 
* Closing connection 0
> 
```

As shown, I can only connect via port 3334.  I tried this on an ESP32 as well as an ESP32-C3 to see if the autopoll() multithreading was a potential issue when used on a single-processor device (the C3), but it worked as expected on both chips.

What happens if you use curl on port 3334?  From your nmap command it looks like port 3334 is not listening, only 80.  Are you using the correct IP address (not perhaps using the address of another chip that is running with port 80 instead)?

**Comment by lukasa1993** [comment]
@HomeSpan so it was OTA problem from USB everything works as expected, apparently from OTA this part is not updated or something like that

**Comment by lukasa1993** [comment]
`  new Characteristic::FirmwareRevision("0.0.2");` doesn't get updated thru OTA as well maybe something is stored and is not updated with OTA

**Comment by HomeSpan** [comment]
Try putting homeSpan.begin after ota, statusPin, etc. instead of before.

**Comment by HomeSpan** [comment]
Note you will need to make this change first using USB.  After you should then be able to update via OTA.

**Comment by HomeSpan** [comment]
To follow up on the above, the source of the problem was that you had enabled OTA after `homeSpan.begin()` instead of before.  When the second parameter of `enableOTA()` is set to `true`, HomeSpan checks to make sure whenever you update via OTA (not via USB), the new sketch also has OTA enabled.  This check occurs when `homeSpan.begin()` is called.  Since you had `enableOTA()` *after* `homeSpan.begin()`, when the check was called HomeSpan did not know OTA was enabled, and rejected the new sketch, leaving the old sketch in place.  This is why the FirmwareRevision() was not updated (the entire sketch is rolled back to the prior version before the update).  Placing `enableOTA()` before `homeSpan.begin()` ensures the check will pass and the new sketch is accepted.

**Comment by lukasa1993** [comment]
> To follow up on the above, the source of the problem was that you had enabled OTA after `homeSpan.begin()` instead of before. When the second parameter of `enableOTA()` is set to `true`, HomeSpan checks to make sure whenever you update via OTA (not via USB), the new sketch also has OTA enabled. This check occurs when `homeSpan.begin()` is called. Since you had `enableOTA()` _after_ `homeSpan.begin()`, when the check was called HomeSpan did not know OTA was enabled, and rejected the new sketch, leaving the old sketch in place. This is why the FirmwareRevision() was not updated (the entire sketch is rolled back to the prior version before the update). Placing `enableOTA()` before `homeSpan.begin()` ensures the check will pass and the new sketch is accepted.

is it possible to error out in this case?

**Comment by lukasa1993** [comment]
okay this was problem with 80 port anyway thanks for help
