### ISSUE TITLE
Linker error: IRAM0 segment data does not fit

### ISSUE THREAD

**Issue by tueddy** [HomeSpan/HomeSpan#595]
Hi,

in a large project after including HomeSpan i get a linker error 
`region iram0_0_seg overflowed by 432 bytes`

I use huge_app partition and without homespan i have enough space available:
```
RAM:   [==        ]  21.8% (used 71492 bytes from 327680 bytes)
Flash: [====      ]  35.5% (used 2328097 bytes from 6553600 bytes)
```

But my app seems to use a lot of IRAM already. Is there a way to save some IRAM with your library to make it linking? 
For example not  include Pixel/LED/RMT features e.g. compiler switch? in `Pixel.cpp` / `PwmPin.cpp` i can see some IRAM_ATTR ..

Thank's & best
Dirk

**Comment by tueddy** [comment]
Thank's! 
I know it's a corner case here but would be helpful to select only needed features and save some (I)RAM. in future..

**Comment by HomeSpan** [comment]
I did a fairly deep dive of how memory is allocated and treated through the different DRAM/IRAM locations, but in the end I found that the compiler is smart enough to ignore loading functions into IRAM that are not used.  So unless you create a Pixel, IRAM is not effected.  Not sure there is any other way of reducing the IRAM usage - I suspect its from the WiFi stack.

**Comment by tueddy** [comment]
Thank's for investigating!
I had success compiling & linking Homespan using "Arduino as component", save some IRAM with some config flags
