### ISSUE TITLE
Sensors stop responding after a couple of minutes

### ISSUE THREAD

**Issue by JorgeFrias** [HomeSpan/HomeSpan#601]
First of all, the library is amazing, the approach with services is an amazing idea, it blew my mind.

I found an issue with sensors, they seem to stop working after a couple of minutes, HomeKit stops receiving updates, and shows the message _"This accessory is not responding"._

The bug can be reproduced with the `ServiceLoops` example, just run it for a couple of minutes and HomeKit stops updating, showing the "not responding" message.

The code in each service `loop()` function still runs but the updates don't get to HomeKit.

The problems with "disconnection" do not seem to occur with other kind of accessories as light bulbs.

-----

I'm using:
- ESP32.
- iOS 16.5.1.
- Old home architecture (I use an iPad as home hub).

**Comment by HomeSpan** [comment]
I loaded the ServiceLoops example onto an ESP32 under iOS 16.5.1 and its been running fine for about 45 minutes.  Both Temperature and Air Quality update every 5 seconds as expected.

Have you made any modifications in any way to the example?  Perhaps you are setting a variable outside the allowed range (HomeSpan will warn you on the Serial Monitor if this occurs).  

If not, my guess is the problem is related to using the iPad as a Home Hub.  I'm on the new architecture and using HomePods for my Hub.  About 6 months ago Apple made significant changes in the HomeKit even notifications process - you may need to move to the new architecture.

**Comment by JorgeFrias** [comment]
Thanks for the answer! That's quite interesting, found the bug working on a custom presence sensor, but I can reproduce the issue with the loops example untouched, it stops working after a couple of minutes every time.

Probably will I need to buy a HomePod for this. Could it be my board configuration (core to run the arduino, memory, etc.)? May I ask which parameters are you using there?

Thank you very much!

**Comment by JorgeFrias** [comment]
Thanks again for your answer, I'm going to buy a HomePod to test this out. I will report my findings once I have everything up and running.

The curious thing here is that my older DIY accessories use the [Arduino HomeKit ESP8266 Library](https://github.com/Mixiaoxiao/Arduino-HomeKit-ESP8266/) I have several lights running 24/7 without notable downtimes.

Also in the last day I have implemented a `HomeSpan HeaterCooler` and I'm having the same disconnection errors, this one doesn't have a `loop()`.

 But as you said, who knows what Apple is doing under the hood.

I will keep testing stuff in the mean time, thanks for the help!

**Comment by JorgeFrias** [comment]
**Solved"** I have more information on this one, just in case someone finds themselves in the same situation.

Adding a HomePod didn't solve the issue, sensors kept dropping.

What solved the problem: Changing the network infrastructure to Eero Mesh. I have no idea why, but this is what worked. I had several TP-Link access points, and the ISP router. I bet the ISP router was messing with the HomeKit communication, but I have no idea why.

Changing the network, made everything work, even without a HomePod, and without upgrading the home architecture, I'm still running the old architecture and everything works flawlessly.

Thanks a lot for the help @homeSpan !

**Comment by HomeSpan** [comment]
Thanks very much for the update - I'm really glad the issue was resolved with the new mesh network.
