### ISSUE TITLE
iOS 16.5.1

### ISSUE THREAD

**Issue by danieled03** [HomeSpan/HomeSpan#602]
it does not allow to pair with any type of device, it says that the device has already been paired and that it needs to be reset. Restoring and in any case it does not allow it to be added: "the accessory cannot be added, it is not compliant"

**Comment by HomeSpan** [comment]
Type 'H' into the Serial Monitor - this resets the Device ID of the ESP32 and will allow it to pair to HomeKit.  Next, use a completely unmodified version of tutorial Example 1, exactly as is, and try to pair.

**Comment by danieled03** [comment]
ok thanks, solved. Is there maybe some example of how .h files are configured to connect different services (other than the led example)? I would also like to create two accessories which are both two garage doors, I create them but in the end I only see one on homekit

**Comment by HomeSpan** [comment]
There are over two dozen examples of all different services in the library - see the tutorials page.
