### ISSUE TITLE
Is it possible to embed HomeSpan into existing firmware?

### ISSUE THREAD

**Issue by butaikis** [HomeSpan/HomeSpan#608]
Hello. I already have firmware with all sorts of wifi, eth, mqtt services. Tried using your library but it didn't work. Apparently it has its own web server and its own connection to wifi. Can this be bypassed somehow? Considering that I already have firmware with all services.

**Comment by HomeSpan** [comment]
You can use your own code to establish the WiFi connection, but the actual server that communicates with HomeKit is very specific and cannot be changed.  Apple uses continuously-open connections with their own encryption formats that HomeSpan needs to conform to.  It may be possible to extract that logic and use it in your own setting, but would likely require a lot of work.

For example, HomeKit connections can only be initiated in one direction - from the controller (i.e. an iPhone) to the Accessory (i.e. HomeSpan or any commercial HomeKit device).  Devices cannot open a connection to the iPhone.  This means that HomeSpan needs to keep multiple connections open indefinitely, which is not how a typical WebServer works.  When HomeSpan needs to communicate something to HomeKit (e.g. an updated temperature, the press of a light-switch button), it relays that information via an HTTP response to one or more of the permanently opened connections.

Note others have used MQTT with HomeSpan, but it needs to be embedded into the HomeSpan app, as opposed to the other way around.

**Comment by butaikis** [comment]
@HomeSpan 

Is it possible to make HomeSpan work not on port 80 but on some other one? Is it possible to have some simple example with separate initialization of a custom server on port 80, wifi, and HomesSpan ?

**Comment by HomeSpan** [comment]
Yes, you can start the HomeSpan server on any port using `homeSpan.setPortNum(uint16_t port)` (see the API for details on all the HomeSpan methods and functions).    To clarify what I meant above, you can create your own logic to set your WiFi credentials (using `homeSpan.setApFunction(void (*func)())`) but there is no hook to override the WiFi process itself (sorry if I created any confusion in my initial response).  You can also use `homeSpan.setWifiCallback(void (*func)())` to specify a function to be called after HomeSpan establishes a WiFi connection - this will allow you to initialize any other components at start-up that require WiFi to have already been established.

I unfortunately don't have any examples of how to run MQTT at the same time as HomeSpan - you may want to reach out to the authors of Issue #23 who seems to have successfully integrated the two.
