### ISSUE TITLE
M2: Accessory LTPK not yet set

### ISSUE THREAD

**Issue by ryanmaule** [HomeSpan/HomeSpan#612]
Getting the following error when trying to use homekitPair and following https://github.com/minamoanes/homebridge-homekit-control#how-to-fix-known-errors

`/var/lib/homebridge/node_modules/homebridge-homekit-control/node_modules/hap-controller/lib/protocol/pairing-protocol.js:415
            throw new Error('M2: Accessory LTPK not yet set');
                  ^

Error: M2: Accessory LTPK not yet set
    at PairingProtocol.parsePairVerifyM2 (/var/lib/homebridge/node_modules/homebridge-homekit-control/node_modules/hap-controller/lib/protocol/pairing-protocol.js:415:19)
    at /var/lib/homebridge/node_modules/homebridge-homekit-control/node_modules/hap-controller/lib/transport/ip/http-client.js:239:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

I'm unable to find any mention of this error anywhere for help.

**Comment by HomeSpan** [comment]
I think you may have posted this to the wrong repository.  Looks like you are using HomeBridge.  This repo is for HomeSpan.

**Comment by ryanmaule** [comment]
Yes, my mistake.  I am using Homespan successfully on the other end of my issue.  Closing.
