### ISSUE TITLE
NeoPixel_RGB limit

### ISSUE THREAD

**Issue by lukasa1993** [HomeSpan/HomeSpan#615]
i have Ws2812b led grid, which has 256 per grid i have 4 of them, when i set `nPixels` from pixels sample it only lights first 256 it never goes onto next grid i also tried `Adafruit_NeoPixel` which works with rest of them but i prefer using pixels from this library any idea what might be wrong ?

**Comment by HomeSpan** [comment]
Are the grids daisy-chained?  In other words, does this look like a single line of 1024 pixels?

**Comment by lukasa1993** [comment]
yes, they are chained, https://www.amazon.com/dp/B0B773C9KS

**Comment by HomeSpan** [comment]
Are you trying to set them all to the same color?  If so, I assume you are setting the size to 1024 (not 256).

**Comment by lukasa1993** [comment]
yes i am setting 1024 and yes same color whatever comes from homekit

**Comment by lukasa1993** [comment]
`    pixel->set(color.HSV(h*p, s*p, v*p),nPixels);       // sets all nPixels to the same HSV color`

problem seems to be with this line

`    pixel->set(color.HSV(h*p, s*p, v*p), 1024);       // sets all nPixels to the same HSV color`

so its example problem not lib it works now for me

**Comment by lukasa1993** [comment]
esp32-wroom-32d, but as i mentioned above it was example problem

**Comment by HomeSpan** [comment]
What exactly was the issue - a problem with the tutorial example?

**Comment by lukasa1993** [comment]
> What exactly was the issue - a problem with the tutorial example?

yes, i just replaced variable with 1024 and it works

**Comment by HomeSpan** [comment]
Ah - I just figured out the issue.  In my tutorial example I define the nPixel variable as uint8_t, which means if you pass the parameter 1024 it will be converted to 256 (actually, it gets converted to zero, but when counting backwards you get the same result).

In the example if you change every instance of `uint8_t nPixels` to `int nPixels` it should work fine.  I'll update that in the tutorial going forward.

For example:

```C++
  NeoPixel_RGB(uint8_t pin, uint8_t nPixels) : Service::LightBulb(){
```

should become:

```C++
  NeoPixel_RGB(uint8_t pin, int nPixels) : Service::LightBulb(){
```

**Comment by lukasa1993** [comment]
great good catch thanks for quick response
