### ISSUE TITLE
Cannot get RFControl to work on ESP32-C3

### ISSUE THREAD

**Issue by lukasmalkmus** [HomeSpan/HomeSpan#617]
I tried to use `RFControl` but couldn't get it to work on my C3 (gets stuck when I add something between the `clear` and `send` methods with `add` or `pulse`.

I tried the example (https://github.com/HomeSpan/HomeSpan/blob/master/docs/RMT.md#example-rfcontrol-sketch) but that resulted in a crash loop.

Any ideas?

**Comment by HomeSpan** [comment]
Did you update the pin number in the example to something that is compatible with your chip?

**Comment by HomeSpan** [comment]
I just tested on a C3 with an LED tied to pin=0 and the example seems to work.

**Comment by lukasmalkmus** [comment]
> Did you update the pin number in the example to something that is compatible with your chip?

That was my problem with the example 🤦 

But it still gets stuck on my codebase. I try to send a pulse on the `update` method of my accessory implementation. I copied the example code over and it gets stuck.

**Comment by lukasmalkmus** [comment]
Is there something special about the `RFControl` implementation that isn't stated in the example? E.g. do I need to set that up in `setup`? My implementation has `*RFControl` as a member in my custom accessory class.

**Comment by HomeSpan** [comment]
I have a full working example for a Samsung remote that may help:

https://github.com/HomeSpan/RemoteTV_SAMSUNG/blob/main/RemoteTV_SAMSUNG.ino

**Comment by lukasmalkmus** [comment]
Interesting. So it looks like the main difference here is that `rf` is declared globally. If I do that in my codebase, HomeSpan gets stuck and doesn't make it past the `Accessory configuration number: x` serial output.

**Comment by HomeSpan** [comment]
Can you post a paired-down sample of your code (minimal logic that causes the problem).

**Comment by lukasmalkmus** [comment]
I removed all my custom accessory implementation and got this minimal example that still crashes. Works fine without the global declaration of `rf`.

```
#define REQUIRED VERSION(1, 8, 0)
#include "HomeSpan.h"
#include "extras/RFControl.h"

RFControl rf(9);

void setup() {
  Serial.begin(115200);

  homeSpan.setStatusPixel(8, 90, 100, 5);
  homeSpan.setStatusAutoOff(15);
  homeSpan.setQRID("RFGO");

  homeSpan.begin(Category::GarageDoorOpeners, "RF Garage Door Opener", "RFGarageDoorOpener", "RFGarageDoorOpener");

  SPAN_ACCESSORY("Garage")
}

void loop() {
  homeSpan.poll();
}
```

**Comment by HomeSpan** [comment]
The problem is with `setStatusPixel()`.  You cannot use the HomeSpan Pixel driver and RFControl at the same time.  See https://github.com/HomeSpan/HomeSpan/blob/master/docs/Pixels.md#resource-usage-and-resource-conflicts for details.

**Comment by lukasmalkmus** [comment]
Ah, thanks. That was it!

Maybe this should be mentioned in the RMT docs, as well? As `setPixel` seemed straight forward, I never looked at that doc page.

One last question: I'm trying to send a 700us pulse. I cannot pass that to `start` as it only takes an `uint8`. Is the solution to adjust my phase ticks accordingly?

**Comment by HomeSpan** [comment]
It's a limitation of the hardware - the RMT peripheral includes an 8-bit divider, hence the limit of uint8.
