### ISSUE TITLE
Wi-Fi connection issue `E (26205) wifi:AP has neither DSSS parameter nor HT Information, drop it`

### ISSUE THREAD

**Issue by oilcan-productions** [HomeSpan/HomeSpan#621]
When connecting Wi-Fi to a mobile hotspot, dedicated like a Huawei, T-Mobile 5G Internet,  or a cell phone hotspot (multiple Android 12 and newer phones and iPhone 14 Pro Max)  the AP is discarded with a list of these messages and the device does not connect.
```

E (31038) wifi:AP has neither DSSS parameter nor HT Information, drop it
E (33483) wifi:AP has neither DSSS parameter nor HT Information, drop it
E (35840) wifi:AP has neither DSSS parameter nor HT Information, drop it
E (38313) wifi:AP has neither DSSS parameter nor HT Information, drop it
E (40678) wifi:AP has neither DSSS parameter nor HT Information, drop it
E (43080) wifi:AP has neither DSSS parameter nor HT Information, drop it
E (47898) wifi:AP has neither DSSS parameter nor HT Information, drop it
E (47979) wifi:AP has neither DSSS parameter nor HT Information, drop it
E (50388) wifi:AP has neither DSSS parameter nor HT Information, drop it
E (52791) wifi:AP has neither DSSS parameter nor HT Information, drop it
E (55145) wifi:AP has neither DSSS parameter nor HT Information, drop it
E (55146) wifi:AP has neither DSSS parameter nor HT Information, drop it
E (55247) wifi:AP has neither DSSS parameter nor HT Information, drop it
E (60022) wifi:AP has neither DSSS parameter nor HT Information, drop it
E (62479) wifi:AP has neither DSSS parameter nor HT Information, drop it
E (67266) wifi:AP has neither DSSS parameter nor HT Information, drop it
```
Connecting to a home AP or enterprise AP works without issue.

**Comment by HomeSpan** [comment]
This seems to be unrelated to HomeSpan but is a problem with the ESP32 library itself:  https://github.com/espressif/esp-idf/issues/9283

**Comment by oilcan-productions** [comment]
It seems though the issue has been fixed in 4.4 and 5.x of espressif. So my thinking is that homespan might be using a library version that is older or is that coming through platform.io?

**Comment by HomeSpan** [comment]
HomeSpan uses the Arduino-ESP library from Espressif (even if using Platform IO you would have needed to install that to get HomeSpan to compile).   The latest version from Espressif is 2.0.11.   This library in turn uses a specific version of the ESP32 IDF (such as version 4.4.5).  When you first launch HomeSpan it will report which version of the Arduino-ESP library you have installed as well as which version of the lDF this library is using (the latter is determined by Espressif).   What version of the Arduino-ESP library are you using?

**Comment by oilcan-productions** [comment]
Here is the output from the startup
```
Message Logs:     Level 0
Status LED:       Pin -  *** WARNING: Status LED Pin is UNDEFINED
Device Control:   Pin -  *** WARNING: Device Control Pin is UNDEFINED
Sketch Version:   v1.0.0
HomeSpan Version: 1.8.0
Arduino-ESP Ver.: 2.0.9
ESP-IDF Version:  4.4.4
ESP32 Chip:       ESP32-D0WD Rev 1 dual-core 4MB Flash
ESP32 Board:      d1_mini32
PWM Resources:    16 channels, 8 timers, max 20-bit duty resolution
Sodium Version:   1.0.12-idf  Lib 9.4
MbedTLS Version:  mbed TLS 2.28.1
Sketch Compiled:  Jul 27 2023 11:41:46
Partition:        app0
MAC Address:     xx:xx:xx:xx:xx
```
Looks like 4.4.4 is the version.

**Comment by HomeSpan** [comment]
Yup, that's 4.4.4.  Hard to say why the error is occurring, but unfortunately not sure there is anything I can do to address.    There must be something unique about hotspots that create this error.

**Comment by oilcan-productions** [comment]
Thank you I will carry forward the discussion with the ESP-IDF folks
