### ISSUE TITLE
Error : This accessory has not been certified to work with HomeKit so some features may not be available.

### ISSUE THREAD

**Issue by nycco** [HomeSpan/HomeSpan#623]
First of all, thank you so much for this really straightforward library!

I wanted to build a DIY Homekit accessory with my ESP32 DevKitv1, and I followed this excellent tutorial: https://www.youtube.com/watch?v=K1xrCyN9T98

Everything went well, from firmware upload to Homekit pairing. However, when I try to use the accessory in the Home App, I encounter an error message for my DIY Homespan accessory: 'This accessory has not been certified to work with HomeKit, so some features may not be available.' As a result, nothing is working (neither the LED nor the Switch).

Thank you in advance for any assistance!

**Comment by HomeSpan** [comment]
The warning message you receive when pairing is implemented by Apple to alert the user that they are using a non-commercial device that has not ben reviewed by Apple.  There is no way to get rid of this message - simply allow it to pair anyway.

In terms of debugging, please start with a completely unmodified version of tutorial Example 1 and see if that works as expected.  The Tutorials are designed to take you from easiest test-project to more complicated projects.  Note as the Tutorials progress to using actual ESP32 pins, you'll need to modify to suit your particular ESP32 board.

**Comment by nycco** [comment]
Thank you for your answer. 

Actually, I understand the alert from Apple, and when I was pairing the ESP with Homekit, I accepted this alert by clicking "Add anyway."

However, the error occurs after the ESP is paired. The Bridge or even the Lightbulb is not recognized by Homekit. You can see a screenshot here: [WhatsApp Image 2023-07-31 at 18 23 46](https://github.com/HomeSpan/HomeSpan/assets/6965089/e903ddc9-6e8f-4f56-872b-07e222a02f80)

Is my ESP32 compatible with your library? (ESP-WROOM-32, DevKitv1)

Thanks.

**Comment by HomeSpan** [comment]
That device should be compatible.  Did you try the Example 1 tutorial?

**Comment by HomeSpan** [comment]
Also, what version of iOS are you using?

**Comment by nycco** [comment]
Yes I tried the Example n°1 without any change. Just upload it on my ESP32. 
I can't even detect the ESP when i want to add an accessory. 

iOS 16.4.1

Thanks

**Comment by HomeSpan** [comment]
Here's a few things to try:

* Did you make sure to unpair the ESP32 before trying to re-pair it with HomeKit?   If you type 's' into the CLI, it will tell you whether or not the device is already paired.  If it is (or even if it isn't), type 'H' into the CLI.  This erases all pairing information and reboots HomeSpan with a new Device ID to make sure it looks new to HomeKit.
* Once rebooted type 'L2' into the CLI to set the log output to the most verbose level.
* Now try pairing by hitting "Add Accessory", and then "More Options" from the iOS Home App. You should see the HomeSpan device as an option.  Select the device and type in the Setup code.  If you don't see the device, type 'E' into the CLI and try again.  This erases all WiFi data as well as pairing info, so you'll need to retype your network credentials.
* If the device still does not show up for pairing, let me know and we can explore more potential ideas.
* If the device does show up and you can start the pairing process, what happens next?  Do the log files show communication between HomeKit and HomeSpan (remember to type 'L2' into the CLI if you reboot the device)?  Do the log files indicate pairing is successful, or did it fail?  If you type 's' into the CLI, does it confirm that the device is paired?
* If paired, you should see an icon for the device in HomeKit.
* Make sure to check all the rooms - sometimes HomeKit will put the tile in the "Default Room" even if you request a different room.

**Comment by nycco** [comment]
Thank you so much for your time! It is finally working! Your library is very good, and the logs in verbose are very explicit.

Before, I saw the Wifi credentials warning, but I didn't think that it was essential. The guy in the video didn't mention that :)

I only encountered a small error when pairing:
ERROR: Unrecognized Controller PairingID.

But it worked!

Last question, but not least: Does Homespan use the HomeKit Accessory Protocol? Have you planned to adapt it with the Matter protocol? 

thnak you so much for your work ! My home automation will pass to the next level!

**Comment by HomeSpan** [comment]
Really glad it is working.  The error you are receiving about the PairingID should be no problem.  It means that HomeKit is trying to establish a connection using a controller it has not yet registered, but it uses multiple controllers so there is no issue.  I have noticed the same error arising about 50% of the time in my own setup and I'm trying to track down which device (HomePod, Apple TV, iPhone, etc.) HomeKit is using to try create that connection for, to see if the problem is out-of-date software on that device.  But regardless it causes no issues with HomeKit itself.

Regarding your last question, yes HomeSpan uses Apple's HomeKit Accessory Protocol (HAP).  No plans at present to add Matter, though I appreciate that it would enable HomeSpan to be used in a non-Apple ecosystem.  Might be something for the future.

**Comment by nycco** [comment]
Thank you for your response.

Yes, it would be great if we could make HomeSpan compatible with non-Apple ecosystems.

Furthermore, I haven't come across any ESP32 IoT library (using any protocol) that is as clear and explicit as yours!

With HomeSpan and Matter, things could definitely change :)
