### ISSUE TITLE
Humidifier - Dehumidifier

### ISSUE THREAD

**Issue by willow2ko** [HomeSpan/HomeSpan#628]
Hello,

I'm working on a Humidifier "only" device , the code I have works but I cannot make my device to only humidify without the need to have also dehumidifying functions.

I went through the HomeSpan issues and discussions looking for some information and I've found nothing at all that can help me. 

Could you please help me create an example for just a humidifier that works?

Thanks,

**Comment by HomeSpan** [comment]
The Apple Service is generic and supports both a Humidifier and Dehumidifier at the same time.  The TargetHumidifierDehumidifierState Characteristic is used to select Humidifier (val=1), Dehumidifier (val=2), or both (val=0), from within the Home App.  However, you can restrict the allowed range of this Characteristic to prevent val=2 and val=1, basically only allowing val=1, which is for the Humidifier.  The easiest way to do this is with the setRange method (set the min=1 and max=1).

**Comment by willow2ko** [comment]
Thanks for the advice but unfortunately didn't work, or I am just not good enough to place setRange in the right place.

This is how the code looks like:

struct DEV_Humidifier : Service::HumidifierDehumidifier {           

  int onPin;
  int offPin;                                   // pin number defined for this LED
  SpanCharacteristic *power;                       // reference to the On Characteristic
  SpanCharacteristic *level1;
  SpanCharacteristic *level2;

  DEV_Humidifier(int onPin, int offPin) : Service::HumidifierDehumidifier(){       // constructor() method

    power=new Characteristic::Active();
    new Characteristic::CurrentRelativeHumidity();
    level1=new Characteristic::CurrentHumidifierDehumidifierState();
    level2=new Characteristic::TargetHumidifierDehumidifierState();
    //new Characteristic::RelativeHumidityHumidifierThreshold();
     
    level1->setRange(0,2,1);
    level2->setRange(1,1,1);

    this->onPin=onPin;                            // don't forget to store ledPin...
    this->offPin=offPin; 
    pinMode(onPin,OUTPUT);                         // ...and set the mode for ledPin to be an OUTPUT (standard Arduino function)
    pinMode(offPin,OUTPUT);                        

  } // end constructor

  boolean update(){                              // update() method

    if(power->getNewVal())
    turnON();
    else
    turnOFF();
    
    return(true);                             // return true
    
  } // update

  void turnON(){
    // generate short pulse to set the latching coil
    digitalWrite(onPin, HIGH);
    delay(100);
    digitalWrite(onPin, LOW);
  } // turnON

  void turnOFF(){
    // generate short pulse to set the reset coil
    digitalWrite(offPin, HIGH);
    delay(100);
    digitalWrite(offPin, LOW);
  } // turnOFF

};   

And this is how I still see the humidifier in the home app:
![IMG_5861](https://github.com/HomeSpan/HomeSpan/assets/39411769/8e2be98a-26a8-47dc-a02c-e10cf5f2ee6a)

**Comment by HomeSpan** [comment]
Sorry, try `setValidValues(1,1)` instead.  I just tested and it seems to do the trick.  Rather than reset the minimum and maximum, this uses a different HAP structure to set the specific allowed values.    Note to make this a humidifier only, you should use RelativeHumidityHumidifierThreshold and delete RelativeHumidityDehumidifierThreshold.

**Comment by willow2ko** [comment]
Thanks again for the great help. It worked with setValidValues(1,1). 
![IMG_5866](https://github.com/HomeSpan/HomeSpan/assets/39411769/91ce46eb-53f4-47a1-8019-f9aaa6555b36)

I appreciate taking the time to help me.

Hasta luego,
