### ISSUE TITLE
Are there any alternative methods to enable pairing mode (other than serial, physical button)

### ISSUE THREAD

**Issue by maisyk** [HomeSpan/HomeSpan#629]
I am aware that you are able to enable pairing mode via serial or via a dedicated button but is there any other means of doing this?

For example, many of the products you buy online with smart home capabilities can be placed into pairing mode by turning them off and on a set number of times rapidly. I was wondering if something like this is possible with HomeSpan and I have just missed it in the docs?

This isn't a problem for devices that are easily accessible but I am thinking for devices that are placed in more hard-to-reach locations let's say for example a warehouse light. Would be much easier to place the device into pairing mode by flicking a switch than getting out a ladder/forklift to get up there. 

If something like this isn't available has anyone got any suggestions on how they would implement such a feature? The only alternative solution I could think of was to pair up a single-button Bluetooth remote which had the sole purpose of putting devices into pairing mode.  This would of course be annoying as that one extra thing to take care end ensure it doesn't get lost. 

So yeah any suggestions are welcome. 

Thanks, 
Maisy

**Comment by HomeSpan** [comment]
When you say "pairing," do you mean pairing with HomeKit or establishing a WiFi connection?  I assume you mean WiFi, because the Serial Button on HomeSpan can be used to activate the HomeSpan Access Point, which allows you to enter your WiFi credentials via a HomeSpan-hosted Web Interface.  Pairing itself is a different process and is always on, meaning that if the device is not paired, it will be ready for pairing with any HomeKit controller, provided you use the pairing code defined for the device.

WiFi connectivity is automatically established if it is lost.  The only thing you need to do initially is provide the WiFi Credentials for your network.  Can you describe in more detail the conditions that you are trying to "reset" by turning on/off power?  It may be something I can add to a future release.

**Comment by maisyk** [comment]
I would like to clarify my previous communication regarding the WiFi pairing process, specifically activating the device's WiFi Access Point (AP).

I am aware that the serial button can initiate the AP. However, in scenarios where the devices are already installed and there's a change in WiFi credentials, it seems the only method to prompt the ESP to re-initiate the AP for updating those credentials would be through physical access to the serial button.

To streamline our operations, could you please confirm if there is an alternative method available to remotely instruct the ESP to reset its WiFi credentials and subsequently activate the AP for reconfiguration?

Thank you for your attention to this matter.

**Comment by HomeSpan** [comment]
Thanks for the details.  HomeSpan does not currently have a way to remotely erase the WiFi credentials but your use-case makes sense.  I'd have to enable the real-time-clock to be able to keep track of power cycles within a fixed period of time, but it should be doable.  I'll do some more research and see if I can add to the next release.  Thanks for the great suggestion.

**Comment by HomeSpan** [comment]
I've added a new homeSpan method `setRebootCallback(void (*func)(uint8_t count), uint32_t upTime)` that provides a generic mechanism to keep track of quick reboots as a result of power-cycling the device.   This callback allows you to create custom code that can be triggered after a specified number of reboots to do just about anything, such as erasing the WiFi Credentials after 3 quick power-cycles and/or Factory resetting the device after 5 power cycles. 

This code, along with full documentation of the function, has been added to the release-1.8.1-dev branch (to be rolled out into production as part of 1.8.1).  Please feel free to give it a try and let me know what you think --- the example in the documentation replicates what you are trying to do above.

**Comment by frankonski** [comment]
@maisyk, just be careful about the security of your solution. If you end up connecting your HomeSpan device to something like a light switch to turn on/off the power to the device, for which you would have added some logic in `setRebootCallbac()` to erase the WiFi settings to put it back in WiFi pairing mode, the question then becomes "_who can access that light switch?_" If anyone has access to that power switch, its not good. 

I would not consider this a "remote" way to reset the WiFi credentials, but rather "physical access", as you can physically control the power to the board.

> if there is an alternative method available to remotely instruct the ESP to reset its WiFi credentials and subsequently activate the AP for reconfiguration

You are looking for a way to trigger a Denial of Service? Sure, you could implement an HTTP handler like `http://host/erase_wifi_credentials`, but that would be a major security mistake unless you have some authentication and authorization logic built-in.

**Comment by HomeSpan** [comment]
New function has been added in dev branch and will be in next production release.
