### ISSUE TITLE
COMPARTIR HOMESPANN CON AMIGOS

### ISSUE THREAD

**Issue by albertobnd19** [HomeSpan/HomeSpan#630]
HOLA
ALGUIEN QUE ME PUEDA AYUDAR A MODIFICAR LAS LIBRERIA PARA QUE HOMEKIT ME DEJE COMPARTIR CON AMIGOS 
PORFAVOR :C

**Comment by HomeSpan** [comment]
In what way are you looking to modify the library - not sure what you mean by sharing with friends.
