### ISSUE TITLE
Sending serial ASCII commands

### ISSUE THREAD

**Issue by Glujaz** [HomeSpan/HomeSpan#632]
Hi there,

I know it's a bit much to ask, but I'm trying to create a HomeKit device which will turn on or off my amp.

it communicates through rs232, and uses ASCII characters. (@115200 8N1)
I tried with something simple for now, which is just using the example code to turn on and off LEDs, but I'm really lost here.

I'm really new to coding (only know basic, VBA, and a little bit of HTML/PHP...), and I just don't understand it. I understand how Homespan is calling for the actions which should be visible in HomeKit, but I don't understand the physical interaction after that with the LED in the example. It seems to be something like "if on, turn the pin on, else, invert".

but for my need, I would require to have 2 pins assigned for serial (TTL if correctly understood ?), and then send the command in ASCII "power_on!" When the switch is turned on, and then send "power_off!" When the switch is turned off.

and if someone can also tell me how from time to time the code asks the state of the amp with "power?" (The amp then replies for example "power=on$"), and update the switch, that would also be very helpful :)

I think, with that, I could be able to do much more, like make the amp show as a TV later on :)

thanks a lot ! 😁

**Comment by HomeSpan** [comment]
It is definitely possible to use HomeSpan in this fashion, and others have indeed created HomeSpan projects that interface with appliances via the serial port.  However, the hard part is not HomeSpan, but rather the serial interface.  The ESP32 supports multiple serial connections, but there is some hardware work you will need to do to convert TTL to RS232.  Fortunately most electronic hobby stores have adapters for this.  Then you'll need create the code for the serial communication between the ESP32 and your amp, which is separate from anything related to HomeSpan.

My recommendation would be first explore the use of an ESP32 to communicate with your amp via serial on a standalone basis (i.e. without HomeSpan).  Once you get that running you can then layer in HomeSpan.

**Comment by Glujaz** [comment]
Ok, so, for now, I have a ttl to RS232 adapter, which I connected to serial 1 (leaving 0 as is, and not using 2). I can send one basic command.

and my understanding was that after an action is done on homespan (switch is turned on), it should call for a command (which is on an other tab in the Arduino IDE). But I don't really understand how to apply when explicitly turned on or off. Or maybe, I'm just absolutely not understanding how all the thing is working.

I'm thinking this for now like a VBA function, where let's say "switch turned on" (main page in the IDE) calls for the function "amp on" for example (in another tab of the IDE)

am I completely wrong here ? I have to admit, as the homespan examples are very basic for my need (LED switching, or variable lighting), but not ESP32 actions... (or maybe I didn't checked enough...)

**Comment by HomeSpan** [comment]
You can use Example 5 to start, which turns on a light.  But instead of a light you can have it do anything.  Note the lines of code that say digitalWrite().  This is what turns on an LED attached to a pin.  You can replace this with anything.  If you know the serial commands to turn on/off your amp, then replace the digitalWrite() with Serial.write() to send the appropriate commend.  Note there is nothing specific to a light in Example 5, with the exception of the lightbulb icon.

**Comment by HomeSpan** [comment]
Have you been able to modify Example 5 per above to use Serial.write() for you RS232 connectivity?

**Comment by Glujaz** [comment]
Sorry for the late reply, I've been quite busy lately...

so, I tried what you said. Create a code which works from itself, and then try to implement this with homespan afterwards. As I'm a complete noob in coding, I tried out using chat GPT to generate the code. The good news is that once it has generated it, I can actually understand it well (I know how to code in basic and shell script), and after telling him some mistake he made, he couple generate me a code which lets me turn the amp on and off to begin with (first time using chatGPT, I was stunned by the result !). Though, in the end, I'm still unable to talk with the amp, unlike what I said initially in my first comments...
The way it works, is that I send a console command to the ESP like "turn on", and then it sends the command via serial to the amp. But as I said, it's not working on the serial side...

Here is my current code :

`#define CONSOLE_SERIAL Serial

bool rs232UpdateEnabled = true; // Initially set RS232 updates to ON

void setup() {
  CONSOLE_SERIAL.begin(115200); // Set the baud rate for the Arduino IDE's serial console
  Serial2.begin(115200, SERIAL_8N1); // Initialize Serial2 for RS232 communication with the amplifier (8 data bits, no parity, 1 stop bit)
  delay(1000); // Allow time for the serial connections to initialize

  // Display a welcome message in the serial console
  CONSOLE_SERIAL.println("Welcome to Amp Control!");
  CONSOLE_SERIAL.println("Type 'on-amp' to turn on the amp, 'off-amp' to turn it off, 'rs232_update_on' to enable RS232 updates, 'rs232_update_off' to disable RS232 updates, 'power?' to get the power status, or 'restart' to restart the ESP32.");
  CONSOLE_SERIAL.print("> "); // Display a prompt for user input
}

void loop() {
  if (CONSOLE_SERIAL.available() > 0) {
    String command = CONSOLE_SERIAL.readStringUntil('\n'); // Read the command from the console
    command.trim(); // Remove leading/trailing whitespaces

    // Check the received command
    if (command == "on-amp") {
      sendCommand("power_on!");
      CONSOLE_SERIAL.println("Sent 'power_on!' command to the amp.");
    } else if (command == "off-amp") {
      sendCommand("power_off!");
      CONSOLE_SERIAL.println("Sent 'power_off!' command to the amp.");
    } else if (command == "rs232_update_on") {
      rs232UpdateEnabled = true;
      CONSOLE_SERIAL.println("RS232 updates enabled.");
    } else if (command == "rs232_update_off") {
      rs232UpdateEnabled = false;
      CONSOLE_SERIAL.println("RS232 updates disabled.");
    } else if (command == "power?") {
      sendCommand("power?");
      delay(100); // Delay to allow time for the response from the amplifier
      if (Serial2.available() > 0) {
        String response = Serial2.readStringUntil('$'); // Read the RS232 response until the terminating "$" character
        if (response.length() > 0) {
          CONSOLE_SERIAL.println("Power status response: " + response);
        }
      } else {
        CONSOLE_SERIAL.println("No response received from the amplifier.");
      }
    } else if (command == "restart") {
      CONSOLE_SERIAL.println("Restarting ESP32...");
      delay(1000); // Optional delay for user feedback
      ESP.restart(); // Restart the ESP32
    } else {
      CONSOLE_SERIAL.println("Invalid command.");
    }

    // Display a prompt for the next user input
    CONSOLE_SERIAL.print("> ");
  }
  
  // Check for RS232 updates if enabled
  if (rs232UpdateEnabled && Serial2.available() > 0) {
    String response = Serial2.readStringUntil('$'); // Read the RS232 response until the terminating "$" character
    if (response.length() > 0) {
      CONSOLE_SERIAL.println("Received RS232 update: " + response);
    }
  }
}

void sendCommand(const char* command) {
  // Send the specified command to the amplifier via Serial2 (RS232)
  Serial2.print(command); // Send the command without a newline
  Serial2.println("!");    // Send the terminating "!" character
  delay(100); // Adjust delay as needed to ensure the command is sent
}
`

But while it's not working, I'm still trying to at least make this code communicate with homespan, and here is where, again, I get some difficulties. I don't know how to switch it from turning a pin on or off, to sending the equivalent of my console command here.


By the way, in the end, I'm putting this project on pause, as I'm waiting for more details from rotel to really manage to communicate with the amp.

what I did instead, as I have an IKEA purifier, smartify the purifier. It's easier to begin with, and understand homespan, as this time, it's really a matter of turning pins on.
But, again, I'm lost with the same issue, although, I think I might have Bette chance to make it work, as I'm using pins to be switched on or off. Except this time, it's 4 pins to be switched, as well 4 pins to get input.

it's not about serial communication anymore, so I might have to create a new issue if I need some help, BP so I'm asking if I can put the code for that purifier instead, here as well :)
(Technically, its the same issue :) )

**Comment by HomeSpan** [comment]
Any update on this - can I close?

**Comment by Glujaz** [comment]
Sorry, it has really been a huge while... I got a bit bored by not finding a solution.
I tried multiple times to use just the LED example 5, then tried with something much simpler as a project (home kiting IKEA's air purifier), but that also did not work.

So for now, I'm really going back to the LED 5 example, and just looking for now to turn on and off the amp by sending the respective commands over serial.

My understanding is that I have to modify in this part

```
  DEV_LED(int ledPin) : Service::LightBulb(){

    power=new Characteristic::On();                 // this is where we create the On Characterstic we had previously defined in setup().  Save this in the pointer created above, for use below
    this->ledPin=ledPin;                            // don't forget to store ledPin...
    pinMode(ledPin,OUTPUT);                         // ...and set the mode for ledPin to be an OUTPUT (standard Arduino function)
    
  } // end constructor

  // Finally, we over-ride the default update() method with instructions that actually turn on/off the LED.  Note update() returns type boolean

  boolean update(){            

    digitalWrite(ledPin,power->getNewVal());        // use a standard Arduino function to turn on/off ledPin based on the return of a call to power->getNewVal() (see below for more info)
   
    return(true);                                   // return true to indicate the update was successful (otherwise create code to return false if some reason you could not turn on the LED)
  
  } // update
};
```

this section :

```
this->ledPin=ledPin;                            // don't forget to store ledPin...
    pinMode(ledPin,OUTPUT);
```

But the boolean this is loosing me. Can you explain it a bit more ?
Because for powering the amp on, I would have to replace the code by this :
`Serial2.print(poweron!)`

and to power it off, it's 
`Serial2.print(poweroff!)`

I can also get the status to confirm the state, but it's just adding an "if" somewhere :)

Thanks in advance, and sorry again :)
