### ISSUE TITLE
ESP32 custom PCB, HomeSpan

### ISSUE THREAD

**Issue by ronny-antoon** [HomeSpan/HomeSpan#633]
i had made a custom PCB for my own design, and i made a sketch that only use your lovely library. 

5 boards same PCB design, and same sketch. 

randomly every 3-5 days one of the boards go offline. it disconnect from wifi without any problem.
and never come back alone.
1)  if i restart the board (unplug and plug power source) it connect and all goes normal as expected.
2) if i restart the router and not restart the board, the board reconnect alone and goes normal as expected.

what you think about this problem??

i have more than 20 devices that connected to the same wifi and never had any problems with the wifi, i tried in another Home (different router) and got the same problem.

**Comment by Olivierbkk** [comment]
it started like this for me a few weeks ago

see #580

**Comment by HomeSpan** [comment]
@ronny-antoon, is the board disconnecting from WiFi itself, or is it staying connected to WiFi but simply losing HomeKit connectivity?  Please see the #580 thread for a complete discussion and suggestions for how to debug and find the source of the problem.

**Comment by ronny-antoon** [comment]
@Olivierbkk I think my problem is the PCB Board, Iam still testing.
i have 3 days without any problems. i enabled the weblog by homespan and waiting for any disconnect issue to see what the log says and what is the disconnected.

**Comment by Olivierbkk** [comment]
Thanks, so far I was not able to find a solution, I am reluctantly turning towards commercial devices and going back to homebridge for some functions such as the security system and dummy switches. Hopefully your problem is easier than mine.

**Comment by ronny-antoon** [comment]
@Olivierbkk @HomeSpan 
i have question related to this issue.
i think my device just disconnect from the Main Hub in my home.(HomePod Gen 2).
i want to ask if their is a function that i can run every X time or a status flag to check every X time, if their is no connection with the Hub then try to connect another time, by reproduce database or MDNS brodcast.

if we can make it by a cli command or by weblog command. iam not sure how to implement this.

thank you guys

**Comment by HomeSpan** [comment]
You can add a way of "bouncing" the MDNS as follows:  At the top of your sketch, add `#include <ESPmDNS.h>`.  Then, somewhere in the `setup()` section of your sketch, create a new CLI command:

```C++
  new SpanUserCommand('b', " - bounce MDNS", [](const char *buf){mdns_service_txt_item_set("_hap","_tcp","bounce","1");});
```

This creates a new user-defined CLI command "@b".  When typed into the Serial Monitor it will add a new MDNS data element that assigns the MDNS text item "bounce" to equal "1".  The word "bounce" does not mean anything, but the fact that it is added causes HomeSpan to re-broadcast the entire MDNS set of messages just as it does when first booting.  Every time "@b" is again typed, HomeSpan will perform an entire fresh re-broadcast even though nothing has changed.

I'm very curious if this addresses the issue.  If so, I can add some logic to check if there are no connections (i.e. it has dropped), and if so, automatically trigger the MDNS re-broadcast.

**Comment by ronny-antoon** [comment]
![image](https://github.com/HomeSpan/HomeSpan/assets/90724911/1ab017c1-274e-4fcd-9942-c477de97cdad)

![image](https://github.com/HomeSpan/HomeSpan/assets/90724911/b4e45060-2a31-437c-b1a5-74350ffaa99e)

**Comment by ronny-antoon** [comment]
![image](https://github.com/HomeSpan/HomeSpan/assets/90724911/a61a41c2-4b0e-446d-b3aa-ab2ecefbaa01)

All three esp32 connected.

But one of them not responding

![image](https://github.com/HomeSpan/HomeSpan/assets/90724911/37a91174-69b0-4d58-b399-df5e03492994)

I will try your cli command. Next time

**Comment by HomeSpan** [comment]
May want to double-check the device that has no MDNS entry is indeed connected to WiFi (the status shown in your router may not reflect actual status).  To double check your device is connected to WiFi, try to connect to it using its IP address from your web browser.  If it returns immediately with a blank page, it means the device is connected.  If it hangs for a while, it means it is not connected.

**Comment by BruderHood** [comment]
Do you think it could also be due to your PCB design? That the antenna of the ESP is disturbed by interference?

**Comment by ronny-antoon** [comment]
> Do you think it could also be due to your PCB design? That the antenna of the ESP is disturbed by interference?


In my opinion, my PCB design could disturb the antenna, but that will lead to disturb the WiFi strength or connectivity, but not the MDNS or the connection between my app and HomeKit.

When the problem is occurred, the WiFi still working, and the website working. All functions working but HomeKit no, MDNS _hap not broadcasting.

**Comment by ronny-antoon** [comment]
Another thing happened today. Maybe could tell you something.
The problem happened again. One of 3 PCBs got no responding.

State1:- PCB name "UXUX"
In APP HomeKit No Responding.
Website running good.
All other functions working.
In Discovery APP MDNS _hap._tcp. Not showing this board.

-- press button for rebroadcast MDNS by adding "bounce: 1"--

State2:-PCB name "UXUX"
In APP HomeKit No Responding.
Website running good.
All other functions working.
In Discovery APP MDNS _hap._tcp. Showing this board as loading. After 5 seconds it disappeared again. 

![image](https://github.com/HomeSpan/HomeSpan/assets/90724911/804bbf53-5c93-4153-aa36-b31603b042b4)

![image](https://github.com/HomeSpan/HomeSpan/assets/90724911/ce4d27f4-3c3a-4f73-8da3-9508352b14dc)

**Comment by ronny-antoon** [comment]
@HomeSpan hey, iam sorry for tagging you, but i need your help. can you check my last comment, and tell me if you got any idea of what's happening. 
thank you

**Comment by HomeSpan** [comment]
Sorry, I can't think of any way of debugging this further.  From web searches it appears that this is not an uncommon problem with using HomeKit devices on some routers, though there does not appear to be a standard way to address.  I had a similar problem in my own setup when using a Linksys Velop mesh network.  I finally tossed it and replaced with a Netgear Orbi mesh network and immediately no longer had any issues with either my HomeSpan or any commercial HomeKit devices that were giving me trouble.  But I don't think my experience is universal --- likely depends on exactly how the router and mesh is configured, network topology, etc.

**Comment by ronny-antoon** [comment]
okay :(
thank you alot for your time.
i will close the issue.

**Comment by Olivierbkk** [comment]
after update 17.2 it seems to be working now, what about you?

**Comment by Olivierbkk** [comment]
nope... I talked too soon... still random disconnections. I am almost done migrating my ESP to other devices but still trying/hoping...
