### ISSUE TITLE
HomeSpan Setup page is empty

### ISSUE THREAD

**Issue by oilcan-productions** [HomeSpan/HomeSpan#634]
After starting the AP and browsing to 192.168.4.1 I get a yellow page with the "HomeSpan Setup" title but no form fileds.

Am I missing something? In my code I call `homeSpan.enableAutoStartAP()` and used the serial command interface to clear out the existing Wi-Fi credentials.

**Comment by HomeSpan** [comment]
Are you accessing the set-up page using an iPhone?  Others have reported it does not work on an Android.  If you see the yellow screen labeled HomeSpan Setup you are definitely in the right place, though I'm not sure why the form is not appearing.

If you set the log level to 2 in your sketch you should be able to see the the HTML for the setup page being generated and transmitted.

**Comment by HomeSpan** [comment]
Any update on this - are you accessing with an iPhone or Android?

**Comment by oilcan-productions** [comment]
Sorry I have been on vacation :). 
The page is empty regardless which browser I use on iOS, Android or PC/Mac.
I don't get any HTML in the output with Loglevel=2, I only get the list of networks found to join then it sits there with `Ready.`

**Comment by HomeSpan** [comment]
Based on the log file above the AP has properly launched.    To confirm, on your iPhone you are opening up you WiFi settings and connecting to HomeSpan's Access point, correct?  Once connecting, the iPhone should automatically launch the HomeSpan Setup Page.  You should not need to open your browser of navigate to any specific IP.

**Comment by oilcan-productions** [comment]
Yes the browser opens automatically and I get a page with the text "HomerSpan Setup" and nothing else
![image](https://github.com/HomeSpan/HomeSpan/assets/77457397/43f4f1ff-8330-4a59-ad18-263932fa1ef9)

**Comment by HomeSpan** [comment]
I've not seen this before.  If you are getting to the page above, then at a minimum you should have seen the HTML in that page printed on the Serial Monitor when the log file is set to L2.   But based on the log file above, you are not seeing anything, which suggests maybe something is cached in your iPhone?  Have you tried hitting "Forget this Network" and relaunching?

One possibility is that the code is not properly handling international ascii characters.  Do any of your networks use international characters (there is a pull request to fix this in the next release if this is indeed the issue).
