### ISSUE TITLE
Example 5 - homekit says "an accessory does not meet requirements"

### ISSUE THREAD

**Issue by nakeeon** [HomeSpan/HomeSpan#636]
Hello! Just learning this amazing library. I've uploaded Example 1 and tried to add it to the homekit - it works fine. Then I uploaded Example 5, but during accessory adding to the homekit it says, "an accessory does not meet requirements".

It is worth noting that I am using PlatformIO in VSCode, not Arduino IDE.

**Comment by HomeSpan** [comment]
Did you change the pin numbers used in Example 5 to match your specific board?

**Comment by nakeeon** [comment]
Yes, I did. I had a working simple code that lights up a LED. Then I tried to integrate a HomeSpan.

**Comment by HomeSpan** [comment]
Did you modify Example 5 at all by adding in additional logic?  If Example 1 works, Example 5 should work as well.  That said, I've not used PlatformIO so there may be something related the install that is causing the issue.

**Comment by nakeeon** [comment]
I only changed the pin number on line 102.
Okay, to be fully compatible I will try using Arduino IDE.

**Comment by nakeeon** [comment]
It worked if compiled and uploaded via Arduino IDE. Thanks!
