### ISSUE TITLE
i not found the  api of reset it to factory!

### ISSUE THREAD

**Issue by averyhome** [HomeSpan/HomeSpan#643]
Hi,thanks, it is a good job.
i remove the accessory from the Home App. and i want use my app send a msg to esp32 to reset it to the factory, then it is clean. it is a new device. and  i can add it again. but i not find the api of use code . only the cli. 
can you teach me how to do it?

**Comment by HomeSpan** [comment]
You can programmatically call any CLI command using `homeSpan.processSerialCommand()`.  So to factory reset, you can call `homeSpan.processSerialCommand("F")`.
