### ISSUE TITLE
Device appears unresponsive with iPhone 14

### ISSUE THREAD

**Issue by XDM525** [HomeSpan/HomeSpan#644]
I am using an ESP32 DEV Module with the unmodified "WorkingLED" example. I am able to connect to the internet and add the device to Apple Home however, when I go to turn on an LED, the device appears unresponsive when using an iPhone 14. 
I had tested total of 5 different iPhones on the same network and 3 of them worked perfectly. See below for which phones I tested. The two that failed were both iPhone 14s. Is anyone else having problems with HomeSpan with iPhone 14? 

Phones Tested
iPhone 14, iOS 16.6.1, Failed testing
iPhone 14, iOS 16.6, Failed testing
iPhone 13 mini, iOS 16.6.1, Passed testing
iPhone 13, iOS 16.6, Passed testing
iPhone 8, iOS 16.6, Passed testing

**Comment by HomeSpan** [comment]
Do you have the same issue with commercial devices or just HomeSpan?  I have not heard of any issues with regard to iPhone version, just iOS version.

**Comment by HomeSpan** [comment]
Has this been resolved - can I close?
