### ISSUE TITLE
Using .setControlPin() faults pairing

### ISSUE THREAD

**Issue by gotfredsen** [HomeSpan/HomeSpan#645]
When I use `homeSpan.setControlPin(3);` in my code, the button works for factory resetting, but then I can't pair. The serial console says the same in both cases:

> DEVICE NOT YET PAIRED -- PLEASE PAIR WITH HOMEKIT APP

but the LED (in my case a Neopixel) shows a long series of fast blink, when I use `homeSpan.setControlPin(3);` ... and the usual double blink when I have commented out `//homeSpan.setControlPin(3);`, allowing me to pair.

Below is the schematic for the button, in case it could be hardware, but as I mentioned, pressing the button does initiates a factory reset - `BUTTON` goes straight to GPIO3 (physically pin 8) on the ESP32-C3 (specifically an ESP32-C3FH4 w/built flash):
![button_schematic](https://github.com/HomeSpan/HomeSpan/assets/2776277/7c8573f8-f860-4b26-9f3b-c14955de5314)

I have tried all combination of `pinMode(3, OUTPUT or INPUT or INPUT_PULLUP);` prior to `homeSpan.begin()`, to see if that would help, but no luck.

Any suggestions would be appreciated.

**Comment by XDM525** [comment]
I believe it may have to do with your button setup. What I would try is remove the line of code pinMode(3, OUTPUT or INPUT or INPUT_PULLUP); as I'm pretty sure homeSpan.setControlPin(3); sets the control pin as INPUT_PULLUP. Then take pin1 from your switch, remove it from VCC and attach it directly to GPIO3 and remove R12. This is what I'm doing and it works for me.

**Comment by HomeSpan** [comment]
That's correct.  The Control pin should be connected to GROUND via a Pushbutton, not VCC.  And HomeSpan configures the  pin automatically.

**Comment by gotfredsen** [comment]
Thank you all.

Like there is a `setStatusDevice` as an alternative to `setStatusPin`, is there a  `ControlDevice` as an alternative to `setControlPin`, which would help me here?

Also can you use CapTouch as a `ControlPin`? I know with `SpanButton` you can do a `TRIGGER_ON_TOUCH`, but can't see if that is available with `setControlPin`....

**Comment by HomeSpan** [comment]
Sorry, at present the control pin is hardcoded to use a pushbutton connected to ground.

**Comment by gotfredsen** [comment]
Ok

**Comment by stzoran1** [comment]
I think I know how we can enhance setControlPin() method to allow push buttons which are pulled down.

I will make a merge request in next couple of days.
