### ISSUE TITLE
wifiCallback is only called the first time wifi connects

### ISSUE THREAD

**Issue by rubillos** [HomeSpan/HomeSpan#655]
If wifi disconnects and then reconnects, the wifiCallback is not called a second time.

Changing the code at line 425 in HomeSpan.cpp to:
```
  if(connected>1) {                          // Do not initialize everything below if this is only a reconnect
    if(wifiCallback)
      wifiCallback();
    return;
  } 
```
would correct this. (And thanks again for this library! I've used it in over  dozen devices!)

**Comment by HomeSpan** [comment]
I realized that for some applications, calling the callback after every re-connect may not be desired if the callback code is designed to run only once.  To provide for maximum flexibility and backwards compatibility, I added an alternative callback function that can be specified using a new *homeSpan* method `setWifiCallbackAll(void (*func)(int count))`, where *func* is a function of type void that accept a single int argument, *count*.   HomeSpan uses this parameter to pass the cumulative count of WiFi connects/re-connects to the callback function.  Unlike `setWifiCallback()`, in this method *func* is called **every** time there is a connection established or re-established after a disconnect.  By checking the *count* parameter in your callback, you can distinguish the initial connection made at start-up (*count=1*) from a re-established connection (*count=2, count=3*, etc.).

The code for this has been added to the **release-1.8.1-dev** branch.  Please feel free to give it a try and let me know how it works.

**Comment by frankonski** [comment]
I can't find exactly where I saw this last week, but one of the ESP-IDF examples uses the WiFi _connect_ and _disconnect_ callbacks to stop and start the web server respectively. Keep things clean. Why have a web server running if the wifi is down.. ;-)

**Comment by HomeSpan** [comment]
Requested function has been added to dev branch and will be in next production release as per above.
