### ISSUE TITLE
maindevice.ino example: nothing logged

### ISSUE THREAD

**Issue by etotman** [HomeSpan/HomeSpan#660]
There are two LOG1 commands in the main loop() but nothing is logged to the serial monitor.  I added two remotedevice test sensors and updated the MAC addresses to use the main homespan device, and both log that data is sent successfully, but the incrementing temperature values are not sent to homekit.

**Comment by HomeSpan** [comment]
Thanks for the suggestion.  I added the MAC Address to RemoteDevice.ino with a note indicating it should be used in the Main Device SpanPoint call.  Code is updated in release-1.8.1-dev branch.
