### ISSUE TITLE
Device States Ready to Pair but fails to show up on HomeKit

### ISSUE THREAD

**Issue by WPWillemse** [HomeSpan/HomeSpan#661]
I have restarted the esp32 more than 18 times and i have reset all the wifi data. I have no idea how to make the device show up on Homekit even though the serial monitor displays that the device is connected to wifi and it is ready to be paired.

**Comment by frankonski** [comment]
Have you read and done [Pairing to HomeKit](https://github.com/HomeSpan/HomeSpan/blob/master/docs/UserGuide.md#pairing-to-homekit)?
In the Home app, tap on _Add Accessory_ and scan the tag.
Anything happening?
