### ISSUE TITLE
Exemple 16 - Programmable Switch, false long press trigger every sec.

### ISSUE THREAD

**Issue by Mathis201** [HomeSpan/HomeSpan#663]
Single press and double press are unresponsive and the long press action triggers every sec without any physical press on the button.

**Comment by HomeSpan** [comment]
did you configure the button correctly?  Needs to be a normally-open button that connects the pin to ground when pressed

**Comment by Mathis201** [comment]
@HomeSpan it’s the following button and the two bottom pins are wired to the 5V and GND. The upper one is connected to pin 23 on the esp 32.
![IMG_5653](https://github.com/HomeSpan/HomeSpan/assets/148016802/9bb8bd61-224b-4a9d-bc48-36bc877c22fc)



> did you configure the button correctly? Needs to be a normally-open button that connects the pin to ground when pressed

**Comment by Mathis201** [comment]
@HomeSpan am I missing something ?

**Comment by HomeSpan** [comment]
Nothing should be connected to 5V.   You need to use a voltmeter to figure out which pins get connected when you press the button.   My guess is that two of the pins are permanently tied together and two of the other pins are permanently tied together, and when you press the button all 4 pins are tied together. 

Alternatively, to test Example 16, don't use a pushbutton and simply use two wires and touch them together.  Once you confirm that's working you can figure out how to connect the pushbutton.

**Comment by Mathis201** [comment]
@HomeSpan thanks a lot for the help ! I will try without the button to make sure it’s working and then I’ll try figuring out how to properly connect the button !

**Comment by Mathis201** [comment]
It’s working now ! One upper pin has to be connected to the GND and the other upper one to the pin on the esp. 
Works with the two bottom one also.
I am guessing that HomeKit is the one deciding the durations of the press and assigning if it’s a single, double or long press. The long press option is quite long for my liking but if I am correct this can’t be changed.

Anyways thanks for the help, it’s working fine now !

**Comment by HomeSpan** [comment]
All the settings can be changed.  See the docs for how to do so.
