### ISSUE TITLE
Trying to get a boolean based on if the "device" is on or off.

### ISSUE THREAD

**Issue by kennydossantos** [HomeSpan/HomeSpan#665]
### Discussed in https://github.com/HomeSpan/HomeSpan/discussions/664

<div type='discussions-op-text'>

<sup>Originally posted by **kennydossantos** October 16, 2023</sup>
Hi, I can't figure out how to use HomeSpan to create for example a virtual lamp to save the sate of the lamp (false or true) to a variable, so I can later use that boolean in my code. For example opening a door using another function. So I would like HomeSpan to save something and if it is true than open door. I have tried myself (see below), but I can't get it to work. I would appreciate all the help I could get.

`#include "HomeSpan.h"

HomeSpan homeKitAccessory("MyAccessory", "AccessoryType");

bool powerState = false;  
Characteristic::On powerCharacteristic("Power", powerState);

void handlePowerChange(bool newValue) {
    if (newValue) {
        MyFunction();
    }
}

void setup() {
    homeKitAccessory.addCharacteristic(&powerCharacteristic);

    powerCharacteristic.onValueChange(std::bind(handlePowerChange, std::placeholders::_1));

    homeKitAccessory.begin();
}

void loop() {
    homeKitAccessory.loop();
}
`</div>

**Comment by HomeSpan** [comment]
The code above seems like it is related to another library, not HomeSpan.  Please review all the tutorials examples as well as the documentation provided to learn how to create HomeSpan sketches.

**Comment by HomeSpan** [comment]
There is nothing specific I can point you to, but the documentation is quite extensive.  If you work through the tutorials you should be able to code what you are looking to do.
