### ISSUE TITLE
Initial settings after restart or reset not working

### ISSUE THREAD

**Issue by mLihs** [HomeSpan/HomeSpan#667]
HomeKit does not update the value after restart when I use the loop function to set a value.
After I manually change the status in HomeKit, I can change the values again using a loop.

**Comment by HomeSpan** [comment]
HomeSpan can optionally save the state of Characteristics so they are retained after restart -- see the [API](https://github.com/HomeSpan/HomeSpan/blob/master/docs/Reference.md#spancharacteristicvalue-boolean-nvsstore) for details.

**Comment by HomeSpan** [comment]
just checking - has this resolved the issue?
