### ISSUE TITLE
Serial output only visible via the USB connection and not TX/RX pins (ESP32-C3)

### ISSUE THREAD

**Issue by phybros** [HomeSpan/HomeSpan#675]
Hi! First off, I love HomeSpan!!

Second, I'm working on a garage door integration, and noticed that if I connect an external USB->serial adapter (e.g. FTDI, CH340x etc) via the TXD/RXD pins on the ESP32-C3 I only get the bootloader message on startup (but my HomeSpan sketch still works perfectly).

If I connect USB directly to IO18/IO19 (USB-, USB+) then I get the bootloader output, AND all the normal HomeSpan output, logging, plus interactive mode etc.

I'd like for the serial output to come out via both channels if possible - I'm not 100% sure how to configure the module to achieve this. I know that I had to set CDC Enabled Boot to True in the past to get USB output, but maybe that disables the regular UART? As I typed this I realized this is not a HomeSpan-specific question, but maybe HomeSpan is doing something / caching something internally to block regular UART output?

**Comment by HomeSpan** [comment]
I'm unfamiliar with the direct USB modes (the chips I have all include built-in UART) so I'm not quite sure about the interaction between the USB and UART.   HomeSpan itself uses `Serial` for all output, which is usually UART0 on GPIOs 20 and 21, but specific chips can be configured differently.  I'm unaware of anything that would automatically couple multiple UARTs or the UART and native USB output.

**Comment by HomeSpan** [comment]
Forgot to ask - what is the specific chip you are selecting in the interface?

**Comment by phybros** [comment]
It's the ESP32C3 Dev Module. And yeah, Maybe I will have a look into esp-idf and the menuconfig options. Maybe there's something burned into the bootloader here

**Comment by phybros** [comment]
Going to close this since it definitely isn't a HomeSpan thing

**Comment by YouCanNotBeSerious** [comment]
Hey, I can contribute something back finally! I'm usually on the receiving end of help ;-)

The -C2 and -S2 and others have to have CDC USB turned on in the Arduino IDE, and then calls to Serial() will come out of a newly created USB-Serial port.  I am wondering if this is related to [my issue.](https://github.com/HomeSpan/HomeSpan/issues/705)
