### ISSUE TITLE
How to obtain web service sensor value?

### ISSUE THREAD

**Issue by rightedges** [HomeSpan/HomeSpan#678]
I'm trying to obtain a sensor value via a web service call within HomeSpan. Is there any example available? Thanks.

**Comment by HomeSpan** [comment]
There is nothing built into HomeSpan, but if you have code that enables you to make the web service call on an ESP32, you should be able to use it within HomeSpan to periodically obtain the sensor value and feed it back to a HomeKit Accessory.

**Comment by rightedges** [comment]
Thanks for the quick response! Make perfect sense. I'll close this.
