### ISSUE TITLE
Changing valid values for SecuritySystemCurrentState and SecuritySystemTargetState have no effect

### ISSUE THREAD

**Issue by frankonski** [HomeSpan/HomeSpan#682]
Ever since I started using HomeSpan with a SecuritySystem service, I had been initializing two characteristics this way:
```
    partitionCurrentState = new Characteristic::SecuritySystemCurrentState(3);
    partitionTargetState = new Characteristic::SecuritySystemTargetState(3);
```

Life was good, development was good, Home app was showing all 4 states (Home, Away, Night, Off).

Then I wanted to see the app without the Night option (for kicks) and used the following, which is also documented in Reference.md, so I used the following:

```
    partitionCurrentState = new Characteristic::SecuritySystemCurrentState(3);
    partitionCurrentState->setValidValues(3,0,1,3);
    partitionTargetState = new Characteristic::SecuritySystemTargetState(3);
    partitionTargetState->setValidValues(3,0,1,3);
```

After reflashing, the Night option didn't automatically disappeared. It took some unknown time (few hours) before I noticed the Night option was finally gone from the app.

I have modified the `updateDatabase()` method temporarily to **force** an update to no avail:
```
boolean Span::updateDatabase(boolean updateMDNS, boolean force){
...
  if(memcmp(tHash,hapConfig.hashCode,48) || force){  // if hash code of current HAP database does not match stored hash code, or if a forced update is done
...
```

Then I set back my code to not use a range of valid values:
```
    partitionCurrentState = new Characteristic::SecuritySystemCurrentState(3);
    partitionTargetState = new Characteristic::SecuritySystemTargetState(3);
```
.. again, to no avail. The Night option is not coming back.

I even forced it to come back:
```
    partitionCurrentState = new Characteristic::SecuritySystemCurrentState(3);
    partitionCurrentState->setValidValues(4,0,1,2,3);
    partitionTargetState = new Characteristic::SecuritySystemTargetState(3);
    partitionTargetState->setValidValues(4,0,1,2,3);
```
again, to no avail. Or so. 
My alarm system has two partitions, represented by two instances of SecuritySystem service. Only one security system in the Home app, on only one phone (not all phones!) has come back showing the Night option. Still forcing a database update.

No luck. No sure how to proceed forward...

**Comment by HomeSpan** [comment]
I have had the same issues, though I don't think I ever saw my iPhone and iMac out of sync in terms of the same Accessory being represented two different ways.

Whenever you change anything related to HAP (such as adding or deleting a setRange), the config number for the database is automatically updated upon next reboot (the updateDatabase does the same thing but without the need to reboot).  This is supposed to cause HomeKit to update and refresh, but it does not always do so cleanly.  

One thing I found is that force-closing the HomeApp and then re-opening usually works, though not always.  I do know that if you change your configuration by adding/subtracting a Service or Characteristic, HomeKit often gets confused.

When I find HomeKit is in an inconsistent state, sometimes the only way to address is to unpair the Accessory, type 'H' into the Serial Monitor (after unpairing) to force a new Device ID to be generated, and then to re-pair.  It's a pain, usually solves the problem.

**Comment by frankonski** [comment]
> Whenever you change anything related to HAP (such as adding or deleting a setRange), the config number for the database is automatically updated upon next reboot (the updateDatabase does the same thing but without the need to reboot).

That means if I added `setValidValue()`, re-compiled, reflashed causing a reboot, the config number was already incremented. So forcing refresh as I did wasn't necessary, thanks for confirming.

I noticed the return value of `mdns_service_txt_item_set` isn't checked. I added code to verify if it returned ESP_OK with my use case, and it does. Meaning that is not it.

My next test will be to try to replace [ESPmDNS 2.0](https://github.com/espressif/arduino-esp32/tree/master/libraries/ESPmDNS) last updated 2 years ago that seems included with the 2.0.13 esp32 Arduino package with [mDNS Service](https://github.com/espressif/esp-protocols/tree/master/components/mdns) last updated last week.

Hopefully this will automagically solve the issue.

**Comment by HomeSpan** [comment]
My understanding is that Arduino-ESP32 version 3 (still in alpha) uses Espressif IDF version 5, which is a significant refactoring compared to IDF version 4 (upon which Arduino-ESP32 version 2 is built).  In IDF version 5, Espressif decided to unbundle a lot of functions, one of which is the mDNS Service.  I'm not sure if this version of the service, which is designed for IDF 5 will work with IDF 4.

**Comment by frankonski** [comment]
> I have had the same issues, though I don't think I ever saw my iPhone and iMac out of sync in terms of the same Accessory being represented two different ways.

well, a new re-flash where I removed the `setValidValues()` had yet another interesting side effect. Not only is the 2 alarms accessories on Phone1 (iOS 17.1.1) still not show the Night state, but Phone2 (iOS 16.7.2) is showing only 1 alarm accessory without the Night state. There is an alarm accessory completely missing. :(

**Comment by frankonski** [comment]
Both alarm accessories are visible in Eve, but one is missing in Apple Home app. Deleting the Home app and reinstalling it solved the mystery of the missing accessory.
However it is still not showing the Night state which leads me to think that this may be in an issue with the data sent by the controller (one of the two AppleTVs...).

**Comment by frankonski** [comment]
More interesting stuff, taking a step back.
AppleTV 1 (old): 4th gen (A1625) running tvOS 7.1
AppleTV 2 (new): 4K 3rd gen (A2723) running tvOS 7.1

Controlling the alarm accessory (changing the alarm state) shows (via HomeSpan weblogs) an IP address from atv1.

I went to atv1 > Settings > AirPlay and HomeKit > Room > Remove From Home. That AppleTV then disapeared from the Home app of the iPad I was also looking at. Then still from the same atv1 menu, I added it back to a Room. The AppleTV then showed up in the Home app, with a status of _Not playing_ instead of _Paused_.

I changed the alarm state and now the IP address showed the update came from atv2. 
Both alarm accessories showed up on the phone where only one showing, and the _Night_ state came back.

So atv2 took over to be the main controller (I think..).

Not sure where to go from here..

**Comment by frankonski** [comment]
@HomeSpan , feel free to close if you think this is not worth looking into this further. What I ended up realizing in the last 3 weeks is that if you go to Home > Home Settings > Home Hubs and bridges, I can see my two AppleTV. One shows Connected, one shows Standby. Tonight, the old ATV shows connected because it is turned on to watch some stuff, while the newer ATV is turned off in another room and shows "Standby".

No way to tell Home "Just always use this one"... I haven't had a chance to log the details of each connected Hub/ATV yet.

**Comment by HomeSpan** [comment]
Thanks - I close this for now and we can re-open in future as needed.
