### ISSUE TITLE
FATAL ERROR: HomeSpan\src\HAP.cpp:29:10: fatal error: sodium.h: No such file or directory

### ISSUE THREAD

**Issue by Elmrz** [HomeSpan/HomeSpan#687]
I created a sketch and uploaded it! Everything worked fine! The next time I tried to upload a sketch, I got the following error: 
```
HomeSpan\src\HAP.cpp:29:10: fatal error: sodium.h: No such file or directory
   29 | #include <sodium.h>
      |          ^~~~~~~~~~
```
To create and download I use Arduino IDE 2.2.1, ESP32-C3 board
MY SKETCH:
```
#include <HomeSpan.h>
#include "Garage1.h"

void setup() {
  Serial.begin(115200);
  homeSpan.setPairingCode("11122333");
  homeSpan.begin(Category::GarageDoorOpeners,"GarageDoors");
  
  new SpanAccessory();
    new Service::AccessoryInformation();
      new Characteristic::Identify();
    new BUTT_G1(12);
}

void loop() {
  homeSpan.poll();
}

```
Garage1.h

```
struct BUTT_G1 : Service::Switch {

  int pinG1;
  SpanCharacteristic *power;

  BUTT_G1(int pinG1) : Service::Switch() {

    power = new Characteristic::On();
    this->pinG1 = pinG1;
    pinMode(pinG1, OUTPUT);
  }

  boolean update() {
    
    digitalWrite(pinG1, power->getNewVal());
    delay(800);
    digitalWrite(pinG1, false);
    power->setVal(false);
    return(true);
  }
};

```

**Comment by HomeSpan** [comment]
It seems that the Arduino-ESP32 library itself may be corrupted.   Are you using the Arudino IDE?  If so, recommend you delete the board manager and follow the instructions on the Arduino-ESP32 GitHub site to re-install the latest production version of the Arduino-ESP32 library (2.0.14) .  Sodium.h is part of that library.

**Comment by Elmrz** [comment]
> It seems that the Arduino-ESP32 library itself may be corrupted. Are you using the Arudino IDE? If so, recommend you delete the board manager and follow the instructions on the Arduino-ESP32 GitHub site to re-install the latest production version of the Arduino-ESP32 library (2.0.14) . Sodium.h is part of that library.

I reinstalled the board library and nothing changed! Only I have the latest version 2.0.13

![Sodium](https://github.com/HomeSpan/HomeSpan/assets/142754806/b566d02e-1803-4851-b9a8-464c2ee0e302)

**Comment by Elmrz** [comment]
Everything worked out after reinstalling the Espressif ESP32 board library! Thank you
