### ISSUE TITLE
HID implementation?

### ISSUE THREAD

**Issue by societyofrobots** [HomeSpan/HomeSpan#69]
Looking to build a BLE based game controller.

I didn't see any examples for HID, just wanted to verify this is implemented.

**Comment by HomeSpan** [comment]
This is a HAP library designed to integrate physical appliances with Apple HomeKit for use in the Home App on an iPhone, iPad, or Mac.   I don't think there is anything in HAP that would be relevant to game controllers.  Also, it's WiFi only (no BLE).
