### ISSUE TITLE
Unable to add accessory with SimpleLightBulb example

### ISSUE THREAD

**Issue by matepetrak** [HomeSpan/HomeSpan#698]
I am testing HomeSpan with the SimpleLightBulb example on ESP32-C3-DevKitM.
My Home app sees the light bult but when I connect with the default code I get the error: "Unable to add accessory".

Log:
Generating new random Accessory ID and Long-Term Ed25519 Signature Keys...
Initializing storage for Paired Controllers data...

Accessory ID:      2D:1E:BA:04:9D:98                               LTPK: AB55C42C36A7F3FCE45DEAFAD7E4D2618DD9544CD0CCDE5C23A1E3EB45F1AB43
No Paired Controllers
Resetting Database Hash...

Content-Type: application/pairing+tlv8
------------ END BODY! ------------
STATE(1) 01
METHOD(1) 00
------------ END TLVS! ------------
In Pair Setup...Found <M1>.  Expected <M1>

>>>>>>>>>> 192.168.1.65 >>>>>>>>>>
HTTP/1.1 200 OK
Content-Type: application/pairing+tlv8
Content-Length: 409

STATE(1) 02
PUBKEY(384) AB890B75C3F2E914491F3F3DE0B514C1F36FD7F76FAF9DC303BC67B8D32C02C069AAFC0140E02CFDB54C920B46A3CFD748EE23706957D4C71D6384BC4B4EDF3694B0A222562ED5F36AE0EF561D7EC3A51621AA42B7527BA5AD175EF0D94224191647AC1AF33C7C5E27DC98242EEE345CAFE5568A12FC34722DB1E727F66C090B217CE272DB552B763B9442E0CEC5316C6945C671102B70050FA6E9FD8C33F42A4237E63E94E16E32767E6C4CC5592659CE257461311B5D9A51AB642F681E5A182F01F5E1FB11B872ECDB6C003144E05ED456F7FB1B66E0E0BC5B418F2C4D77BA3604FD6BCCB3CF451A3D6D212882BD66487D1A5F81395871CED7D33C0B4FB11BE3E5BFA1716DBD32BC166EFBCAA2C5C56D1F14632CB36010BB51898ABCEE10F496432F6CDD8F62E9D94B5E5D69909CAFAAD56EF9041BB798C3C7749EE14EF9C61ED4D8668B2C49090E94D473B9DEC4E5443685E2CF9E414AC1D99E0FAFCF94853C5C1DDE801D46E31941B86A8867F9B26D852D4B0DF8B932FBB893F56A48A41F
SALT(16) 2DDC723347FDFF9A9C5B9362E023196D
------------ SENT! --------------

**Comment by HomeSpan** [comment]
Are you sure you entered the correct code?  Also, can you confirm you are running an absolutely unmodified version of Example 1 with nothing connected to the device except for the serial cable?   Note you can reset the device by typing 'H' into the serial monitor, which clears out all the pairing info.

Also, what version of the HomeSpan software and Arduino-ESP32 library are you using?  What version of iOS?

**Comment by matepetrak** [comment]
I am copy pasting the example code. I used 466-37-726 to connect (wo dashes)

**Comment by HomeSpan** [comment]
Note you should not need to copy/paste anything.  The examples are in the library (assuming you are using Arduino IDE).

**Comment by matepetrak** [comment]
Tested with the example feature in Arduino IDE too, still not working.

**Comment by HomeSpan** [comment]
@matepetrak, anything to update - have you got this working?
