### ISSUE TITLE
How many web log rows is too many?

### ISSUE THREAD

**Issue by YouCanNotBeSerious** [HomeSpan/HomeSpan#699]
I have a simple question - what would a sensible upper limit be for the web log table? 

Context - I see issues like [this one](https://github.com/HomeSpan/HomeSpan/issues/684) and realise how very new I am to all of the aspects of embedded programming :-). I am trying to learn about the various concepts in more detail - stack, heap etc and getting there slowly...  but for a test accessory I am putting together with HomeSpan, is there any reason not to specify say 100 rows?  1000?

I appreciate the answer for a project with 50 bulb accessories vs one with 1 will be different, just looking for a rough guidance, and what might happen or be observed if I exceeded a sensible number.

**Comment by HomeSpan** [comment]
You are only limited by the memory of the ESP32.  There are some inefficiencies in the the current production branch that cause memory to fill up after about 300 web log entries (of course it depends on the size of each entry) but this has been addressed in the latest development branch and I've successfully run with 500 entries.
