### ISSUE TITLE
Statical code check with cppcheck (PlatformIO)

### ISSUE THREAD

**Issue by tueddy** [HomeSpan/HomeSpan#702]
Hi,

i used cppcheck in PlatformIO and got besides some warnings  these high:errors:

```
.pio\libdeps\lolin_d32_pro\HomeSpan\src\HomeSpan.h:507: [high:error] Null pointer dereference: val [ctunullpointer]
pio\libdeps\lolin_d32_pro\FastLED\src\FastLED.h:268: [high:error] Found an exit path from function with non-void return type that has missing return statement [missingReturn]
.pio\libdeps\lolin_d32_pro\FastLED\src\FastLED.h:283: [high:error] Found an exit path from function with non-void return type that has missing return statement [missingReturn]
.pio\libdeps\lolin_d32_pro\FastLED\src\FastLED.h:298: [high:error] Found an exit path from function with non-void return type that has missing return statement [missingReturn]
.pio\libdeps\lolin_d32_pro\FastLED\src\pixelset.h:193: [high:error] Found an exit path from function with non-void return type that has missing return statement [missingReturn]
```

![grafik](https://github.com/HomeSpan/HomeSpan/assets/11274319/6dae7fcc-df97-4eb6-ba37-6d1158f8aae0)

Checked against current master. Hope this helps to get this fantastic library even better & more stable ;-)

**Comment by HomeSpan** [comment]
Thanks!  I checked line 7 of HomeSpan.h but did not see any issues (the pointer should never be null).  The other lines referencing FatLED.h and pixelset.h are not part of HomeSpan - perhaps something in your local build/sketch?

**Comment by tueddy** [comment]
OK, statical code check can give false-positives. 
I will check again with your current dev branch..
