### ISSUE TITLE
Intermittent State Update Issues with Multiple Accessories in HomeSpan

### ISSUE THREAD

**Issue by stzoran1** [HomeSpan/HomeSpan#703]
**HomeKit Configuration:** Multiple accessories (2 Garage Openers, 3 Lights) on a single ESP32
**Issue Description**
I am experiencing an issue where one of my HomeSpan accessories ("Magacin", a Garage Door Opener) does not correctly update its state in the Home app. This occurs despite the accessory's physical state changing as expected.

**Steps to Reproduce**
Initialize two Garage Door Openers ("Kapija" and "Magacin") and three Lights in setup() using HomeSpan.
Both Garage Door Openers are configured identically.
On triggering the Garage Door Openers, "Kapija" updates its state correctly in the Home app (both icon status and actual physical state).
"Magacin" changes its physical state correctly (the relay operates as expected), but the icon status in the Home app does not update to reflect the current state.
**Troubleshooting Steps Undertaken**
Swapped the initialization order of "Kapija" and "Magacin" with no change in behavior.
Checked for Wi-Fi stability and signal strength.
Ensured that there are no pin conflicts and that the ESP32 firmware and HomeSpan library are up to date.

**Expected Behavior**
All accessories should update their state in the Home app consistent with their physical state changes.

```
#include <Arduino.h>
#include <HomeSpan.h>
#include <My_Door_Opener.h>
#include <My_Light.h>

void setup()
{
  Serial.begin(115200);

  homeSpan.setStatusPin(18);
  // Added manualy this method in HomeSpan.h in order to support push buttons connected to Vcc
  //  void setControlPinHigh(uint8_t pin) { controlButton = new PushButton(pin, PushButton::TRIGGER_ON_HIGH); } // sets Control Pin for pulled down push buttons
  homeSpan.setControlPinHigh(34); // SW3

  homeSpan.setPairingCode("11223344");

  homeSpan.enableOTA(false);

  homeSpan.enableAutoStartAP();

  homeSpan.begin(Category::GarageDoorOpeners, "HomeSpan Bridge Ugrinovci");

  new SpanAccessory();
  new Service::AccessoryInformation();
  new Characteristic::Identify();
  new Characteristic::SerialNumber("BRIDGE123");

  // It is important not to use BRIDGE category for the first accessory
  // BRIDGE is causing weird behavior with the second accessory preventing automatic state updates

  // RELAY 1 on pin 4
  new SpanAccessory();
  new Service::AccessoryInformation();
  new Characteristic::Identify();
  new Characteristic::Name("Kapija");
  new Characteristic::SerialNumber("OPENER123");
  new My_Door_Opener(4, 2); // pin, and period in seconds

  // RELAY 2 on pin 16
  new SpanAccessory();
  new Service::AccessoryInformation();
  new Characteristic::Identify();
  new Characteristic::Name("Magacin");
  new Characteristic::SerialNumber("OPENER456");
  new My_Door_Opener(16, 6); // pin, and period in seconds

  // RELAY 3 on pin 17 unused

  // RELAY 4 on pin 25 Light
  new SpanAccessory();
  new Service::AccessoryInformation();
  new Characteristic::Identify();
  new Characteristic::Name("Svetlo Zid 1");
  new Characteristic::SerialNumber("LIGHT123");
  new My_Light(25);

  // RELAY 5 on pin 27 Light
  new SpanAccessory();
  new Service::AccessoryInformation();
  new Characteristic::Identify();
  new Characteristic::Name("Svetlo Zid 2");
  new Characteristic::SerialNumber("LIGHT234");
  new My_Light(27);

  // RELAY 6 on pin 26 Light
  new SpanAccessory();
  new Service::AccessoryInformation();
  new Characteristic::Identify();
  new Characteristic::Name("Svetlo Zid 3");
  new Characteristic::SerialNumber("LIGHT345");
  new My_Light(26);
}

void loop()
{
  homeSpan.poll();
}

```

```
struct My_Door_Opener : Service::GarageDoorOpener
{ // LED Blinker

    int relayPin; // pin number defined for this LED
    int timeInMiliSeconds;
    unsigned long lastTime = 0;
    boolean stateChanged = false;

    SpanCharacteristic *currentState;        // reference to the CurrentDoorState Characteristic
    SpanCharacteristic *targetState;         // reference to the TargetDoorState Characteristic
    SpanCharacteristic *obstructionDetected; // reference to the ObstructionDetected Characteristic

    My_Door_Opener(int relayPin, int timeInSeconds) : Service::GarageDoorOpener()
    { // constructor() method

        currentState = new Characteristic::CurrentDoorState(1);
        targetState = new Characteristic::TargetDoorState(1); // default to closed
        obstructionDetected = new Characteristic::ObstructionDetected(false);

        this->relayPin = relayPin;
        this->timeInMiliSeconds = timeInSeconds * 1000;
        pinMode(relayPin, OUTPUT);
        digitalWrite(relayPin, HIGH); // turn pin off

        Serial.print("Configuring Door Opener: Pin="); // initialization message
        Serial.println(relayPin);

    } // end constructor

    boolean update()
    { // update() method

        Serial.print("Updating Door Opener: Pin="); // initialization message
        Serial.println(relayPin);

        lastTime = millis();
        stateChanged = true;

        if (targetState->getNewVal() == 0)
        { // check to ensure HomeKit is requesting we "turn on" this device (else ignore)

            Serial.print("Opening the Door on pin=");
            Serial.println(relayPin);

            digitalWrite(relayPin, LOW); // turn pin on

            currentState->setVal(2); // opening
        }
        else
        {
            Serial.print("Closing the Door on pin=");
            Serial.println(relayPin);

            digitalWrite(relayPin, HIGH); // turn pin off

            currentState->setVal(3); // closing
        }

        return (true); // return true

    } // update

    void loop()
    {
        if (!targetState->getVal() && targetState->timeVal() > this->timeInMiliSeconds)
        {
            Serial.println("Resetting Door Control\n"); // log message

            digitalWrite(relayPin, HIGH); // turn pin off

            targetState->setVal(1); // closed

            currentState->setVal(3); // closing

            lastTime = millis();
            stateChanged = true;
        }

        if (stateChanged == true && millis() - lastTime > 1000)
        {
            Serial.print("Setting State to:");
            Serial.println(targetState->getVal());

            stateChanged = false;
            currentState->setVal(targetState->getVal());
        }

    } // loop
};

```

```
struct My_Light : Service::LightBulb
{ // ON/OFF LED

    int ledPin;                // pin number defined for this LED
    SpanCharacteristic *power; // reference to the On Characteristic

    My_Light(int ledPin) : Service::LightBulb()
    { // constructor() method

        power = new Characteristic::On();
        this->ledPin = ledPin;
        pinMode(ledPin, OUTPUT);

        digitalWrite(ledPin, HIGH); // turn pin off

    } // end constructor

    boolean update()
    { // update() method

        digitalWrite(ledPin, !power->getNewVal());

        return (true); // return true

    } // update
};

```

**Comment by HomeSpan** [comment]
Are you using a Home Hub?  Also, before detailed debugging, try unpairing the device, resetting the device ID by typing 'H' into the Serial Monitor, and re-pairing.  If during development you change some of the details of the Accessories, or even the order in which the Accessories are defined in the sketch, this can cause the Home App to be confused.

**Comment by stzoran1** [comment]
I did several tests:

1. Inside existing home, having Home Hub  (Apple HomePod Mini). Tried factory reset, tried option H to unbind device, tried renaming accessories, tried changing order. Nothing helped.
2. Then I created new home, just for testing purposes, without any Home Hubs and behavior is the same.

I also tried changing:

```
homeSpan.begin(Category::GarageDoorOpeners, "HomeSpan Bridge Ugrinovci");
```

to 

```
homeSpan.begin(Category::Bridges, "HomeSpan Bridge Ugrinovci");
```

but no luck. Behavior is the same. If I close the HomeApp and reopen it, statuses are updated as expected. So I guess it is something related to live broadcasting status change.

**Comment by stzoran1** [comment]
Any suggestions for this maybe? I am trying to figure it out myself but still no luck.

**Comment by frankonski** [comment]
Hi @stzoran1, in `My_Door_Opener`, change your logic in the `update()` method.

Think of the `update()` method as being the method called when you tap a new accessory state in the Home app, and the `loop()` method to get _what is the current state_.

Only set your garage door's `targetState` in the `update()` method, as when you tap Open in the app, your garage door don't automatically gets opened. The **target state** should be "opened", which will translate in the Home app as displaying an "Opening" status.

Then in your `loop()` method, only when you know for sure that the opening of the garage door is complete should you call `setVal(OPEN)` .. something like that. Then the Home app will go from "Opening" to "Open".

**Comment by stzoran1** [comment]
@frankonski thank you for suggestion, I tried it but no success. It seems something else is causing described issue.

**Comment by HomeSpan** [comment]
Have you tried changing the delay parameters?  That seems to be the only difference between the two doors. 

Also, you should not be setting targetState in the sketch.  It's set by the Home App.  The only reason you would set in a sketch is if you had a separate physical button connected to the esp32 to open and close the door and needed to let the Home App know the button requested the door to be opened or closed.

**Comment by stzoran1** [comment]
I tried changing delay parameter, that was, btw, first thing I tried, but no difference. The most confusing things is that first DoorOpener works perfectly, and second is having this glitch. 

I will try without changing target state to see how it will behave.

**Comment by stzoran1** [comment]
```
struct My_Door_Opener : Service::GarageDoorOpener
{ // LED Blinker

    int relayPin; // pin number defined for this LED
    int timeInMiliSeconds;
    unsigned long lastTime = 0;
    boolean stateChanged = false;
    boolean isOpening = false;

    SpanCharacteristic *currentState;        // reference to the CurrentDoorState Characteristic
    SpanCharacteristic *targetState;         // reference to the TargetDoorState Characteristic
    SpanCharacteristic *obstructionDetected; // reference to the ObstructionDetected Characteristic

    My_Door_Opener(int relayPin, int timeInSeconds) : Service::GarageDoorOpener()
    { // constructor() method

        currentState = new Characteristic::CurrentDoorState(1);
        targetState = new Characteristic::TargetDoorState(1); // default to closed
        obstructionDetected = new Characteristic::ObstructionDetected(false);

        this->relayPin = relayPin;
        this->timeInMiliSeconds = timeInSeconds * 1000;
        pinMode(relayPin, OUTPUT);
        digitalWrite(relayPin, HIGH); // turn pin off

        Serial.print("Configuring Door Opener: Pin="); // initialization message
        Serial.println(relayPin);

    } // end constructor

    boolean update()
    { // update() method

        Serial.print("Updating Door Opener: Pin="); // initialization message
        Serial.println(relayPin);

        lastTime = millis();
        stateChanged = true;

        if (targetState->getNewVal() == 0)
        { // check to ensure HomeKit is requesting we "turn on" this device (else ignore)

            Serial.print("Opening the Door on pin=");
            Serial.println(relayPin);

            digitalWrite(relayPin, LOW); // turn pin on

            currentState->setVal(2); // opening

            isOpening = true;
        }
        else
        {
            Serial.print("Closing the Door on pin=");
            Serial.println(relayPin);

            digitalWrite(relayPin, HIGH); // turn pin off

            currentState->setVal(3); // closing
        }

        return (true); // return true

    } // update

    void loop()
    {
        if (isOpening && targetState->timeVal() > this->timeInMiliSeconds)
        {
            Serial.println("Resetting Door Control\n"); // log message

            digitalWrite(relayPin, HIGH); // turn pin off

            //targetState->setVal(1); // closed

            currentState->setVal(3); // closing

            lastTime = millis();
            stateChanged = true;

            isOpening = false;
        }

        if (stateChanged == true && millis() - lastTime > 1000)
        {

            if(currentState->getVal() == 2) {
                Serial.print("Setting State to:");
                Serial.println("0");
                currentState->setVal(0);
            } else if(currentState->getVal() == 3) {
                Serial.print("Setting State to:");
                Serial.println("1");
                currentState->setVal(1);
            }  else {
                Serial.println("Unknown");
            }

            stateChanged = false;
            
        }

    } // loop
};

```

Tried this version of code, without setting targetState in loop but it is even worse. Toggle button in HomeApp is now not updating at all.

**Comment by stzoran1** [comment]
https://share.icloud.com/photos/098YeCyk9zv_BVegx6XcL5rDg


Please try watching this video. I recorded behaviour on my iPhone

**Comment by frankonski** [comment]
Back to your `setup()` code, not sure if this is related, but don't you have to create the Name and SerialNumber characteristics **first** before calling `Characteristic::Identify()`?

**Comment by stzoran1** [comment]
@frankonski just tried 

```
// RELAY 1 on pin 4
  new SpanAccessory();
  new Service::AccessoryInformation();
  new Characteristic::Name("Kapija");
  new Characteristic::SerialNumber("OPENER123");
  new Characteristic::Identify();
  new My_Door_Opener(4, 2); // pin, and period in seconds

  // RELAY 2 on pin 16
  new SpanAccessory();
  new Service::AccessoryInformation();
  new Characteristic::Name("Magacin");
  new Characteristic::SerialNumber("OPENER456");
  new Characteristic::Identify();
  new My_Door_Opener(16, 6); // pin, and period in seconds

```

but no difference

**Comment by frankonski** [comment]
So you know, an iPad may serve as a Hub. Double-check if you have more than one Hub. go to Home > Home Settings > Home Hubs and Bridges. Check which one shows "Connected" vs "Standby".

**Comment by stzoran1** [comment]
@frankonski I am using HomePods as hubs. I tried 3 cases:
1. Home without hubs
2. Home with just one hub
3. Home with multiple tabs

No difference, behavior is the same.

**Comment by HomeSpan** [comment]
@stzoran1, anything to update on this one?  Should I keep issue open?

**Comment by stzoran1** [comment]
@HomeSpan no updates. Behavior is still same. I failed to find a solution so far.

**Comment by frankonski** [comment]
How does your current code looks like? so to start from fresh.

**Comment by stzoran1** [comment]
@frankonski I tried from start but it didn't help. It seem problem is somewhere deep inside the protocol of communication. When I split those 2 relays into 2 devices, all is working fine. When both openers (relays) are on same device (same bridge) then problem occurs.

**Comment by stzoran1** [comment]
I have no idea what to test and change. @frankonski if you want I can post whole project here so you can test on your own. Maybe you get some idea what we can try.

**Comment by frankonski** [comment]
zipped. If you don’t mind, I can take a look.

**Comment by stzoran1** [comment]
@frankonski here you go. Wish you luck. If you get any idea please share and I will jump in and help.

[homekit-native-esp32-kalem-ugrinovci.zip](https://github.com/HomeSpan/HomeSpan/files/13931424/homekit-native-esp32-kalem-ugrinovci.zip)

**Comment by HomeSpan** [comment]
As a side test, I verified that two garage doors operating on the same device configured as a bridge (using category=GarageDoorOpeners) works fine using the code from Example 13 - Target States.

**Comment by stzoran1** [comment]
Thank you all for your help and instructions. I tried all suggested and no luck. I will put this on hold until I get some more time I can invest in this issue.
