### ISSUE TITLE
Where to apply homeSpan.processSerialCommand?

### ISSUE THREAD

**Issue by HSkul** [HomeSpan/HomeSpan#716]
I wanted to temporarily upload a sketch using OTA where I erased the Homekit pairing information (ESP32 thought it was paired but Home disagreed) by including 
`homeSpan.processSerialCommand("U");`
and then once it had been erased, upload a new sketch with it removed.  But once it ran the sketch and erased the pairing information, it looks like it went into an infinite reboot loop, requiring me to physically connect it to the computer and update the code.  It is strange as it seems like this should work.  
  So my question is, does the homeSpan.processSerialCommand("U") need to come before or after homeSpan.begin or should it not matter?  I ran it just before (I couldn't find any information on where to put  .processSerialCommand but I may have missed it).
  Thanks, HS

BTW, here is the log after I connected it to the computer.  Starting the MAX boards is my sketch before setting up homeSpan.

_10:30:09.128 -> ets Jun  8 2016 00:22:57
10:30:09.128 -> 
10:30:09.128 -> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
10:30:09.128 -> configsip: 0, SPIWP:0xee
10:30:09.128 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
10:30:09.128 -> mode:DIO, clock div:1
10:30:09.128 -> load:0x3fff0030,len:1344
10:30:09.128 -> load:0x40078000,len:13964
10:30:09.128 -> load:0x40080400,len:3600
10:30:09.128 -> entry 0x400805f0
10:30:09.901 -> Starting MAX board: 0
10:30:09.901 -> Starting MAX board: 1
10:30:09.901 -> 
10:30:09.901 -> *** HomeSpan Pairing Data DELETED ***
10:30:09.901 -> 
10:30:09.901 -> Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
10:30:09.901 -> 
10:30:09.901 -> Core  1 register dump:
10:30:09.901 -> PC      : 0x400db5e9  PS      : 0x00060a30  A0      : 0x800d3f8c  A1      : 0x3ffb1fc0  
10:30:09.901 -> A2      : 0x3ffc7550  A3      : 0x00000000  A4      : 0x00000000  A5      : 0x3ffc77dc  
10:30:09.934 -> A6      : 0x00000000  A7      : 0x3ffc7550  A8      : 0x800db5d6  A9      : 0x3ffb1fa0  
10:30:09.934 -> A10     : 0x00000028  A11     : 0x3f404747  A12     : 0x3ffc4fe8  A13     : 0x00000460  
10:30:09.934 -> A14     : 0x00000028  A15     : 0x00000000  SAR     : 0x0000001b  EXCCAUSE: 0x0000001c  
10:30:09.934 -> EXCVADDR: 0x00000000  LBEG    : 0x4008ad29  LEND    : 0x4008ad39  LCOUNT  : 0xfffffff5  
10:30:09.934 -> 
10:30:09.934 -> 
10:30:09.968 -> Backtrace: 0x400db5e6:0x3ffb1fc0 0x400d3f89:0x3ffb2260 0x400e5902:0x3ffb2290
10:30:09.968 -> 
10:30:09.968 -> 
10:30:09.968 -> 
10:30:09.968 -> 
10:30:09.968 -> ELF file SHA256: 070b06dcef27a03d
10:30:09.968 -> 
10:30:10.134 -> Rebooting..._

**Comment by HomeSpan** [comment]
It should come after homeSpan.begin(), otherwise it will try to erase pairing data before initialization.  Note you should not need to unpair the device this way - it will automatically unpair if you unpair from the Home App, unless you use the Home App to unpair when the device is out of range.

**Comment by HSkul** [comment]
Got it.  Thank you!  Yes, I can't remember how it happened.  I'm having some issues with my setup which may have to do with insufficient power.  Being able to upload a new sketch over OTA and give serial commands like this is super helpful.

  Thanks!!
