### ISSUE TITLE
SOC_TOUCH_VERSIONs actually working the other way around

### ISSUE THREAD

**Issue by dhyananbho** [HomeSpan/HomeSpan#720]
Thank you for your excellent library. The docs are the best I've ever read on Github - congratulations.

The touch pins on ESP32 and ESP32-Sx work in different directions, as you described in tutorial 15_RealPushButtons. I think it's actually the other way around.

I have an old WEMOS Loline 32 board that I bought a few years ago when the -S2 and -S3 boards were not yet available. The HomeSpan software recognizes this board as being SOC_TOUCH_VERSION_1 set, which is correct and means that the touch level should decrease when the button is touched (as you described). But my board behaves the other way around: with the Example ESP32 > Touch > TouchRead script, I have a stable baseline at 16 to 17 and when I touch, the value increases to 150 to 250.

When I run the 15_RealPushButtons script, all three buttons are permanently touched and changing the threshold doesn't help either. This is logical because the board works in the opposite direction.

Thanks for checking and correcting.

**Comment by HomeSpan** [comment]
I can't reproduce this.  If I run the ESP32 example TouchRead script using an ESP32 chip and chose "WEMOS LOLIN32" in the Arduino interface, the Serial monitor reports a baseline of about 70, and it *decreases* to less than 35 when touched.  My sensor is nothing but a jumper wire connected to pin 14.  I don't have an actual WEMOS device, but all ESP32 chips should operate the same way (as well as all ESP32-S2 operating in the opposite direction).

What pin are you using?  Also, are you using a separate touch sensor, or just a plain wire?

**Comment by HomeSpan** [comment]
Also, the logic for this part of the code has been in place for quite some time and tested on ESP32, ESP32-S2, and ESP32-S3, so it seems that if there is issue it is somehow specific to the WEMOS?

**Comment by dhyananbho** [comment]
Thank you for your quick reply.

First I used the T0 (pin 4), T2 (pin2) and T3 (pin 15) with simple wires in the tutorial script 15_RealPushButtons and it didn't work.
Then I checked the touch values with the TouchRead script (see below) and the serial plotter. I found that the touch values moved in a wide range and it was not possible to find a reliable threshold.
To make the touch buttons more reliable, I took a thin steel sheet as a base plate, which I connected to GND, stuck a double-sided tape as insulation over the entire surface and glued 4 small steel sheets on top, which were connected to the pins as touch buttons (see fotos). This arrangement gave me a stable baseline of 16 to 17 and a touch value of well over 100 (see screenshot).
Then I went back to the tutorial script 15_RealPushButtons and it still didn't work. It set the threshold to 8 and waited for a falling value below 8 as a trigger. In HomeSpan/src/Utils.h and ../Utils.cpp I changed the > and < at two places and the *=2 and /=2 at one place and it worked fine.

Maybe it's something WEMOS specific. I'll check tomorrow with a different board and different touch pins.

—————

// ESP32 Touch Test
// Just test touch pin - Touch0 is T0 which is on GPIO 4.

void setup()
{
  Serial.begin(115200);
  delay(1000); // give me time to bring up serial monitor
  Serial.println("ESP32 Touch Test");
}

void loop()
{
  Serial.print(touchRead(T0));  // T0 is pin 4
  Serial.print(" ");
  Serial.print(touchRead(T2));  // T2 is pin 2
  Serial.print(" ");
  Serial.print(touchRead(T3));  // T3 is pin 15
  Serial.println(" ");
  delay(500);
}
![IMG_2869](https://github.com/HomeSpan/HomeSpan/assets/41578064/0765e27c-4544-4c7d-838c-f734e5700546)
![IMG_2871](https://github.com/HomeSpan/HomeSpan/assets/41578064/28631a65-fc58-4e2d-a462-55ba02ddaa1e)
![IMG_2868](https://github.com/HomeSpan/HomeSpan/assets/41578064/300a3c38-3346-4268-a5bc-8308aa81bcff)

![Bildschirmfoto 2023-12-22 um 01 12 14](https://github.com/HomeSpan/HomeSpan/assets/41578064/d3e3ee49-3bea-4f6d-afbb-7c8c584a1bc4)

**Comment by HomeSpan** [comment]
Maybe your sensor configuration led to a reverse polarity of the signal?

**Comment by dhyananbho** [comment]
No, I had the same direction with only wires, but with a lot of noise.

**Comment by dhyananbho** [comment]
Now I have tried the above TouchRead script with two other boards:
1. TTGO LoRa32-OLED board, which is also quite old
2. AI Thinker ESP32-CAM board, which I bought recently and which has an ESP32-S
All three boards show the same behavior - the touch value increases when touched.

**Comment by HomeSpan** [comment]
I can't explain this.

If you have an ESP32, touching a bare wire yields a lower number when using the touchRead example.   Using an Adafruit ESP32 Featherboard, I get the same results as in this [tutorial](https://randomnerdtutorials.com/esp32-touch-pins-arduino-ide/).

Also, you can see from the Espressif examples that for the [ESP32](https://github.com/espressif/esp-idf/tree/v4.4.6/examples/peripherals/touch_sensor/touch_sensor_v1/touch_pad_read) touching the pin yields a lower value, where touching the pin for the [ESP32-S2 and -S3](https://github.com/espressif/esp-idf/tree/v4.4.6/examples/peripherals/touch_sensor/touch_sensor_v2/touch_pad_read) yield higher values.

I'm wondering if this is an ESP32-S issue (the Arduino IDE uses esp32, but for the purpose of the touch sensor it is version 2, not version 1)?

**Comment by HomeSpan** [comment]
Note that regardless of the cause, you can address this directly in your sketch without modifying any of the HomeSpan code.  Simply create your own triggerType function for SpanButton as described in Example 15 and flip the '<' to a '>'.
