### ISSUE TITLE
esp_sntp.h: No such file or directory

### ISSUE THREAD

**Issue by hrubiak** [HomeSpan/HomeSpan#724]
Sorry I'm new at Arduino, I'm getting an error compiling the 01-SimpleLightBulb
I'm using an ESP32 WROOM 32 board in Arduino IDE 1.8.19 on MacOS
Does anyone recognize this error?

Multiple libraries were found for "WiFi.h"
/Users/ross/Documents/Arduino/libraries/HomeSpan/src/HomeSpan.cpp:36:22: fatal error: esp_sntp.h: No such file or directory
 Used: /Users/ross/Library/Arduino15/packages/esp32/hardware/esp32/1.0.4/libraries/WiFi
compilation terminated.
 Not used: /Applications/Arduino.app/Contents/Java/libraries/WiFi
exit status 1
Error compiling for board ESP32 Dev Module.

**Comment by HomeSpan** [comment]
You need to update your ESP32 library. The latest version is 2.0.14.

**Comment by hrubiak** [comment]
That worked, thank you!
