### ISSUE TITLE
ULN2003 stepper motor driver and 28BYJ-48 with HomeSpan

### ISSUE THREAD

**Issue by D0NEDAN** [HomeSpan/HomeSpan#731]
Hi, I wanted to ask how to combine this great library with code for operating stepper motor 28BYJ-48 with ULN2003 driver. Ive seen the stepper category in the files but the drivers are different and I know very little about Arduino programming. I would like to control my window blinds with the ESP32 and HomeKit connected using HomeSpan. Currently Ive managed to write a simple code for 3 buttons but I would like to get rid of them and control it with the HomeKit. Please help, Its also my semester project. Thank you
[EKP-project_SmartBlinds.ino.zip](https://github.com/HomeSpan/HomeSpan/files/13834125/EKP-project_SmartBlinds.ino.zip)

**Comment by D0NEDAN** [comment]
I just don't know how to use the code I already written into the form HomeSpan uses. The examples are for different motor drivers with different stepper libraries so I don't know how that works. What would be truly amazing is to have full control over the blinds I just don't know how to write the code for it, as I mentioned earlier I have very little experience with this kind of programming. Thanks to anyone who gives me some information or help.

**Comment by D0NEDAN** [comment]
This is as much as I could get out of ChatGPT
[smartBlinds02.zip](https://github.com/HomeSpan/HomeSpan/files/13853690/smartBlinds02.zip)

**Comment by aldospanjaard** [comment]
Hey DONEDAN, thanks for your work. I tried this on my esp32; but while i see the lights of the driver bord change when i input a homekit command, it doesnt turn the motor. The motor and the wiring/voltage work, I could verify it with a different program. Did you manage to get it to work? I'd much appreciate any assistance.

**Comment by HomeSpan** [comment]
Ca you post a link to the specific driver board you are using.

**Comment by aldospanjaard** [comment]
I’m using the same uln2003 driver board and the same stepper motor.

**Comment by HomeSpan** [comment]
There are no links in this thread, only sketches.  I can try to help if you provide me with a link to a website that shows the board you are using.

**Comment by aldospanjaard** [comment]
For the stepper motor driver board, it’s this one: https://www.otronic.nl/nl/uln2003an-stepper-motor-driver-board-groen.html?source=googlebase&gad_source=1&gclid=Cj0KCQiA-62tBhDSARIsAO7twbZs7XI0mn_1UrD9GZ0WWxIOKxczR_i3tH_CmIn0i-twg7JZ7HFy9gYaAp_hEALw_wcB, the esp32 is an esp32-wrover module with a camera.

**Comment by HomeSpan** [comment]
This is very helpful - thanks.

Based on what I can see, you should be able to use the existing TB6612 logic configured for 4-wire mode.  To test this, load the [TB6612 Example](https://github.com/HomeSpan/HomeSpan/blob/master/docs/Stepper.md#example-sketches) but change the constructor from this:

```C++
motor=new Stepper_TB6612(23,32,22,14,33,27);    // this is for a 6-wire configuration - NO GOOD for unl2003
```
to  this:

```C++
motor=new Stepper_TB6612(23,32,22,14);   // this is for a 4-wire configuration - suitable for unl2003
```

Then make the following connections from the ESP32 to the UNL2003

ESP Pin 23 -> UNL Input 1
ESP Pin 32 -> UNL Input 3
ESP Pin 22 -> UNL Input 2
ESP Pin 14 -> UNL Input 4

You can use different pins if needed - just make sure the pins you use match those listed in the *Stepper_TB6612()* constructor above.

If the motor does not move, try switching the wires between Input 3 and Input 2.

**Comment by jdaviddiaz111** [comment]
I was also looking for how to drive a stepper motor with the uln2003 driver. The recommendation that you have shared to use the TB6612 driver works for the uln2003, however I am not very clear about how I can increase the speed since it is very slow and how to tell it how many steps it should go through, could you help me with these questions?

**Comment by jdaviddiaz111** [comment]
The stepper motor I am using is the 28BYJ-48. https://www.mouser.com/datasheet/2/758/stepd-01-data-sheet-1143075.pdf

**Comment by HomeSpan** [comment]
Glad you were able to get it working.  

To run any stepper motor as fast as possible, use one of the two FULL STEP modes and set the time delay between steps to 1 millisecond, which is the lowest allowed value.  The motor you have may not support such a small delay, so you will need to experiment until you find the smallest delay that works correctly. 

Note that the motor you have contains a gear drive that causes it to go slower but has better torque.  Different manufacturers of your motor use different gear ratios, so you will need to determine for yourself how many steps it takes to make a full revolution.  

All the details you need are provided on the HomeSpan Stepper Motor page.

**Comment by jdaviddiaz111** [comment]
Thank you very much for your comments, I changed the delay and it actually spins a little faster. I have been doing tests and after a few minutes after having the motor connected, without using it, just waiting for instructions, it gets very hot, I don't know why it is. The truth is that I only want to achieve that it can move a certain number of steps and then return to the initial position since the example code that is on the page allows it to be moved as far as the user wants and it has become a little difficult for me to understand. . Could you help me with the "struct" to make the motor only move a number of steps and then return to the initial position? And if you have any idea why it's getting so hot too?

**Comment by jdaviddiaz111** [comment]
Or if you can explain to me a little how I can indicate the steps I want to reach, allowing it to be indicated by the person who wants the engine to move so much, I would appreciate it. For example, if I want the motor to move 5000 steps, how would it be?

**Comment by jdaviddiaz111** [comment]
https://gist.github.com/jdaviddiaz111/563241c700635c330eaea44fe0e3967c this is the code I´m using

**Comment by HomeSpan** [comment]
The motor will get hot if you leave it in an active state after it stops moving.  In other words, you are applying constant power to keep the motor in a fixed position, making it hard to turn.  This is often desired, but if NOT, then as explained in the documentation you can set the end state to StepperControl::DISABLE.  This way there will be no current once the motor finished moving, which means it will cool down.

**Comment by HomeSpan** [comment]
I'm not sure I understand the question.  To get the motor to move *you need to explicitly* tell it how many steps to take.  Note that the example script is just a simple example to test that the motor spins.  You still need to read through the detailed methods described in the documentation and choose which methods works best for your project --- in every case you have complete control over how many steps the motor will take. 

Are you trying to make a HomeKit project or just use the motor for other purposes?   If for HomeKit, please study the MotorizedWindowShade example referenced in the Stepper Motor documentation.  It details all the techniques and methods that are available.

**Comment by jdaviddiaz111** [comment]
I continued doing tests with the 29byj-48 stepper motor and the uln2003 driver and I think it does not work well with the library that you suggested using, one motor was damaged and another does not spin very well, what could be another alternative to use the driver uln2003?
​
