### ISSUE TITLE
Non Functioning new stepper class

### ISSUE THREAD

**Issue by D0NEDAN** [HomeSpan/HomeSpan#735]
I need someone's help on creating new stepper class for driver ULN2003. I don't understand why doesn't it work. There is some problem with the "override"

#include "StepperControl.h"

//////////////////////////

struct Stepper_ULN2003 : StepperControl {

  int in1Pin;
  int in2Pin;
  int in3Pin;
  int in4Pin;

//////////////////////////

  Stepper_ULN2003(int in1Pin, int in2Pin, int in3Pin, int in4Pin, std::pair<uint32_t, uint32_t> taskParams = {1, 0})
      : StepperControl(taskParams.first, taskParams.second) {
    this->in1Pin = in1Pin;
    this->in2Pin = in2Pin;
    this->in3Pin = in3Pin;
    this->in4Pin = in4Pin;

    pinMode(in1Pin, OUTPUT);
    pinMode(in2Pin, OUTPUT);
    pinMode(in3Pin, OUTPUT);
    pinMode(in4Pin, OUTPUT);

    setStepType(HALF_STEP); // You can adjust the step type based on ULN2003 requirements
  }

//////////////////////////

  void onStep(boolean direction) override {
    if (direction) {
      // Clockwise step sequence
      for (int i = 0; i < 4; i++) {
        singleStep(true);
      }
    } else {
      // Counter-clockwise step sequence
      for (int i = 0; i < 4; i++) {
        singleStep(false);
      }
    }
  }

  // Perform a single step (common logic for both directions)
  void singleStep(boolean forward) {
    digitalWrite(in1Pin, forward ? HIGH : LOW);
    digitalWrite(in2Pin, forward ? HIGH : LOW);
    digitalWrite(in3Pin, forward ? HIGH : LOW);
    digitalWrite(in4Pin, forward ? HIGH : LOW);
    delayMicroseconds(1000); // Experiment with the delay based on your motor and application
    digitalWrite(in1Pin, LOW);
    digitalWrite(in2Pin, LOW);
    digitalWrite(in3Pin, LOW);
    digitalWrite(in4Pin, LOW);
    delayMicroseconds(1000);
  }

//////////////////////////

  void onEnable() override {
  }

//////////////////////////

  void onDisable() override {
  }

};

**Comment by HomeSpan** [comment]
What's not working?

Also, please encapsulate your code in markdown so I can copy to test.

**Comment by D0NEDAN** [comment]
Thanks for your swift response, I am under deadline and solving this problem would help me immeasurably. The problem is in every part where "override" is mentioned. I took inspiration from the Stepper_A3967 class and tried to write the class for ULN2009 but I get a lot of errors. I hope I marked the code correctly. Just in case I attached my whole project (sketch)
[smartBlinds02.zip](https://github.com/HomeSpan/HomeSpan/files/13854378/smartBlinds02.zip)


`#include "StepperControl.h"

//////////////////////////

struct Stepper_ULN2003 : StepperControl {

  int in1Pin;
  int in2Pin;
  int in3Pin;
  int in4Pin;

//////////////////////////

  Stepper_ULN2003(int in1Pin, int in2Pin, int in3Pin, int in4Pin, std::pair<uint32_t, uint32_t> taskParams = {1, 0})
      : StepperControl(taskParams.first, taskParams.second) {
    this->in1Pin = in1Pin;
    this->in2Pin = in2Pin;
    this->in3Pin = in3Pin;
    this->in4Pin = in4Pin;

    pinMode(in1Pin, OUTPUT);
    pinMode(in2Pin, OUTPUT);
    pinMode(in3Pin, OUTPUT);
    pinMode(in4Pin, OUTPUT);

    setStepType(HALF_STEP); // You can adjust the step type based on ULN2003 requirements
  }

//////////////////////////

  void onStep(boolean direction) override {
    if (direction) {
      // Clockwise step sequence
      for (int i = 0; i < 4; i++) {
        singleStep(true);
      }
    } else {
      // Counter-clockwise step sequence
      for (int i = 0; i < 4; i++) {
        singleStep(false);
      }
    }
  }

  // Perform a single step (common logic for both directions)
  void singleStep(boolean forward) {
    digitalWrite(in1Pin, forward ? HIGH : LOW);
    digitalWrite(in2Pin, forward ? HIGH : LOW);
    digitalWrite(in3Pin, forward ? HIGH : LOW);
    digitalWrite(in4Pin, forward ? HIGH : LOW);
    delayMicroseconds(1000); // Experiment with the delay based on your motor and application
    digitalWrite(in1Pin, LOW);
    digitalWrite(in2Pin, LOW);
    digitalWrite(in3Pin, LOW);
    digitalWrite(in4Pin, LOW);
    delayMicroseconds(1000);
  }

//////////////////////////

  void onEnable() override {
    // Implementation for enabling the motor (if needed)
    // Example: No enable pin on the ULN2003, so this method can be left empty
  }

//////////////////////////

  void onDisable() override {
    // Implementation for disabling the motor (if needed)
    // Example: No disable pin on the ULN2003, so this method can be left empty
  }

//////////////////////////

  StepperControl *setStepType(int mode) override {
    // Implementation for setting the step type (if needed)
    // Example: No microstepping support in ULN2003, so this method can be left empty
    return this;
  }
};
`

**Comment by HomeSpan** [comment]
Replace `#include "StepperControl.h"` with `#include "extras/StepperControl.h"`  This allows me to compile fine (though I have no idea if your code will properly operate the motor).

There is a mis-statement in the docs - I will update.

**Comment by D0NEDAN** [comment]
Now the "override" error is solved but the ESP32 is not showing up in the HomeKit (I tried to connect it with the LED, that worked). Is there a problem in the main part?
```
include "HomeSpan.h"
#include "Stepper_ULN2003.h"

////////////////////////////////////

struct DEV_WindowShade : Service::WindowCovering {

  Characteristic::CurrentPosition currentPos{0, true};
  Characteristic::TargetPosition targetPos{0, true};

  StepperControl *mainMotor;

  DEV_WindowShade(StepperControl *mainMotor) : Service::WindowCovering() {
    this->mainMotor = mainMotor;

    mainMotor->setAccel(10, 20);
    mainMotor->setStepType(StepperControl::HALF_STEP);

    LOG0("Initial Open/Close Position: %d\n", currentPos.getVal());

    mainMotor->setPosition(currentPos.getVal() * 20);
  }

  ///////////

  boolean update() {
    if (targetPos.updated()) {
      mainMotor->moveTo(targetPos.getNewVal() * 20, 5, StepperControl::BRAKE);
      LOG1("Setting Shade Position=%d\n", targetPos.getNewVal());
    }

    return true;
  }

  ///////////

  void loop() {
    if (currentPos.getVal() != targetPos.getVal() && !mainMotor->stepsRemaining()) {
      currentPos.setVal(targetPos.getVal());
      LOG1("Main Motor Stopped at Shade Position=%d\n", currentPos.getVal());
    }
  }
};

////////////////////////////////////

void setup() {
  Serial.begin(115200);

  homeSpan.begin(Category::WindowCoverings, "Motorized Shade");
  new SpanAccessory();
  new Service::AccessoryInformation();
  new Characteristic::Identify();
  new DEV_WindowShade(new Stepper_ULN2003(19, 18, 5, 17));
}

//////////////////////////////////////

void loop() {
  homeSpan.poll();
}

```

**Comment by D0NEDAN** [comment]
I got it to connected but the stepper class doesn't work
