### ISSUE TITLE
HomeSpan-native way of sending data

### ISSUE THREAD

**Issue by Julius-Bendt** [HomeSpan/HomeSpan#745]
Hello there,

First of all - thanks for this great library! it makes building Homekit available devices an absolut breeze!

I wanted to create dashboards such as seen in Home Assistant for values that my devices are picking up.
As I enjoy the fact that Apple handles network security for me, and that I don't want to open up my network, i'm staying away from homekit.

Therefore, I wanted to send the values that my devices are picking up to a local server, running on a pi. These value will afterwards be displayed in a web application (obviously only accessable from my home network)

While I have written some code that works, I was wondering if HomeSpan includes any way to send data asynchronous?
Any webClient I can access, so I don't have instansiate a new one? 
Does HomeSpan use another json library? 

if not, I fully understand that this feature might be out of scope for HomeSpan

```c++
#include <HomeSpan.h>
#include <WiFi.h>
#include <ArduinoJson.h>

const char *ssid = "ssid";
const char *password = "password";
const char *apiEndpoint = "192.168.x.x";
const int apiPort = 4321;

void setup()
{
    Serial.begin(115200);

    // Debug purposes
    homeSpan.setWifiCredentials(ssid, password);
    homeSpan.setPairingCode("11111111");

    // Send data to local api once wifi is connected
    // This is mainly for debug purposes. The sendData-function will eventually be moved into the loop-function
    // Data will be send, once HomeSpan sends data to Homekit
    homeSpan.setWifiCallback(sendData);

    // Straight out of example 1 - imagine theres a lot of sensors here
    homeSpan.begin(Category::Lighting, "HomeSpan send data test");
    new SpanAccessory();
    new Service::AccessoryInformation();
    new Characteristic::Identify();
    new Service::LightBulb();
    new Characteristic::On();
}

void loop()
{
    homeSpan.poll();
    // sendData() will eventually go here
}

void sendData()
{
    Serial.print("Connected to wifi, sending data!");

    // Format data as json
    StaticJsonDocument<200> jsonDoc;
    jsonDoc["temperature"] = 20;
    jsonDoc["humidity"] = 40;
    jsonDoc["light"] = 35;
    jsonDoc["movement"] = 0;

    // Convert JSON to a string
    String jsonString;
    serializeJson(jsonDoc, jsonString);

    // Make an asynchronous request to the API
    WiFiClient client;
    if (client.connect(apiEndpoint, apiPort))
    {
        Serial.println("Connected to API");

        // Format the headers
        String requestHeaders = "POST /sendData HTTP/1.1\r\n" +
                                String("Host: ") + String(apiEndpoint) + "\r\n" +
                                "Content-Type: application/json\r\n" +
                                "Content-Length: " + String(jsonString.length()) + "\r\n\r\n" +
                                jsonString;

        // Send the HTTP request
        client.print(requestHeaders);
        delay(500); // Debug purposes
        client.stop();
        Serial.println("Data sent to API");
    }
    else
    {
        Serial.println("Connection to API failed");
    }
}
```

**Comment by HomeSpan** [comment]
Follow-up: If you are just looking to make outbound web calls, you probably don't need to instantiate a second server.  Using WiFiClient as per your example should be fine.  However, make sure to disconnect the client after data has been transmitted and allow the instance to delete at the end of the function call to make sure there are still sockets open for use by HomeSpan. 

To make sure HomeSpan itself does not use up all the sockets preventing you from making an outbound transmission, you can call homeSpan.reserveSockets(). See the API for details.
