### ISSUE TITLE
Platformio implementation

### ISSUE THREAD

**Issue by beckmx** [HomeSpan/HomeSpan#75]
I was trying to add the library as a dependency to my project and noticed, it pops up these messages, in Arduino I guess those are ignored:

```
.pio/libdeps/odroid_esp32/HomeSpan/src/Span.h:35:22: error: 'opt' was not declared in this scope
 #define OPT(HAPCHAR) opt.push_back(&hapChars.HAPCHAR)

```

**Comment by HomeSpan** [comment]
Does this cause a failure or is it just a warning message (sorry, I don't use Platform IO)?

**Comment by beckmx** [comment]
Yes, that is identified as an error, warnings are ignored but a bunch of similar lines where opt is used are raising these issues
