### ISSUE TITLE
Peer to Peer Communication

### ISSUE THREAD

**Issue by cgarland26** [HomeSpan/HomeSpan#753]
Does HomeSpan require Peer-to-Peer communication? I connected my HomePod to my wifi and it gave me the warning ""___ssid" doesn't support peer-to-peer communication". I cant connect to my esp32, so I'm worried that this is the issue (which is one that I probably can't fix as it is a communal wifi). Is this the issue that I'm running into or is there something else?

**Comment by HomeSpan** [comment]
HomeSpan operates like any other commercial HomeKit device with regard to connectivity. If your WiFi does not allow you to add a HomePod (for whatever reason) HomeSpan will likely not be able to operate on that network either.

**Comment by cgarland26** [comment]
I am allowed to add the HomePod to my wifi, but it gave me a warning when I did so saying that some features may be disabled because peer to peer communication isn't allowed. I haven't tried connecting any other devices to the HomePod. If I tried to connect another smart device to the HomePod and it works, do you think that that should mean that the HomeSpan should work in theory? I'm just trying to diagnose my issue.

**Comment by HomeSpan** [comment]
If a commercial HomeKit device works, HomeSpan should work.  What error are you getting from HomeSpan?

**Comment by HomeSpan** [comment]
If the issue is that you can't connect the ESP32 itself to WIFI, try a standalone example unrelated to HomeSpan to make sure there is not something about how the ESP32 connects to Wifi that is problematic.

**Comment by cgarland26** [comment]
I'm not getting any errors from HomeSpan. It's just not appearing when I go to connect it with my phone. It connects to my WiFi, my HomePod is connected to my WiFi, and my phone is connected to my WiFi, but my phone can't find it when I try to connect. When I get back, I will try one of the examples.

**Comment by HomeSpan** [comment]
That means it's very likely MDNS, which is required by HomeKit (and therefore HomeSpan) has been prevented on the WiFi you are using - it is a form of peer-to-peer communication.

**Comment by homonto** [comment]
and to add what @HomeSpan  said: if you have multi ssid and multi vlans, you need to allow firewall to broadcast mdns to all vlans and devices to be allowed port 5353 (mdns)

**Comment by HomeSpan** [comment]
@cgarland26, were you able to resolve this?
