### ISSUE TITLE
Support for Orvibo, Sonoff NSPanel Pro/NSPanel and/or any other touch screen?

### ISSUE THREAD

**Issue by majortom64** [HomeSpan/HomeSpan#754]
Do you have any to use any of the touch screens as HomeKit switches/lights (_i.e._ send switch commands and receive light commands to use for status display)?

**Comment by HomeSpan** [comment]
Sorry, HomeSpan does not have any components that directly support touch screens.  However, other libraries that support a touch screen might be able to be used alongside of HomeSpan.
