### ISSUE TITLE
Multiclicks SpanButton

### ISSUE THREAD

**Issue by Nezaemmy** [HomeSpan/HomeSpan#755]
Hello I'm using HomeSpan to control 4  accessories with one button, is there an option to add more than double clicks like 3 clicks?
Thank you

**Comment by HomeSpan** [comment]
Sorry, HomeSpan only directly supports double-clicking.  However, you could create some custom logic/code that tracked the double-clicks and then waited for a short period to act until it sees if there is another single-click or double-click.  I've not tried this before but by maintaining a state variable that tracks clicks may be doable.

**Comment by Nezaemmy** [comment]
Thanks for your swift response, please can you give me a hint of how I can create  this custom logic
