### ISSUE TITLE
When restarting after a power failure, the ESP32 will no longer reconnect to WIFI

### ISSUE THREAD

**Issue by Ripable0** [HomeSpan/HomeSpan#757]
Hello dear Homespan community!

I have the following problem:
After we had a power outage a few days ago, I noticed that my garden gate control, which I implemented with Homespan, no longer worked.
I connected the laptop to the ESP32 to see what was going on. After establishing the connection, I finally saw on the serial monitor that the ESP32 reconnected as if by magic after establishing the USB connection.

I reproduced this phenomenon, it's the same every time.

If the ESP32 has a power interruption, it will no longer establish a WIFI connection. Only when I want to check the Arduino with the serial monitor is a connection established as if nothing had ever happened.

I tried replacing the 5V relay with a 3V relay, but the ESP reaction remains the same.

Has anyone had problems like this?

**Comment by HomeSpan** [comment]
To confirm, if you connect the laptop to the ESP32 it connects fine to HomeKit?  But if you unplug the ESP32 from the laptop and power it directly, it stops communicating with HomeKit?  I assume you are not moving the ESP32 during this test so it's not the case that the device is going in/out of range.

How are you powering the ESP32 when it is not connected to a laptop?  When connected to the Serial port, is the connection direct, or are you using a Serial-to-USB converter?

**Comment by frankonski** [comment]
Depending how serial monitoring is done, I have seen boards rebooting when the connection is established. So connecting to USB might be simply rebooting the device and you’d lose the reason of the disconnect.

**Comment by Ripable0** [comment]
> To confirm, if you connect the laptop to the ESP32 it connects fine to HomeKit? But if you unplug the ESP32 from the laptop and power it directly, it stops communicating with HomeKit? I assume you are not moving the ESP32 during this test so it's not the case that the device is going in/out of range.
> 
> How are you powering the ESP32 when it is not connected to a laptop? When connected to the Serial port, is the connection direct, or are you using a Serial-to-USB converter?

No if i connect my laptop to the ESP32 it connects and reboots normally. When WIFI connects is established, i can unplug my laptop and from this time on, it runs fine, until the next power outage. The only problem is the restart after an power outage. At this time the ESP32 will not connect to wifi as it normally should.

**Comment by HomeSpan** [comment]
Sorry, I'm not following.  Can you please explain the details of your setup, the exact chip you are using, how it is all powered, what, if anything changes, if you turn off the power to the chip and then turn it back on, etc.  What the symptoms are, etc.

**Comment by andywaplinger** [comment]
@HomeSpan @Ripable0 I think this is the problem/solution he's having https://github.com/HomeSpan/HomeSpan/issues/131#issuecomment-918054695

I was having the same issue until I found that thread. In my case, I added `bool disableUSBserial = false;` at the top of my sketch to quickly enable/disable the serial, then in my setup I have
```Serial.begin(115200);
  if (disableUSBserial == true) {
    pinMode(3,INPUT_PULLUP);
  };
