### ISSUE TITLE
WiFi connect

### ISSUE THREAD

**Issue by aemlnt** [HomeSpan/HomeSpan#76]
Hello. I am using [WiFiManager](https://github.com/tzapu/WiFiManager) library which manages my connection. I am trying to pass wifi parameters from this library to HomeSpan:
`   homeSpan.setApSSID(wm.getWiFiSSID().c_str());`
`   homeSpan.setApPassword(wm.getWiFiPass().c_str());`
But it doesn't work. What am I doing wrong?

**Comment by HomeSpan** [comment]
HomeSpan already has an optional built-in Access Point - you should not need to use WiFiManager (and it likely would interfere with the rest of HomeSpan's WiFi stack).  Please review the [User Guide](https://github.com/HomeSpan/HomeSpan/blob/master/docs/UserGuide.md) for how to start HomeSpan's Access Point so you can enter and store your WiFi Credentials on the ESP32.

Alternatively, you can skip using HomeSpan's Access Point and instead enter and save your WiFi Credentials via the Serial Monitor as described in the [Command Line Interface](https://github.com/HomeSpan/HomeSpan/blob/master/docs/CLI.md).

Note that HomeSpan does *not* permit you to hardcode your WiFi Credentials in the sketch, which is what it seems you may be trying to do - you need to use one of the two procedures above.

The methods you are calling, `setApSSID()` and `setAPPassword()`, are for the purposes of allowing you to override the SSID and Password of HomeSpan's optional Access Point, not to set your own network WiFi Credentials.

Hope this helps clear up any confusion.
