### ISSUE TITLE
Weblogs keeping TCP connections open

### ISSUE THREAD

**Issue by frankonski** [HomeSpan/HomeSpan#761]
Enable weblogs. Set HomeSpan LogLovel to 1. 
Start Wireshark. 
Monitor the serial port.
Use Chrome & open up Developers Tools on the Network tab.
Hit the weblogs URL.

What you will see in the serial monitor is not **one** TCP connection saying "Client #<num> Connected:", but two or 3 lines.
Chrome developers tools will show only one connection.
WireShark will also only one outbound connection, one "HTTP GET", one response.

Then wait few seconds.

Wireshark will then show constant TCP Keep-Alive coming from HomeSpan.
Furthermore, the serial monitor will show these:
```
[1437511][D][WiFiClient.cpp:536] connected(): Disconnected: RES: 0, ERR: 128
```
It looks like there are references to this browser connection still being used by HomeSpan (or WiFi?) which causes this 2nd error, but all seems somewhat related.

I tried to narrow it down, turning off `TCP_KEEPALIVE` and `SO_KEEPALIVE` on the client socket in `HAP.cpp:getStatusURL()` to no avail.
```
    int tcp_keepalive = 0;
    int so_keepalive = 0;
    hapClient->client.setSocketOption(IPPROTO_TCP, TCP_KEEPALIVE, &tcp_keepalive, sizeof(tcp_keepalive));
    hapClient->client.setSocketOption(SOL_SOCKET, SO_KEEPALIVE, &so_keepalive, sizeof(so_keepalive));
```
I hoped to nail it down and submit a PR, but I'll need help on this one.

It looks like `WiFiServer` does set TCP_KEEPALIVE: https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/src/WiFiServer.cpp#L58 , but I seem unable to unset it for HTTP connections that weblogs have to deal with. Keeping TCP connections live eat un-necessary sockets.

**Comment by frankonski** [comment]
Adding an additional TCP_KEEPIDLE to disable it seems to have done the trick:
```
hapClient->client.setSocketOption(IPPROTO_TCP, TCP_KEEPIDLE, &tcp_keepidle, sizeof(tcp_keepalive);
```
But now **I did see** two outgoing TCP connections from Chrome (in Incognito mode, if that changes anything). Why? No clue. But the issue is that the second connection doesn't send the `GET /status` command, hence never goes to `getStatusURL()` where I added these socket options, so there is this constant socket leak.

Question for @HomeSpan : does HAP **really need** TCP keepalives???

**Comment by HomeSpan** [comment]
No idea.  This is really below the level of the application layer and I have not spent much time exploring.  I do know that it is a requirement of HAP that HomeSpan should never close a HAP connection unless it is trying to force an unpairing when all the admin controllers are deleted.  If HomeSpan closes its HAP connection then setVal() can't send updates of status changes to HomeKit (it would have nowhere to send them). 

There are of course no requirements related to the weblogs, and HomeSpan closes that connection as soon as the weblog finishes transmitting. 

But that's at the application layer.  How the ESP32 handles TCP sockets is another matter and it may optimize things at those lower layers.  

I do know that based on my testing, if I have 14 free sockets, HomeSpan will accept and maintain all 14 simultaneously without a problem.  I would be careful about assuming how sockets get consumed in practice by simply looking at keep-alive and wireshark.  My guess is that this is not necessarily indicative of how the ESP will operate in practice. 

Have you run into situations where you cannot connect into or out of the ESP32 even though there seem to be only be a few connections established?

**Comment by frankonski** [comment]
> it is a requirement of HAP that HomeSpan should never close a HAP connection

Ok. 

I think I have initially understood the problem the opposite way (I didn't carefully look at the network trace.. shame..) The TCP keepalives are sent by Chrome, and HomeSpan / ESP32 simply replies to them. Yes Chrome seems to establish more than one TCP connection to HomeSpan, but the second remains silent, and ESP32 never disconnects it. Chrome does disconnect that silent socket after ~4 minutes.

I have also understood something: HomeSpan will keep any socket connected. Just run a couple of `telnet <host> 80` in parallel, they will all remain connected and HomeSpan will never close these connections unless a new one comes in, at which point a random connection will get dropped to handle new incoming one.

> Have you run into situations where you cannot connect into or out of the ESP32 even though there seem to be only be a few connections established?

No. I thought HomeSpan was keeping connections with keepalives, which was actually Chrome keeping it connected... 

All good, no issues. Thanks again!
