### ISSUE TITLE
NTP Libraries reboot the device 

### ISSUE THREAD

**Issue by Nezaemmy** [HomeSpan/HomeSpan#762]
I'm using NTP Libraries to configure the specific time when the accessories connected to esp 32 will work. adding NTP Libraries reboot the microcontroller. I tried many NTP Libraries the result remain the same.
example of one NTP library : https://github.com/sstaub/NTP

EX 05. WorkingLED    

#include "HomeSpan.h" 
#include "DEV_LED.h"          
#include "NTP.h"
WiFiUDP wifiUdp;
NTP ntp(wifiUdp);

void setup() {
ntp.begin();

*ntp.bigin() makes esp to reboot  

This is the result on the serial monitor:

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13964
load:0x40080400,len:3600
entry 0x400805f0

assert failed: tcpip_send_msg_wait_sem IDF/components/lwip/lwip/src/api/tcpip.c:455 (Invalid mbox)

Backtrace: 0x4008392d:0x3ffb1f80 0x4008e071:0x3ffb1fa0 0x40093a25:0x3ffb1fc0 0x400fa751:0x3ffb20f0 0x4010b389:0x3ffb2120 0x4010b3e9:0x3ffb2140 0x400f9f11:0x3ffb2190 0x400e1594:0x3ffb21b0 0x400e161d:0x3ffb21f0 0x400e1ec8:0x3ffb2220 0x400e1f0d:0x3ffb2240 0x400d397f:0x3ffb2260 0x400e477e:0x3ffb2290

**Comment by HomeSpan** [comment]
Have you tested the NTP library on its own - without HomeSpan to make sure it is working correctly?  Also, HomeSpan already has NTP built in - see the WebLog for details.  If you use the WebLog just to acquire the time then normal C++ commands to return the time will work without the need for any NTP calls.

**Comment by Nezaemmy** [comment]
@HomeSpan, NTPlibrary works well on its own, and also I tested it with other homekit library it is working well.
Using NTP Library for example I wanted to add:  
if (ntp.hours()==17 && ntp.minutes()==30 && ntp.seconds()<2){
       flag_for_motion =true;
              }

**Comment by HomeSpan** [comment]
The NTP library you mention above works fine with HomeSpan.  You are using the library incorrectly.  Note in the example provided with the NTP library that you need to FIRST establish a WiFi connection BEFORE calling `ntp.begin()`, else you will crash the ESP32.

Since HomeSpan handles WiFi connectivity for you in the background, you therefore need to wait until HomeSpan has established WiFi connectivity before calling `ntp.begin()`.  To start processes after WiFi has been established you can use the `homeSpan.setWifiCallback()` method.  See the API Reference for details.

As a test, I duplicated the NTP example inside HomeSpan using the following code and it works as expected:

```C++
#include "HomeSpan.h"
#include "NTP.h"

WiFiUDP wifiUdp;
NTP ntp(wifiUdp);

void setup() {

  Serial.begin(115200);

  ntp.ruleDST("CEST", Last, Sun, Mar, 2, 120); // last sunday in march 2:00, timetone +120min (+1 GMT + 1h summertime offset)
  ntp.ruleSTD("CET", Last, Sun, Oct, 3, 60); // last sunday in october 3:00, timezone +60min (+1 GMT)

  homeSpan.setWifiCallback(startNTP);   // here we set a function to be called once WiFi is established
  
  homeSpan.begin(Category::Lighting,"HomeSpan LightBulb");

  
  new SpanAccessory();
    new Service::AccessoryInformation(); 
      new Characteristic::Identify();
    new Service::LightBulb();
      new Characteristic::On();
}

//////////////////////////////////////

void loop(){
  homeSpan.poll();
  ntp.update();
  Serial.println(ntp.formattedTime("%d. %B %Y")); // dd. Mmm yyyy
  Serial.println(ntp.formattedTime("%A %T")); // Www hh:mm:ss
  delay(1000);  // NOTE:  This is for testing only.  In practice, never put a delay in loop() when using HomeSpan unless you use autoPoll() in setup() instead of poll()
}

//////////////////////////////////////

void startNTP(){
  Serial.printf("Starting NTP...\n");
  ntp.begin();
}
```

**Comment by Nezaemmy** [comment]
@HomeSpan Thank you so much for your help
