### ISSUE TITLE
Sodium FATAL ERROR v3 : HomeSpan\src\HAP.cpp:29:20: fatal error: sodium.h: No such file or directory

### ISSUE THREAD

**Issue by MaikxSt** [HomeSpan/HomeSpan#763]
My ESP32 C6 with the Bord Manager esp32 by Espressif Vers. 3.0.0-alpha3 has this Error.

HomeSpan/src/HAP.cpp:29:10: fatal error: sodium.h: No such file or directory
   29 | #include <sodium.h>
      |          ^~~~~~~~~~
compilation terminated.

**Comment by HomeSpan** [comment]
HomeSpan only runs on Arduino-ESP32 version 2.  Version 3 is still in early alpha and likely will require substantive changes to HomeSpan to get it running.  Won't begin that until production version 3 is released from Espressif (or at least a late-stage beta).

**Comment by HomeSpan** [comment]
Nothing at present.  Will be some time before I explore since there is still quite a bit of functionality to add to HomeSpan in the current stack (TLV Characteristics will be next up, followed by Ethernet support).
