### ISSUE TITLE
M2: Accessory -> iOS Device – ‘SRP Start Responseʼ code

### ISSUE THREAD

**Issue by pallaviwhy** [HomeSpan/HomeSpan#767]
Hi,
 M1: iOS Device -> Accessory – ‘SRP Start Requestʼ code can be found in HAP.cpp void HAPClient::processRequest() function. But where is the M2: Accessory -> iOS Device – ‘SRP Start Responseʼ code?
 
![image](https://github.com/HomeSpan/HomeSpan/assets/139468660/733cc6c9-9d5c-4834-8efd-d2d20fefba5c)

**Comment by HomeSpan** [comment]
You are misunderstanding the HAP specifications.   M1, M3, and M5 are processes that run on the iPhone and those states (along with associated data) are sent to a HomeKit device (in this case HomeSpan).  For each state received, HomeSpan performs a variety of calculations and then responds with M2, M4, and M6, accordingly, as shown in the HAP.cpp code.

**Comment by pallaviwhy** [comment]
Understood
