### ISSUE TITLE
Expected behavior of using setPortNum() with weblogs?

### ISSUE THREAD

**Issue by frankonski** [HomeSpan/HomeSpan#772]
Even though `homeSpan.setPortNum(82)` is called during `setup()`, and serial output shows
```
Web Logging enabled at http://HomeSpan-F6E9725E8007.local:82/status with max number of entries=50
```
the weblogs are actually only available at `http://HomeSpan-F6E9725E8007.local/status` (port 80). Expected?

See 
[CustomWebserverWithWebLogs.zip](https://github.com/HomeSpan/HomeSpan/files/14250158/CustomWebserverWithWebLogs.zip)

and feel free to include it as a new *example/Other Example* sketch after setting the URL to `NULL` when calling `enableWebLogs()`.

Ready to unzip and use.

Note also that when setting the URL to NULL, HomeSpan still returns a 404, like if the socket is still listening on port 80 while it should be listening on port 82.

**Comment by HomeSpan** [comment]
WebLogs are not separate from the rest of the HomeSpan HTTP process, so changing the port for HomeSpan should result in the same for WebLogs.  I'll double check to see what's going on.

**Comment by frankonski** [comment]
User error.. I called `setPortNum()` and `enableWebLog()` **after** calling `begin()` instead of **before**.

This is bad:
```
  homeSpan.begin(Category::Lighting,"HomeSpan LightBulb with custom web server");

  // Tell HomeSpan to use a different port number for HAP-specific communications
  homeSpan.setPortNum(82);
  
  // Enabling weblogs, with an NTP server, but without using the built-in handler to serve weblogs.
  homeSpan.enableWebLog(50,"pool.ntp.org",TIMEZONE,"status");

  // Callback when Wifi is connected. Only then will the web server be started.
  homeSpan.setWifiCallback(wifi_connected);
```

This is good:
```
  // Tell HomeSpan to use a different port number for HAP-specific communications
  homeSpan.setPortNum(82);
  
  // Enabling weblogs, with an NTP server, but without using the built-in handler to serve weblogs.
  homeSpan.enableWebLog(50,"pool.ntp.org",TIMEZONE,"status");

  // Callback when Wifi is connected. Only then will the web server be started.
  homeSpan.setWifiCallback(wifi_connected);

  homeSpan.begin(Category::Lighting,"HomeSpan LightBulb with custom web server");
```

**Comment by HomeSpan** [comment]
Glad it's working.  In a future release I am going to combine homeSpan.begin() and homeSpan.autoPoll() into a single homeSpan.start() that should be placed at the end of `setup()` to avoid any issues like this.

**Comment by HomeSpan** [comment]
No worries - I'll  use the current zip.
