### ISSUE TITLE
Help needed: GPIO output gpio_num error

### ISSUE THREAD

**Issue by zackdvd** [HomeSpan/HomeSpan#773]
Hi, thanks for this amazing work and commented code!

I'm trying to combine this project with ESPiLight, so it is easy to control different RF 433Mhz sockets. Protocols etc. are used from pilight project. 

I've a working project, but everytime I switch the light on with homekit I get a lot of these messages: 
`E (18158) gpio: gpio_set_level(226): GPIO output gpio_num error
`

When I comment out all the related homespan code, it works. 
I only use one Acessory (the RF one I created based on DEV_LED.h) and no other GPIO stuff. 
I call one test send() function and that works. Only after homespan is loaded, I get the errors. 
I did not use setStatusPin, but to be sure set it to 3:  homeSpan.setStatusPin(3);

Are there known interferences? Any ideas what I could test?

Thank you for your help!

**Comment by HomeSpan** [comment]
This means you are using an invalid pin for your board and function.  Nothing to do directly with HomeSpan.  Please make sure the pin you are choosing is both supported by your specific board and that it is not an "input only" pin or is otherwise being used by another module.

**Comment by zackdvd** [comment]
Hey, thanks for your answer. Of course you were right, I was confused that it ran with homespan content commented out, but not including the homespan parts. 
BUT: I badly mixed up some references/pointers, so within Service::LightBulb constructor the GPIO pin was not valid anymore. 

Your comment helped me to continue searching for the fault, and now it works! 
Need to code some more, but then I have my homekit->pilight->RF sockets  ESP32 gateway! 
Any possibility to donate to you for your great work?

**Comment by HomeSpan** [comment]
Really glad you were able to resolve the issue 👍.

Re donations, I appreciate the offer but the best way to contribute is by using the system and asking questions when issues arise - this helps make the software better and informs others of common issues...so thank you 😄 !

**Comment by zackdvd** [comment]
Thank you Gregg! 
I'll try to finish my code, make it nice and share!
