### ISSUE TITLE
setWifiCallbackAll

### ISSUE THREAD

**Issue by Nezaemmy** [HomeSpan/HomeSpan#776]
Hi 
Thank you for adding "setWifiCallbackAll " 
I'm trying to use it but I'm failed to do it
I have a function called  void startNTP(), I used  homeSpan.setWifiCallback(startNTP); to startNTP after wifi connected.

I want to use homeSpan.setWifiCallbackAll 
 I tried this 
int count=0;
if( WiFi.isConnected()){
count++;
}
homeSpan.setWifiCallbackAll(startNTP(count>0));

Help me the best way I can use it
Thank you so much

**Comment by HomeSpan** [comment]
I'm not sure you need to call startNTP more than once after WiFi is called.  I don't know exactly what the routine does, but it would likely recover automatically once WiFi is re-established without needing to be started again.  Also, note that the ESP32 has built-in NTP functionality which is called from `homeSpan.enableWebLog()` so you can set the clock this way without needing startNTP() at all.

Regardless, if you want to use `setWifiCallbackAll(void (*func)(int count))`, note that as per the documentation:

> the function *func* must be of type *void* and accept a single *int* argument, *count*, into which HomeSpan passes the number of times WiFi has been established 

If you've not used C/C++ a lot, this syntax can sometimes cause confusion.  In your example above, when you write `startNTP(count>0)`, you are NOT passing a function, but rather you are passing the return value of startNTP (whatever that may be), which is incorrect.

To use `setWifiCallbackAll(void (*func)(int count))` you would still simply write `homeSpan.setWifiCallbackAll(startNTP)`.  The key is that `startNTP()` itself needs to be defined to accept a single `int` argument like this: `void startNTP(int myCount)`.  This allows HomeSpan to PASS YOU the number of times it has re-established WiFi.  Your code regarding `WiFi.isConnected()` above should be deleted - you do NOT need to compute any of this yourself.

In sum, if you've used `homeSpan.setWifiCallback(startNTP)`, you **call** `homeSpan.setWifiCallbackAll(startNTP)` in **exactly** the same way, except that you modify the definition of your function from `void startNTP(){}` to `void startNTP(int myCount){}` and inside that function *myCount* will automatically provide the number of times WiFi has been re-established. I purposely used *myCount* instead to *count* to emphasize that this is a variable internal to startNTP() and can be named anything you want.  All HomeSpan knows is that it is going to pass an *int* to startNTP() as the first (and only) argument - it does not care what you call it.

Note that many of the HomeSpan callbacks work in this same manner (it is a standard C/C++ construct, also extensively used by the ESP32 IDF code).

**Comment by Nezaemmy** [comment]
@HomeSpan Thank you so much for your support and good explanation.
 With your guidance, now the code is running very well.
 Thank you

**Comment by frankonski** [comment]
btw, in “setup()”, you can always call “sntp_set_time_sync_notification_cb(your_callback);”

This gets called about every 3 hours and you can use that to get the ntp time sync.

**Comment by Nezaemmy** [comment]
> I'm not sure you need to call startNTP more than once after WiFi is called. I don't know exactly what the routine does, but it would likely recover automatically once WiFi is re-established without needing to be started again. Also, note that the ESP32 has built-in NTP functionality which is called from `homeSpan.enableWebLog()` so you can set the clock this way without needing startNTP() at all.

 I use NTP library in order to get this kind of statement in my code:
 if ( ntp.hours()==17 && ntp.minutes()>=30){
   flag_for_motion =true;
    }
May I use  `homeSpan.enableWebLog()` to get the same statement as that? if it is possible I can use it to get some free space, 
My sketch size is (94%) of program storage space

**Comment by HomeSpan** [comment]
This is a good question - I just added a [new FAQ](https://github.com/HomeSpan/HomeSpan/blob/master/docs/FAQ.md#how-can-i-read-the-current-date-and-time-from-within-my-sketch) that provides all the details in case others have the same question as well.

Note if you find your sketch is getting too big, you can compile using a larger partition scheme by selecting a new one directly from the Tools Menu on the Arduino IDE.  I tend to use the one labeled "Minimal SPIFFS" instead of the default.  The default reserves 1.5MB of flash for a SPIFFS partition, which is not used at all by HomeSpan.  Under "Minimal SPIFFS" the useable flash memory for your sketch increases by about 50%, and you should find the sketch now takes up only 63% of the program space.

**Comment by Nezaemmy** [comment]
Thank you
