### ISSUE TITLE
FATAL ERROR after installing to 1.9.0

### ISSUE THREAD

**Issue by fbernaly** [HomeSpan/HomeSpan#779]
I have this simple sketch that turns ON/OFF an LED strip in HomeKit using your library.

I was using `v1.8.0`. I followed the examples and tutorials, and my sketch was working with no issues so far.

Today I updated to `v1.9.0` with no changes in my code, and I am getting this error upon the ESP32 starting:

```
13:07:35.380 -> ets Jun  8 2016 00:22:57
13:07:35.380 -> 
13:07:35.380 -> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
13:07:35.380 -> configsip: 0, SPIWP:0xee
13:07:35.380 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
13:07:35.380 -> mode:DIO, clock div:1
13:07:35.380 -> load:0x3fff0030,len:1344
13:07:35.380 -> load:0x40078000,len:13964
13:07:35.380 -> load:0x40080400,len:3600
13:07:35.380 -> entry 0x400805f0
13:07:35.810 -> E (284) psram: PSRAM ID read error: 0xffffffff
13:07:36.640 -> 
13:07:36.640 -> 
13:07:36.640 -> *** FATAL ERROR: Requested allocation of 400 bytes failed.  Program Halting.
```

Any idea on how to solve that? I was reading your release notes and it seems that you included a bunch of nice improvements, but so far it is breaking my code.

Here is my Sketch: https://github.com/fbernaly/esp-fun/tree/master/ReadingLedLight

**Comment by HomeSpan** [comment]
Based on above, it looks like you are running with PSRAM.  Try turning off to see if that resolves.  See [here](https://github.com/HomeSpan/HomeSpan/blob/master/docs/Solutions.md#homespan-crashes-when-i-enable-psram-but-works-fine-if-i-disable-psram) for details.

**Comment by HomeSpan** [comment]
Were you able to resolve?  Was the issue a pin that you were using?

**Comment by fbernaly** [comment]
I was selecting `ESP32 Wrover Module` instead of `ESP32-WROOM-DA Module`. I selected the correct board and it started working.

![Screenshot 2024-02-20 at 3 09 20 PM](https://github.com/HomeSpan/HomeSpan/assets/7014968/e5d24b7c-9455-4812-aefb-205ed3f36753)
