### ISSUE TITLE
Color wheel is inverted

### ISSUE THREAD

**Issue by honear** [HomeSpan/HomeSpan#784]
Hi!
I'm having an issue with my Neopixels where everything works, but the color wheel seems to be inverted on the HomeKit app. I'm using the Pixels example and RGBW configuration.

By inverted I mean it just seems to be flipped horizontally, and when I pick green on the app, the neopixel lights up red.

**Comment by HomeSpan** [comment]
By coincidence, @frankonski just posted a similar problem.  See #781 for discussion and expected solution.  Which specific Neopixel are you using?

**Comment by honear** [comment]
Oh! I didn't see it on mobile, my apologies. I'll follow that discussion. I'm only using 1 neopixel, this one:
https://shop.pimoroni.com/products/ultra-bright-4-watt-chainable-rgbw-neopixel-led-warm-white-3000k?variant=39432816427091

**Comment by HomeSpan** [comment]
Thanks for the link --- it seems the protocol for this chip is indeed reversed from the protocol I used in the Pixel library.  Should be able to address shortly.

**Comment by HomeSpan** [comment]
@honear, please see update in #781

**Comment by HomeSpan** [comment]
Since everything seems to be working with the update in the dev branch I'll close this issue - please feel free to re-open if needed.
