### ISSUE TITLE
Captive portal

### ISSUE THREAD

**Issue by Nezaemmy** [HomeSpan/HomeSpan#788]
Hi, I use the command line "W" or homeSpan.setWifiCredentials(ssid, pwd);  to configure WiFi. I want to ask if there is an option to use the captive portal to configure WiFi.
I tried to use one of library that has this option with HomeSpan but seems like the device does not store the credentials, the device can't remember WiFi credentials after reconnecting from the power.
This is the library I tried to use  https://github.com/SanteriLindfors/WiFiProvisioner.
I use ESP32 S3 with RGB to indicate the WiFi status, and long press on the device boot button to configure the captive portal.

#include "HomeSpan.h" 
#include <WiFiProvisioner.h> 
WiFiProvisioner::WiFiProvisioner provisioner;  

#define PIXEL_PIN 48    
Pixel testPixel(PIXEL_PIN);

struct DEV_LED : Service::LightBulb {               

  int ledPin;
  int bootButton;   // on device button                                    
  SpanCharacteristic *power;                        
  DEV_LED(int ledPin,int bootButton) : Service::LightBulb(){

    power=new Characteristic::On(); 
    new SpanButton(bootButton,1000,5,500,SpanButton::TRIGGER_ON_LOW);

    this->ledPin=ledPin;
    this->bootButton=bootButton;                           
    pinMode(ledPin,OUTPUT);                         
    
  } 
  boolean update(){            
    digitalWrite(ledPin,power->getNewVal());        
    return(true);                                   
  } 
   void button(int pin, int pressType) override {

    if(pin==bootButton){
      if(pressType==SpanButton::LONG){            
        provisioner.connectToWiFi(); 
    } } } 
};

void setup() {

  Serial.begin(115200);
  testPixel.set(Pixel::RGB(10,0,0)); // Red color
  
 homeSpan.begin(Category::Bridges,"HomeSpan LED");
  new SpanAccessory(); 
    new Service::AccessoryInformation(); 
      new Characteristic::Identify();                
    new DEV_LED(16,0);       
} 
//////////////////////////////////////
void loop(){
  
  homeSpan.poll();

   if( WiFi.isConnected()){
    testPixel.set(Pixel::RGB(0,0,10)); //Blue color
  }
  if( !WiFi.isConnected()){
    testPixel.set(Pixel::RGB(0,10,0)); // Green color
  }
  
}

**Comment by HomeSpan** [comment]
Please read through the documentation, including the user guide.  There is already a captive portal built into HomeSpan.

**Comment by Nezaemmy** [comment]
thank you
