### ISSUE TITLE
Double side switch (DPDT) 

### ISSUE THREAD

**Issue by danielhsu0624** [HomeSpan/HomeSpan#793]
I trying add a real switch connect to esp32.So that i can control one relay from real switch or my iphone.
I had read toggleswitch manual,and programmer's multitest.ino example,but still have no clue.
I'm newbie of program,and i really tried to comprehend it.
**I need some pros give me some example with annotation for newbie, help me undersand how this work.**
Thank for the community TAT

**Comment by HomeSpan** [comment]
The tutorials are fully annotated and explain everything.  Tutorial 15-RealPushButtons covers the use of switches, though I recommend you start with the first few tutorials to get a good foundation. 

(note Multtest.ino is not a tutorial and is also quite complicated.)

**Comment by danielhsu0624** [comment]
@HomeSpan I do should start at the first. I going to try more.
Thanks for suggestion:D
