### ISSUE TITLE
enableAutoStartAP()

### ISSUE THREAD

**Issue by Nezaemmy** [HomeSpan/HomeSpan#795]
Hi, Is there a way the code can proceed to homeSpan.begin() after sometime homeSpan.enableAutoStartAP()  waiting configuration?

I tried this but the device stuck on homeSpan.enableAutoStartAP() forever until WIFI credentials configured to begin homeSpan.begin().
homeSpan.setApTimeout(30); // 30 secs
homeSpan.enableAutoStartAP();   
homeSpan.begin(Category::Bridges,"LED");

**Comment by HomeSpan** [comment]
This can't be done at present.  The AP requires rebooting upon exit, so after the 30-second time-out, the AP turns off and the device reboots.  But if no WiFi credentials were input, the AP autostarts once again upon reboot, creating an endless cycle.

**Comment by Nezaemmy** [comment]
Thank you
