### ISSUE TITLE
Ip cameras

### ISSUE THREAD

**Issue by ashrafatshy7** [HomeSpan/HomeSpan#803]
Is there any example for the IpCameras Category?

**Comment by HomeSpan** [comment]
Sorry, HomeSpan does not currently support audio or video services.

**Comment by ashrafatshy7** [comment]
Okay, I thought it supported, because it written in the Categories.md. 

Not every category that written in the Categories.md is supported?

**Comment by HomeSpan** [comment]
The Category setting in any HomeKit device is not functional. It's just for display purposes during pairing and provides hints to the Home App about what icons to use.  The actual functions of a HomeKit device are determined by the Services and Characteristics.  All the Services and Characteristics that are implemented in HomeSpan are defined on the Services.md page.
