### ISSUE TITLE
setPairingCode() has no effect: Home Kit only takes default pairing code

### ISSUE THREAD

**Issue by etkaar** [HomeSpan/HomeSpan#805]
While the serial monitor shows that setPairingCode() was successful, it has no effect. Home Kit says the pairing code is invalid. Only the default one (46637726) can be used.

`Generating SRP verification data for new Setup Code: 222-24-444 ... New Code Saved!`

```
void setup() {
  Serial.begin(115200);
  
  homeSpan.setPairingCode("22224444");
}
```

**Comment by HomeSpan** [comment]
see #786 posted at top

**Comment by etkaar** [comment]
I do in fact use _setWifiCredentials()_, but for me, it does not work. It is even not setting the WiFi credentials now. The serial monitor is just indefinitely showing that, every second. I don't really know what is going on here:

<img width="505" alt="image" src="https://github.com/HomeSpan/HomeSpan/assets/40885610/8822b9b6-dfd2-44bf-9b34-95994f573d45">
