### ISSUE TITLE
Long time support

### ISSUE THREAD

**Issue by etkaar** [HomeSpan/HomeSpan#806]
Since ESP32 also has Home Kit support now, will HomeSpan be supported long-term? ☺️

**Comment by HomeSpan** [comment]
Not sure I understand the question.  What do you mean ESP32 also has HomeKit  support - are you referring to the Espressif HomeKit module?

Re HomeSpan, no guarantee of any support, now or in the future.  It's just a hobby and provided for free - code is available so you can fork and maintain/change in the future if needed.   Also depends heavily on Apple - they no longer publish any specs for hobby-based users and can change the protocol without notice at any time rendering HomeSpan (as well as HomeBridge and similar solutions) inoperable.  Hopefully they continue to maintain backwards compatibility, even if everyone needs to continuously try to reverse-engineer how Apple changes things with each release. 

Also, please use discussions for questions (trying to reserve Issues for bugs and problems).

**Comment by etkaar** [comment]
Yes, I was referring to the ESP HomeKit SDK :)
