### ISSUE TITLE
Add support for white pixels

### ISSUE THREAD

**Issue by frankonski** [HomeSpan/HomeSpan#810]
Got myself a warm white & cold white led strip with WS2811 controller, which, after playing with the demo samples you added recently, was able to figure out that 1 pixel (1 IC) was lighting on warm white on Red, cold white on Blue, and Green was well... ignored.

So I went on to modify the `pixelType` type and added a new one:
```
  pixelType_t WHITE_WxC={15,0,23,0}; // GBR, R=warm white, G=nothing, B=cold white
```
and added a new `Color` constructor as such:
```
      Color WarmColdWhite(uint8_t warm, uint8_t cold)
      {
        this->red = warm;
        this->blue = cold;
        return(*this);        
      }
```
with its respective static public method in the `Pixel` class:
```
   static Color WarmColdWhite(uint8_t warm, uint8_t cold){return(Color().WarmColdWhite(warm,cold));}  // an alternative method for returning an RGB Color
```
then modified your `flashColor()` method sample with a `flashWhite()`...
```
void flashWhite(bool warm, bool cold) {
  for(int i=0;i<MAX_BRIGHTNESS;i++){
    testPixel.set(Pixel::WarmColdWhite(i*warm,i*cold),NPIXELS);
    delay(4);
  }
    
  for(int i=MAX_BRIGHTNESS;i>=0;i--){
    testPixel.set(Pixel::WarmColdWhite(i*warm,i*cold),NPIXELS);
    delay(4);
  }
}
```
and initialized the `PixelStrand` sample with `pixel=new Pixel(pin,PixelType::WHITE_WxC);`.

So far so good, all is working fine for now.

Now, where I am having issues is with a change to the _Holiday Lights_ project which, using Eve, allows you to set the color of the RGB leg strip using the `px->H.getValue()`, `S` and `V` received from the app. The app has two tabs to define the color. One tab is called "Color", the second tab is called "White". From there, it looks like you can define start and end value for a gradian, from _Warm White_ to `Cold White`. Defining `Characteristic::ColorTemperature colorTemp;` within the `PixelStrand` class, I was hoping to see a change to `px->colorTemp.getNewVal<uint32_t>()` within the `ManualControl : SpecialEffect` class, to no avail.

Setting LogLevel to 2, we can also see that even though the _White_ tab is selected, Eve seems to send back HSV values, not any type of color temperature, or gradiant-style values..

Any suggestion to turn HSV values to this _WarmWhite / ColdWhite_ pair of values?

**Comment by frankonski** [comment]
.. I spoke too soon, `ColorTemperature` does seem to get updated now. I will do some cleanup and may end up submitting a draft PR if all works well.

**Comment by HomeSpan** [comment]
Can you send me a link to the specific strip you have -- I'm curious as to how they present the underlying specs.  Since it seems like every possible combination is possible, rather than add a new Pixel type to HomeSpan, it may make sense to simply add some documentation so that these new use-cases can be extended directly from the users sketch.

**Comment by frankonski** [comment]
Sorry, I saw your comment before I pushed a draft PR. You will notice the new method to set white colors, which makes the final code cleaner. Also, the new Pixel type will (I think) ensure that the Green is never set. Without this, I seemed to have strange lighting.

I can push a PR to Holiday Lights, or add an example if you'd like to see how it all worked out for me.

**Comment by JordanMalan** [comment]
+1 I'm using a strip that uses red for the 3000K and green for the 5000K
https://www.amazon.com/dp/B0BNDRF325?ref=ppx_yo2ov_dt_b_product_details&th=1

**Comment by frankonski** [comment]
@JordanMalan, are you currently using HomeSpan 1.9.0, or the "dev" branch?
If you are using the "dev" branch, which `pixelType_t` type are you currently using to get warm for red, and cold for green?

Are you able to pull from my fork to cherry-pick my commit? I can try adding more white-only `pixelType_t` values so you can use it the way I did.

**Comment by JordanMalan** [comment]
@frankonski I'm using 1.8.0 since 1.9.0 seems to have some issue when adding to HomeKit. I'm using the example Pixel sketch.

The only real reason I wish this was better supported in homespan is so the color picker in the home app is correct.

I'll try to pull your code and test, I actually don't mind having many pixel types for different pin arrangements 

You're using WHITE_WxC where I might use WHITE_WCx. But I wonder if there's a better way to do this in general, like if someone made a hypothetical red / white / blue strip for example it would be nice to have morph led which takes any user defined colors 🤷

**Comment by frankonski** [comment]
If you have pulled my fork for testing, try adding this pixel type (and using it) to `src/extra/Pixel.h`:
```
  pixelType_t WHITE_WCx={15,32,0,0}; // GBR, R=warm white, G=cold white, B=nothing  
```
Let me know if it works.

**Comment by frankonski** [comment]
@JordanMalan, did you get a chance to try my fork fork testing? I solved a last issue in my use of a cold/warm white LED strip, and it is now working like a charm using either the Home app or Eve app, which show a “temperature” light selector (no rainbow color selector). 

I use a modified version of the Holiday Lights project, so I don’t know if @HomeSpan would prefer a PR in an new example in HomeSpan, or in Holiday Lights itself so it supports the new Pixel constructor…

**Comment by HomeSpan** [comment]
Given the new release I think we can close this one.
