### ISSUE TITLE
AP not created with control button

### ISSUE THREAD

**Issue by ruchiram** [HomeSpan/HomeSpan#821]
I'm using ESP32 Wroom development board. I have connected push button to D12 and LED to D2. And then homeSpan.setControlPin(12) and homeSpan.setStatusPixel(2) were used to define the pins. After pressing the control button, device goes to command mode (I can see it via serial monitor). But the AP was not created

**Comment by HomeSpan** [comment]
Pressing and holding the control button causes HomeSpan to go into command mode (also known as *Device Configuration Mode*), but then you have to select which command you want to run, also using the control button, as described in the [User Guide](https://github.com/HomeSpan/HomeSpan/blob/master/docs/UserGuide.md#device-configuration-mode).  Did you activate Action 3 to start the AP?

**Comment by ruchiram** [comment]
how do i select the action 3?

**Comment by HomeSpan** [comment]
It's fully explained in the [User Guide](https://github.com/HomeSpan/HomeSpan/blob/master/docs/UserGuide.md#device-configuration-mode).

**Comment by ruchiram** [comment]
In the documentation it says you have to go to the option 3. But not mentioned how to do that. I need to connect to the AP created from the ESP. But there is not AP created at that time

**Comment by HomeSpan** [comment]
This is from the documentation page:

When the Device Configuration Mode is first started, the Status LED will blink once per second to indicate Action 1 has been selected. To select the Action 2, briefly press and release the Control Button. The Status LED will now exhibit a double-blink pattern with a one second pause between blinks, indicating Action 2 has been selected. Each press of the Control Button selects the next action and causes the Status LED to blink according to the Action number. Pressing the Control Button once you reach Action 5 brings the selection back to Action 1.

To execute the selected Action press and hold the Control Button for 3 seconds, at which time the Status LED will begin to flash rapidly (10 times a second). Upon releasing the button HomeSpan will perform the Action selected, and the Status LED will change patterns to reflect the new state of the device after the Action has been taken.

If no Action has been executed within 120 seconds (2 minutes) of starting the Device Configuration Mode, Action 1 is automatically executed and the Device Configuration Mode is exited.

**Comment by frankonski** [comment]
Make sure you are not using the pre-existing, soldered buttons of your development board. These buttons are reserved. You need to add your own physical button.
