### ISSUE TITLE
1.9.0 01-SimpleLightBulb erroring out

### ISSUE THREAD

**Issue by kkakroo** [HomeSpan/HomeSpan#824]
Trying to run `01-SimpleLightBulb` with version `1.9.0 ` and getting below error.

```
Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:13260
load:0x40080400,len:3028
entry 0x400805e4
E (303) psram: PSRAM ID read error: 0xffffffff
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400da1f5  PS      : 0x00060a30  A0      : 0x800d39a0  A1      : 0x3ffb21d0  
A2      : 0x3ffc4684  A3      : 0x00000001  A4      : 0x3ffb8a60  A5      : 0x3ffc4924  
A6      : 0x00000000  A7      : 0x00000000  A8      : 0x00000000  A9      : 0x3ffb21b0  
A10     : 0x3ffb8aec  A11     : 0x00000004  A12     : 0x3ffbda54  A13     : 0x00000000  
A14     : 0x3ffb7c80  A15     : 0x00000000  SAR     : 0x00000019  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000000  LBEG    : 0x400ee63d  LEND    : 0x400ee647  LCOUNT  : 0x00000000  
Backtrace: 0x400da1f2:0x3ffb21d0 0x400d399d:0x3ffb2260 0x400e53a6:0x3ffb2290

ELF file SHA256: 394896f4370ce8c0
```
Tools tab screenshot
<img width="452" alt="image" src="https://github.com/HomeSpan/HomeSpan/assets/8538475/cb465135-2c2a-417a-8c8b-f182cfe4eb40">

 `1.8.0` compiled and uploaded fine but getting error after scanning the sample setup code/setting a custom one i get below error.
![39E2C404-463F-451B-BC07-42EF7D397058_4_5005_c](https://github.com/HomeSpan/HomeSpan/assets/8538475/fc0870b1-d20c-4e52-bf96-574e66831d3d)

on retrying i get this
![25971911-3055-4D4E-934E-BA159A0D80BC_4_5005_c](https://github.com/HomeSpan/HomeSpan/assets/8538475/11108f2f-7c4c-451c-931b-c80a24b799c1)

Apologies in advance if i've missed something trivial as i'm new to this.

**Comment by HomeSpan** [comment]
I cannot reproduce the reboot error under 1.9.0, but I do not have an ESP32 with PSRAM.  What specific ESP32 are you using?  Are you sure the settings are flash=DIO and not flash=QIO?

Also, try uploading with the erase-flash option "enabled" to ensure there are no flash corruption issues.  Can also try running with PSRAM disabled.

Re the Unable to Add Accessory:  it seems like the first pairing may have failed before completing, but HomeSpan may think the pairing succeeded.  If you type 'H' into the CLI, this will erase all pairing info.  Note that erasing the flash before uploading (as per above) will erase all stored HomeSpan info automatically.

**Comment by kkakroo** [comment]
Using a `ESP32-WROOM-32D`.

Updating the settings recommended by you(`flash=QIO` and `PSRAM=disabled`) and erasing the pairing info fixed both the issues.


Such a well architected and documented library. Thank you.
