### ISSUE TITLE
Temporary WiFi recommendations

### ISSUE THREAD

**Issue by zuozhehao** [HomeSpan/HomeSpan#83]
Is it possible to start a temporary WiFi network by default when it detects that no WiFi settings have been saved?

**Comment by HomeSpan** [comment]
This is a good suggestion and I can create an option in HomeSpan so that the hot-spot automatically launches upon power-up if there is no saved WiFi info.   Can you tell me something about how you would use this so I can determine all the parameters needed?

**Comment by zuozhehao** [comment]
> This is a good suggestion and I can create an option in HomeSpan so that the hot-spot automatically launches upon power-up if there is no saved WiFi info. Can you tell me something about how you would use this so I can determine all the parameters needed?

I think that there is no special way. I hope there is a switch like "enableOTA", which can automatically start temporary WiFi without setting WiFi information.

**Comment by HomeSpan** [comment]
Based on the recommendation above, a new method, `homeSpan.enableAutoStartAP()`, has been added to the code and is available in the dev branch for those who would like to test.  Will be included in the next patch release.

Invoking this new method somewhere at the beginning of your sketch will cause HomeSpan to automatically launch the WiFi Access Point upon startup if WiFi Credentials are not found.

**Comment by zuozhehao** [comment]
OK, I'll try. Thank you
