### ISSUE TITLE
Accessory not reachable

### ISSUE THREAD

**Issue by jamesy0ung** [HomeSpan/HomeSpan#832]
I am using HomeSpan 1.9.0 on an ESP32 (original). It is connected to my wifi network, and I can ping it's ip address without any issues. I can also see it broadcasting using an app from the App Store called Discovery, however when I try to connect to it, it will fail and state the accessory is not reachable.

` 
rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:13260
load:0x40080400,len:3028
entry 0x400805e4

************************************************************
Welcome to HomeSpan!
Apple HomeKit for the Espressif ESP-32 WROOM and Arduino IDE
************************************************************

** Please ensure serial monitor is set to transmit <newlines>

Message Logs:     Level 2
Status LED:       Pin 2
Device Control:   Pin 0
Sketch Version:   n/a
HomeSpan Version: 1.9.0
Arduino-ESP Ver.: 2.0.14
ESP-IDF Version:  4.4.6
ESP32 Chip:       ESP32-D0WDQ6 Rev 1 dual-core 4MB Flash
ESP32 Board:      doitESP32devkitV1
PWM Resources:    16 channels, 8 timers, max 20-bit duty resolution
Sodium Version:   1.0.12-idf  Lib 9.4
MbedTLS Version:  mbed TLS 2.28.4
Sketch Compiled:  Apr  8 2024 14:53:32
Partition:        app0
MAC Address:      78:E3:6D:18:2E:8C

Device Name:      Environmental Sensor

HTU21D Temperature - Constructor: 27.72C
HTU21D initial Temperature - end Constructor: 27.72C
HTU21D Humidity - Constructor: 66.42%
HTU21D initial Humidity - end Constructor: 66.42%

*** HomeSpan Info ***

➤ Accessory:  AID=1
   ➟ Service AccessoryInformation:  IID=1, UUID="3E"
      ⇨ Characteristic Name("Environmental Sensor"):  IID=2, UUID="23", Perms=PR
      ⇨ Characteristic Manufacturer("Snowball's Chance "):  IID=3, UUID="20", Perms=PR
      ⇨ Characteristic SerialNumber("78:E3:6D:18:2E:8C"):  IID=4, UUID="30", Perms=PR
      ⇨ Characteristic Model("HS Sensors"):  IID=5, UUID="21", Perms=PR
      ⇨ Characteristic FirmwareRevision("0.1a"):  IID=6, UUID="52", Perms=PR+EV
      ⇨ Characteristic Identify(1):  IID=7, UUID="14", Perms=PW
   ➟ Service HAPProtocolInformation:  IID=8, UUID="A2"
      ⇨ Characteristic Version("1.1.0"):  IID=9, UUID="37", Perms=PR
➤ Accessory:  AID=2
   ➟ Service AccessoryInformation:  IID=1, UUID="3E"
      ⇨ Characteristic Name("Temperature Sensor"):  IID=2, UUID="23", Perms=PR
      ⇨ Characteristic Manufacturer("Snowball's Chance"):  IID=3, UUID="20", Perms=PR
      ⇨ Characteristic SerialNumber("78:E3:6D:18:2E:8C"):  IID=4, UUID="30", Perms=PR
      ⇨ Characteristic Model("HomeSpan Temperature Sensor"):  IID=5, UUID="21", Perms=PR
      ⇨ Characteristic FirmwareRevision("0.1a"):  IID=6, UUID="52", Perms=PR+EV
      ⇨ Characteristic Identify(1):  IID=7, UUID="14", Perms=PW
   ➟ Service TemperatureSensor:  IID=8, UUID="8A"
      ⇨ Characteristic CurrentTemperature(27.7216):  IID=9, UUID="11", Perms=PR+EV, Custom-Range=[-50,100]
➤ Accessory:  AID=3
   ➟ Service AccessoryInformation:  IID=1, UUID="3E"
      ⇨ Characteristic Name("Humidity Sensor"):  IID=2, UUID="23", Perms=PR
     ⇨ Characteristic Manufacturer("Snowball's Chance"):  IID=3, UUID="20", Perms=PR
      ⇨ Characteristic SerialNumber("78:E3:6D:18:2E:8C"):  IID=4, UUID="30", Perms=PR
      ⇨ Characteristic Model("HomeSpan Humididty Sensor"):  IID=5, UUID="21", Perms=PR
      ⇨ Characteristic FirmwareRevision("0.1a"):  IID=6, UUID="52", Perms=PR+EV
      ⇨ Characteristic Identify(1):  IID=7, UUID="14", Perms=PW
   ➟ Service HumiditySensor:  IID=8, UUID="82"
      ⇨ Characteristic CurrentRelativeHumidity(66.4182):  IID=9, UUID="10", Perms=PR+EV, Range=[0,100]

Service                             UUID         AID  IID  Update  Loop  Button  Linked Services
------------------------------  --------  ----------  ---  ------  ----  ------  ---------------
AccessoryInformation                  3E           1    1     YES    NO      NO  -
HAPProtocolInformation                A2           1    8      NO    NO      NO  -
AccessoryInformation                  3E           2    1     YES    NO      NO  -
TemperatureSensor                     8A           2    8      NO   YES      NO  -
AccessoryInformation                  3E           3    1     YES    NO      NO  -
HumiditySensor                        82           3    8      NO   YES      NO  -

Configured as Bridge: NO

Database Validation:  Warnings=0, Errors=0

*** End Info ***

Generating new random Accessory ID and Long-Term Ed25519 Signature Keys...

Accessory ID:      A6:7A:52:47:99:E6                               LTPK: 1F432CE7E29CCF99EDEF8C582FD63025BDA3343F99D5825C5C2F18CCD4ABC118
No Paired Controllers
Resetting Database Hash...

Accessory configuration has changed.  Updating configuration number to 1

Environmental Sensor is READY!

Trying to connect to [Wifi Network].  Waiting 1 sec...

*** Log Level set to 2

HTU21D Temperature - Sensor Loop 27.72C
HTU21D Humidity - Sensor Loop 66.43%
WiFi Connected!  IP Address = 192.168.4.4

Starting MDNS...

HostName:      HomeSpan-A67A524799E6.local:80
Display Name:  Environmental Sensor
Model Name:    HomeSpan-ESP32
Setup ID:      HSPN

Starting HAP Server on port 80 supporting 14 simultaneous HomeKit Controller Connections...

DEVICE NOT YET PAIRED -- PLEASE PAIR WITH HOMEKIT APP`

**Comment by loqimean** [comment]
I have the same problem too((((

**Comment by HomeSpan** [comment]
Any update on this - as noted above, please start all testing with a clean version Example 1.
