### ISSUE TITLE
Pixel issue.

### ISSUE THREAD

**Issue by anlpereira** [HomeSpan/HomeSpan#835]
UPDATE:

The final version of the code is now checked-in on the "dev" branch.  To simplify use, I eliminated the recently-added `setColorMap()` method (which was mostly for initial testing purposes) and instead changed the constructor from `Pixel(int pin, boolean isRGBW);` to `Pixel(int pin, pixelType_t pixelType);` where *pixelType* should be set to one of the following:

* PixelType::RGB
* PixelType::RBG
* PixelType::BRG
* PixelType::BGR
* PixelType::GBR
* PixelType::GRB
* PixelType::RGBW
* PixelType::RBGW
* PixelType::BRGW
* PixelType::BGRW
* PixelType::GBRW
* PixelType::GRBW

Example: `Pixel testPixel(12, PixelType::RGBW);`

This allows you to simultaneously set the order of the RGB colors as well as specify whether your device also has a White LED.   In the new constructor, setting *pixelType* is optional.  If left blank, the default is PixelType::GRB, which matches the behavior in all previous versions of HomeSpan.  The original constructor, `Pixel(int pin, boolean isRGBW)` still works as expected, but I've flagged it as *deprecated* so you will receive a warning when compiling if used.

Finally, I added a standalone PixelTester sketch to help determine which setting to use for any given device.  You'll find it under Other Examples.

_Originally posted by @HomeSpan in https://github.com/HomeSpan/HomeSpan/issues/781#issuecomment-1963285105_

**Comment by anlpereira** [comment]
Hi, where in the pixel.ino example I could add the PixelType::GRB?  
I'm trying to add, but it is showing this "error: 'PixelType' has not been declared"
pixel=new Pixel(pin, PixelType::GRB); 

Thank you very much.

**Comment by angel41671** [comment]
Good morning!

I am having exactly the same issue :(
Any little help would be very welcome.
Thank you in advance!
