### ISSUE TITLE
SpanPoint not able to send RGB values

### ISSUE THREAD

**Issue by xradeon** [HomeSpan/HomeSpan#841]
Hi I just implemented the example in the [SpanPointLightSwitch Repository](https://github.com/HomeSpan/SpanPointLightSwitch) and just changed the type of value to send.

I first tried with 
```
typedef struct {
  int red = 0;
  int green = 0;
  int blue = 0;
} LightBulbData;
```
but I was only getting the red value when using the 
```
LightBulbData data; 
mainDevice->get(&lightBulbData);
Serial.printf("Received LightBulbData. R:%d G:%d B: %d\n", data.red, data.green, data.blue);
```

Then I trying using an `int array[3]` with the same result of only receiving `array[0]`. Also tried using a `uint32_t` manually encoding the 3 integers but still I'm only getting a max value of 255 (beyond that I receive 0).

Of course I replaced 

`mainDevice = new SpanPoint(MAIN_DEVICE_MAC, sizeof(uint32_t), sizeof(boolean));`
&
`remoteDevice = new SpanPoint(macAddress, sizeof(boolean), sizeof(uint32_t), 1, false);`

with the correct type of value for each try... 

Anything I'm doing wrong?

**Comment by HomeSpan** [comment]
Can you send the full sketch?
