### ISSUE TITLE
Homespan not infomation wifi conect

### ISSUE THREAD

**Issue by kungfupho** [HomeSpan/HomeSpan#842]
![image](https://github.com/HomeSpan/HomeSpan/assets/168355765/52a1bb64-b62b-4f04-9e65-f69133c33f0a)

"I can't connect my homespan to my home wifi."

**Comment by HomeSpan** [comment]
For initial testing, please always start fresh with a completely unmodified version of Example 1.

Also, the homespan wifi page is meant to be open on an iPhone in Safari.  Above it looks like you are using something different.
