### ISSUE TITLE
HomeSpan not compatible with Board esp32 from espressif

### ISSUE THREAD

**Issue by 19Andrei97** [HomeSpan/HomeSpan#855]
I had an hard time understanding what the problem was and why I was getting a "sodium.h missing" error message. The issue in the end was because esp32 was updated to 3.0 and apparently is not compatible with the HomeSpan anymore. SOLUTION: Just install esp32 version 2.0.14 as indicated also in the main page of this project.

This is just a FYI message.

**Comment by Glujaz** [comment]
Confirmed, to be the solution. 2.0.17 works.

**Comment by HomeSpan** [comment]
I've added a check to warn during compilation if the wrong board manager is used.  This check is in the dev branch and will be rolled out as part of next release.

**Comment by HomeSpan** [comment]
Version 1.9.1, just released, contains logic to warn users if they try to compile under Arduino-ESP32 3.X.  Though the latest ESP32 library (3.0.2) now contains the sodium library, there is still a lot of incompatibility issues that need to be addressed in the next release of HomeSpan (which I'll likely name 2.0.0 to reflect the big changes needed to be made to compatible with ESP32 3.X).
