### ISSUE TITLE
Device not reachable after esp32

### ISSUE THREAD

**Issue by loqimean** [HomeSpan/HomeSpan#860]
Hi, in a few days ago I got my device with a "No response" error, so, I deleted it and tried to connect it again what wasn't successful, but at least 2 month device was working fine, with a "No response" problem sometimes, but it works, rather now.

**Comment by HomeSpan** [comment]
These issues are difficult to debug as a "no response" error can stem from many causes.  If the device was working fine for 2 months and just started to give you problems it is likely a WiFi / MDNS issue.  If you've made any change to your WiFi network (updated the software, moved a router, added a new WiFi device, etc.) that could have negative implications to how the router processes MDNS messages.  Also, I found that MDNS tends to have problems when the WiFi strength at the ESP32 device is -70 dB or less.   You can check the strength of your WiFi signal at the device by enabling the Web Log.
