### ISSUE TITLE
Trigger Rule 'singleTime > longTime = ALWAYS LONG' not fulfilled

### ISSUE THREAD

**Issue by etkaar** [HomeSpan/HomeSpan#865]
The [documentation](https://github.com/HomeSpan/HomeSpan/blob/master/docs/Reference.md) says:

> If singleTime>longTime, only Long Press triggers can occur

However, following code

```
const uint16_t MINIMUM_PRESS_TIME = 10;
new SpanButton(pin_number, MINIMUM_PRESS_TIME, (MINIMUM_PRESS_TIME + 1), 0, trigger_type);

[...]

WEBLOG("Call Detected: %s.", (pressType == SpanButton::LONG) ? "LONG" : (pressType == SpanButton::SINGLE) ? "SINGLE" : "DOUBLE");
```

still results with `SINGLE` instead of `LONG`:

![image](https://github.com/HomeSpan/HomeSpan/assets/40885610/013e95a1-8d25-4c28-9847-f37d6b2d5ae5)

However, to trigger that, time consuming stuff in the main loop might be required which can be simulated by a `delay()`:

```
void loop() {
    delay(1000);
}
```

**Comment by HomeSpan** [comment]
Please see the examples that fully describe how to use SpanButton.  There is nothing you need to do with any delays in the loop or anywhere else.

**Comment by HomeSpan** [comment]
Sorry, I am not able to reproduce this problem.  The test sketch below works as expected --- with longTime set to 10ms and shortTime set to 11ms I only see LONG presses.  Note that for this to work the push button needs to be normally open and connects the pin (in this case pin 25) to GROUND when closed.

```C++

#include "HomeSpan.h"

struct DUMMY_LED : Service::LightBulb {
  
  Characteristic::On power;

  DUMMY_LED() : Service::LightBulb(){

    new SpanButton(25,10,11,0);
    
  }

  void button(int pin, int pressType) override {

    Serial.printf("Button %s\n",pressType==SpanButton::LONG?"LONG":(pressType==SpanButton::SINGLE)?"SINGLE":"DOUBLE");
  }

};
      
//////////////////////////////////

void setup() {
 
  Serial.begin(115200);

  homeSpan.begin(Category::Lighting,"HomeSpan Light");

  new SpanAccessory();                                                          
    new Service::AccessoryInformation();
      new Characteristic::Identify(); 
    
    new DUMMY_LED();
 
} // end of setup()

//////////////////////////////////////

void loop(){
  
  homeSpan.poll();
  
} // end of loop()
```

**Comment by etkaar** [comment]
You need to add _delay(1000)_ into the main loop to simulate a delay due to other stuff or errors such like timeouts due to network spikes.

**Comment by HomeSpan** [comment]
Still seems to work.  The following sketch with a delay of 1000ms only produces LONG presses, though you need to hold the button down for at least  1000ms to get a response.  Can you confirm you are using a normally-open button that connects your pin to ground when pressed?

```C++

#include "HomeSpan.h"

struct DUMMY_LED : Service::LightBulb {
  
  Characteristic::On power;

  DUMMY_LED() : Service::LightBulb(){

    new SpanButton(25,10,11,0);
    
  }

  void button(int pin, int pressType) override {

    Serial.printf("Button %s\n",pressType==SpanButton::LONG?"LONG":(pressType==SpanButton::SINGLE)?"SINGLE":"DOUBLE");
  }

};
      
//////////////////////////////////

void setup() {
 
  Serial.begin(115200);

  homeSpan.begin(Category::Lighting,"HomeSpan Light");

  new SpanAccessory();                                                          
    new Service::AccessoryInformation();
      new Characteristic::Identify(); 
    
    new DUMMY_LED();
 
} // end of setup()

//////////////////////////////////////

void loop(){
  
  homeSpan.poll();
  delay(1000);
  
} // end of loop()

```

**Comment by etkaar** [comment]
> [...] Can you confirm you are using a normally-open button that connects your pin to ground when pressed?
In my case, the pin was connected to 3.3V, not to ground. Do you think that could make a difference?

**Comment by HomeSpan** [comment]
What do you have set for the trigger_type?

**Comment by etkaar** [comment]
```
  static bool trigger_type(int pin_number) {
    if (digitalRead(pin_number) == HIGH) {
      return true;
    }

    return false;
  }
```

**Comment by HomeSpan** [comment]
Since you are defining your own trigger function, did you also remember to configure the pin (in your case you would need to configure it as an input with PULL_DOWN activated).  Note TRIGGER_ON_HIGH is built in to SpanButton, so no need to create your own.

**Comment by etkaar** [comment]
Yes, indeed:

```
    /**
    * Button we use to trigger the press
    */
    pinMode(this->pin_number, INPUT);
```

When I have time, I will try to reproduce the issue.

**Comment by HomeSpan** [comment]
Any update on this, or can I close for now?
