### ISSUE TITLE
"no response" - how to debug?

### ISSUE THREAD

**Issue by zackdvd** [HomeSpan/HomeSpan#873]
Hi,
my device was working perfectly, until some days ago. I get the "no response" message for all connected devices. 
It works for some seconds after reboot, but then stops working. 

Weblog doesn't give me any infos, also serial monitor not. 

So I set Log Level to 2 in serial console. 
It works, when I switch a light I see the debug infos. 
But after appr. 1 minute, homekit tells me "no response". 
No debug message. I still can execute "i" for information and get a lot. But I do not see any failure. 

Any hints, what I could do to dig into the failure? 
I really wonder, since it just stops working, without reflash or other changes...

Thank you!

**Comment by HomeSpan** [comment]
Did anything change on your network (are you using a mesh router).  This can include updating router software, moving the router, moving the HomeSpan device, etc.  Also, any changes or updates to your iPhone, any Home Pods, or Apple TV (are you using a Home Hub?).  Does the web log indicate that WiFi was dropping at any point?

**Comment by zackdvd** [comment]
Hi,
thanks for answering so quick. I had the same thoughts, did I change anything? I'm on your side, ESP32 did not changed, so something else must be the reason. 

- Apple TV and iPhone: only normal SW updates, no Beta, no new devices. 
- Router: no change, maybe new SW (not under my control, vodafone device. I'll check), not replacement
- HomeSpan device: **After** it stopped working, I moved it, also connected to my laptop. No change

This is the web-log (not more):
<img width="764" alt="image" src="https://github.com/HomeSpan/HomeSpan/assets/19238490/2cec8d59-e366-4b16-8412-6f68e612f9da">

I still can access serial console and give commands.

**Comment by zackdvd** [comment]
I tried it again, now its working for some minutes. I keep you updated. 
I hate these kinds of failures.

**Comment by zackdvd** [comment]
Will do, thanks for the tip! Closed for now!
