### ISSUE TITLE
ESP32 Arduino Smart Home Project With HomeSpan(HomeKit protocol) VS. MATTER protocol 

### ISSUE THREAD

**Issue by 0100101101001011** [HomeSpan/HomeSpan#885]
Hi there! First and foremost, I'd like to express my gratitude for creating such an amazing project!

I am currently working on a smart home project involving smart lights with Apple Home support. I am contemplating the pros and cons of integrating an esp32 Arduino project with Apple Home using either HomeKit or Matter protocol. Could you please provide some insights into the advantages and disadvantages of these two protocols for this specific integration?

**Comment by ronny-antoon** [comment]
HomeSpan better in all things, but their is one problem that forced me to move to Matter, the MDNS issue that randomly happens.
Matter its slow than HomeSpan, hard than HomeSpan, But never "no Response" even that they have a memory leak.

**Comment by HomeSpan** [comment]
I think that's right.  MDNS is not universally supported the same way by every router, so in some cases it's just too unpredictable. 

A good case study is the commercial company Rachio - they build really nice irrigation controllers and automatic water hose valves.  A few years ago they announced HomeKit compatibility, but ran into the same problems.  It works really well for some people, but not very well for others.  They eventually decided to stop supporting HomeKit, though they retained the software and the pairing codes so you can still use it if you'd like (just don't call them if it doesn't work).

In my own home I originally used a Linksys Velop mesh network for a year and it worked fine.  Then the Velop started having problems  as a result of firmware updates.  At first the problems did not impact HomeSpan stuff, but with each new update I had more and more problems with HomeSpan as well as commercial HomeKit devices.  I eventually threw the Velop system in the garbage and switched to a NetGear Orbi mesh network and it's been rock solid for 3+ years.  Not sure why some routers work better than others.

I recommend starting with HomeSpan.  If you load example 1 and it is stable for a few weeks, that likely means your routers fully support the MDNS protocol (at least the version used by Espressif).  If unstable (using Example 1), then you may want to try Matter.

**Comment by ronny-antoon** [comment]
If you are a developer person, and have a good experience, i will advise you to go for espressif framework and not arduino.
You can control everything in espressif.
But in arduino you will get some compiled files that cant really change and sone flags that cant change. So i recommend using esp_matter over some arduino matter.

But in overall HomeSpan the better simple faster for development and use.
