### ISSUE TITLE
Not working when ESP32 is external powered

### ISSUE THREAD

**Issue by bastifpv** [HomeSpan/HomeSpan#887]
The project works great when I connect the ESP via the USB port and all devices are available. 
But if I connect it via the external pins with a power supply it does not work. I also cannot read out any errors, as I have no serial access. 
The circuit works because other projects run without problems

**Comment by HomeSpan** [comment]
Please see the HomeSpan Solutions page that addresses this issue.

**Comment by bastifpv** [comment]
Oh didn't find it. Can you send a link?
Thanks ;)
