### ISSUE TITLE
Add support for Stateful Programmable Switch

### ISSUE THREAD

**Issue by frankonski** [HomeSpan/HomeSpan#888]
Looks like HomeKit has the ability to have a [stateful programmable switch](https://developer.apple.com/documentation/homekit/hmservicetypestatefulprogrammableswitch).
HomeSpan has the standard on/off switch, and also a stateless (button) programmable switch, but not stateful programmable switch.

The reason for this is that I would like the switch to have an On/Off state based on whether or not the alarm siren of a SecuritySystem is triggered. 

The switch would turn On on alarm triggered, and one would do a single tap on the switch to turn the alarm Off.
And when the switch is Off, a long press (or double/triple tap) would be required to trigger the alarm on.

The issue with HomeKit's SecuritySystem is that its's AlarmTriggered state overwrites any Armed/Stay/Night state. So to turn off the alarm, one needs to tap to disable the alarm, which goes against normal alarm panel. If an alarm gets triggered, one would enter their code to stop the alarm from ringing, but the state would remain Armed.

**Comment by HomeSpan** [comment]
I experimented with adding a Stateful Programmable Switch a while back but Home App says it's unsupported.  I just tried again using the UUIDs from the HomeBridge API, but still does not work.  Note that though this Service is listed in the Apple Dev pages for HomeKit, those pages are very out of date.  Also, only a Stateless, but not Stateful, Programmable switch is included in HAP-R2.

Also, even if Stateful did work, I'm not sure it would do what you wanted.  The purpose of a Programmable Switch service is that you send a button press code to the Home App and you tell HomeKit what it should do with that button press from with the Home App (nothing to do with HomeSpan at that point).  You are therefore limited to only what the Home App will allow you to select, which is usually just turning things on/off.  Resetting an alarm would likely be way too specific for Apple to have included this in the generic automations section.

**Comment by HomeKidd** [comment]
Statefull Programmable Switch is working in the Eve app using HomeSpan. 😄 
![IMG_3265](https://github.com/user-attachments/assets/c7b4e254-652e-458a-9f58-06887ddf78fc)

**Comment by HomeSpan** [comment]
what UUID codes are you using?

**Comment by HomeKidd** [comment]
> what UUID codes are you using?

[StatefulProgrammableSwitch Service](https://nrchkb.github.io/wiki/service/stateful-programmable-switch/) and the required Characteristics 😄

**Comment by HomeSpan** [comment]
Thanks - those are the ones I tried but did not test on Eve.  What happens in the Home App when you pair a device with these?  I get "Not Supported" with no way of setting the buttons.

**Comment by HomeKidd** [comment]
> Thanks - those are the ones I tried but did not test on Eve. What happens in the Home App when you pair a device with these? I get "Not Supported" with no way of setting the buttons.

It's like the Doorbell Service, it needs to be added for a Light Switch Service 😄 But I've didn't test it, just was curious what it is 😄

**Comment by HomeSpan** [comment]
Hmmm.  That's strange since I'm not sure what purpose it would serve if it needs to be hardcoded to a particular implemented service.  You can already add internal buttons to any service and have the state of the service updated in HomeKit.  If the Stateful service operates like the Stateless, it should be programmable from the Home App where you select the service you want to change from there.

**Comment by frankonski** [comment]
After adding a new service and new hapchar to HomeSpan source I’m now able to get to the same state as both of you:
The stateless switch has options (in both Eve and Home app) to **assign** a scene (in Eve) or create a new automation based on single, double or long presses. But the app itself shows no button (???) in either app.
The stateful switch on the other hand has a toggle button (with values of 0 and 1 as in the screenshot above) only in Eve, I can toglle it and the `update()` method will get called. But Home app shows a house icon that says “Not supported” and details shows “This accessory is not currently supported by the Home app”.

Maybe I am missing the point, but what is the purpose of a stateless switch if you have no way to push a button? And what is the point of a stateful switch if you can’t define press type (single, double, long)?

**Comment by HomeSpan** [comment]
What distinguishes a Programmable button from an ordinary switch service is the source of the control.  For a regular switch service, the user controls the operation from the Home App, and the accessory performs some function (like turning on a light).  

For a Programmable switch service, it's the exact opposite.  The user controls the button from the accessory, and the Home App takes the action (based on how you program it from within the Home App).  There is no button in the Home App for a Programmable Switch because there would be nothing for it to do. The Home App would already have buttons for the scenes, etc. that are operated by the Programmable Switch. I can see why having a duplicate button on the Home App might be convenient, but the design of the Home App is such that buttons are used to send commands to Accessories, and Scenes are used trigger actions (which themselves send commands to Accessories). 

This is the way the stateless switch works.

The stateful switch does not make as much sense to me.  It should only have the on/off characteristic - I don't know why it also allows the single/double/long options.  Those are stateless, not stateful constructs.  If you did have a service that supported both, Apple would not have needed to create separate stateful and stateless versions. 

All that said, there is limited Apple docs on this so who knows what they really expect.

**Comment by HomeSpan** [comment]
As an aside, note that you can add new services and characteristics directly from within a sketch using the CUSTOM macros.  No need to make changes to the source code.  The Reference API provides details and examples of how to do this.

**Comment by frankonski** [comment]
So for a programmable switch service, when you say 

> The user controls the button from the accessory,

This can only be a physical accessory, correct? It can't be a `SpanAccessory` with a `Service::Switch` service? At least, I tried and that didn't work.

I ended up with an ugly workaround to what I need to do. I create a new `SpanAccessory` with this `MyStatefulSwitch` class:
```
struct MyStatefulSwitch : Service::Switch {

  
  SpanCharacteristic *status;       // Swictch status, On of OFf
  unsigned long pressStartTime = 0; // Used to see how long a press to turn on will last
  
  MyStatefulSwitch() : Service::Switch(){

    status=new Characteristic::On();
        
  }

  boolean update(){
    // Receiving an update to turn off from the app should always be honored.
    if (!status->getNewVal()) {
      Serial.printf("Turning off on purpose\n");
      pressStartTime = 0;
  
    // Received an update to turn on the switch
    } else {
      unsigned long timeNow = millis();

      // Check if user is pressing for at least 2 seconds (or multi-tap for 2 seconds)
      if (pressStartTime > 0 && pressStartTime + 2000 < timeNow) {
        Serial.printf("Now on on purpose\n");
        pressStartTime = 0;
      } else {
        if (pressStartTime == 0) pressStartTime = timeNow;
        Serial.printf("Switching back off - pressStartTime: %lu - millis(): %lu\n", pressStartTime, timeNow);
        return false;
      }
    }

    return true;
  
  } // update

  void loop(){

    // This handles the case where a hold of the On switch was cancelled. The switch would have been switched back off
    // for at least 3 seconds.
    if(!status->getVal() && pressStartTime > 0 && pressStartTime + 3000 < millis()) {
        Serial.printf("Resetting hold time\n");
        pressStartTime = 0;
    }
    
  }
  
};
```

It kinda does what I need, which is turn & stay on only when pressed for 2 seconds, and always turn off when asked.

**Comment by frankonski** [comment]
I found this quote somewhere else that says differently what you said above:
> Apple wants hooks to set up their own automations as opposed to providing an interface to emit events that are handled elsewhere. Home app doesn't provide a programming interface or a UI to directly [create push / hold buttons]

After experimenting a bit more, I got to a point where both stateless and stateful switches in Eve would actually show a button, but just a toggle one, not one that could be pressed and hold. And the actions that can be defined on the stateless one don’t react on toggling the button/switch.

Meanwhile, the Home app wouldn’t show that toggle button for the stateless switch, and would continue reporting “Not supported” for the stateful one.

So I guess I hit a hard limitation of Homekit here and fine tune my ugly workaround above..

Feel free to close that issue.

**Comment by HomeSpan** [comment]
Before closing out, I just want to confirm that the StatelessProgrammableSwitch Service, when used with the ProgrammableSwitchEvent Characteristic does work exactly as expected as per Tutorial Example 16.  When you pair, you get a "programmable" button in the Home App that lets you define actions for Short/Long/Double presses, in accordance with Apple's original HAP-R2 spec, and as described in the comment section of Example 16.

What does not work is the so-called StatefulProgrammableSwitch Service, which is not defined in HAP-R2 (nor in HomeSpan), but seems to be present in some of the Apple swift docs.   Unlike the StatelessProgrammableSwitch Service, the StatefulProgrammableSwitch Service shows up as Not Supported in the Home App.

**Comment by frankonski** [comment]
> When you pair, you get a "programmable" button in the Home App that lets you define actions for Short/Long/Double presses, in accordance with Apple's original HAP-R2 spec, and as described in the comment section of Example 16.

Yes.

I kept playing around and ran into some nice (?) behavior.

First, define an accessory with a normal `Service::Switch()`. Easy.
2nd, add the missing `ProgrammableSwitchOutputState` characteristic in `Characteristics.h`
```
  HAPCHAR( ProgrammableSwitchOutputState, 74, PR+PW+EV, UINT8, false );
```
3rd, add this newly added added characteristic to the `DEV_ProgButton.h` example in its constructor
```
new Characteristic::ProgrammableSwitchOutputState();
```
Run. In Home app, nothing unusual about the Stateless Programmable Switch accessory. In Eve, that same accessory now has a off/on (0/1) toggle button now displayed.
Add an overridden `update()` method and we can see that toggling this button calls the `update()` method.

Where it gets interesting is when the permissions of the `ProgrammableSwitchEvent` are changed to enable `write`:
```
//  HAPCHAR( ProgrammableSwitchEvent, 73, PR+EV+NV, UINT8, true );
  HAPCHAR( ProgrammableSwitchEvent, 73, PR+PW+EV, UINT8, true );
```
If the single-press event of the stateless programmable switch is configured for a Shortcut that controls the Switch initially created, setting this Write permission actually controls that switch. If the Write permission is not enabled, the Switch doesn't change state.

**Comment by frankonski** [comment]
.. not quite. Can't reproduce. I will upload a sketch once I get it working again.

**Comment by frankonski** [comment]
There it is. In Eve, this will show a toggle button. Hope app won't show it.
```
struct DEV_ProgButton : Service::StatelessProgrammableSwitch {       // Stateless Programmable Switch
 
  SpanCharacteristic *switchEvent;                  // reference to the ProgrammableSwitchEvent Characteristic
  SpanCharacteristic *outState;
  boolean triggerEvent = false;
  
  DEV_ProgButton() : Service::StatelessProgrammableSwitch(){

    SpanButton *button = new SpanButton(0, 2000U, 5U, 200U, &dummy_not_used);
    
    switchEvent=new Characteristic::ProgrammableSwitchEvent();  // Programmable Switch Event Characteristic (will be set to SINGLE, DOUBLE or LONG press)                
      new Characteristic::Name("My stateless switch");
    
    switchEvent->setValidValues(2, SpanButton::SINGLE, SpanButton::DOUBLE);
    outState = new Characteristic::ProgrammableSwitchOutputState();    
  }

  static boolean dummy_not_used(int arg) {
    return false;
  }

  boolean update() override {
    triggerEvent = true;
    return true;
  }

  void loop() override {
    // By setting a new value to switchEvent, this will trigger the configured event in the
    // app for a single press, double press, or long press.
    if (triggerEvent) {
      switchEvent->setVal(outState->getVal() == 0 ? SpanButton::SINGLE : SpanButton::DOUBLE);
      triggerEvent = false;
    }
  }
};
```
But nevertheless, I went using a different approach and created a "tap-trice-within-3-seconds switch" to turn on which fits my needs:
```
struct MyStatefulSwitch : Service::Switch {

  
  SpanCharacteristic *status;       // Swictch status, On of OFf
  unsigned long pressStartTime = 0; // Used to see how long a press to turn on will last
  uint8_t tapCount = 0;
  
  MyStatefulSwitch() : Service::Switch(){
    status=new Characteristic::On();        
  }

  boolean update(){

    // Receiving an update to turn off from the app should always be honored.
    if (!status->getNewVal()) {
      Serial.printf("Turning off on purpose\n");
      pressStartTime = 0;
      tapCount = 0;
      return true;
    // Received an update to turn on the switch
    } else {
      unsigned long timeNow = millis();

      tapCount++;

      if (tapCount == 1) {
        pressStartTime = timeNow;
        Serial.printf("First tap\n");
      } else if (timeNow - pressStartTime < 3000) {
        if (tapCount == 3) {
          Serial.printf("Now on on purpose\n");
          return true;    
        } else {
          Serial.printf("Not yet...\n");
        }
      } else {
        tapCount = 1;
        pressStartTime = timeNow;
        Serial.printf("Restarting at 1\n");
      }
    }

    return false;
  } // update

  void loop(){
    // This handles the case where a hold of the On switch was cancelled. The switch would have been switched back off
    // for at least 3 seconds.
    if(!status->getVal() && pressStartTime > 0 && pressStartTime + 3000 < millis()) {
        Serial.printf("Resetting hold time\n");
        pressStartTime = 0;
    } 
  }
};
```

**Comment by HomeSpan** [comment]
Can this one be closed?

**Comment by frankonski** [comment]
yeah…
