### ISSUE TITLE
Apple Home left device turned on after device reconnect

### ISSUE THREAD

**Issue by loqimean** [HomeSpan/HomeSpan#889]
Hi there. I have two questions and hope you'll help me. So, there it is:
1. When I turn on device, it's reached by Apple Home app, so, when I touch my touch-button, the state of button isn't updated in the app, until I press button in the app (app I mean Apple Home app), so, after that the touch on a touch-button updates the status in the app. Why? How I can fix that?
2. If I left turned on device state in app, then restart HomeSpan accessory, so, default state is off, but in the Apple Home app state after reconnecting will be the same as it was before. I guess it's remembering feature, so, how I can fix it?

**Comment by HomeSpan** [comment]
Can you confirm you using a HomeKit Hub such as a HomePod or Apple TV?

**Comment by loqimean** [comment]
nope, I don't use it

**Comment by loqimean** [comment]
what about the second case I did remembering the state of device

**Comment by HomeSpan** [comment]
A noted on the main HomeSpan page, you must use a Home Hub to reliably use HomeSpan (or really any HomeKit device).  If you don't then the shortly after you close the Home App your HomeKit devices will disconnect and not reconnect again until you operate it again with the Home App.   Apple no longer supports proper operation of HomeKit devices without the use of a Home Hub.  This does not mean that under some circumstances some things may work some times.  But most things won't work as expected (and this can change at any time as Apple updates the HomeKit back end quite often).
