### ISSUE TITLE
QR Code Connection not working

### ISSUE THREAD

**Issue by VirtualGentlemen** [HomeSpan/HomeSpan#89]
Hello,
I'm trying to connect to the HomeSpan via the QR Code, but I am having some issues:

I'm using a [ESP-32 from AzDelivery](https://www.az-delivery.de/en/products/esp32-developmentboard).
Arduino ESP32 Board Library: ESP32 v1.0.6
HomeSpan: v1.2.1

I upload any example sketch using default settings except Core Debug Level set to "Verbose".
Set a Code Via S Command (example: S 01201012)
Copy the Payload and create a QR Code from it.
Scanning the QR Code with the Home App opens the accessory adding page. When confirming and trying to add it times out after a while. There are no log messages from the ESP32 attempting a Pairing process.

However when booting I get these Errors:

> [I][WiFiClient.cpp:517] connected(): Unexpected: RES: -1, ERR: 9
[E][WiFiClient.cpp:463] available(): fail on fd 0, errno: 9, "Bad file number"
[I][WiFiClient.cpp:517] connected(): Unexpected: RES: -1, ERR: 9
[E][WiFiClient.cpp:463] available(): fail on fd 0, errno: 9, "Bad file number"
[I][WiFiClient.cpp:517] connected(): Unexpected: RES: -1, ERR: 9
[E][WiFiClient.cpp:463] available(): fail on fd 0, errno: 9, "Bad file number"
[I][WiFiClient.cpp:517] connected(): Unexpected: RES: -1, ERR: 9
[E][WiFiClient.cpp:463] available(): fail on fd 0, errno: 9, "Bad file number"
[I][WiFiClient.cpp:517] connected(): Unexpected: RES: -1, ERR: 9
[E][WiFiClient.cpp:463] available(): fail on fd 0, errno: 9, "Bad file number"
[I][WiFiClient.cpp:517] connected(): Unexpected: RES: -1, ERR: 9
[E][WiFiClient.cpp:463] available(): fail on fd 0, errno: 9, "Bad file number"
[I][WiFiClient.cpp:517] connected(): Unexpected: RES: -1, ERR: 9
[E][WiFiClient.cpp:463] available(): fail on fd 0, errno: 9, "Bad file number"
[I][WiFiClient.cpp:517] connected(): Unexpected: RES: -1, ERR: 9
[E][WiFiClient.cpp:463] available(): fail on fd 0, errno: 9, "Bad file number"

I'm not sure if they are responsible for the non working QR Pairing.
Can someone help?

**Comment by VirtualGentlemen** [comment]
For Clarification: I am assuming via the QR code, the iPhone will send the ESP32 the Wifi Credentials and then connect to it. Is that not the case? 
When adding wifi credentials, the QR code works. However, that adds a new step to the pairing process that i want to avoid.

**Comment by HomeSpan** [comment]
Thanks for the clarification.  Unfortunately, the QR code can only be used for pairing, not for transmitting WiFi credentials, so the two-step process is required.  There are mechanisms to to use a QR code for both, but this is only available in the commercial MiFi implementation of HomeKit, not the HAP-R2 non-commercial version used by HomeSpan.

**Comment by VirtualGentlemen** [comment]
I looked it up on the official esp-homekit-sdk and found the same result - makes me sad this is only avaiable for the MiFi programm.
The Strange Wifi Erroros persist, but I will ignore them for now.
