### ISSUE TITLE
Out of compliance error.

### ISSUE THREAD

**Issue by maltortan** [HomeSpan/HomeSpan#890]
I am a new in this project. I am just trying with some relays. 
The exact code worked a month ago, re-flashed another esp32 and suddenly apple homekit could not add accessory. Stating "out of compliance error".

#include "HomeSpan.h" 

struct RelayAccessory : Service::AccessoryInformation {

  int relayPin;
  SpanCharacteristic *power; // characteristic to control relay

  RelayAccessory(int pin, const char *name) : relayPin(pin) {
    Serial.println("Creating RelayAccessory");
    new Characteristic::Name(name); // accessory name
    power = new Characteristic::On(); // On/Off characteristic

    pinMode(relayPin, OUTPUT);
    digitalWrite(relayPin, LOW); // Ensure relay is off initially
    Serial.println("RelayAccessory created");
  }

  boolean update() {
    // Set relay state based on the characteristic value
    Serial.print("Updating relay state to: ");
    Serial.println(power->getNewVal());
    digitalWrite(relayPin, power->getNewVal() ? HIGH : LOW);
    return true;
  }
};

void setup() {

  Serial.begin(115200);

     homeSpan.setWifiCredentials("***","*****");
     homeSpan.setPairingCode("98491999");
  homeSpan.begin(Category::Bridges,"Irrumabo");
  new SpanAccessory();
  new Service::AccessoryInformation();
  new RelayAccessory(15, "Relay 1");  /

  new SpanAccessory();
  new Service::AccessoryInformation();
  new RelayAccessory(2, "Relay 2");
    
} 

void loop(){
  
  homeSpan.poll();
  
}

**Comment by HomeSpan** [comment]
Your code above does not seem right.  You have RelayAccessory defined as `struct RelayAccessory : Service::AccessoryInformation`, as opposed to something light a Lightbulb or Switch.

**Comment by maltortan** [comment]
Thank You for the very quick Response. I worked with accessory switch. And it worked.
