### ISSUE TITLE
It's a weird error when initializing `AsyncWebServer` if #include "HomeSpan.h"

### ISSUE THREAD

**Issue by markgravity** [HomeSpan/HomeSpan#898]
Here is my code

```
#include <ESPAsyncWebServer.h>
#include "HomeSpan.h"

AsyncWebServer server(80); // Or any other port

void setup() {}
void loop() {}
```

After uploading it successfully to my ESP32 C3 Super Mini, I got this error
```
00:07:28.439 -> Build:Feb  7 2021
00:07:28.439 -> rst:0x3 (RTC_SW_SYS_RST),boot:0xf (SPI_FAST_FLASH_BOOT)
00:07:28.439 -> Saved PC:0x403cf94c
00:07:28.439 -> SPIWP:0xee
00:07:28.439 -> mode:DIO, clock div:1
00:07:28.439 -> load:0x3fcd5810,len:0x438
00:07:28.439 -> load:0x403cc710,len:0x90c
00:07:28.439 -> load:0x403ce710,len:0x2624
00:07:28.439 -> entry 0x403cc710
```

**Comment by HomeSpan** [comment]
Sorry, I'm unfamiliar with the details of the ESPAsyncWebServer and its use is not specifically supported in HomeSpan.  The Async server may or may not work --- I believe others may have used it successfully with HomeSpan, but I've not tried.

Though I'm not planning to adding support for Async compatibility (to the extent it can be done), HomeSpan is nevertheless fully compatible with the Arduino-ESP32 basic WebServer library --- there are some examples in the HomeSpan Tutorials that demonstrate how this works.

**Comment by markgravity** [comment]
Thank you. I will check the examples 🙏
