### ISSUE TITLE
Pixel definition for PixelType::BRG is incorrect

### ISSUE THREAD

**Issue by MacWoodworking** [HomeSpan/HomeSpan#905]
The colors are incorrect when using PixelType::BRG are incorrect, currently defined as:

pixelType_t BRG={23,15,31,0};

Should be 

pixelType_t BRG={15,31,23,0};

**Comment by HomeSpan** [comment]
I think you may be correct -- I'll review and check all the mappings.

**Comment by HomeSpan** [comment]
The mapping logic has been reworked as part of HomeSpan 2.0.0-rc.1 (just released).

**Comment by HomeSpan** [comment]
Will close for now - please feel free to re-open if the issue persists after trying out the new release.
