### ISSUE TITLE
Custom acctions on accessory setting

### ISSUE THREAD

**Issue by mohammadrezaghane** [HomeSpan/HomeSpan#908]
Hi, first of all, thank you for your great work. I have a question: I noticed toggle buttons in the accessory settings section of some accessories. How can I implement similar buttons?

**Comment by HomeSpan** [comment]
Can you be more specific about exactly what you'd like to do?  Nite toggle buttons are supported in HomeSpan and fully described in the API.

**Comment by mohammadrezaghane** [comment]
I have logi doorbell in my home app , in bell accessory setting I have toogle buttons that can control status light and night vision light off or on 
![Untitled](https://github.com/user-attachments/assets/9d95243d-d8f1-46a4-9246-567b6a728dce)

**Comment by mohammadrezaghane** [comment]
Is there anyway to do that?
