### ISSUE TITLE
1.9.1 build faild

### ISSUE THREAD

**Issue by averyhome** [HomeSpan/HomeSpan#916]
Hi 
my arudino esp32 manager is 2.x
and my home span is 1.9.1
but build faild 
PLATFORM: Espressif 32 (6.6.0) > Espressif ESP32-C3-DevKitM-1
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-builtin, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 3.20014.231204 (2.0.14) 
 - tool-esptoolpy @ 1.40501.0 (4.5.1) 
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 35 compatible libraries
Scanning dependencies...
Dependency Graph
|-- FastLED @ 3.7.6
|-- HomeSpan @ 1.9.1
Building in release mode
The log info:
.pio/libdeps/esp32-c3-devkitm-1/HomeSpan/src/HAP.cpp:30:10: fatal error: ESPmDNS.h: No such file or directory
.pio/libdeps/esp32-c3-devkitm-1/HomeSpan/src/Network.cpp:30:10: fatal error: DNSServer.h: No such file or directory
*** [.pio/build/esp32-c3-devkitm-1/lib7c3/HomeSpan/HAP.cpp.o] Error 1
*** [.pio/build/esp32-c3-devkitm-1/lib7c3/HomeSpan/HomeSpan.cpp.o] Error 1
*** [.pio/build/esp32-c3-devkitm-1/lib7c3/HomeSpan/Network.cpp.o] Error 1
Indexing .pio/build/esp32-c3-devkitm-1/libb45/libSPI.a
In file included from .pio/libdeps/esp32-c3-devkitm-1/HomeSpan/src/Utils.cpp:29:
.pio/libdeps/esp32-c3-devkitm-1/HomeSpan/src/HomeSpan.h:40:10: fatal error: ArduinoOTA.h: No such file or directory

remove HomeSpan @ 1.9.1 the project build ok
 can you tell me how to do it !
![Uploading 截屏2024-09-14 11.55.05.png…]()

**Comment by frankonski** [comment]
Strange. See the bottom comment of #897, and check if you can apply the same workaround. I didn’t get that error with HS 1.9.1, only 1.10.0.

**Comment by averyhome** [comment]
Hello, I encountered the same situation as him, but his solution didn't work for me. I used FastLED in my project, and I'm not sure if it had any impact. Removing FastLED would make it compile successfully, which is very strange.

**Comment by averyhome** [comment]
Strange, i write like this, and It build success
i do not sure  will it do new problem

lib_deps = 
	Update
	ArduinoOTA
	DNSServer
	WiFi
	ESPmDNS
	fastled/FastLED@^3.7.6
	h2zero/NimBLE-Arduino@^1.4.2
	bblanchon/ArduinoJson@^7.1.0
	homespan/HomeSpan@^1.9.1

**Comment by HomeSpan** [comment]
Any more on this, or can it be closed?

**Comment by frankonski** [comment]
it would be nice to nail down a solution that works for all…

**Comment by HomeSpan** [comment]
To solve this I need to start using PIO to debug, but lots of other priorities in the short term.

**Comment by averyhome** [comment]
Hi, tahnk you , and you can close it, it build ok now
