### ISSUE TITLE
NFC_SETUP: Didn't find PN53x board

### ISSUE THREAD

**Issue by RedJohn14** [HomeSpan/HomeSpan#919]
Hello!

I used some ESP32-S and wire everything correct. NFC reader LED is on. But everytime I started the ESP get this error message:

NFC_SETUP: Didn't find PN53x board

Any ideas what my mistake is? What i can do to run this setup correctly :-(

See also my settings:

![279D090D-5856-4AA7-A995-794A55C882BB](https://github.com/user-attachments/assets/28612511-c3ec-4b42-b1e4-0fda9b2e9767)
![710A571A-98A8-4107-9C27-F352764CB8EC_4_5005_c](https://github.com/user-attachments/assets/c2ec73e2-1cb7-46fb-94f1-ce4ea9a2138b)
![AF70F670-433E-4321-AB71-5AA3221D0783](https://github.com/user-attachments/assets/742d1b0f-0ca8-4133-8867-9c0ed61f2dc4)

**Comment by shreyashparajuli** [comment]
Hey, did you ever find any solution to it?

**Comment by TheoL0** [comment]
Hi, I work on a project and I need the PN532 and not the MFRC522 but it's not working too, I can scan I2C adress so it's not the chip but any ideas ??
