### ISSUE TITLE
Problem with QR Code Payload

### ISSUE THREAD

**Issue by felix6262** [HomeSpan/HomeSpan#920]
//Homespan: Basics
  homeSpan.setControlPin(ControlButton,PushButton::TRIGGER_ON_HIGH);     
  homeSpan.setCommandTimeout(180);           
  homeSpan.setStatusPin(GreenLED);           
  homeSpan.setStatusAutoOff(300);            
  homeSpan.setPairingCode("52476439");      
  homeSpan.setSketchVersion("1.0.0");       
  homeSpan.setQRID("07A8");                  

  //Homespan: Access Point
  homeSpan.setApSSID("HomeSpan-Setup-Ventilation"); 
  homeSpan.setApPassword("homespan-01");               
  homeSpan.setApTimeout(600);                           
  homeSpan.enableAutoStartAP();                         
                          
  //Homespan: Starten als Bridge
  homeSpan.begin(Category::Bridges, "Keller Bridge", "HomeSpanDIY", "HomeSpan-BasementVentilation"); 
  
  
  My homeSpan code looks like this. This Page https://github.com/HomeSpan/HomeSpan/blob/master/docs/QRCodes.md says the monitor should automaticly show me the payload for that "X-HM://". But nothing shows up, when i reupload the code with diffrent codes.

**Comment by HomeSpan** [comment]
The QR code is only shown in the Serial Monitor when you change the Pairing Setup Code interactively using the 'S' command from the CLI.  It is not shown if you change the Setup Code programmatically from within a sketch.

Note you can also create your own QR code by using the HomeKit Simulator App as described in QRCodes.md and simply enter your Pairing Setup Code, QRID, and Category info (I find this the easiest for my own projects).

**Comment by felix6262** [comment]
i used this: https://github.com/HomeSpan/HomeSpan/blob/master/docs/QRCodes.md#setup-payload-algorithm-optional-reading

AAnd asked chat gpt to get a X-HM:/... but didnt realy worked. Always says, device already there. 

#include <stdio.h>
#include <stdint.h>
#include <string.h>

// Base36 Tabelle (Index 0 bis 35 für Ziffern und Buchstaben)
static const char base36_table[] = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";

// Funktion zur Konvertierung einer Zahl in eine Base-36-Zeichenkette
void to_base36(uint64_t value, char *output, int length) {
    output[length] = '\0';  // Null-Terminierung
    for (int i = length - 1; i >= 0; i--) {
        output[i] = base36_table[value % 36];
        value /= 36;
    }
}

// Funktion zur Generierung des HomeKit QR-Codes
void generate_homekit_qr_code(uint8_t category, uint8_t supportsBLTE, uint8_t supportsIP, uint8_t supportsNFC, uint32_t setupCode, const char* setupID, char* qrCode) {
    // Schritt 1: Version und Reserved Bits (immer 0)
    uint64_t payload = 0;

    // Schritt 2: Kategorie setzen (Bits 38-31)
    payload |= ((uint64_t)(category & 0xFF)) << 31;

    // Schritt 3: BLTE, IP, NFC Unterstützung setzen (Bits 29, 28, 27)
    payload |= ((uint64_t)(supportsBLTE ? 1 : 0)) << 29;
    payload |= ((uint64_t)(supportsIP ? 1 : 0)) << 28;
    payload |= ((uint64_t)(supportsNFC ? 1 : 0)) << 27;

    // Schritt 4: Setup-Code setzen (Bits 26-0) – Setup-Code auf 8-stellig begrenzen
    payload |= ((uint64_t)(setupCode % 100000000));

    // Schritt 5: Debug-Ausgabe (zur Kontrolle der Bit-Felder)
    printf("Payload (45-bit Wert): %llu\n", payload);  // Debugging-Information

    // Schritt 6: Umwandlung des Payload in Base-36 (9 Zeichen)
    char base36Payload[10];  // Platz für 9 Zeichen + Null-Terminator
    to_base36(payload, base36Payload, 9);

    // Schritt 7: Erstellen des finalen QR-Code-Strings im Format X-HM://<Base36-Payload><SetupID>
    sprintf(qrCode, "X-HM://%s%s", base36Payload, setupID);
}

int main() {
    // Spezifische Daten
    uint8_t category = 2;        // Kategorie: Bridge (2)
    uint8_t supportsBLTE = 0;    // Unterstützt kein BLTE
    uint8_t supportsIP = 1;      // Unterstützt IP
    uint8_t supportsNFC = 0;     // Unterstützt kein NFC
    uint32_t setupCode = 52466439;  // Setup-Code (8-stellig: 524-66-439)
    const char* setupID = "07Z8";   // Setup-ID (4 Zeichen)

    // Speicher für den QR-Code
    char qrCode[64];

    // Generiere den HomeKit-QR-Code
    generate_homekit_qr_code(category, supportsBLTE, supportsIP, supportsNFC, setupCode, setupID, qrCode);

    // Gib den QR-Code aus
    printf("Generated HomeKit QR Code: %s\n", qrCode);

    return 0;
}

**Comment by HomeSpan** [comment]
As noted, HomeSpan provides a direct method for producing the full QR Code.  You need to type 'S' into the CLI and set the Setup Pairing Code interactively.  HomeSpan then displays the QR Code on the Serial Monitor. You can also use Apple's HomeKit Simulator and input the data to produce the actual QR Graphic directly.  You're welcome to try to write your own code to do this, but that's outside the scope of support for this project.

Also, remember that once you pair a device, it can't be paired again unless you first unpair it.  So if your device is already paired, you can't use theQR Code for anything.  You need to unpair the device first.
