### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by lukasa1993** [HomeSpan/HomeSpan#927]
https://gist.github.com/lukasa1993/9ea58b3bec015a2b8ea84c39a370ffe1

i am using thermostat sample with few modifications it runs out memory fast

**Comment by HomeSpan** [comment]
There's a lot of non-HomeSpan code in your sketch - to debug, remove everything else so that you can see if there is in fact a memory leak from within HomeSpan itself.  If so, I can try to address.  If not, then it is something about the extra code you added (Async, Timers, etc...)

**Comment by lukasa1993** [comment]
ill strip it off but all these code is already used in old homespan so thought it was save will remove anyway

**Comment by lukasa1993** [comment]
https://gist.github.com/lukasa1993/5c3e99995cc788b763653a306ca4abec

this is stripped version still drops memory rapidly i think i  removed everything

**Comment by lukasa1993** [comment]
`delete[] sensor;` might have been fix on my end

**Comment by lukasa1993** [comment]
@HomeSpan btw how i can only support heating and not show cooling?

**Comment by HomeSpan** [comment]
See `SpanCharacteristic *setValidValues(int n, [int v1, int v2 ...])`

**Comment by HomeSpan** [comment]
what do you mean by persist values?

**Comment by lukasa1993** [comment]
like temperature measurement or target temperature to be same after restart

**Comment by HomeSpan** [comment]
The values of any Characteristic are automatically saved if you set the second parameter to "true" then you create the Characteristic.  See the API and examples for details.  HomeSpan does not save anything that is not a value tied to a Characteristic, though you can use the NVS directly to save stuff if needed.

**Comment by lukasa1993** [comment]
@HomeSpan it becomes unresponsive after i turn it off for few minutes and turn back on there is no issue in logs but in homekit its unresponsive how can i debuh this ?

**Comment by HomeSpan** [comment]
If I'm understanding correctly, you have no problem when the device, is on, but if you turn off and then back on it shows "No Response" in HomeKit.  Can you confirm that you can reach the device via Web Log to make sure it is indeed connecting back to WiFi.  Also, can you confirm you are running with a Home Hub.

Note that your iPhone and every Home Hub MUST be on the same version of iOS.  If you upgraded your iPhone to iOS 18, make sure all your HomePods and Apple TV and also update to latest software.

Finally, check the Serial Monitor to make sure that you are not sending an out-of-range variable upon restart.  For example, the default range for Temperature is 0-100 Celsius.  If you send a Temp of -10 during start-up, the Home App will go "unresponsive".   The Serial Monitor will warn you whenever this occurs so you can double check there.

**Comment by lukasa1993** [comment]
logs are good, i am sending udp brodcast every 5 second so wifi i can confirm working, i have homepod as homehub which is also on ios 18, i noticed that after restart in about 5-10 minute it came back as responsive but initially it seems to be offline

**Comment by lukasa1993** [comment]
@HomeSpan cant seems to fix this one it doesn't respond in 5-10 anymore either after shutdowns http responds but in homekit its unresponsive

**Comment by HomeSpan** [comment]
Did this just start happening recently?

**Comment by lukasa1993** [comment]
this is only one on new build i have bunch on old one and all work fine

**Comment by HomeSpan** [comment]
Which builds work, which do not.  

Also, have you confirmed you are not running out of memory anymore once fixed?

Have you made sure the names of your devices are all different.  You can't duplicate a HomeSpan device name or the Home App gets confused.  

May also want to try unpairing, type 'H' into Serial Monitor to refresh device ID and pair again.

**Comment by lukasa1993** [comment]
1.9.0 works have multiple deployments 

i have only this named new one no other names

i have repaid few times with E command 


one thing i noticed rebooting homehub also helps reconnect

**Comment by HomeSpan** [comment]
So, if you re-compile your sketch with 1.9.0 it works fine, but it does not if you compile with 1.9.1?  Assuming exact same sketch and same location of device in house?

**Comment by lukasa1993** [comment]
no no i am trying 2.0 with new sketch i just have other stuff on 1.9 which works

**Comment by HomeSpan** [comment]
Okay, but same question applies.  Do you get the same error if you compile the sketch that is giving you problems with an older build.    

I can't tell from what you have provided whether there is an issue with 2.0 orbits something else.  

The fact that you have other devices working with 1.9 does not tell us anything.  Need to recompile the exact sketch that is giving you problems with 2.0 but use 1.9 and the device needs to not be moved to ensure it will have the same WiFi signal, which is often the cause of many problems.
