### ISSUE TITLE
*** ERROR:  Bad GET request - URL not found

### ISSUE THREAD

**Issue by ashrafatshy7** [HomeSpan/HomeSpan#928]
Which URL was not found?
I cannot add the accessory to the homekit app.

WiFi Connected!  IP Address = 10.0.0.23

Starting MDNS...

HostName:      HomeSpan-7F86A7EF545F.local:80
Display Name:  BridgeLight
Model Name:    HomeSpan-ESP32
Setup ID:      HSPN

Starting HAP Server on port 80...

*** ERROR:  Bad GET request - URL not found

**Comment by frankonski** [comment]
I wanted to submit a PR about ignoring all `GET /favicon.ico` for some time. You will see this error everytime you hit your weblog URL, among any other legitimate unhandled url.

**Comment by ashrafatshy7** [comment]
why I cannot find the bridge in the homekit app?
I'm using homespan v1.9.1



#include "HomeSpan.h"
#include "SwitchControl.h"

void setup() {
   Serial.begin(115200);

  homeSpan.setWifiCredentials("XX", "XXXXX");
  homeSpan.setWifiCallback([](){homeSpan.setPairingCode("75698521");});
  homeSpan.begin(Category::Bridges,"BridgeLight");

  

  new SpanAccessory();                          
    new Service::AccessoryInformation();
      new Characteristic::Identify(); 

  new SpanAccessory();
    new Service::AccessoryInformation();
      new Characteristic::Identify();
      new Characteristic::Name("LED1"); 
    new SwitchControl(2, 26);

}



void loop() {
  
  homeSpan.poll();
}

**Comment by HomeSpan** [comment]
Seems like you got this resolved - what was the solution (And what was the problem - were you not able to pair with HomeKit, or something else?)

**Comment by ashrafatshy7** [comment]
That wasn't an issue, please check issue #929
