### ISSUE TITLE
Problem Connecting to Wi-Fi

### ISSUE THREAD

**Issue by ashrafatshy7** [HomeSpan/HomeSpan#929]
I'm using HomeSpan v2.0.0-rc.1 with an ESP32C6.

When attempting to connect to Wi-Fi, I get the following output:

Trying to connect to home.  Waiting 1 sec...
ESP-ROM:esp32c6-20220919
Build:Sep 19 2022
rst:0x8 (TG1_WDT_HPSYS),boot:0xc (SPI_FAST_FLASH_BOOT)
Saved PC:0x40000002
SPIWP:0xee
mode:DIO, clock div:2
load:0x40875720,len:0x109c
load:0x4086c110,len:0xc40
load:0x4086e610,len:0x2da8
entry 0x4086c110

and stuck. 
sometimes the esp32 c6 restarts and appears the same output.

![image](https://github.com/user-attachments/assets/dc137095-a537-414d-84d8-bad15e3dc8e5)

also does not work when trying to type the SSID and password manually by pressing W.

![image](https://github.com/user-attachments/assets/0fdcbcaf-914b-4304-9a7a-9a3c9aad70a9)

**Comment by HomeSpan** [comment]
Does this occur when running with an unmodified version of tutorial example 1?

**Comment by ashrafatshy7** [comment]
Example 1 executed successfully. However, after adding homeSpan.setWifiCredentials("ssid", "password"); to the code, I reencountered the same issue.

**Comment by HomeSpan** [comment]
I cannot reproduce this --- I'm running on an ESP32-C6 with same config parameters.   Do you have any special characters in your WiFi credentials?  Also, what version of the Arduino-ESP32 Board Manager are you using?

**Comment by ashrafatshy7** [comment]
I do not have characters in my WiFi credentials. 
I’m using this board: https://s.click.aliexpress.com/e/_oExlGlR

board manager: esp32 by Espressif Systems V3.1.0-RC1

homespn V2.0.0-rc. 1

**Comment by HomeSpan** [comment]
Board Manager 3.1.0-RC1 is a pre-release so may have bugs.  I generally don't test any new Board Managers until they are in full production.  Do you have this problem if you use a production version of the Board Manager (latest is 3.0.5).

**Comment by ashrafatshy7** [comment]
I utilized Board V3.0.5, and it functioned perfectly. Thank you!
