### ISSUE TITLE
Homespan keeps disconnecting

### ISSUE THREAD

**Issue by chrmuh** [HomeSpan/HomeSpan#935]
Hi,

I have the same problem as some others here, my homespan board (Olimex ESP32-POE-ISO) is often disconnectingfrom the the wifi. But if I press a lamp on the homekit app it connects again and turns on the lamp but after a few seconds it disconnects.

I found in some discussions that changing the "AirTime Fairness" of the router helps to avoid this problem. Is this really the best solution?
Is using Ethernet/LAN a better idea to avoid that?

Or do I need a homekit control center (like an Apple TV or Home Pod) in my home in order to avoid such disconnecting problems?
Or is for test reasons an iPhone enough?

Best wishes

**Comment by HomeSpan** [comment]
If you don't have a HomeHub the Home App will not stay connected to any HomeKit device, but will only reconnect when you try to operate the device once again from the Home App.  Based on what you described, I think that is the issue.

**Comment by chrmuh** [comment]
Thanks for your fast answer. Is there also the possibility to wake up the connection bevor an update is done by the esp?
because ist automatically updates the connection if I do someting on the iPhone.

I do not want to buy a Apple TV right away, because I am just testing all the functions. To start implementing in a year or so.

**Comment by HomeSpan** [comment]
No, HomeKit devices cannot initiate a connection to the Home App.  The connection is not established and controlled by the Home App only or a Home Hub.

**Comment by HomeSpan** [comment]
Sorry, above should say connection is ONLY established by Home App or Home Hub.

**Comment by chrmuh** [comment]
Thanks for your help. But I am not quite sure about that. I have run some tests now. It seams that your example program 1 is running without any disconnecting. But when I try to use update functions (to send temperature results or Button state) it keeps disconnecting.
Further when I use the hotspot of my PC it disconnects faster than when I use my home Wifi. 

So I rather think that it has to do something with the airtime fairness of the routers, as it was mentioned in another post.

I will try to add ethernet connection and will update on that.
Do you have any more ideas?

Do I only see the Log outputs of Disconnected and Connected, when I use the update function and therefore I do not see it in the first few exames?

**Comment by HomeSpan** [comment]
As noted above, without a Home Hub, it's not really possible to diagnose the issues.  You should NOT be getting any WiFi disconnects - that would be a separate problem unrelated to having a Home Hub.

But HomeSpan disconnecting from the Home App is controlled solely by the Home App.  It keeps the connection open until it decides to close it.  A Home Hub keeps the connection open all the time.  Without a Home Hub, the iPhone closes the connection after some unknown and possibly random period of idle time - Apple provides no transparency to this process.

**Comment by chrmuh** [comment]
Oh well ok thanks for saving me time! I am thinking of programming a automation on the phone that calls the esp every 30 sec as long as I am testing. Or is this making the phone slow?

But apart from that do you think it is also possible to use a third party hub? Apple writes this on their website but I do not find any good youtube videos where someone has done that. I am thinking of https://m.alza.at/moes-matter-zigbee-hub-d12316470.htm?kampan=adw1_alza_pla_all_akce_alza-days_m_9062727_Moes2402&gbraid=0AAAAAD2xsm5PLhqbmErfslFuBR2AmYhn0&gclid=CjwKCAjwjsi4BhB5EiwAFAL0YMhaPbXcdLtm9RxRpE7i_oXzPL0zSKTh8MJ8H5-AsJkyRtc3L04YTxoCN6EQAvD_BwE

But I am not sure if than the home app is working or if I need the app of the hub. Do you have any idea?

**Comment by HomeSpan** [comment]
There are lots of types of hubs for different purposes.  For native HomeKit devices Apple requires an Apple TV generation 4 or an Apple Home Pod.  Those are the only choices.

**Comment by HomeSpan** [comment]
Anything more on this, or can I close?

**Comment by kangear** [comment]
Hi, I have a same problem, I used esp32-c3 as HomeSpan device, HomePod mini as Home Hub, If I reboot esp32-c3, Home Hub won't reconnect esp32-c3 for long time. Home Hub will reconnect esp32-c3 when I reopen Home App or let HomePod do some control. I want to they reconncet immediately after esp32-c3 rebooting.

**Comment by HomeSpan** [comment]
What exact Services are you running on the HomeSpan device?

**Comment by kangear** [comment]
Even fake temp.

```cpp
#include "HomeSpan.h"

// A standalone Temperature sensor
struct DEV_TempSensor : Service::TemperatureSensor {     

  // reference to the Current Temperature Characteristic
  SpanCharacteristic *temp; 
  int old = 20;                                      

  // constructor() method
  DEV_TempSensor() : Service::TemperatureSensor() {      

    // start dhttemp Object
    // dht.begin();                                    

    // instantiate the Current Temperature Characteristic
    temp = new Characteristic::CurrentTemperature(-10.0);     
    // expand the range from the HAP default of 0-100 to -50 to 100 to allow for negative temperatures
    temp->setRange(-50, 100);                                 

    // initialization message
    Serial.print("Configuring Temperature Sensor");           
    Serial.print("\n");

  } // end constructor

  void loop() {

    // the temperature refreshes every 10 seconds by the elapsed time
    if (temp->timeVal() > 10000) {
      // read temperature from sensor dht22
      float temperature = 20;
      if (old == 20)
        temperature = 22;
      else
        temperature = 20;
      old = temperature;
      // if (isnan(temperature))
      //   return;
      // if ((temperature < TEMP_MIN) || (temperature > TEMP_MAX)) {
      //   temperature = 0;
      // }
      // set the new temperature; this generates an Event Notification and also resets the elapsed time
      temp->setVal(temperature);                            

      Serial.print("Temperature Update: ");
      Serial.print(temperature);
      Serial.print(" ; ");
      Serial.print("\n");

    }
  } // loop
};


void setup() {
 
  Serial.begin(115200);
  homeSpan.setLogLevel(2);

  homeSpan.begin(Category::Sensors,"HomeSpan Temp");

  new SpanAccessory();
    new Service::AccessoryInformation();
      new Characteristic::Identify(); 
      new Characteristic::Name("Temp Sensor");
    new DEV_TempSensor();   
  //  new Service::LockMechanism();
  //    new Characteristic::LockCurrentState();
  //    new Characteristic::LockTargetState();
      
} // end of setup()

//////////////////////////////////////

void loop(){
  
  homeSpan.poll();         // run HomeSpan!
  
} // end of loop()
```

I added some log in HomeSpan lib code, `hapServer->hasClient()` always be false, if I ask HomePod tell me temp, then I can see HomePod start connect esp32c3.

![image](https://github.com/user-attachments/assets/a0fa04db-925c-4eaa-afee-3e2673d16125)

**Comment by kangear** [comment]
![image](https://github.com/user-attachments/assets/f5e5b1d4-f71f-4eef-985d-6f3b36a6e5d7)
![image](https://github.com/user-attachments/assets/40965759-401a-438b-ad86-e792b083a44b)

**Comment by HomeSpan** [comment]
I'm not sure what problem you are seeing.   When a HomeKit device boots, it does not control whether HomeKit itself connects to it.  Your central HomeKit hub controls that.  It will only connect when it needs to.  For example, if you have a temp sensor, the first time HomeKit will connect is when you request something related to temperature, such as opening your Home App or asking Siri for the temp.    Once connected, HomeKit will generally keep the connection open, but it may close it from time to time.

**Comment by HomeSpan** [comment]
In contrast, if you set up a HomeKit automation that somehow used the temperature (maybe to give you a warning if it got too low) then your Home App and Home Hub would know it needed to monitor the temperature continuously, EVEN IF YOU NEVER ASK.  In that case, Home Kit will generally try to connect to a rebooted device right away so it can start receiving notifications.  

Same would be the case of alarm sensors, doorbells, etc.

**Comment by kangear** [comment]
Actually, you are right. It’s an automation problem. for my case I waited for more than five minutes, it never connect after rebooting, even this temp sensor as automation condition.

I knew this it’s not a HomSpan’s problem, I just want to know what’s wrong with it, maybe TCP keeplive timeout or router problem or My HomePod mini problem.

**Comment by HomeSpan** [comment]
Do you have your Home Pod configured as a Home Hub.  Also, one thing to note is that all devices need to be on the same iOS.  Need to make sure your phone and Home Pod are both on 18.1 OR 18.2, etc.

**Comment by kangear** [comment]
Yes, I do configure my HomePod as Home Hub, It work fine in the normal case. Now I just want to it work fine in the worst case such as route rebooting and esp32c3 rebooting. 

I also make sure the OS version, both them are 18.2, I think I need do more observe or try other router for testing. thank you. I feel that's not good for power off the board immediately, It would be better that esp32c3 take the initiativeclose TCP when check the power off, maybe I need give a capacitance to the board.

**Comment by HomeSpan** [comment]
Closing for now.   Please feel free to re-open if needed.
