### ISSUE TITLE
invalid hostname

### ISSUE THREAD

**Issue by eilidan** [HomeSpan/HomeSpan#936]
Hello Developer,

During the usage, I encountered a very strange issue. After compilation, the log shows an error: Error: Can't start MDNS due to invalid hostname 'HomeSpan-0B0C9931222A'. I have tried to find a solution. Even using homespan.sethostnamesuffix still results in this error. I've checked the condition if(strlen(hostName)>255 || hostName[0]=='-' || hostName[strlen(hostName)-1]=='-' || strlen(hostName)!=strlen(d) and all of these conditions are met. Could you please help me check where the problem might be? My development board is esp32c3, and I am using HomeSpan version 1.9.1.

Best regards,

Eilidan

**Comment by HomeSpan** [comment]
Can you try typing 'H' into the CLI to reset the host name and see what happens.

**Comment by eilidan** [comment]
> Can you try typing 'H' into the CLI to reset the host name and see what happens.

When I entered 'H', the microcontroller reset, but the issue still persists after connecting to WiFi.

**Comment by HomeSpan** [comment]
Does this occur if you run with a completely unmodified (no edits at all) Tutorial 1 sketch?

**Comment by eilidan** [comment]
> Does this occur if you run with a completely unmodified (no edits at all) Tutorial 1 sketch?

I haven't tried this method yet. I'll give it a shot later. Thank you for your response.

**Comment by eilidan** [comment]
> Does this occur if you run with a completely unmodified (no edits at all) Tutorial 1 sketch?

I tried using the code from Example 1 without making any modifications, but it still shows an invalid hostname.
