### ISSUE TITLE
Air Conditioners control

### ISSUE THREAD

**Issue by zuozhehao** [HomeSpan/HomeSpan#94]
I can't find the information about the air conditioners switch and mode control in the HAP specification non commercial version document. It's convenient for me to tell you how to obtain these two parameters.

Thank you.

**Comment by HomeSpan** [comment]
Sorry, I'm not sure I'm following.  Which HAP Service or Characteristic are you looking for?

**Comment by zuozhehao** [comment]
Thank you for your response.
I don't know how to get the status of the switch (on and off the air conditioner) sent by the Home App, and the mode (cooling, heating, wind speed) switch.

**Comment by huexpub** [comment]
heatcooler

**Comment by HomeSpan** [comment]
You found one of the printing errors in Apple's HAP manual.  The *HeaterCooler* Service (8.18) requires the *Target Heater Cooler State* Characteristic (9.111).  This Characteristic is listed on page 223 but it is only partially described.  The missing part is printed in a standalone table on the top of page 228.  This table looks like it is part of the Characteristic on the previous page, but it's actually the second part of the *Target Heater Cooler State* Characteristic used to determine if the device is set to Heat, Cool, or both.   This printing error also tripped me up when I first developed HomeSpan.

Also, as described on page 143, you can control the speed of the fan either with the *Rotation Speed* Characteristic, or by adding a separate *Fan* Service to the same Accessory.

Finally, as described on page 144, the *Heater Cooler* Service also requires the use of the *Active* Characteristic.  This is used to turn on/off the whole unit.

**Comment by zuozhehao** [comment]
Thank you.
