### ISSUE TITLE
Please tell me how to actually install gpio in Example 13. Thank you.

### ISSUE THREAD

**Issue by attacdc** [HomeSpan/HomeSpan#945]
Please tell me how to actually install gpio in Example 13. Thank you.

**Comment by HomeSpan** [comment]
Sorry, I don't understand what you are asking.

**Comment by attacdc** [comment]
> 抱歉，我不明白你在問什麼。

Please tell me how to actually install the GPIO 
pin numbers on the Garage Door.

**Comment by delingren** [comment]
Example 13 is not a functional physical garage door opener. Rather, it's an example demonstrating how a garage door opener would interact with HomeKit. You would need to implement the logic and electronics yourself. I did exactly that a while ago and you're welcome to take a look: https://github.com/delingren/homeautomation/tree/master/garage_door_opener. Feel free to reach out to me if I can help.
