### ISSUE TITLE
Not enough memory

### ISSUE THREAD

**Issue by Sidla** [HomeSpan/HomeSpan#946]
Hello, 

Im not even able to upload first example into my 4MB esp32, is that because of the new version 2.0 and required esp version library 3 and up?

Waht the solution, should I buy esp with more memory?

The first example error: 

`Sketch uses 1408901 bytes (107%) of program storage space. Maximum is 1310720 bytes.
Global variables use 60212 bytes (18%) of dynamic memory, leaving 267468 bytes for local variables. Maximum is 327680 bytes.
Sketch too big; see https://support.arduino.cc/hc/en-us/articles/360013825179 for tips on reducing it.
text section exceeds available space in board

Compilation error: text section exceeds available space in board`

**Comment by HomeSpan** [comment]
Please read through the README page.  It explains all of this.  You do not need to buy any memory - just need to configure your partitions correctly.
