### ISSUE TITLE
wrong status of unresponsive outlets 

### ISSUE THREAD

**Issue by thncode** [HomeSpan/HomeSpan#948]
I do have a number of outlets in use and some of them are not always active. Although I do let update() return false, it briefly reports in homekit "not reachable" but switches back then as like they are online - what could that be? 

Rgrds,
 Thomas

**Comment by HomeSpan** [comment]
update() should never return false unless there is a hardware error.  For example if you have code to operate a relay and you can also detect that the relay is broken, you can return false if the user tries to operate the relay from the Home App.  But in almost all cases it should return true.  If you return false the Home App will report a problem.

**Comment by HomeSpan** [comment]
Behavior is uncertain in Home App when update returns a false.  Also, what do you mean that the outlet is not powered?  Do you mean the ESP32 has power but AC power is not available for the outlet itself?  To represent that state you may want to try using the OutletInUse Characteristic (it's not exactly on point, but may serve the purpose).
