### ISSUE TITLE
About changing accessories

### ISSUE THREAD

**Issue by ismail-ozturk** [HomeSpan/HomeSpan#951]
Hello, I am creating a SpanAccessory according to the mainConfig.selectedMode value in the Setup function.

When I change mainConfig.selectedMode, the other one naturally goes to "No response" in the home application.
When I want to add an accessory, I cannot see any accessory.

When changing mainConfig.selectedMode, I can delete the existing paired device and give the opportunity to pair again.
The question I want to ask is;

Is it possible to see the new accessory without pairing it again?

Code:
```
if (mainConfig.selectedMode == "Led")
  {
    homeSpan.begin(Category::Lighting, "LightBulb", HOSTNAME.c_str());

    new SpanAccessory();
    new Service::AccessoryInformation();
    new Characteristic::Identify();

    new Characteristic::Manufacturer(HOSTNAME.c_str());
   
    new Characteristic::FirmwareRevision("1.0.6");

    new DEV_LED("LED1", relay_1, switch_1); 
    new DEV_LED("LED2", relay_2, switch_2); 
  }
  else if (mainConfig.selectedMode == "Garaj")
  {
    homeSpan.begin(Category::GarageDoorOpeners, "Garage", HOSTNAME.c_str());

    new SpanAccessory();
    new Service::AccessoryInformation();
    new Characteristic::Identify();

    new Characteristic::Manufacturer(HOSTNAME.c_str());
    
    new Characteristic::FirmwareRevision("1.0.6");

    new DEV_GarageDoor();
  }
```

**HomeSpan Ver. 1.9.1**

**Comment by HomeSpan** [comment]
In general you can't change Accessory definitions in HomeKit without un-pairing and re-pairing unless you ensure that you preserve the AID for each Accessory and you don't change the order of any Characteristics.  This makes it possible to add/delete multiple copies of the same Accessory (for example, a bridge with an arbitrary number of dimmable light Accessories). 

It is possible to do this without even re-booting your HomeSpan device.  See the Programmable Hub example for details.
