### ISSUE TITLE
Possibility needed to export pairing information

### ISSUE THREAD

**Issue by mgeramb** [HomeSpan/HomeSpan#953]
I want provide a feature in my device to export the pairing configuration, so that a user can transfer the whole configuration to another device without the need to reconfigure all devices in the home app. Would this be somehow possible?

**Comment by HomeSpan** [comment]
Yes, this is called device cloning.  See the main HomeSpan page for a link that explains how to clone.

**Comment by mgeramb** [comment]
Thank you!
