### ISSUE TITLE
Duplicate paired controller ID?

### ISSUE THREAD

**Issue by frankonski** [HomeSpan/HomeSpan#954]
I had been running a light strip with HS 2.0.0-rc1 for 45+ days with no issues, no reboot, no power loss, no hand, perfectly stable.
Then it started showing non-responsive, and/or taking ~30 seconds to respond, even though I have my router set to disable mesh routing & force this device to remain connected to a specific AP.
Disconnecting from power and connecting to laptop's USB, all seemed "normal".

I checked both of my AppleTV (gen3 and gen4), both updated to AppleTV OS 18.1.

Then I noticed in the Home.app that in _Home Settings_, _Home Hubs and Bridges_, it was set to "Automatic selection". I forced it to my gen4, then the strip started working fine again. But looking at "Connection Info" in HomeSpan CLI, it currently show **two admin clients** with the same controller ID.

```
*** HomeSpan Status ***

IP Address:        192.168.xx.xx
Web Logging:       http://mezzanine.local:80/status

Accessory ID:      1A:72:86:5C:D4:C2                               LTPK: FB664AC0ADD8F6A295FFF46B5B5F0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Paired Controller: F39B0A91-0F77-4889-AE9F-C942A1E6E9FE   (admin)  LTPK: 86ED9F58BF4CDB23D76088FC6A7BCxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Paired Controller: E66112C1-2B7E-48DC-9FB8-B1B6D7CE235E   (admin)  LTPK: 4D5FBF74118F779740C91FC21CF88xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Paired Controller: 2B9A4486-CC18-44B8-BEB0-5AC2BCD5B3CB (regular)  LTPK: EF883D81C9157772D5982EA2908E3xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Client #5: 192.168.xx.105  ID=E66112C1-2B7E-48DC-9FB8-B1B6D7CE235E   (admin)
Client #2: 192.168.xx.104  ID=E66112C1-2B7E-48DC-9FB8-B1B6D7CE235E   (admin)

*** End Status ***
```
Is this normal?

**Comment by HomeSpan** [comment]
Yes, multiple clients can use the same controller IDs. Apple does not provide any docs on how or when it uses different clients to connect to a device.

**Comment by frankonski** [comment]
So when HS needs to notify controllers, do you notify "by controller ID", or by client IP connected and not really use _ControllerID_ ?

**Comment by HomeSpan** [comment]
Controller ID is only used to verify a connection when first made (you can see this in the Log files).  Once a socket connection has been verified the Controller ID is no longer used during normal communication.  Notifications are sent to all open socket connections (without regard to the Controller ID), if that socket connection has subscribed to notifications for any given service/characteristic.

**Comment by HomeSpan** [comment]
Anything more on this, or can I close?

**Comment by frankonski** [comment]
Things seems to have been somewhat stabilized for a while. ok to close, and I will update to the most recent release. I wonder if I will still have to move the `#include <DNSServer.h>` to `HomeSpan.cpp` to get things to compile with PIO, but that is a separate topic.
