### ISSUE TITLE
Retreiving HomeSpan NTP time in custom code portions ?

### ISSUE THREAD

**Issue by erickfr06** [HomeSpan/HomeSpan#956]
Hello.

Within a HS sketch using NTP (via weblog initialization), once NTP correctly initialized, HS probably maintains a struc tm* to keep current time.  How to access this reference time in custom code ?

Any attempt to get a parallel  time request (in custom code) from NTP leads to random glitches on time, for example tm_hour shifting +/- 1 hour during few seconds every 10/15 minutes. Maybe this is because the tm struct inside <time.h> is known to be not thread safe and must not be accedded twice without lock mechanism.  Maybe espressif code for timekeeping is not executed on the same ESP32 core then "arduino" binary code.

So probably we need to let HS core exclusively getting time  and then  to have calls to retreive time from HS.
I've not found any information on the documentation for retreiving the time already initialized by HS and used (for example) in weblog.

Thanks for your advice.

**Comment by HomeSpan** [comment]
There is already a FAQ on this:  https://github.com/HomeSpan/HomeSpan/blob/master/docs/FAQ.md#how-can-i-read-the-current-date-and-time-from-within-my-sketch.

**Comment by erickfr06** [comment]
Missed it, sorry !
Thanks a lot.

**Comment by erickfr06** [comment]
Missed it, sorry !
Thanks a lot.
