### ISSUE TITLE
Add ESP32 Touch

### ISSUE THREAD

**Issue by PeteBurgess** [HomeSpan/HomeSpan#96]
I’d like to use the button class but I’d like to be able to do touch sensitive instead of a button. Can I just copy/paste the class replacing the first “int” with “string” or does it get more complicated ?

Sorry, not a total novice but this is all way out of my wheelhouse.

**Comment by HomeSpan** [comment]
Sorry, but the Touch Sensor library on the ESP32 is quite complicated and the button class would need to be significantly changed to incorporate that library.

**Comment by pcossutta** [comment]
@PeteBurgess to use touch in the Arduino IDE is as easy as do a comparison: `touchRead(13) < TOUCH_LMT`. `TOUCH_LMT` depends on the surface used as sensor, but you could easily print touchRead values and calibrate from there. Of course you need everything related to a button after that. such as [debounce](https://arduinogetstarted.com/tutorials/arduino-button-debounce). Hope it helps.

Code sample:
```
int lastState = LOW;
int lastDebouncedState = LOW;
int currentState;
unsigned long lastDebounceTime = 0;
#define TOUCH_LMT 35
#define DEBOUNCE_DELAY 50

void setup() {
}

void loop(){ 
  currentState = touchRead(13) < TOUCH_LMT;
  // If the switch/button changed, due to noise or pressing:
  if (currentState != lastState) {
    // reset the debouncing timer
    lastDebounceTime = millis();
    // save the the last flickerable state
    lastState = currentState;
  }
  if ((millis() - lastDebounceTime) > DEBOUNCE_DELAY) {
    if(lastDebouncedState == HIGH && currentState == LOW) 
      Serial.println("Button pressed");
    else if(lastDebouncedState == LOW && currentState == HIGH)
      Serial.println("Button released");
    lastDebouncedState = currentState;
}     
```

**Comment by HomeSpan** [comment]
Wow - thank you!  I had no idea the ESP32-Arduino library had this feature.  This makes it a LOT easier to integrate.  I will extend the button class to allow the use of touchRead.  Probably won't be able to get it into the next update (which I'm hoping to release later this week) but should be able to add it to the next one (as well as provide it earlier in dev once ready).

**Comment by PeteBurgess** [comment]
Thanks. I’ve used it before, it actually works pretty well.

**Comment by guigoruiz1** [comment]
Hello, has this been implemented?

**Comment by HomeSpan** [comment]
Sorry, I have not yet added that to HomeSpan, but hope to in a future release.  Given other similar requests for alternative buttons (pull-ups, use of multiplexers, etc.) I anticipate making something more generic so that the user can define a function that simply returns true/false depending on whether the "button" is pressed, regardless of button type.

Note you can still use the touch library at present with HomeSpan, but you will need to add logic to process the "touches" in the `loop()` method of a Service, instead of using `SpanButton`

**Comment by HomeSpan** [comment]
HomeSpan version 1.6.0 (just released) now includes the ability to use touch pad/sensors with SpanButton.  Complete details can be found in the the latest version of [SpanButton()](https://github.com/HomeSpan/HomeSpan/blob/master/docs/Reference.md#spanbuttonint-pin-uint16_t-longtime-uint16_t-singletime-uint16_t-doubletime-boolean-triggertypeint) in the API documentation, with additional tutorial instructions  describing how touch pad sensitivity is calibrated added to the end of [Example 15 - RealPushButtons](https://github.com/HomeSpan/HomeSpan/tree/master/examples/15-RealPushButtons).  Thanks for raising this request!

**Comment by guigoruiz1** [comment]
Is it possible to use the touch sensor as control pin?

**Comment by HomeSpan** [comment]
No, you can only use touch for SpanButton at this time. Control still needs to be a physical button to ground.
