### ISSUE TITLE
Include setOTAPassword

### ISSUE THREAD

**Issue by pcossutta** [HomeSpan/HomeSpan#97]
This is not an issue, just a suggestion, as the title say it would be great to have a setOTAPassword(pwd) as there is a setStatusPin(pin). It is not as easy to implement as the setStatusPin but I think it could be a great addition.

BTW thanks for your great effort, this library works flawlessly !

**Comment by zuozhehao** [comment]
This is the same as the WIFI password. It is not frequently modified. It is safe to modify it directly through the command line and save it in the NVS.

**Comment by pcossutta** [comment]
Yes, but it would be nice to have a similar API for all the configuration parameters also it will allow to distribute the code without patching the library.

**Comment by zuozhehao** [comment]
> Yes, but it would be nice to have a similar API for all the configuration parameters also it will allow to distribute the code without patching the library.

https://github.com/HomeSpan/HomeSpan/blob/master/docs/CLI.md

`O - prompts you to set the password used for Over-the-Air (OTA) Updating`

**Comment by pcossutta** [comment]
Yes, but it's an extra step. What is the problem of having some more configuration method ? I could help to implement it if getting time to do it is the problem.

**Comment by HomeSpan** [comment]
It's actually a design choice (which I may change given all the feedback).  In general, it's never a good idea to store passwords in code.  Since Apple HomeKit is all about security, I wanted to follow that philosophy to the extent possible without going overboard with encrypting passwords.  This also makes it easier to share code without ever worrying if you forgot to delete you password.

**Comment by pcossutta** [comment]
@HomeSpan I totally agree with you. What I have in mind is not a static password in code but one generated using the MAC Address or some internal serial number. In that case this feature will be useful.
