### ISSUE TITLE
HomeSpan without Apple tv or apple home pod

### ISSUE THREAD

**Issue by Victoooorrr** [HomeSpan/HomeSpan#970]
Hello,

I’m trying to use HomeSpan to control relays, but I’m having trouble getting it to work when the ESP32 is disconnected from my PC.

I’m currently running version 1.7.2 of HomeSpan. Is it still possible to use this "older version" with just the ESP32 connected to the same WiFi network as the Apple Home app?

Thank you in advance for your help.

**Comment by Victoooorrr** [comment]
nervermind it's work :), big thanks to the owner of this

**Comment by HomeSpan** [comment]
Can I close this issue then?
