### ISSUE TITLE
change to includes path?

### ISSUE THREAD

**Issue by n0rt0nthec4t** [HomeSpan/HomeSpan#973]
First off, thank you for the working on this library. I normally develop with nodejs/hapnodejs/homerbidge, but have a project using this.

Just updated from 1.8 to 2.1 library, and noticed needed to amend the include path for the pwm stuff

from

```
#include "extras/PwmPin.h"              // HomeSpan support library for PWM functions
```

to 

```
#include "src/extras/PwmPin.h"              // HomeSpan support library for PWM functions
```

Just wondering if this was intended or some change I missed with previous library versions

Thanks again

**Comment by HomeSpan** [comment]
Glad you are finding the library useful. 

Includes for those functions are no longer needed.  All you need to do is include HomeSpan.h and everything else will be brought in. 

I don't remember when I made the change but it should be in one of the prior release notes.

**Comment by n0rt0nthec4t** [comment]
Thanks. Was in v1.9 searching release notes
