### ISSUE TITLE
Enable AP by default when no WIFI credentials

### ISSUE THREAD

**Issue by pcossutta** [HomeSpan/HomeSpan#98]
I don't see a point for manually enabling AP if you already have an USB connection to configure the WIFI credentials. 

Probably, it would be best to directly starts in AP mode when no wifi credentials are available or let the user decide on init.

**Comment by zuozhehao** [comment]
This suggestion has been implemented, please check the document.
https://github.com/HomeSpan/HomeSpan/blob/master/docs/Reference.md
`void enableOTA(boolean auth=true)`

**Comment by pcossutta** [comment]
I didn't talk about OTA, It is about the AP mode where the ESP acts as a server to configure WIFI credentials.

**Comment by zuozhehao** [comment]
> I didn't talk about OTA, It is about the AP mode where the ESP acts as a server to configure WIFI credentials.

https://github.com/HomeSpan/HomeSpan/issues/83
`homeSpan.enableAutoStartAP()`

**Comment by pcossutta** [comment]
Thank you ! I read the docs but didn't find that.

**Comment by HomeSpan** [comment]
Note `homeSpan.enableAutoStartAP()` is a new method recently added to the *dev* branch.  It will be released in the next patch (1.3.0) later this week.
