### ISSUE TITLE
Device discovery and connection response speed

### ISSUE THREAD

**Issue by zuozhehao** [HomeSpan/HomeSpan#99]
After I restore the factory settings, the device will take longer to be discovered，pairing time also takes a long time.
I used another library a few days ago and found this problem.

**Comment by HomeSpan** [comment]
Pairing time seems to take a lot longer since about iOS 14.3 or so.  Not sure what Apple changed, but sometimes I need to wait 10-20 seconds after pairing is complete for the Home App to show the new Accessories.

**Comment by zuozhehao** [comment]
I'm comparing with the code of another library. I use a simple example of using another library. Without any special operation, homespan will be much slower, especially after restoring the factory settings (clearing all NVS contents)
